// SVG region mapping for Afghanistan
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const afgSvgToSlugMapping: RegionMapping = {
  "AFBDS": {
    "name": "Badakhshan",
    "slug": "badakhshan"
  },
  "AFTAK": {
    "name": "Takhar",
    "slug": "takhar"
  },
  "AFKDZ": {
    "name": "Kunduz",
    "slug": "kunduz"
  },
  "AFBAL": {
    "name": "Balkh",
    "slug": "balkh"
  },
  "AFJOW": {
    "name": "Jawzjan",
    "slug": "jawzjan"
  },
  "AFFYB": {
    "name": "Faryab",
    "slug": "faryab"
  },
  "AFBDG": {
    "name": "Badghis",
    "slug": "badghis"
  },
  "AFHER": {
    "name": "Hirat",
    "slug": "hirat"
  },
  "AFNIM": {
    "name": "Nimroz",
    "slug": "nimroz"
  },
  "AFFRA": {
    "name": "Farah",
    "slug": "farah"
  },
  "AFKNR": {
    "name": "Kunar",
    "slug": "kunar"
  },
  "AFNUR": {
    "name": "Nuristan",
    "slug": "nuristan"
  },
  "AFNAN": {
    "name": "Nangarhar",
    "slug": "nangarhar"
  },
  "AFKHO": {
    "name": "Khost",
    "slug": "khost"
  },
  "AFPKA": {
    "name": "Paktya",
    "slug": "paktya"
  },
  "AFPIA": {
    "name": "Paktika",
    "slug": "paktika"
  },
  "AFZAB": {
    "name": "Zabul",
    "slug": "zabul"
  },
  "AFKAN": {
    "name": "Kandahar",
    "slug": "kandahar"
  },
  "AFHEL": {
    "name": "Hilmand",
    "slug": "hilmand"
  },
  "AFURU": {
    "name": "Uruzgan",
    "slug": "uruzgan"
  },
  "AFGHA": {
    "name": "Ghazni",
    "slug": "ghazni"
  },
  "AFPAN": {
    "name": "Panjshayr",
    "slug": "panjshayr"
  },
  "AFKAB": {
    "name": "Kabul",
    "slug": "kabul"
  },
  "AFLAG": {
    "name": "Laghman",
    "slug": "laghman"
  },
  "AFLOG": {
    "name": "Logar",
    "slug": "logar"
  },
  "AFKAP": {
    "name": "Kapisa",
    "slug": "kapisa"
  },
  "AFWAR": {
    "name": "Wardak",
    "slug": "wardak"
  },
  "AFBAM": {
    "name": "Bamyan",
    "slug": "bamyan"
  },
  "AFPAR": {
    "name": "Parwan",
    "slug": "parwan"
  },
  "AFSAR": {
    "name": "Sari Pul",
    "slug": "sari-pul"
  },
  "AFGHO": {
    "name": "Ghor",
    "slug": "ghor"
  },
  "AFBGL": {
    "name": "Baghlan",
    "slug": "baghlan"
  },
  "AFSAM": {
    "name": "Samangan",
    "slug": "samangan"
  },
  "AFDAY": {
    "name": "Daykundi",
    "slug": "daykundi"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return afgSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return afgSvgToSlugMapping[regionId];
}
