// SVG region mapping for Angola
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const agoSvgToSlugMapping: RegionMapping = {
  "AOCAB": {
    "name": "Cabinda",
    "slug": "cabinda"
  },
  "AOCCU": {
    "name": "Cuando Cubango",
    "slug": "cuando-cubango"
  },
  "AOMOX": {
    "name": "Moxico",
    "slug": "moxico"
  },
  "AONAM": {
    "name": "Namibe",
    "slug": "namibe"
  },
  "AOCNN": {
    "name": "Cunene",
    "slug": "cunene"
  },
  "AOZAI": {
    "name": "Zaire",
    "slug": "zaire"
  },
  "AOUIG": {
    "name": "Uíge",
    "slug": "uge"
  },
  "AOLNO": {
    "name": "Lunda Norte",
    "slug": "lunda-norte"
  },
  "AOMAL": {
    "name": "Malanje",
    "slug": "malanje"
  },
  "AOLSU": {
    "name": "Lunda Sul",
    "slug": "lunda-sul"
  },
  "AOCUS": {
    "name": "Cuanza Sul",
    "slug": "cuanza-sul"
  },
  "AOBGU": {
    "name": "Benguela",
    "slug": "benguela"
  },
  "AOBGO": {
    "name": "Bengo",
    "slug": "bengo"
  },
  "AOLUA": {
    "name": "Luanda",
    "slug": "luanda"
  },
  "AOBIE": {
    "name": "Bie",
    "slug": "bie"
  },
  "AOCNO": {
    "name": "Cuanza Norte",
    "slug": "cuanza-norte"
  },
  "AOHUI": {
    "name": "Huíla",
    "slug": "hula"
  },
  "AOHUA": {
    "name": "Huambo",
    "slug": "huambo"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return agoSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return agoSvgToSlugMapping[regionId];
}
