// SVG region mapping for Anguilla
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const aiaSvgToSlugMapping: RegionMapping = {
  "AIX02": {
    "name": "East End",
    "slug": "east-end"
  },
  "AIX10": {
    "name": "Stoney Ground",
    "slug": "stoney-ground"
  },
  "AIX06": {
    "name": "North Side",
    "slug": "north-side"
  },
  "AIX13": {
    "name": "The Valley",
    "slug": "the-valley"
  },
  "AIX05": {
    "name": "North Hill",
    "slug": "north-hill"
  },
  "AIX07": {
    "name": "Sandy Ground",
    "slug": "sandy-ground"
  },
  "AIX09": {
    "name": "South Hill",
    "slug": "south-hill"
  },
  "AIX14": {
    "name": "West End",
    "slug": "west-end"
  },
  "AIX01": {
    "name": "Blowing Point",
    "slug": "blowing-point"
  },
  "AIX11": {
    "name": "The Farrington",
    "slug": "the-farrington"
  },
  "AIX08": {
    "name": "Sandy Hill",
    "slug": "sandy-hill"
  },
  "AIX04": {
    "name": "Island Harbour",
    "slug": "island-harbour"
  },
  "AIX03": {
    "name": "George Hill",
    "slug": "george-hill"
  },
  "AIX12": {
    "name": "The Quarter",
    "slug": "the-quarter"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return aiaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return aiaSvgToSlugMapping[regionId];
}
