// SVG region mapping for Albania
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const albSvgToSlugMapping: RegionMapping = {
  "AL09": {
    "name": "Dib��r",
    "slug": "dibr"
  },
  "AL07": {
    "name": "Kukës",
    "slug": "kuks"
  },
  "AL06": {
    "name": "Korçë",
    "slug": "kor"
  },
  "AL03": {
    "name": "Elbasan",
    "slug": "elbasan"
  },
  "AL05": {
    "name": "Gjirokastër",
    "slug": "gjirokastr"
  },
  "AL12": {
    "name": "Vlorë",
    "slug": "vlor"
  },
  "AL10": {
    "name": "Shkodër",
    "slug": "shkodr"
  },
  "AL04": {
    "name": "Fier",
    "slug": "fier"
  },
  "AL11": {
    "name": "Tiranë",
    "slug": "tiran"
  },
  "AL02": {
    "name": "Durrës",
    "slug": "durrs"
  },
  "AL08": {
    "name": "Lezhë",
    "slug": "lezh"
  },
  "AL01": {
    "name": "Berat",
    "slug": "berat"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return albSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return albSvgToSlugMapping[regionId];
}
