// SVG region mapping for Andorra
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const andSvgToSlugMapping: RegionMapping = {
  "AD05": {
    "name": "Ordino",
    "slug": "ordino"
  },
  "AD02": {
    "name": "Canillo",
    "slug": "canillo"
  },
  "AD03": {
    "name": "Encamp",
    "slug": "encamp"
  },
  "AD04": {
    "name": "La Massana",
    "slug": "la-massana"
  },
  "AD06": {
    "name": "Sant Julià de Lòria",
    "slug": "sant-juli-de-lria"
  },
  "AD08": {
    "name": "Escaldes-Engordany",
    "slug": "escaldes-engordany"
  },
  "AD07": {
    "name": "Andorra la Vella",
    "slug": "andorra-la-vella"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return andSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return andSvgToSlugMapping[regionId];
}
