// SVG region mapping for United Arab Emirates
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const areSvgToSlugMapping: RegionMapping = {
  "AEFU": {
    "name": "Fujayrah",
    "slug": "fujayrah"
  },
  "AESH": {
    "name": "Sharjah",
    "slug": "sharjah"
  },
  "AERK": {
    "name": "Ras Al Khaymah",
    "slug": "ras-al-khaymah"
  },
  "AEDU": {
    "name": "Dubay",
    "slug": "dubay"
  },
  "AEAZ": {
    "name": "Abu Dhabi",
    "slug": "abu-dhabi"
  },
  "AEUQ": {
    "name": "Umm Al Qaywayn",
    "slug": "umm-al-qaywayn"
  },
  "AEAJ": {
    "name": "Ajman",
    "slug": "ajman"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return areSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return areSvgToSlugMapping[regionId];
}
