// SVG region mapping for Argentina
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const argSvgToSlugMapping: RegionMapping = {
  "ARA": {
    "name": "Salta",
    "slug": "salta"
  },
  "ARB": {
    "name": "Buenos Aires",
    "slug": "buenos-aires"
  },
  "ARC": {
    "name": "Ciudad de Buenos Aires",
    "slug": "ciudad-de-buenos-aires"
  },
  "ARD": {
    "name": "San Luis",
    "slug": "san-luis"
  },
  "ARE": {
    "name": "Entre Ríos",
    "slug": "entre-rios"
  },
  "ARF": {
    "name": "La Rioja",
    "slug": "la-rioja"
  },
  "ARG": {
    "name": "Santiago del Estero",
    "slug": "santiago-del-estero"
  },
  "ARH": {
    "name": "Chaco",
    "slug": "chaco"
  },
  "ARJ": {
    "name": "San Juan",
    "slug": "san-juan"
  },
  "ARK": {
    "name": "Catamarca",
    "slug": "catamarca"
  },
  "ARL": {
    "name": "La Pampa",
    "slug": "la-pampa"
  },
  "ARM": {
    "name": "Mendoza",
    "slug": "mendoza"
  },
  "ARN": {
    "name": "Misiones",
    "slug": "misiones"
  },
  "ARP": {
    "name": "Formosa",
    "slug": "formosa"
  },
  "ARQ": {
    "name": "Neuquén",
    "slug": "neuquen"
  },
  "ARR": {
    "name": "Río Negro",
    "slug": "rio-negro"
  },
  "ARS": {
    "name": "Santa Fe",
    "slug": "santa-fe"
  },
  "ART": {
    "name": "Tucumán",
    "slug": "tucuman"
  },
  "ARU": {
    "name": "Chubut",
    "slug": "chubut"
  },
  "ARV": {
    "name": "Tierra del Fuego",
    "slug": "tierra-del-fuego"
  },
  "ARW": {
    "name": "Corrientes",
    "slug": "corrientes"
  },
  "ARX": {
    "name": "Córdoba",
    "slug": "cordoba"
  },
  "ARY": {
    "name": "Jujuy",
    "slug": "jujuy"
  },
  "ARZ": {
    "name": "Santa Cruz",
    "slug": "santa-cruz"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return argSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return argSvgToSlugMapping[regionId];
}
