// SVG region mapping for Argentina
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const argSvgToSlugMapping: RegionMapping = {
  "ARE": {
    "name": "Buenos Aires",
    "slug": "buenos-aires"
  },
  "ARA": {
    "name": "Buenos Aires",
    "slug": "buenos-aires"
  },
  "ARY": {
    "name": "Jujuy",
    "slug": "jujuy"
  },
  "ARP": {
    "name": "La Pampa",
    "slug": "la-pampa"
  },
  "ARN": {
    "name": "Buenos Aires",
    "slug": "buenos-aires"
  },
  "ARH": {
    "name": "Chaco",
    "slug": "chaco"
  },
  "ARW": {
    "name": "W",
    "slug": "w"
  },
  "ARK": {
    "name": "K",
    "slug": "k"
  },
  "ARF": {
    "name": "Distrito Federal",
    "slug": "distrito-federal"
  },
  "ARJ": {
    "name": "Jujuy",
    "slug": "jujuy"
  },
  "ARM": {
    "name": "Catamarca",
    "slug": "catamarca"
  },
  "ARQ": {
    "name": "Neuquen",
    "slug": "neuquen"
  },
  "ARU": {
    "name": "Buenos Aires",
    "slug": "buenos-aires"
  },
  "ARR": {
    "name": "Buenos Aires",
    "slug": "buenos-aires"
  },
  "ARZ": {
    "name": "Mendoza",
    "slug": "mendoza"
  },
  "ARV": {
    "name": "V",
    "slug": "v"
  },
  "ARB": {
    "name": "Buenos Aires",
    "slug": "buenos-aires"
  },
  "ARC": {
    "name": "Catamarca",
    "slug": "catamarca"
  },
  "ARS": {
    "name": "Buenos Aires",
    "slug": "buenos-aires"
  },
  "ART": {
    "name": "Catamarca",
    "slug": "catamarca"
  },
  "ARG": {
    "name": "Rio Negro",
    "slug": "rio-negro"
  },
  "ARD": {
    "name": "Cordoba",
    "slug": "cordoba"
  },
  "ARL": {
    "name": "Distrito Federal",
    "slug": "distrito-federal"
  },
  "ARX": {
    "name": "X",
    "slug": "x"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return argSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return argSvgToSlugMapping[regionId];
}
