// SVG region mapping for Armenia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const armSvgToSlugMapping: RegionMapping = {
  "AMTV": {
    "name": "Tavush",
    "slug": "tavush"
  },
  "AMLO": {
    "name": "Lori",
    "slug": "lori"
  },
  "AMSH": {
    "name": "Shirak",
    "slug": "shirak"
  },
  "AMGR": {
    "name": "Gegharkunik",
    "slug": "gegharkunik"
  },
  "AMVD": {
    "name": "Vayots Dzor",
    "slug": "vayots-dzor"
  },
  "AMSU": {
    "name": "Syunik",
    "slug": "syunik"
  },
  "AMAR": {
    "name": "Ararat",
    "slug": "ararat"
  },
  "AMAG": {
    "name": "Aragatsotn",
    "slug": "aragatsotn"
  },
  "AMAV": {
    "name": "Armavir",
    "slug": "armavir"
  },
  "AMKT": {
    "name": "Kotayk",
    "slug": "kotayk"
  },
  "AMER": {
    "name": "Erevan",
    "slug": "erevan"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return armSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return armSvgToSlugMapping[regionId];
}
