// SVG region mapping for Antigua and Barbuda
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const atgSvgToSlugMapping: RegionMapping = {
  "AG06": {
    "name": "Saint Paul",
    "slug": "saint-paul"
  },
  "AG08": {
    "name": "Saint Philip",
    "slug": "saint-philip"
  },
  "AG07": {
    "name": "Saint Peter",
    "slug": "saint-peter"
  },
  "AG03": {
    "name": "Saint George",
    "slug": "saint-george"
  },
  "AG04": {
    "name": "Saint John",
    "slug": "saint-john"
  },
  "AG05": {
    "name": "Saint Mary",
    "slug": "saint-mary"
  },
  "AG10": {
    "name": "Barbuda",
    "slug": "barbuda"
  },
  "AG11": {
    "name": "Redonda",
    "slug": "redonda"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return atgSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return atgSvgToSlugMapping[regionId];
}
