// SVG region mapping for Australia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const ausSvgToSlugMapping: RegionMapping = {
  "AUWA": {
    "name": "Western Australia",
    "slug": "western-australia"
  },
  "AUNT": {
    "name": "Northern Territory",
    "slug": "northern-territory"
  },
  "AUSA": {
    "name": "South Australia",
    "slug": "south-australia"
  },
  "AUQLD": {
    "name": "Queensland",
    "slug": "queensland"
  },
  "AUNSW": {
    "name": "New South Wales",
    "slug": "new-south-wales"
  },
  "AUVIC": {
    "name": "Victoria",
    "slug": "victoria"
  },
  "AUTAS": {
    "name": "Tasmania",
    "slug": "tasmania"
  },
  "AUACT": {
    "name": "Australian Capital Territory",
    "slug": "australian-capital-territory"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return ausSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return ausSvgToSlugMapping[regionId];
}
