// SVG region mapping for Austria
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const autSvgToSlugMapping: RegionMapping = {
  "AT3": {
    "name": "3",
    "slug": "3"
  },
  "AT4": {
    "name": "4",
    "slug": "4"
  },
  "AT1": {
    "name": "1",
    "slug": "1"
  },
  "AT8": {
    "name": "8",
    "slug": "8"
  },
  "AT7": {
    "name": "7",
    "slug": "7"
  },
  "AT5": {
    "name": "5",
    "slug": "5"
  },
  "AT2": {
    "name": "2",
    "slug": "2"
  },
  "AT6": {
    "name": "6",
    "slug": "6"
  },
  "AT9": {
    "name": "9",
    "slug": "9"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return autSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return autSvgToSlugMapping[regionId];
}
