// SVG region mapping for Austria
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const autSvgToSlugMapping: RegionMapping = {
  "AT1": {
    "name": "Burgenland",
    "slug": "burgenland"
  },
  "AT2": {
    "name": "Kärnten",
    "slug": "karnten"
  },
  "AT3": {
    "name": "Niederösterreich",
    "slug": "niederosterreich"
  },
  "AT4": {
    "name": "Oberösterreich",
    "slug": "oberosterreich"
  },
  "AT5": {
    "name": "Salzburg",
    "slug": "salzburg"
  },
  "AT6": {
    "name": "Steiermark",
    "slug": "steiermark"
  },
  "AT7": {
    "name": "Tirol",
    "slug": "tirol"
  },
  "AT8": {
    "name": "Vorarlberg",
    "slug": "vorarlberg"
  },
  "AT9": {
    "name": "Wien",
    "slug": "wien"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return autSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return autSvgToSlugMapping[regionId];
}
