// SVG region mapping for Azerbaijan
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const azeSvgToSlugMapping: RegionMapping = {
  "AZQAZ": {
    "name": "Qazax",
    "slug": "qazax"
  },
  "AZAGA": {
    "name": "Ağstafa",
    "slug": "astafa"
  },
  "AZTOV": {
    "name": "Tovuz",
    "slug": "tovuz"
  },
  "AZGAD": {
    "name": "Gədəbəy",
    "slug": "gdby"
  },
  "AZDAS": {
    "name": "Daşkəsən",
    "slug": "daksn"
  },
  "AZKAL": {
    "name": "Kəlbəcər",
    "slug": "klbcr"
  },
  "AZLAC": {
    "name": "Lachin",
    "slug": "lachin"
  },
  "AZQBI": {
    "name": "Qubadli",
    "slug": "qubadli"
  },
  "AZZAN": {
    "name": "Zəngilan",
    "slug": "zngilan"
  },
  "AZSAR": {
    "name": "Şərur",
    "slug": "rur"
  },
  "AZSAD": {
    "name": "Sədərək",
    "slug": "sdrk"
  },
  "AZKAN": {
    "name": "Kangarli",
    "slug": "kangarli"
  },
  "AZBAB": {
    "name": "Babək",
    "slug": "babk"
  },
  "AZSAH": {
    "name": "Şahbuz",
    "slug": "ahbuz"
  },
  "AZCUL": {
    "name": "Culfa",
    "slug": "culfa"
  },
  "AZORD": {
    "name": "Ordubad",
    "slug": "ordubad"
  },
  "AZBAL": {
    "name": "Balakən",
    "slug": "balakn"
  },
  "AZZAQ": {
    "name": "Zaqatala",
    "slug": "zaqatala"
  },
  "AZXAC": {
    "name": "Xaçmaz",
    "slug": "xamaz"
  },
  "AZQUS": {
    "name": "Qusar",
    "slug": "qusar"
  },
  "AZOGU": {
    "name": "Oğuz",
    "slug": "ouz"
  },
  "AZSAK": {
    "name": "Şəki",
    "slug": "ki"
  },
  "AZQAX": {
    "name": "QAX",
    "slug": "qax"
  },
  "AZQAB": {
    "name": "Qəbələ",
    "slug": "qbl"
  },
  "AZSMX": {
    "name": "Samux",
    "slug": "samux"
  },
  "AZIMI": {
    "name": "İmişli",
    "slug": "imili"
  },
  "AZBIL": {
    "name": "Biləsuvar",
    "slug": "bilsuvar"
  },
  "AZCAL": {
    "name": "Cəlilabad",
    "slug": "clilabad"
  },
  "AZYAR": {
    "name": "Yardımlı",
    "slug": "yardml"
  },
  "AZLER": {
    "name": "Lerik",
    "slug": "lerik"
  },
  "AZCAB": {
    "name": "Cəbrayıl",
    "slug": "cbrayl"
  },
  "AZFUZ": {
    "name": "Füzuli",
    "slug": "fzuli"
  },
  "AZBEY": {
    "name": "Beyləqan",
    "slug": "beylqan"
  },
  "AZAST": {
    "name": "Astara",
    "slug": "astara"
  },
  "AZSBN": {
    "name": "Dəvəçi",
    "slug": "dvi"
  },
  "AZSIY": {
    "name": "Siyəzən",
    "slug": "siyzn"
  },
  "AZXIZ": {
    "name": "Xizı",
    "slug": "xiz"
  },
  "AZSM": {
    "name": "Sumqayıt",
    "slug": "sumqayt"
  },
  "AZBA": {
    "name": "Bakı",
    "slug": "bak"
  },
  "AZSAL": {
    "name": "Salyan",
    "slug": "salyan"
  },
  "AZNEF": {
    "name": "Neftçala",
    "slug": "neftala"
  },
  "AZLAN": {
    "name": "Lankaran",
    "slug": "lankaran"
  },
  "AZMAS": {
    "name": "Masallı",
    "slug": "masall"
  },
  "AZLA": {
    "name": "Lankaran City",
    "slug": "lankaran-city"
  },
  "AZNX": {
    "name": "Naxçıvan",
    "slug": "naxvan"
  },
  "AZXCI": {
    "name": "Xocalı",
    "slug": "xocal"
  },
  "AZAGM": {
    "name": "Ağdam",
    "slug": "adam"
  },
  "AZTAR": {
    "name": "Tərtər",
    "slug": "trtr"
  },
  "AZGOR": {
    "name": "Goranboy",
    "slug": "goranboy"
  },
  "AZXVD": {
    "name": "Xocavənd",
    "slug": "xocavnd"
  },
  "AZHAC": {
    "name": "Hajigabul",
    "slug": "hajigabul"
  },
  "AZABS": {
    "name": "Abşeron",
    "slug": "aberon"
  },
  "AZGYG": {
    "name": "Xanlar",
    "slug": "xanlar"
  },
  "AZKUR": {
    "name": "Kürdəmir",
    "slug": "krdmir"
  },
  "AZZAR": {
    "name": "Zərdab",
    "slug": "zrdab"
  },
  "AZSAB": {
    "name": "Sabirabad",
    "slug": "sabirabad"
  },
  "AZSR": {
    "name": "Shirvan",
    "slug": "shirvan"
  },
  "AZSAT": {
    "name": "Saatlı",
    "slug": "saatl"
  },
  "AZBAR": {
    "name": "Bərdə",
    "slug": "brd"
  },
  "AZSKR": {
    "name": "Şəmkir",
    "slug": "mkir"
  },
  "AZAGU": {
    "name": "Ağsu",
    "slug": "asu"
  },
  "AZSMI": {
    "name": "Şamaxı",
    "slug": "amax"
  },
  "AZQBA": {
    "name": "Quba",
    "slug": "quba"
  },
  "AZUCA": {
    "name": "Ucar",
    "slug": "ucar"
  },
  "AZQOB": {
    "name": "Qobustan",
    "slug": "qobustan"
  },
  "AZISM": {
    "name": "İsmayıllı",
    "slug": "ismayll"
  },
  "AZYEV": {
    "name": "Yevlakh Rayon",
    "slug": "yevlakh-rayon"
  },
  "AZGA": {
    "name": "Gəncə",
    "slug": "gnc"
  },
  "AZMI": {
    "name": "Mingəçevir",
    "slug": "mingevir"
  },
  "AZGOY": {
    "name": "Göyçay",
    "slug": "gyay"
  },
  "AZAGS": {
    "name": "Ağdaş",
    "slug": "ada"
  },
  "AZAGC": {
    "name": "Ağcabədi",
    "slug": "acabdi"
  },
  "AZXA": {
    "name": "Stepanakert",
    "slug": "stepanakert"
  },
  "AZYE": {
    "name": "Yevlakh",
    "slug": "yevlakh"
  },
  "AZNA": {
    "name": "Naftalan",
    "slug": "naftalan"
  },
  "AZSA": {
    "name": "Şəki",
    "slug": "ki"
  },
  "AZSUS": {
    "name": "Şuşa",
    "slug": "ua"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return azeSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return azeSvgToSlugMapping[regionId];
}
