// SVG region mapping for Burundi
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const bdiSvgToSlugMapping: RegionMapping = {
  "BIBB": {
    "name": "Bubanza",
    "slug": "bubanza"
  },
  "BIBM": {
    "name": "Bujumbura Mairie",
    "slug": "bujumbura-mairie"
  },
  "BIBL": {
    "name": "Bujumbura Rural",
    "slug": "bujumbura-rural"
  },
  "BIBR": {
    "name": "Bururi",
    "slug": "bururi"
  },
  "BICA": {
    "name": "Cankuzo",
    "slug": "cankuzo"
  },
  "BICI": {
    "name": "Cibitoke",
    "slug": "cibitoke"
  },
  "BIGI": {
    "name": "Gitega",
    "slug": "gitega"
  },
  "BIKR": {
    "name": "Karuzi",
    "slug": "karuzi"
  },
  "BIKY": {
    "name": "Kayanza",
    "slug": "kayanza"
  },
  "BIKI": {
    "name": "Kirundo",
    "slug": "kirundo"
  },
  "BIMA": {
    "name": "Makamba",
    "slug": "makamba"
  },
  "BIMU": {
    "name": "Muramvya",
    "slug": "muramvya"
  },
  "BIMY": {
    "name": "Muyinga",
    "slug": "muyinga"
  },
  "BIMW": {
    "name": "Mwaro",
    "slug": "mwaro"
  },
  "BING": {
    "name": "Ngozi",
    "slug": "ngozi"
  },
  "BIRM": {
    "name": "Rumonge",
    "slug": "rumonge"
  },
  "BIRT": {
    "name": "Rutana",
    "slug": "rutana"
  },
  "BIRY": {
    "name": "Ruyigi",
    "slug": "ruyigi"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return bdiSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return bdiSvgToSlugMapping[regionId];
}
