// SVG region mapping for Belgium
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const belSvgToSlugMapping: RegionMapping = {
  "BEBRU": {
    "name": "Brussels",
    "slug": "brussels"
  },
  "BEVLG": {
    "name": "Flanders",
    "slug": "flanders"
  },
  "BEWAL": {
    "name": "Wallonia",
    "slug": "wallonia"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return belSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return belSvgToSlugMapping[regionId];
}
