// SVG region mapping for Benin
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const benSvgToSlugMapping: RegionMapping = {
  "BJAL": {
    "name": "Alibori",
    "slug": "alibori"
  },
  "BJBO": {
    "name": "Borgou",
    "slug": "borgou"
  },
  "BJPL": {
    "name": "Plateau",
    "slug": "plateau"
  },
  "BJCO": {
    "name": "Collines",
    "slug": "collines"
  },
  "BJOU": {
    "name": "Ouémé",
    "slug": "oum"
  },
  "BJAK": {
    "name": "Atakora",
    "slug": "atakora"
  },
  "BJDO": {
    "name": "Donga",
    "slug": "donga"
  },
  "BJZO": {
    "name": "Zou",
    "slug": "zou"
  },
  "BJKO": {
    "name": "Kouffo",
    "slug": "kouffo"
  },
  "BJMO": {
    "name": "Mono",
    "slug": "mono"
  },
  "BJAQ": {
    "name": "Atlantique",
    "slug": "atlantique"
  },
  "BJLI": {
    "name": "Littoral",
    "slug": "littoral"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return benSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return benSvgToSlugMapping[regionId];
}
