// SVG region mapping for Burkina Faso
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const bfaSvgToSlugMapping: RegionMapping = {
  "BFTAP": {
    "name": "Tapoa",
    "slug": "tapoa"
  },
  "BFKMP": {
    "name": "Kompienga",
    "slug": "kompienga"
  },
  "BFLER": {
    "name": "Léraba",
    "slug": "lraba"
  },
  "BFCOM": {
    "name": "Komoé",
    "slug": "komo"
  },
  "BFPON": {
    "name": "Poni",
    "slug": "poni"
  },
  "BFNOU": {
    "name": "Noumbiel",
    "slug": "noumbiel"
  },
  "BFOUD": {
    "name": "Oudalan",
    "slug": "oudalan"
  },
  "BFSOM": {
    "name": "Soum",
    "slug": "soum"
  },
  "BFLOR": {
    "name": "Loroum",
    "slug": "loroum"
  },
  "BFYAT": {
    "name": "Yatenga",
    "slug": "yatenga"
  },
  "BFSOR": {
    "name": "Sourou",
    "slug": "sourou"
  },
  "BFKOS": {
    "name": "Kossi",
    "slug": "kossi"
  },
  "BFBAN": {
    "name": "Banwa",
    "slug": "banwa"
  },
  "BFHOU": {
    "name": "Houet",
    "slug": "houet"
  },
  "BFKEN": {
    "name": "Kénédougou",
    "slug": "kndougou"
  },
  "BFSEN": {
    "name": "Séno",
    "slug": "sno"
  },
  "BFYAG": {
    "name": "Yagha",
    "slug": "yagha"
  },
  "BFKMD": {
    "name": "Komondjari",
    "slug": "komondjari"
  },
  "BFKOP": {
    "name": "Koulpélogo",
    "slug": "koulplogo"
  },
  "BFBLG": {
    "name": "Boulgou",
    "slug": "boulgou"
  },
  "BFNAO": {
    "name": "Nahouri",
    "slug": "nahouri"
  },
  "BFSIS": {
    "name": "Sissili",
    "slug": "sissili"
  },
  "BFIOB": {
    "name": "Ioba",
    "slug": "ioba"
  },
  "BFBAL": {
    "name": "Balé",
    "slug": "bal"
  },
  "BFSNG": {
    "name": "Sanguié",
    "slug": "sangui"
  },
  "BFTUI": {
    "name": "TUI",
    "slug": "tui"
  },
  "BFBGR": {
    "name": "Bougouriba",
    "slug": "bougouriba"
  },
  "BFMOU": {
    "name": "Mou Houn",
    "slug": "mou-houn"
  },
  "BFKOT": {
    "name": "Kouritenga",
    "slug": "kouritenga"
  },
  "BFGAN": {
    "name": "Ganzourgou",
    "slug": "ganzourgou"
  },
  "BFZOU": {
    "name": "Zoundwéogo",
    "slug": "zoundwogo"
  },
  "BFZIR": {
    "name": "Ziro",
    "slug": "ziro"
  },
  "BFBLK": {
    "name": "Boulkiemdé",
    "slug": "boulkiemd"
  },
  "BFKAD": {
    "name": "Kadiogo",
    "slug": "kadiogo"
  },
  "BFOUB": {
    "name": "Oubritenga",
    "slug": "oubritenga"
  },
  "BFGOU": {
    "name": "Gourma",
    "slug": "gourma"
  },
  "BFGNA": {
    "name": "Gnagna",
    "slug": "gnagna"
  },
  "BFBAZ": {
    "name": "Bazéga",
    "slug": "bazga"
  },
  "BFKOW": {
    "name": "Kourwéogo",
    "slug": "kourwogo"
  },
  "BFNAY": {
    "name": "Nayala",
    "slug": "nayala"
  },
  "BFPAS": {
    "name": "Passoré",
    "slug": "passor"
  },
  "BFZON": {
    "name": "Zondoma",
    "slug": "zondoma"
  },
  "BFNAM": {
    "name": "Namentenga",
    "slug": "namentenga"
  },
  "BFSMT": {
    "name": "Sanmatenga",
    "slug": "sanmatenga"
  },
  "BFBAM": {
    "name": "Bam",
    "slug": "bam"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return bfaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return bfaSvgToSlugMapping[regionId];
}
