// SVG region mapping for Bangladesh
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const bgdSvgToSlugMapping: RegionMapping = {
  "BDA": {
    "name": "Bagar Hat",
    "slug": "bagar-hat"
  },
  "BDB": {
    "name": "Bagar Hat",
    "slug": "bagar-hat"
  },
  "BDC": {
    "name": "Chandpur",
    "slug": "chandpur"
  },
  "BDD": {
    "name": "Bandarban",
    "slug": "bandarban"
  },
  "BDH": {
    "name": "Bagar Hat",
    "slug": "bagar-hat"
  },
  "BDE": {
    "name": "Feni",
    "slug": "feni"
  },
  "BDF": {
    "name": "Faridpur",
    "slug": "faridpur"
  },
  "BDG": {
    "name": "Bagar Hat",
    "slug": "bagar-hat"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return bgdSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return bgdSvgToSlugMapping[regionId];
}
