// SVG region mapping for Bulgaria
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const bgrSvgToSlugMapping: RegionMapping = {
  "BG02": {
    "name": "Burgas",
    "slug": "burgas"
  },
  "BG28": {
    "name": "Yambol",
    "slug": "yambol"
  },
  "BG26": {
    "name": "Haskovo",
    "slug": "haskovo"
  },
  "BG05": {
    "name": "Vidin",
    "slug": "vidin"
  },
  "BG14": {
    "name": "Pernik",
    "slug": "pernik"
  },
  "BG23": {
    "name": "Sofia",
    "slug": "sofia"
  },
  "BG12": {
    "name": "Montana",
    "slug": "montana"
  },
  "BG10": {
    "name": "Kyustendil",
    "slug": "kyustendil"
  },
  "BG01": {
    "name": "Blagoevgrad",
    "slug": "blagoevgrad"
  },
  "BG19": {
    "name": "Silistra",
    "slug": "silistra"
  },
  "BG18": {
    "name": "Ruse",
    "slug": "ruse"
  },
  "BG08": {
    "name": "Dobrich",
    "slug": "dobrich"
  },
  "BG06": {
    "name": "Vratsa",
    "slug": "vratsa"
  },
  "BG15": {
    "name": "Pleven",
    "slug": "pleven"
  },
  "BG04": {
    "name": "Veliko Tarnovo",
    "slug": "veliko-tarnovo"
  },
  "BG09": {
    "name": "Kardzhali",
    "slug": "kardzhali"
  },
  "BG21": {
    "name": "Smolyan",
    "slug": "smolyan"
  },
  "BG03": {
    "name": "Varna",
    "slug": "varna"
  },
  "BG16": {
    "name": "Plovdiv",
    "slug": "plovdiv"
  },
  "BG24": {
    "name": "Stara Zagora",
    "slug": "stara-zagora"
  },
  "BG20": {
    "name": "Sliven",
    "slug": "sliven"
  },
  "BG27": {
    "name": "Shumen",
    "slug": "shumen"
  },
  "BG17": {
    "name": "Razgrad",
    "slug": "razgrad"
  },
  "BG25": {
    "name": "Targovishte",
    "slug": "targovishte"
  },
  "BG07": {
    "name": "Gabrovo",
    "slug": "gabrovo"
  },
  "BG13": {
    "name": "Pazardzhik",
    "slug": "pazardzhik"
  },
  "BG11": {
    "name": "Lovech",
    "slug": "lovech"
  },
  "BG22": {
    "name": "Grad Sofiya",
    "slug": "grad-sofiya"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return bgrSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return bgrSvgToSlugMapping[regionId];
}
