// SVG region mapping for Bahrain
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const bhrSvgToSlugMapping: RegionMapping = {
  "BH13": {
    "name": "Al Manāmah",
    "slug": "al-manmah"
  },
  "BH17": {
    "name": "Ash Shamālīyah",
    "slug": "ash-shamlyah"
  },
  "BH14": {
    "name": "Al Janūbīyah",
    "slug": "al-janbyah"
  },
  "BH15": {
    "name": "Al Muḩarraq",
    "slug": "al-muarraq"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return bhrSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return bhrSvgToSlugMapping[regionId];
}
