// SVG region mapping for Bahamas
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const bhsSvgToSlugMapping: RegionMapping = {
  "BSAK": {
    "name": "Acklins",
    "slug": "acklins"
  },
  "BSBY": {
    "name": "Berry Islands",
    "slug": "berry-islands"
  },
  "BSBI": {
    "name": "Biminis",
    "slug": "biminis"
  },
  "BSBP": {
    "name": "Black Point",
    "slug": "black-point"
  },
  "BSCI": {
    "name": "Cat Island",
    "slug": "cat-island"
  },
  "BSCO": {
    "name": "Central Abaco",
    "slug": "central-abaco"
  },
  "BSCS": {
    "name": "Central Andros",
    "slug": "central-andros"
  },
  "BSCE": {
    "name": "Central Eleuthera",
    "slug": "central-eleuthera"
  },
  "BSFP": {
    "name": "City of Freeport",
    "slug": "city-of-freeport"
  },
  "BSCK": {
    "name": "Crooked Island",
    "slug": "crooked-island"
  },
  "BSEG": {
    "name": "East Grand Bahama",
    "slug": "east-grand-bahama"
  },
  "BSEX": {
    "name": "Exuma",
    "slug": "exuma"
  },
  "BSGC": {
    "name": "Grand Cay",
    "slug": "grand-cay"
  },
  "BSHI": {
    "name": "Harbour Island",
    "slug": "harbour-island"
  },
  "BSHT": {
    "name": "Hope Town",
    "slug": "hope-town"
  },
  "BSIN": {
    "name": "Inagua",
    "slug": "inagua"
  },
  "BSLI": {
    "name": "Long Island",
    "slug": "long-island"
  },
  "BSMC": {
    "name": "Mangrove Cay",
    "slug": "mangrove-cay"
  },
  "BSMG": {
    "name": "Mayaguana",
    "slug": "mayaguana"
  },
  "BSMI": {
    "name": "Moore's Island",
    "slug": "moores-island"
  },
  "BSNP": {
    "name": "New Providence",
    "slug": "new-providence"
  },
  "BSNO": {
    "name": "North Abaco",
    "slug": "north-abaco"
  },
  "BSNS": {
    "name": "North Andros",
    "slug": "north-andros"
  },
  "BSNE": {
    "name": "North Eleuthera",
    "slug": "north-eleuthera"
  },
  "BSRI": {
    "name": "Ragged Island",
    "slug": "ragged-island"
  },
  "BSRC": {
    "name": "Rum Cay",
    "slug": "rum-cay"
  },
  "BSSS": {
    "name": "San Salvador",
    "slug": "san-salvador"
  },
  "BSSO": {
    "name": "South Abaco",
    "slug": "south-abaco"
  },
  "BSSA": {
    "name": "South Andros",
    "slug": "south-andros"
  },
  "BSSE": {
    "name": "South Eleuthera",
    "slug": "south-eleuthera"
  },
  "BSSW": {
    "name": "Spanish Wells",
    "slug": "spanish-wells"
  },
  "BSWG": {
    "name": "West Grand Bahama",
    "slug": "west-grand-bahama"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return bhsSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return bhsSvgToSlugMapping[regionId];
}
