// SVG region mapping for Bosnia and Herzegovina
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const bihSvgToSlugMapping: RegionMapping = {
  "BASRP": {
    "name": "Republika Srpska",
    "slug": "republika-srpska"
  },
  "BABRC": {
    "name": "Brčko distrikt",
    "slug": "brko-distrikt"
  },
  "BABIH": {
    "name": "Federacija Bosne i Hercegovine",
    "slug": "federacija-bosne-i-hercegovine"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return bihSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return bihSvgToSlugMapping[regionId];
}
