// SVG region mapping for Belarus
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const blrSvgToSlugMapping: RegionMapping = {
  "BYHO": {
    "name": "Gomel",
    "slug": "gomel"
  },
  "BYBR": {
    "name": "Brest",
    "slug": "brest"
  },
  "BYVI": {
    "name": "Vitebsk",
    "slug": "vitebsk"
  },
  "BYHR": {
    "name": "Grodno",
    "slug": "grodno"
  },
  "BYMA": {
    "name": "Mogilev",
    "slug": "mogilev"
  },
  "BYMI": {
    "name": "Minsk",
    "slug": "minsk"
  },
  "BYHM": {
    "name": "City of Minsk",
    "slug": "city-of-minsk"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return blrSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return blrSvgToSlugMapping[regionId];
}
