// SVG region mapping for Belize
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const blzSvgToSlugMapping: RegionMapping = {
  "BZCY": {
    "name": "Cayo",
    "slug": "cayo"
  },
  "BZOW": {
    "name": "Orange Walk",
    "slug": "orange-walk"
  },
  "BZCZL": {
    "name": "Corozal",
    "slug": "corozal"
  },
  "BZTOL": {
    "name": "Toledo",
    "slug": "toledo"
  },
  "BZSC": {
    "name": "Stann Creek",
    "slug": "stann-creek"
  },
  "BZBZ": {
    "name": "Belize",
    "slug": "belize"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return blzSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return blzSvgToSlugMapping[regionId];
}
