// SVG region mapping for Bermuda
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const bmuSvgToSlugMapping: RegionMapping = {
  "BMHAM": {
    "name": "Hamilton",
    "slug": "hamilton"
  },
  "BMSMI": {
    "name": "Smith's",
    "slug": "smiths"
  },
  "BMDEV": {
    "name": "Devonshire",
    "slug": "devonshire"
  },
  "BMPEM": {
    "name": "Pembroke",
    "slug": "pembroke"
  },
  "BMHA": {
    "name": "City of Hamilton",
    "slug": "city-of-hamilton"
  },
  "BMPAG": {
    "name": "Paget",
    "slug": "paget"
  },
  "BMWAR": {
    "name": "Warwick",
    "slug": "warwick"
  },
  "BMSOU": {
    "name": "Southampton",
    "slug": "southampton"
  },
  "BMSAN": {
    "name": "Sandys",
    "slug": "sandys"
  },
  "BMSGE": {
    "name": "Saint George's",
    "slug": "saint-georges"
  },
  "BMSG": {
    "name": "City of Saint George",
    "slug": "city-of-saint-george"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return bmuSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return bmuSvgToSlugMapping[regionId];
}
