// SVG region mapping for Bolivia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const bolSvgToSlugMapping: RegionMapping = {
  "BOL": {
    "name": "La Paz",
    "slug": "la-paz"
  },
  "BOO": {
    "name": "Cochabamba",
    "slug": "cochabamba"
  },
  "BOP": {
    "name": "La Paz",
    "slug": "la-paz"
  },
  "BOT": {
    "name": "Potosi",
    "slug": "potosi"
  },
  "BOS": {
    "name": "Chuquisaca",
    "slug": "chuquisaca"
  },
  "BOH": {
    "name": "Chuquisaca",
    "slug": "chuquisaca"
  },
  "BON": {
    "name": "Beni",
    "slug": "beni"
  },
  "BOB": {
    "name": "Beni",
    "slug": "beni"
  },
  "BOC": {
    "name": "Chuquisaca",
    "slug": "chuquisaca"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return bolSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return bolSvgToSlugMapping[regionId];
}
