// SVG region mapping for Brazil
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const braSvgToSlugMapping: RegionMapping = {
  "BRRS": {
    "name": "Rio Grande do Sul",
    "slug": "rio-grande-do-sul"
  },
  "BRRR": {
    "name": "Roraima",
    "slug": "roraima"
  },
  "BRPA": {
    "name": "Pará",
    "slug": "par"
  },
  "BRAC": {
    "name": "Acre",
    "slug": "acre"
  },
  "BRAP": {
    "name": "Amapá",
    "slug": "amap"
  },
  "BRMS": {
    "name": "Mato Grosso do Sul",
    "slug": "mato-grosso-do-sul"
  },
  "BRPR": {
    "name": "Paraná",
    "slug": "paran"
  },
  "BRSC": {
    "name": "Santa Catarina",
    "slug": "santa-catarina"
  },
  "BRAM": {
    "name": "Amazonas",
    "slug": "amazonas"
  },
  "BRRO": {
    "name": "Rondônia",
    "slug": "rondnia"
  },
  "BRMT": {
    "name": "Mato Grosso",
    "slug": "mato-grosso"
  },
  "BRMA": {
    "name": "Maranhão",
    "slug": "maranho"
  },
  "BRPI": {
    "name": "Piauí",
    "slug": "piau"
  },
  "BRCE": {
    "name": "Ceará",
    "slug": "cear"
  },
  "BRRN": {
    "name": "Rio Grande do Norte",
    "slug": "rio-grande-do-norte"
  },
  "BRPB": {
    "name": "Paraíba",
    "slug": "paraba"
  },
  "BRPE": {
    "name": "Pernambuco",
    "slug": "pernambuco"
  },
  "BRAL": {
    "name": "Alagoas",
    "slug": "alagoas"
  },
  "BRSE": {
    "name": "Sergipe",
    "slug": "sergipe"
  },
  "BRBA": {
    "name": "Bahia",
    "slug": "bahia"
  },
  "BRES": {
    "name": "Espírito Santo",
    "slug": "esprito-santo"
  },
  "BRRJ": {
    "name": "Rio de Janeiro",
    "slug": "rio-de-janeiro"
  },
  "BRSP": {
    "name": "São Paulo",
    "slug": "so-paulo"
  },
  "BRGO": {
    "name": "Goiás",
    "slug": "gois"
  },
  "BRDF": {
    "name": "Distrito Federal",
    "slug": "distrito-federal"
  },
  "BRMG": {
    "name": "Minas Gerais",
    "slug": "minas-gerais"
  },
  "BRTO": {
    "name": "Tocantins",
    "slug": "tocantins"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return braSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return braSvgToSlugMapping[regionId];
}
