// SVG region mapping for Barbados
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const brbSvgToSlugMapping: RegionMapping = {
  "BB06": {
    "name": "Saint Joseph",
    "slug": "saint-joseph"
  },
  "BB02": {
    "name": "Saint Andrew",
    "slug": "saint-andrew"
  },
  "BB09": {
    "name": "Saint Peter",
    "slug": "saint-peter"
  },
  "BB07": {
    "name": "Saint Lucy",
    "slug": "saint-lucy"
  },
  "BB04": {
    "name": "Saint James",
    "slug": "saint-james"
  },
  "BB08": {
    "name": "Saint Michael",
    "slug": "saint-michael"
  },
  "BB01": {
    "name": "Christ Church",
    "slug": "christ-church"
  },
  "BB10": {
    "name": "Saint Philip",
    "slug": "saint-philip"
  },
  "BB05": {
    "name": "Saint John",
    "slug": "saint-john"
  },
  "BB03": {
    "name": "Saint George",
    "slug": "saint-george"
  },
  "BB11": {
    "name": "Saint Thomas",
    "slug": "saint-thomas"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return brbSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return brbSvgToSlugMapping[regionId];
}
