// SVG region mapping for Brunei
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const brnSvgToSlugMapping: RegionMapping = {
  "BNTE": {
    "name": "Temburong",
    "slug": "temburong"
  },
  "BNBM": {
    "name": "Brunei and Muara",
    "slug": "brunei-and-muara"
  },
  "BNTU": {
    "name": "Tutong",
    "slug": "tutong"
  },
  "BNBE": {
    "name": "Belait",
    "slug": "belait"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return brnSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return brnSvgToSlugMapping[regionId];
}
