// SVG region mapping for Bhutan
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const btnSvgToSlugMapping: RegionMapping = {
  "BTTY": {
    "name": "Tashi Yangtse",
    "slug": "tashi-yangtse"
  },
  "BT44": {
    "name": "Lhuntshi",
    "slug": "lhuntshi"
  },
  "BT33": {
    "name": "Bumthang",
    "slug": "bumthang"
  },
  "BT13": {
    "name": "13",
    "slug": "13"
  },
  "BT14": {
    "name": "Samchi",
    "slug": "samchi"
  },
  "BT12": {
    "name": "Chhukha",
    "slug": "chhukha"
  },
  "BT31": {
    "name": "Geylegphug",
    "slug": "geylegphug"
  },
  "BT34": {
    "name": "Shemgang",
    "slug": "shemgang"
  },
  "BT45": {
    "name": "Samdrup Jongkhar",
    "slug": "samdrup-jongkhar"
  },
  "BT41": {
    "name": "Tashigang",
    "slug": "tashigang"
  },
  "BT15": {
    "name": "Thimphu",
    "slug": "thimphu"
  },
  "BT11": {
    "name": "Paro",
    "slug": "paro"
  },
  "BTGA": {
    "name": "Gasa",
    "slug": "gasa"
  },
  "BT21": {
    "name": "Chirang",
    "slug": "chirang"
  },
  "BT24": {
    "name": "Wangdi Phodrang",
    "slug": "wangdi-phodrang"
  },
  "BT22": {
    "name": "Daga",
    "slug": "daga"
  },
  "BT23": {
    "name": "Punakha",
    "slug": "punakha"
  },
  "BT42": {
    "name": "Mongar",
    "slug": "mongar"
  },
  "BT32": {
    "name": "Tongsa",
    "slug": "tongsa"
  },
  "BT43": {
    "name": "Pemagatsel",
    "slug": "pemagatsel"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return btnSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return btnSvgToSlugMapping[regionId];
}
