// SVG region mapping for Botswana
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const bwaSvgToSlugMapping: RegionMapping = {
  "BWGA": {
    "name": "GABORONE",
    "slug": "gaborone"
  },
  "BWFR": {
    "name": "FRANCISTOWN",
    "slug": "francistown"
  },
  "BWLO": {
    "name": "LOBATSE",
    "slug": "lobatse"
  },
  "BWSP": {
    "name": "SELIBE PHIKWE",
    "slug": "selibe-phikwe"
  },
  "BWJW": {
    "name": "JWANENG",
    "slug": "jwaneng"
  },
  "BWST": {
    "name": "SOWA TOWN",
    "slug": "sowa-town"
  },
  "BWSO": {
    "name": "SOUTHERN",
    "slug": "southern"
  },
  "BWSE": {
    "name": "SOUTH EAST",
    "slug": "south-east"
  },
  "BWKW": {
    "name": "KWENENG",
    "slug": "kweneng"
  },
  "BWKL": {
    "name": "KGATLENG",
    "slug": "kgatleng"
  },
  "BWCE": {
    "name": "CENTRAL",
    "slug": "central"
  },
  "BWNE": {
    "name": "NORTH EAST",
    "slug": "north-east"
  },
  "BWNW": {
    "name": "NORTH WEST",
    "slug": "north-west"
  },
  "BWCH": {
    "name": "CHOBE",
    "slug": "chobe"
  },
  "BWGH": {
    "name": "GHANZI",
    "slug": "ghanzi"
  },
  "BWKG": {
    "name": "KGALAGADI",
    "slug": "kgalagadi"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return bwaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return bwaSvgToSlugMapping[regionId];
}
