// SVG region mapping for Central African Republic
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const cafSvgToSlugMapping: RegionMapping = {
  "CFVK": {
    "name": "Vakaga",
    "slug": "vakaga"
  },
  "CFHK": {
    "name": "Haute-Kotto",
    "slug": "haute-kotto"
  },
  "CFHM": {
    "name": "Haut-Mbomou",
    "slug": "haut-mbomou"
  },
  "CFKG": {
    "name": "Kémo",
    "slug": "kmo"
  },
  "CFUK": {
    "name": "Ouaka",
    "slug": "ouaka"
  },
  "CFBK": {
    "name": "Basse-Kotto",
    "slug": "basse-kotto"
  },
  "CFMB": {
    "name": "Mbomou",
    "slug": "mbomou"
  },
  "CFMP": {
    "name": "Ombella-M'Poko",
    "slug": "ombella-mpoko"
  },
  "CFBGF": {
    "name": "Bangui",
    "slug": "bangui"
  },
  "CFLB": {
    "name": "Lobaye",
    "slug": "lobaye"
  },
  "CFBB": {
    "name": "Bamingui-Bangoran",
    "slug": "bamingui-bangoran"
  },
  "CFAC": {
    "name": "Ouham",
    "slug": "ouham"
  },
  "CFOP": {
    "name": "Ouham-Pendé",
    "slug": "ouham-pend"
  },
  "CFSE": {
    "name": "Sangha-Mbaéré",
    "slug": "sangha-mbar"
  },
  "CFNM": {
    "name": "Nana-Mambéré",
    "slug": "nana-mambr"
  },
  "CFHS": {
    "name": "Mambéré-Kadéï",
    "slug": "mambr-kad"
  },
  "CFKB": {
    "name": "Nana-Grébizi",
    "slug": "nana-grbizi"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return cafSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return cafSvgToSlugMapping[regionId];
}
