// SVG region mapping for Canada
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const canSvgToSlugMapping: RegionMapping = {
  "CABC": {
    "name": "British Columbia",
    "slug": "british-columbia"
  },
  "CAAB": {
    "name": "Alberta",
    "slug": "alberta"
  },
  "CASK": {
    "name": "Saskatchewan",
    "slug": "saskatchewan"
  },
  "CAMB": {
    "name": "Manitoba",
    "slug": "manitoba"
  },
  "CAON": {
    "name": "Ontario",
    "slug": "ontario"
  },
  "CAQC": {
    "name": "Québec",
    "slug": "qubec"
  },
  "CANB": {
    "name": "New Brunswick",
    "slug": "new-brunswick"
  },
  "CAYT": {
    "name": "Yukon",
    "slug": "yukon"
  },
  "CANU": {
    "name": "Nunavut",
    "slug": "nunavut"
  },
  "CANL": {
    "name": "Newfoundland and Labrador",
    "slug": "newfoundland-and-labrador"
  },
  "CANS": {
    "name": "Nova Scotia",
    "slug": "nova-scotia"
  },
  "CANT": {
    "name": "Northwest Territories",
    "slug": "northwest-territories"
  },
  "CAPE": {
    "name": "Prince Edward Island",
    "slug": "prince-edward-island"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return canSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return canSvgToSlugMapping[regionId];
}
