// SVG region mapping for Switzerland
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const cheSvgToSlugMapping: RegionMapping = {
  "CHVS": {
    "name": "Valais",
    "slug": "valais"
  },
  "CHTI": {
    "name": "Ticino",
    "slug": "ticino"
  },
  "CHGR": {
    "name": "Graubünden",
    "slug": "graubnden"
  },
  "CHSH": {
    "name": "Schaffhausen",
    "slug": "schaffhausen"
  },
  "CHTG": {
    "name": "Thurgau",
    "slug": "thurgau"
  },
  "CHZH": {
    "name": "Zürich",
    "slug": "zrich"
  },
  "CHAG": {
    "name": "Aargau",
    "slug": "aargau"
  },
  "CHBS": {
    "name": "Basel-Stadt",
    "slug": "basel-stadt"
  },
  "CHBL": {
    "name": "Basel-Landschaft",
    "slug": "basel-landschaft"
  },
  "CHSG": {
    "name": "Sankt Gallen",
    "slug": "sankt-gallen"
  },
  "CHSO": {
    "name": "Solothurn",
    "slug": "solothurn"
  },
  "CHJU": {
    "name": "Jura",
    "slug": "jura"
  },
  "CHGE": {
    "name": "Genève",
    "slug": "genve"
  },
  "CHVD": {
    "name": "Vaud",
    "slug": "vaud"
  },
  "CHNE": {
    "name": "Neuchâtel",
    "slug": "neuchtel"
  },
  "CHBE": {
    "name": "Bern",
    "slug": "bern"
  },
  "CHLU": {
    "name": "Lucerne",
    "slug": "lucerne"
  },
  "CHZG": {
    "name": "ZG",
    "slug": "zg"
  },
  "CHUR": {
    "name": "Fribourg",
    "slug": "fribourg"
  },
  "CHSZ": {
    "name": "Schwyz",
    "slug": "schwyz"
  },
  "CHGL": {
    "name": "Glarus",
    "slug": "glarus"
  },
  "CHNW": {
    "name": "Nidwalden",
    "slug": "nidwalden"
  },
  "CHFR": {
    "name": "Fribourg",
    "slug": "fribourg"
  },
  "CHOW": {
    "name": "Obwalden",
    "slug": "obwalden"
  },
  "CHAR": {
    "name": "Appenzell Ausserrhoden",
    "slug": "appenzell-ausserrhoden"
  },
  "CHAI": {
    "name": "Appenzell Innerrhoden",
    "slug": "appenzell-innerrhoden"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return cheSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return cheSvgToSlugMapping[regionId];
}
