// SVG region mapping for Chile
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const chlSvgToSlugMapping: RegionMapping = {
  "CLAP": {
    "name": "Arica y Parinacota",
    "slug": "arica-y-parinacota"
  },
  "CLTA": {
    "name": "Tarapacá",
    "slug": "tarapac"
  },
  "CLAN": {
    "name": "Antofagasta",
    "slug": "antofagasta"
  },
  "CLAT": {
    "name": "Atacama",
    "slug": "atacama"
  },
  "CLCO": {
    "name": "Coquimbo",
    "slug": "coquimbo"
  },
  "CLRM": {
    "name": "Región Metropolitana de Santiago",
    "slug": "regin-metropolitana-de-santiago"
  },
  "CLVS": {
    "name": "Valparaíso",
    "slug": "valparaso"
  },
  "CLML": {
    "name": "Maule",
    "slug": "maule"
  },
  "CLLI": {
    "name": "Libertador General Bernardo O'Higgins",
    "slug": "libertador-general-bernardo-ohiggins"
  },
  "CLNB": {
    "name": "Ñuble",
    "slug": "uble"
  },
  "CLAR": {
    "name": "La Araucanía",
    "slug": "la-araucana"
  },
  "CLBI": {
    "name": "Bío-Bío",
    "slug": "bo-bo"
  },
  "CLLR": {
    "name": "Los Ríos",
    "slug": "los-ros"
  },
  "CLLL": {
    "name": "Los Lagos",
    "slug": "los-lagos"
  },
  "CLAI": {
    "name": "Aisén del General Carlos Ibáñez del Campo",
    "slug": "aisn-del-general-carlos-ibez-del-campo"
  },
  "CLMA": {
    "name": "Magallanes y Antártica Chilena",
    "slug": "magallanes-y-antrtica-chilena"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return chlSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return chlSvgToSlugMapping[regionId];
}
