// SVG region mapping for China
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const chnSvgToSlugMapping: RegionMapping = {
  "CNSN": {
    "name": "Shaanxi Province",
    "slug": "shaanxi-province"
  },
  "CNSH": {
    "name": "Shanghai Municipality",
    "slug": "shanghai-municipality"
  },
  "CNCQ": {
    "name": "Chongqing Municipality",
    "slug": "chongqing-municipality"
  },
  "CNZJ": {
    "name": "Zhejiang Province",
    "slug": "zhejiang-province"
  },
  "CNJX": {
    "name": "Jiangxi Province",
    "slug": "jiangxi-province"
  },
  "CNYN": {
    "name": "Yunnan Province",
    "slug": "yunnan-province"
  },
  "CNSD": {
    "name": "Shandong Province",
    "slug": "shandong-province"
  },
  "CNLN": {
    "name": "Liaoning Province",
    "slug": "liaoning-province"
  },
  "CNXZ": {
    "name": "Tibet Autonomous Region",
    "slug": "tibet-autonomous-region"
  },
  "CNGS": {
    "name": "Gansu province",
    "slug": "gansu-province"
  },
  "CNHK": {
    "name": "Hong Kong Special Administrative Region",
    "slug": "hong-kong-special-administrative-region"
  },
  "CNQH": {
    "name": "Qinghai Province",
    "slug": "qinghai-province"
  },
  "CNBJ": {
    "name": "Beijing Municipality",
    "slug": "beijing-municipality"
  },
  "CNMO": {
    "name": "Macao Special Administrative Region",
    "slug": "macao-special-administrative-region"
  },
  "CNNM": {
    "name": "Inner Mongolia Autonomous Region",
    "slug": "inner-mongolia-autonomous-region"
  },
  "CNHB": {
    "name": "Hubei Province",
    "slug": "hubei-province"
  },
  "CNAH": {
    "name": "Anhui Province",
    "slug": "anhui-province"
  },
  "CNGZ": {
    "name": "Guizhou Province",
    "slug": "guizhou-province"
  },
  "CNNX": {
    "name": "Ningxia Hui Autonomous Region",
    "slug": "ningxia-hui-autonomous-region"
  },
  "CNJS": {
    "name": "Jiangsu Province",
    "slug": "jiangsu-province"
  },
  "CNXJ": {
    "name": "Xinjiang Uygur Autonomous Region",
    "slug": "xinjiang-uygur-autonomous-region"
  },
  "CNSX": {
    "name": "Shanxi Province",
    "slug": "shanxi-province"
  },
  "CNHN": {
    "name": "Hunan Province",
    "slug": "hunan-province"
  },
  "CNSC": {
    "name": "Sichuan Province",
    "slug": "sichuan-province"
  },
  "CNGX": {
    "name": "Guangxi Zhuang Autonomous Region",
    "slug": "guangxi-zhuang-autonomous-region"
  },
  "CNJL": {
    "name": "Jilin Province",
    "slug": "jilin-province"
  },
  "CNTW": {
    "name": "Taiwan Province",
    "slug": "taiwan-province"
  },
  "CNHE": {
    "name": "Hebei Province",
    "slug": "hebei-province"
  },
  "CNTJ": {
    "name": "Tianjin Municipality",
    "slug": "tianjin-municipality"
  },
  "CNGD": {
    "name": "Guangdong Province",
    "slug": "guangdong-province"
  },
  "CNFJ": {
    "name": "Fujian Province",
    "slug": "fujian-province"
  },
  "CNHL": {
    "name": "Heilongjiang Province",
    "slug": "heilongjiang-province"
  },
  "CNHA": {
    "name": "Henan Province",
    "slug": "henan-province"
  },
  "CNHI": {
    "name": "Hainan Province",
    "slug": "hainan-province"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return chnSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return chnSvgToSlugMapping[regionId];
}
