// SVG region mapping for Côte d'Ivoire
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const civSvgToSlugMapping: RegionMapping = {
  "CIDN": {
    "name": "Denguélé",
    "slug": "dengul"
  },
  "CIZZ": {
    "name": "Zanzan",
    "slug": "zanzan"
  },
  "CILG": {
    "name": "Lagunes",
    "slug": "lagunes"
  },
  "CISV": {
    "name": "Savanes",
    "slug": "savanes"
  },
  "CIMG": {
    "name": "Montagnes",
    "slug": "montagnes"
  },
  "CIBS": {
    "name": "Bas-Sassandra",
    "slug": "bas-sassandra"
  },
  "CISM": {
    "name": "Sassandra-Marahoué",
    "slug": "sassandra-marahou"
  },
  "CIVB": {
    "name": "Vallée du Bandama",
    "slug": "valle-du-bandama"
  },
  "CIWR": {
    "name": "Woroba",
    "slug": "woroba"
  },
  "CIYM": {
    "name": "Yamoussoukro",
    "slug": "yamoussoukro"
  },
  "CIGD": {
    "name": "Gôh-Djiboua",
    "slug": "gh-djiboua"
  },
  "CIAB": {
    "name": "Abidjan",
    "slug": "abidjan"
  },
  "CILC": {
    "name": "Lacs",
    "slug": "lacs"
  },
  "CICM": {
    "name": "Comoé",
    "slug": "como"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return civSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return civSvgToSlugMapping[regionId];
}
