// SVG region mapping for Cameroon
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const cmrSvgToSlugMapping: RegionMapping = {
  "CMSU": {
    "name": "Sud",
    "slug": "sud"
  },
  "CMEN": {
    "name": "Extrême-Nord",
    "slug": "extrme-nord"
  },
  "CMNO": {
    "name": "Nord",
    "slug": "nord"
  },
  "CMAD": {
    "name": "Adamaoua",
    "slug": "adamaoua"
  },
  "CMNW": {
    "name": "Nord-Ouest",
    "slug": "nord-ouest"
  },
  "CMSW": {
    "name": "Sud-Ouest",
    "slug": "sud-ouest"
  },
  "CMES": {
    "name": "Est",
    "slug": "est"
  },
  "CMLT": {
    "name": "Littoral",
    "slug": "littoral"
  },
  "CMOU": {
    "name": "Ouest",
    "slug": "ouest"
  },
  "CMCE": {
    "name": "Centre",
    "slug": "centre"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return cmrSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return cmrSvgToSlugMapping[regionId];
}
