// SVG region mapping for Congo, Democratic Republic of the
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const codSvgToSlugMapping: RegionMapping = {
  "CDBU": {
    "name": "Bas-Uele",
    "slug": "bas-uele"
  },
  "CDEQ": {
    "name": "Equateur",
    "slug": "equateur"
  },
  "CDHK": {
    "name": "Haut-Katanga",
    "slug": "haut-katanga"
  },
  "CDHL": {
    "name": "Haut-Lomami",
    "slug": "haut-lomami"
  },
  "CDHU": {
    "name": "Haut-Uele",
    "slug": "haut-uele"
  },
  "CDIT": {
    "name": "Ituri",
    "slug": "ituri"
  },
  "CDKS": {
    "name": "Kasaï",
    "slug": "kasa"
  },
  "CDKC": {
    "name": "Kasaï-Central",
    "slug": "kasa-central"
  },
  "CDKE": {
    "name": "Kasaï-Oriental",
    "slug": "kasa-oriental"
  },
  "CDKN": {
    "name": "Kinshasa",
    "slug": "kinshasa"
  },
  "CDBC": {
    "name": "Kongo-Central",
    "slug": "kongo-central"
  },
  "CDKG": {
    "name": "Kwango",
    "slug": "kwango"
  },
  "CDKL": {
    "name": "Kwilu",
    "slug": "kwilu"
  },
  "CDLO": {
    "name": "Lomami",
    "slug": "lomami"
  },
  "CDLU": {
    "name": "Lualaba",
    "slug": "lualaba"
  },
  "CDMN": {
    "name": "Maï-Ndombe",
    "slug": "ma-ndombe"
  },
  "CDMA": {
    "name": "Maniema",
    "slug": "maniema"
  },
  "CDMO": {
    "name": "Mongala",
    "slug": "mongala"
  },
  "CDNK": {
    "name": "Nord-Kivu",
    "slug": "nord-kivu"
  },
  "CDNU": {
    "name": "Nord-Ubangi",
    "slug": "nord-ubangi"
  },
  "CDSA": {
    "name": "Sankuru",
    "slug": "sankuru"
  },
  "CDSK": {
    "name": "Sud-Kivu",
    "slug": "sud-kivu"
  },
  "CDSU": {
    "name": "Sud-Ubangi",
    "slug": "sud-ubangi"
  },
  "CDTA": {
    "name": "Tanganyika",
    "slug": "tanganyika"
  },
  "CDTO": {
    "name": "Tshopo",
    "slug": "tshopo"
  },
  "CDTU": {
    "name": "Tshuapa",
    "slug": "tshuapa"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return codSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return codSvgToSlugMapping[regionId];
}
