// SVG region mapping for Congo
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const cogSvgToSlugMapping: RegionMapping = {
  "CG7": {
    "name": "Likouala",
    "slug": "likouala"
  },
  "CG8": {
    "name": "Cuvette",
    "slug": "cuvette"
  },
  "CG14": {
    "name": "Plateaux",
    "slug": "plateaux"
  },
  "CG12": {
    "name": "Pool",
    "slug": "pool"
  },
  "BZV": {
    "name": "Brazzaville",
    "slug": "brazzaville"
  },
  "CG11": {
    "name": "Bouenza",
    "slug": "bouenza"
  },
  "CG9": {
    "name": "Niari",
    "slug": "niari"
  },
  "CG5": {
    "name": "Kouilou",
    "slug": "kouilou"
  },
  "CG13": {
    "name": "Sangha",
    "slug": "sangha"
  },
  "CG15": {
    "name": "Cuvette-Ouest",
    "slug": "cuvette-ouest"
  },
  "CG2": {
    "name": "Lékoumou",
    "slug": "lekoumou"
  },
  "CG16": {
    "name": "Pointe Noire",
    "slug": "pointe-noire"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return cogSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return cogSvgToSlugMapping[regionId];
}
