// SVG region mapping for Congo
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const cogSvgToSlugMapping: RegionMapping = {
  "CG7": {
    "name": "7",
    "slug": "7"
  },
  "CG8": {
    "name": "8",
    "slug": "8"
  },
  "CG14": {
    "name": "Plateaux",
    "slug": "plateaux"
  },
  "CG12": {
    "name": "Pool",
    "slug": "pool"
  },
  "CGBZV": {
    "name": "Brazzaville",
    "slug": "brazzaville"
  },
  "CG11": {
    "name": "Bouenza",
    "slug": "bouenza"
  },
  "CG9": {
    "name": "9",
    "slug": "9"
  },
  "CG5": {
    "name": "5",
    "slug": "5"
  },
  "CG13": {
    "name": "Sangha",
    "slug": "sangha"
  },
  "CG15": {
    "name": "Cuvette-Ouest",
    "slug": "cuvette-ouest"
  },
  "CG2": {
    "name": "2",
    "slug": "2"
  },
  "CG16": {
    "name": "Pointe Noire",
    "slug": "pointe-noire"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return cogSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return cogSvgToSlugMapping[regionId];
}
