// SVG region mapping for Colombia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const colSvgToSlugMapping: RegionMapping = {
  "CONAR": {
    "name": "Nariño",
    "slug": "nario"
  },
  "COPUT": {
    "name": "Putumayo",
    "slug": "putumayo"
  },
  "COCHO": {
    "name": "Chocó",
    "slug": "choc"
  },
  "COGUA": {
    "name": "Guainía",
    "slug": "guaina"
  },
  "COVAU": {
    "name": "Vaupés",
    "slug": "vaups"
  },
  "COAMA": {
    "name": "Amazonas",
    "slug": "amazonas"
  },
  "COLAG": {
    "name": "La Guajira",
    "slug": "la-guajira"
  },
  "COCES": {
    "name": "Cesar",
    "slug": "cesar"
  },
  "CONSA": {
    "name": "Norte de Santander",
    "slug": "norte-de-santander"
  },
  "COARA": {
    "name": "Arauca",
    "slug": "arauca"
  },
  "COBOY": {
    "name": "Boyacá",
    "slug": "boyac"
  },
  "COVID": {
    "name": "Vichada",
    "slug": "vichada"
  },
  "COCAU": {
    "name": "Cauca",
    "slug": "cauca"
  },
  "COVAC": {
    "name": "Valle del Cauca",
    "slug": "valle-del-cauca"
  },
  "COANT": {
    "name": "Antioquia",
    "slug": "antioquia"
  },
  "COCOR": {
    "name": "Córdoba",
    "slug": "crdoba"
  },
  "COSUC": {
    "name": "Sucre",
    "slug": "sucre"
  },
  "COBOL": {
    "name": "Bolívar",
    "slug": "bolvar"
  },
  "COATL": {
    "name": "Atlántico",
    "slug": "atlntico"
  },
  "COMAG": {
    "name": "Magdalena",
    "slug": "magdalena"
  },
  "COSAP": {
    "name": "San Andrés y Providencia",
    "slug": "san-andrs-y-providencia"
  },
  "COCAQ": {
    "name": "Caquetá",
    "slug": "caquet"
  },
  "COHUI": {
    "name": "Huila",
    "slug": "huila"
  },
  "COGUV": {
    "name": "Guaviare",
    "slug": "guaviare"
  },
  "COCAL": {
    "name": "Caldas",
    "slug": "caldas"
  },
  "COCAS": {
    "name": "Casanare",
    "slug": "casanare"
  },
  "COMET": {
    "name": "Meta",
    "slug": "meta"
  },
  "CODC": {
    "name": "Distrito Capital de Bogotá",
    "slug": "distrito-capital-de-bogot"
  },
  "COSAN": {
    "name": "Santander",
    "slug": "santander"
  },
  "COTOL": {
    "name": "Tolima",
    "slug": "tolima"
  },
  "COQUI": {
    "name": "Quindío",
    "slug": "quindo"
  },
  "COCUN": {
    "name": "Cundinamarca",
    "slug": "cundinamarca"
  },
  "CORIS": {
    "name": "Risaralda",
    "slug": "risaralda"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return colSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return colSvgToSlugMapping[regionId];
}
