// SVG region mapping for Comoros
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const comSvgToSlugMapping: RegionMapping = {
  "KMM": {
    "name": "Moûhîlî",
    "slug": "mouhili"
  },
  "KMA": {
    "name": "Andjouân",
    "slug": "andjouan"
  },
  "KMG": {
    "name": "Andjazîdja",
    "slug": "andjazidja"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return comSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return comSvgToSlugMapping[regionId];
}
