// SVG region mapping for Cabo Verde
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const cpvSvgToSlugMapping: RegionMapping = {
  "CVBR": {
    "name": "Brava",
    "slug": "brava"
  },
  "CVCF": {
    "name": "Santa Catarina do Fogo",
    "slug": "santa-catarina-do-fogo"
  },
  "CVMO": {
    "name": "Mosteiros",
    "slug": "mosteiros"
  },
  "CVSF": {
    "name": "São Filipe",
    "slug": "so-filipe"
  },
  "CVTA": {
    "name": "Tarrafal",
    "slug": "tarrafal"
  },
  "CVCA": {
    "name": "Santa Catarina",
    "slug": "santa-catarina"
  },
  "CVRS": {
    "name": "Ribeira Grande de Santiago",
    "slug": "ribeira-grande-de-santiago"
  },
  "CVPR": {
    "name": "Praia",
    "slug": "praia"
  },
  "CVSD": {
    "name": "São Domingos",
    "slug": "so-domingos"
  },
  "CVCR": {
    "name": "Santa Cruz",
    "slug": "santa-cruz"
  },
  "CVSM": {
    "name": "São Miguel",
    "slug": "so-miguel"
  },
  "CVMA": {
    "name": "Maio",
    "slug": "maio"
  },
  "CVBV": {
    "name": "Boa Vista",
    "slug": "boa-vista"
  },
  "CVRB": {
    "name": "Ribeira Brava",
    "slug": "ribeira-brava"
  },
  "CVTS": {
    "name": "Tarrafal de São Nicolau",
    "slug": "tarrafal-de-so-nicolau"
  },
  "CVSL": {
    "name": "SL",
    "slug": "sl"
  },
  "CVSV": {
    "name": "São Vicente",
    "slug": "so-vicente"
  },
  "CVRG": {
    "name": "Ribeira Grande",
    "slug": "ribeira-grande"
  },
  "CVPN": {
    "name": "Porto Novo",
    "slug": "porto-novo"
  },
  "CVPA": {
    "name": "Paul",
    "slug": "paul"
  },
  "CVSS": {
    "name": "São Salvador do Mundo",
    "slug": "so-salvador-do-mundo"
  },
  "CVSO": {
    "name": "São Lourenço dos Órgãos",
    "slug": "so-loureno-dos-rgos"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return cpvSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return cpvSvgToSlugMapping[regionId];
}
