// SVG region mapping for Costa Rica
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const criSvgToSlugMapping: RegionMapping = {
  "CRA": {
    "name": "Alajuela",
    "slug": "alajuela"
  },
  "CRG": {
    "name": "Cartago",
    "slug": "cartago"
  },
  "CRL": {
    "name": "Alajuela",
    "slug": "alajuela"
  },
  "CRP": {
    "name": "Puntarenas",
    "slug": "puntarenas"
  },
  "CRH": {
    "name": "Heredia",
    "slug": "heredia"
  },
  "CRSJ": {
    "name": "San José",
    "slug": "san-jos"
  },
  "CRC": {
    "name": "Cartago",
    "slug": "cartago"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return criSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return criSvgToSlugMapping[regionId];
}
