// SVG region mapping for Cuba
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const cubSvgToSlugMapping: RegionMapping = {
  "CU14": {
    "name": "Guantánamo",
    "slug": "guantnamo"
  },
  "CU09": {
    "name": "Camagüey",
    "slug": "camagey"
  },
  "CU08": {
    "name": "Ciego de Ávila",
    "slug": "ciego-de-vila"
  },
  "CU11": {
    "name": "Holguín",
    "slug": "holgun"
  },
  "CU99": {
    "name": "Isla de la Juventud",
    "slug": "isla-de-la-juventud"
  },
  "CU07": {
    "name": "Sancti Spíritus",
    "slug": "sancti-spritus"
  },
  "CU05": {
    "name": "Villa Clara",
    "slug": "villa-clara"
  },
  "CU04": {
    "name": "Matanzas",
    "slug": "matanzas"
  },
  "CU10": {
    "name": "Las Tunas",
    "slug": "las-tunas"
  },
  "CU16": {
    "name": "Mayabeque",
    "slug": "mayabeque"
  },
  "CU03": {
    "name": "Ciudad de la Habana",
    "slug": "ciudad-de-la-habana"
  },
  "CU15": {
    "name": "Artemisa",
    "slug": "artemisa"
  },
  "CU01": {
    "name": "Pinar del Río",
    "slug": "pinar-del-ro"
  },
  "CU06": {
    "name": "Cienfuegos",
    "slug": "cienfuegos"
  },
  "CU12": {
    "name": "Granma",
    "slug": "granma"
  },
  "CU13": {
    "name": "Santiago de Cuba",
    "slug": "santiago-de-cuba"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return cubSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return cubSvgToSlugMapping[regionId];
}
