// SVG region mapping for Cyprus
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const cypSvgToSlugMapping: RegionMapping = {
  "CY04": {
    "name": "Ammochostos",
    "slug": "ammochostos"
  },
  "CY03": {
    "name": "Larnaca",
    "slug": "larnaca"
  },
  "CY02": {
    "name": "Limassol",
    "slug": "limassol"
  },
  "CY05": {
    "name": "Paphos",
    "slug": "paphos"
  },
  "CY01": {
    "name": "Lefkosia",
    "slug": "lefkosia"
  },
  "CY06": {
    "name": "Keryneia",
    "slug": "keryneia"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return cypSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return cypSvgToSlugMapping[regionId];
}
