// SVG region mapping for Czechia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const czeSvgToSlugMapping: RegionMapping = {
  "CZ42": {
    "name": " Ústecký kraj",
    "slug": "-steck-kraj"
  },
  "CZ31": {
    "name": " Jihočeský kraj",
    "slug": "-jihoesk-kraj"
  },
  "CZ64": {
    "name": " Jihomoravský kraj",
    "slug": "-jihomoravsk-kraj"
  },
  "CZ41": {
    "name": " Karlovarský kraj",
    "slug": "-karlovarsk-kraj"
  },
  "CZ52": {
    "name": " Královéhradecký kraj",
    "slug": "-krlovhradeck-kraj"
  },
  "CZ51": {
    "name": " Liberecký kraj",
    "slug": "-libereck-kraj"
  },
  "CZ80": {
    "name": " Moravskoslezský kraj",
    "slug": "-moravskoslezsk-kraj"
  },
  "CZ71": {
    "name": " Olomoucký kraj",
    "slug": "-olomouck-kraj"
  },
  "CZ53": {
    "name": " Pardubický kraj",
    "slug": "-pardubick-kraj"
  },
  "CZ32": {
    "name": " Plzeňský kraj",
    "slug": "-plzesk-kraj"
  },
  "CZ10": {
    "name": " Praha",
    "slug": "-praha"
  },
  "CZ20": {
    "name": " Středočeský kraj",
    "slug": "-stedoesk-kraj"
  },
  "CZ63": {
    "name": " Kraj Vysočina",
    "slug": "-kraj-vysoina"
  },
  "CZ72": {
    "name": " Zlínský kraj",
    "slug": "-zlnsk-kraj"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return czeSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return czeSvgToSlugMapping[regionId];
}
