// SVG region mapping for Germany
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const deuSvgToSlugMapping: RegionMapping = {
  "DESN": {
    "name": "Sachsen",
    "slug": "sachsen"
  },
  "DEBY": {
    "name": "Bayern",
    "slug": "bayern"
  },
  "DERP": {
    "name": "Rheinland-Pfalz",
    "slug": "rheinland-pfalz"
  },
  "DESL": {
    "name": "Saarland",
    "slug": "saarland"
  },
  "DESH": {
    "name": "Schleswig-Holstein",
    "slug": "schleswig-holstein"
  },
  "DENI": {
    "name": "Niedersachsen",
    "slug": "niedersachsen"
  },
  "DENW": {
    "name": "Nordrhein-Westfalen",
    "slug": "nordrhein-westfalen"
  },
  "DEBW": {
    "name": "Baden-Württemberg",
    "slug": "baden-wrttemberg"
  },
  "DEBB": {
    "name": "Brandenburg",
    "slug": "brandenburg"
  },
  "DEMV": {
    "name": "Mecklenburg-Vorpommern",
    "slug": "mecklenburg-vorpommern"
  },
  "DEHB": {
    "name": "Bremen",
    "slug": "bremen"
  },
  "DEHH": {
    "name": "Hamburg",
    "slug": "hamburg"
  },
  "DEHE": {
    "name": "Hessen",
    "slug": "hessen"
  },
  "DETH": {
    "name": "Thüringen",
    "slug": "thringen"
  },
  "DEST": {
    "name": "Sachsen-Anhalt",
    "slug": "sachsen-anhalt"
  },
  "DEBE": {
    "name": "Berlin",
    "slug": "berlin"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return deuSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return deuSvgToSlugMapping[regionId];
}
