// SVG region mapping for Djibouti
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const djiSvgToSlugMapping: RegionMapping = {
  "DJAS": {
    "name": "Ali Sabieh",
    "slug": "ali-sabieh"
  },
  "DJAR": {
    "name": "Arta",
    "slug": "arta"
  },
  "DJDI": {
    "name": "Dikhil",
    "slug": "dikhil"
  },
  "DJTA": {
    "name": "Tadjourah",
    "slug": "tadjourah"
  },
  "DJOB": {
    "name": "Obock",
    "slug": "obock"
  },
  "DJDJ": {
    "name": "Djibouti",
    "slug": "djibouti"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return djiSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return djiSvgToSlugMapping[regionId];
}
