// SVG region mapping for Dominica
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const dmaSvgToSlugMapping: RegionMapping = {
  "DM09": {
    "name": "Saint Patrick",
    "slug": "saint-patrick"
  },
  "DM03": {
    "name": "Saint David",
    "slug": "saint-david"
  },
  "DM02": {
    "name": "Saint Andrew",
    "slug": "saint-andrew"
  },
  "DM05": {
    "name": "Saint John",
    "slug": "saint-john"
  },
  "DM11": {
    "name": "Saint Peter",
    "slug": "saint-peter"
  },
  "DM06": {
    "name": "Saint Joseph",
    "slug": "saint-joseph"
  },
  "DM10": {
    "name": "Saint Paul",
    "slug": "saint-paul"
  },
  "DM04": {
    "name": "Saint George",
    "slug": "saint-george"
  },
  "DM07": {
    "name": "Saint Luke",
    "slug": "saint-luke"
  },
  "DM08": {
    "name": "Saint Mark",
    "slug": "saint-mark"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return dmaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return dmaSvgToSlugMapping[regionId];
}
