// SVG region mapping for Denmark
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const dnkSvgToSlugMapping: RegionMapping = {
  "DK83": {
    "name": "Syddanmark",
    "slug": "syddanmark"
  },
  "DK82": {
    "name": "Midtjylland",
    "slug": "midtjylland"
  },
  "DK81": {
    "name": "Nordjylland",
    "slug": "nordjylland"
  },
  "DK85": {
    "name": "Sjaælland",
    "slug": "sjalland"
  },
  "DK84": {
    "name": "Hovedstaden",
    "slug": "hovedstaden"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return dnkSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return dnkSvgToSlugMapping[regionId];
}
