// SVG region mapping for Dominican Republic
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const domSvgToSlugMapping: RegionMapping = {
  "DO34": {
    "name": "Cibao Noroeste",
    "slug": "cibao-noroeste"
  },
  "DO37": {
    "name": "El Valle",
    "slug": "el-valle"
  },
  "DO38": {
    "name": "Enriquillo",
    "slug": "enriquillo"
  },
  "DO42": {
    "name": "Yuma",
    "slug": "yuma"
  },
  "DO39": {
    "name": "Higuamo",
    "slug": "higuamo"
  },
  "DO33": {
    "name": "Cibao Nordeste",
    "slug": "cibao-nordeste"
  },
  "DO35": {
    "name": "Cibao Norte",
    "slug": "cibao-norte"
  },
  "DO41": {
    "name": "Valdesia",
    "slug": "valdesia"
  },
  "DO40": {
    "name": "Ozama",
    "slug": "ozama"
  },
  "DO36": {
    "name": "Cibao Sur",
    "slug": "cibao-sur"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return domSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return domSvgToSlugMapping[regionId];
}
