// SVG region mapping for Algeria
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const dzaSvgToSlugMapping: RegionMapping = {
  "DZ54": {
    "name": "Timimoun",
    "slug": "timimoun"
  },
  "DZ44": {
    "name": "Ain-Defla",
    "slug": "ain-defla"
  },
  "DZ46": {
    "name": "Ain-Temouchent",
    "slug": "ain-temouchent"
  },
  "DZ16": {
    "name": "Alger",
    "slug": "alger"
  },
  "DZ23": {
    "name": "Annaba",
    "slug": "annaba"
  },
  "DZ05": {
    "name": "Batna",
    "slug": "batna"
  },
  "DZ08": {
    "name": "Bechar",
    "slug": "bechar"
  },
  "DZ06": {
    "name": "Bejaia",
    "slug": "bejaia"
  },
  "DZ07": {
    "name": "Biskra",
    "slug": "biskra"
  },
  "DZ09": {
    "name": "Blida",
    "slug": "blida"
  },
  "DZ34": {
    "name": "Bordj Bou Arrer",
    "slug": "bordj-bou-arrer"
  },
  "DZ10": {
    "name": "Bouira",
    "slug": "bouira"
  },
  "DZ35": {
    "name": "Boumerdes",
    "slug": "boumerdes"
  },
  "DZ02": {
    "name": "Chlef",
    "slug": "chlef"
  },
  "DZ25": {
    "name": "Constantine",
    "slug": "constantine"
  },
  "DZ17": {
    "name": "Djelfa",
    "slug": "djelfa"
  },
  "DZ36": {
    "name": "El-Tarf",
    "slug": "el-tarf"
  },
  "DZ32": {
    "name": "El Bayadh",
    "slug": "el-bayadh"
  },
  "DZ49": {
    "name": "El M'Ghair",
    "slug": "el-mghair"
  },
  "DZ47": {
    "name": "Ghardaia",
    "slug": "ghardaia"
  },
  "DZ24": {
    "name": "Guelma",
    "slug": "guelma"
  },
  "DZ33": {
    "name": "Illizi",
    "slug": "illizi"
  },
  "DZ18": {
    "name": "Jijel",
    "slug": "jijel"
  },
  "DZ40": {
    "name": "Khenchela",
    "slug": "khenchela"
  },
  "DZ03": {
    "name": "Laghouat",
    "slug": "laghouat"
  },
  "DZ28": {
    "name": "M'Sila",
    "slug": "msila"
  },
  "DZ29": {
    "name": "Mascara",
    "slug": "mascara"
  },
  "DZ26": {
    "name": "Medea",
    "slug": "medea"
  },
  "DZ43": {
    "name": "Mila",
    "slug": "mila"
  },
  "DZ27": {
    "name": "Mostaganem",
    "slug": "mostaganem"
  },
  "DZ45": {
    "name": "Naama",
    "slug": "naama"
  },
  "DZ31": {
    "name": "Oran",
    "slug": "oran"
  },
  "DZ55": {
    "name": "Touggourt",
    "slug": "touggourt"
  },
  "DZ04": {
    "name": "Oum El Bouaghi",
    "slug": "oum-el-bouaghi"
  },
  "DZ48": {
    "name": "Relizane",
    "slug": "relizane"
  },
  "DZ20": {
    "name": "Saida",
    "slug": "saida"
  },
  "DZ19": {
    "name": "Setif",
    "slug": "setif"
  },
  "DZ22": {
    "name": "Sidi Bel Abbes",
    "slug": "sidi-bel-abbes"
  },
  "DZ21": {
    "name": "Skikda",
    "slug": "skikda"
  },
  "DZ41": {
    "name": "Souk-Ahras",
    "slug": "souk-ahras"
  },
  "DZ57": {
    "name": "In Salah",
    "slug": "in-salah"
  },
  "DZ12": {
    "name": "Tebessa",
    "slug": "tebessa"
  },
  "DZ14": {
    "name": "Tiaret",
    "slug": "tiaret"
  },
  "DZ37": {
    "name": "Tindouf",
    "slug": "tindouf"
  },
  "DZ42": {
    "name": "Tipaza",
    "slug": "tipaza"
  },
  "DZ38": {
    "name": "Tissemsilt",
    "slug": "tissemsilt"
  },
  "DZ15": {
    "name": "Tizi Ouzou",
    "slug": "tizi-ouzou"
  },
  "DZ13": {
    "name": "Tlemcen",
    "slug": "tlemcen"
  },
  "DZ53": {
    "name": "Béni Abbès",
    "slug": "bni-abbs"
  },
  "DZ50": {
    "name": "El Menia",
    "slug": "el-menia"
  },
  "DZ52": {
    "name": "Bordj Baji Mokhtar",
    "slug": "bordj-baji-mokhtar"
  },
  "DZ01": {
    "name": "Adrar",
    "slug": "adrar"
  },
  "DZ30": {
    "name": "Ouargla",
    "slug": "ouargla"
  },
  "DZ39": {
    "name": "El Oued",
    "slug": "el-oued"
  },
  "DZ11": {
    "name": "Tamanrasset",
    "slug": "tamanrasset"
  },
  "DZ56": {
    "name": "Djanet",
    "slug": "djanet"
  },
  "DZ58": {
    "name": "In Guezzam",
    "slug": "in-guezzam"
  },
  "DZ51": {
    "name": "Ouled Djellal",
    "slug": "ouled-djellal"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return dzaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return dzaSvgToSlugMapping[regionId];
}
