// SVG region mapping for Ecuador
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const ecuSvgToSlugMapping: RegionMapping = {
  "ECE": {
    "name": "El Oro",
    "slug": "el-oro"
  },
  "ECC": {
    "name": "Canar",
    "slug": "canar"
  },
  "ECU": {
    "name": "Azuay",
    "slug": "azuay"
  },
  "ECD": {
    "name": "Esmeraldas",
    "slug": "esmeraldas"
  },
  "ECY": {
    "name": "Azuay",
    "slug": "azuay"
  },
  "ECS": {
    "name": "Esmeraldas",
    "slug": "esmeraldas"
  },
  "ECZ": {
    "name": "Azuay",
    "slug": "azuay"
  },
  "ECL": {
    "name": "Bolivar",
    "slug": "bolivar"
  },
  "ECO": {
    "name": "Bolivar",
    "slug": "bolivar"
  },
  "ECG": {
    "name": "Galapagos",
    "slug": "galapagos"
  },
  "ECW": {
    "name": "W",
    "slug": "w"
  },
  "ECSE": {
    "name": "Santa Elena",
    "slug": "santa-elena"
  },
  "ECM": {
    "name": "Chimborazo",
    "slug": "chimborazo"
  },
  "ECA": {
    "name": "Azuay",
    "slug": "azuay"
  },
  "ECF": {
    "name": "F",
    "slug": "f"
  },
  "ECN": {
    "name": "Canar",
    "slug": "canar"
  },
  "ECT": {
    "name": "Cotopaxi",
    "slug": "cotopaxi"
  },
  "ECH": {
    "name": "Carchi",
    "slug": "carchi"
  },
  "ECB": {
    "name": "Bolivar",
    "slug": "bolivar"
  },
  "ECI": {
    "name": "Bolivar",
    "slug": "bolivar"
  },
  "ECX": {
    "name": "Cotopaxi",
    "slug": "cotopaxi"
  },
  "ECR": {
    "name": "Bolivar",
    "slug": "bolivar"
  },
  "ECP": {
    "name": "Cotopaxi",
    "slug": "cotopaxi"
  },
  "ECSD": {
    "name": "Santo Domingo de los Tsáchilas",
    "slug": "santo-domingo-de-los-tschilas"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return ecuSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return ecuSvgToSlugMapping[regionId];
}
