// SVG region mapping for Ecuador
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const ecuSvgToSlugMapping: RegionMapping = {
  "ECA": {
    "name": "Azuay",
    "slug": "azuay"
  },
  "ECB": {
    "name": "Bolivar",
    "slug": "bolivar"
  },
  "ECC": {
    "name": "Carchi",
    "slug": "carchi"
  },
  "ECD": {
    "name": "Orellana",
    "slug": "orellana"
  },
  "ECE": {
    "name": "Esmeraldas",
    "slug": "esmeraldas"
  },
  "ECF": {
    "name": "Cañar",
    "slug": "canar"
  },
  "ECG": {
    "name": "Guayas",
    "slug": "guayas"
  },
  "ECH": {
    "name": "Chimborazo",
    "slug": "chimborazo"
  },
  "ECI": {
    "name": "Imbabura",
    "slug": "imbabura"
  },
  "ECL": {
    "name": "Loja",
    "slug": "loja"
  },
  "ECM": {
    "name": "Manabi",
    "slug": "manabi"
  },
  "ECN": {
    "name": "Napo",
    "slug": "napo"
  },
  "ECO": {
    "name": "El Oro",
    "slug": "el-oro"
  },
  "ECP": {
    "name": "Pichincha",
    "slug": "pichincha"
  },
  "ECR": {
    "name": "Los Rios",
    "slug": "los-rios"
  },
  "ECS": {
    "name": "Morona Santiago",
    "slug": "morona-santiago"
  },
  "CSD": {
    "name": "Santo Domingo de los Tsáchilas",
    "slug": "santo-domingo-de-los-tsachilas"
  },
  "CSE": {
    "name": "Santa Elena",
    "slug": "santa-elena"
  },
  "ECT": {
    "name": "Tungurahua",
    "slug": "tungurahua"
  },
  "ECU": {
    "name": "Sucumbios",
    "slug": "sucumbios"
  },
  "ECW": {
    "name": "Galápagos",
    "slug": "galapagos"
  },
  "ECX": {
    "name": "Cotopaxi",
    "slug": "cotopaxi"
  },
  "ECY": {
    "name": "Pastaza",
    "slug": "pastaza"
  },
  "ECZ": {
    "name": "Zamora Chinchipe",
    "slug": "zamora-chinchipe"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return ecuSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return ecuSvgToSlugMapping[regionId];
}
