// SVG region mapping for Egypt
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const egySvgToSlugMapping: RegionMapping = {
  "EGSIN": {
    "name": "Shamal Sina'",
    "slug": "shamal-sina"
  },
  "EGASN": {
    "name": "Aswan",
    "slug": "aswan"
  },
  "EGBA": {
    "name": "Al Bahr al Ahmar",
    "slug": "al-bahr-al-ahmar"
  },
  "EGMT": {
    "name": "Matruh",
    "slug": "matruh"
  },
  "EGWAD": {
    "name": "Al Wadi at Jadid",
    "slug": "al-wadi-at-jadid"
  },
  "EGSUZ": {
    "name": "As Suways",
    "slug": "as-suways"
  },
  "EGJS": {
    "name": "Janub Sina'",
    "slug": "janub-sina"
  },
  "EGPTS": {
    "name": "Bur Sa`id",
    "slug": "bur-said"
  },
  "EGDK": {
    "name": "Ad Daqahliyah",
    "slug": "ad-daqahliyah"
  },
  "EGSHR": {
    "name": "Ash Sharqiyah",
    "slug": "ash-sharqiyah"
  },
  "EGIS": {
    "name": "Al Isma`iliyah",
    "slug": "al-ismailiyah"
  },
  "EGDT": {
    "name": "Dumyat",
    "slug": "dumyat"
  },
  "EGKFS": {
    "name": "Kafr ash Shaykh",
    "slug": "kafr-ash-shaykh"
  },
  "EGBH": {
    "name": "Al Buhayrah",
    "slug": "al-buhayrah"
  },
  "EGALX": {
    "name": "Al Iskandariyah",
    "slug": "al-iskandariyah"
  },
  "EGC": {
    "name": "Cairo",
    "slug": "cairo"
  },
  "EGGZ": {
    "name": "Al Jizah",
    "slug": "al-jizah"
  },
  "EGMN": {
    "name": "Al Minya",
    "slug": "al-minya"
  },
  "EGFYM": {
    "name": "Al Fayyum",
    "slug": "al-fayyum"
  },
  "EGBNS": {
    "name": "Bani Suwayf",
    "slug": "bani-suwayf"
  },
  "EGMNF": {
    "name": "Al Minufiyah",
    "slug": "al-minufiyah"
  },
  "EGKB": {
    "name": "Al Qalyubiyah",
    "slug": "al-qalyubiyah"
  },
  "EGGH": {
    "name": "Al Gharbiyah",
    "slug": "al-gharbiyah"
  },
  "EGSHG": {
    "name": "Suhaj",
    "slug": "suhaj"
  },
  "EGKN": {
    "name": "Qina",
    "slug": "qina"
  },
  "EGAST": {
    "name": "Asyut",
    "slug": "asyut"
  },
  "EGLX": {
    "name": "Luxor",
    "slug": "luxor"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return egySvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return egySvgToSlugMapping[regionId];
}
