// SVG region mapping for Eritrea
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const eriSvgToSlugMapping: RegionMapping = {
  "ERDK": {
    "name": "Debubawi Keyih Bahri",
    "slug": "debubawi-keyih-bahri"
  },
  "ERDU": {
    "name": "Debub",
    "slug": "debub"
  },
  "ERSK": {
    "name": "Semenawi Keyih Bahri",
    "slug": "semenawi-keyih-bahri"
  },
  "ERGB": {
    "name": "Gash Barka",
    "slug": "gash-barka"
  },
  "ERMA": {
    "name": "Maekel",
    "slug": "maekel"
  },
  "ERAN": {
    "name": "Anseba",
    "slug": "anseba"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return eriSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return eriSvgToSlugMapping[regionId];
}
