// SVG region mapping for Spain
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const espSvgToSlugMapping: RegionMapping = {
  "ESNC": {
    "name": "Navarra, Comunidad Foral de",
    "slug": "navarra-comunidad-foral-de"
  },
  "ESPV": {
    "name": "País Vasco",
    "slug": "pas-vasco"
  },
  "ESRI": {
    "name": "La Rioja",
    "slug": "la-rioja"
  },
  "ESCT": {
    "name": "Cataluña",
    "slug": "catalua"
  },
  "ESAR": {
    "name": "Aragon",
    "slug": "aragon"
  },
  "ESEX": {
    "name": "Extremadura",
    "slug": "extremadura"
  },
  "ESGA": {
    "name": "Galicia",
    "slug": "galicia"
  },
  "ESCL": {
    "name": "Castilla y León",
    "slug": "castilla-y-len"
  },
  "ESVC": {
    "name": "Comunidad Valenciana",
    "slug": "comunidad-valenciana"
  },
  "ESMC": {
    "name": "Murcia",
    "slug": "murcia"
  },
  "ESAN": {
    "name": "Andalucía",
    "slug": "andaluca"
  },
  "ESAS": {
    "name": "Asturias",
    "slug": "asturias"
  },
  "ESCB": {
    "name": "Cantabria",
    "slug": "cantabria"
  },
  "ESCN": {
    "name": "Islas Canarias",
    "slug": "islas-canarias"
  },
  "ESIB": {
    "name": "Islas Baleares",
    "slug": "islas-baleares"
  },
  "ESCM": {
    "name": "Castilla la Mancha",
    "slug": "castilla-la-mancha"
  },
  "ESMD": {
    "name": "Comunidad de Madrid",
    "slug": "comunidad-de-madrid"
  },
  "ESCE": {
    "name": "Ceuta",
    "slug": "ceuta"
  },
  "ESML": {
    "name": "Melilla",
    "slug": "melilla"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return espSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return espSvgToSlugMapping[regionId];
}
