// SVG region mapping for Estonia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const estSvgToSlugMapping: RegionMapping = {
  "EE714": {
    "name": "Saaremaa",
    "slug": "saaremaa"
  },
  "EE784": {
    "name": "Tallinn",
    "slug": "tallinn"
  },
  "EE141": {
    "name": "Anija",
    "slug": "anija"
  },
  "EE689": {
    "name": "Ruhnu",
    "slug": "ruhnu"
  },
  "EE907": {
    "name": "Vormsi",
    "slug": "vormsi"
  },
  "EE255": {
    "name": "Järva",
    "slug": "jarva"
  },
  "EE245": {
    "name": "Jõelähtme",
    "slug": "joelahtme"
  },
  "EE198": {
    "name": "Harku",
    "slug": "harku"
  },
  "EE353": {
    "name": "Kuusalu",
    "slug": "kuusalu"
  },
  "EE478": {
    "name": "Muhu",
    "slug": "muhu"
  },
  "EE338": {
    "name": "Kose",
    "slug": "kose"
  },
  "EE291": {
    "name": "Kastre",
    "slug": "kastre"
  },
  "EE651": {
    "name": "Raasiku",
    "slug": "raasiku"
  },
  "EE653": {
    "name": "Rae",
    "slug": "rae"
  },
  "EE890": {
    "name": "Viimsi",
    "slug": "viimsi"
  },
  "EE899": {
    "name": "Viljandi",
    "slug": "viljandi"
  },
  "EE917": {
    "name": "Võru",
    "slug": "voru"
  },
  "EE834": {
    "name": "Türi",
    "slug": "turi"
  },
  "EE317": {
    "name": "Kohila",
    "slug": "kohila"
  },
  "EE205": {
    "name": "Hiiumaa",
    "slug": "hiiumaa"
  },
  "EE171": {
    "name": "Elva",
    "slug": "elva"
  },
  "EE901": {
    "name": "Vinni",
    "slug": "vinni"
  },
  "EE251": {
    "name": "Jõhvi",
    "slug": "johvi"
  },
  "EE446": {
    "name": "Maardu",
    "slug": "maardu"
  },
  "EE897": {
    "name": "Viljandi",
    "slug": "viljandi"
  },
  "EE296": {
    "name": "Keila",
    "slug": "keila"
  },
  "EE663": {
    "name": "Rakvere",
    "slug": "rakvere"
  },
  "EE726": {
    "name": "Saue",
    "slug": "saue"
  },
  "EE928": {
    "name": "Väike-Maarja",
    "slug": "vaike-maarja"
  },
  "EE321": {
    "name": "Kohtla-Järve",
    "slug": "kohtla-jarve"
  },
  "EE803": {
    "name": "Toila",
    "slug": "toila"
  },
  "EE615": {
    "name": "Põhja-Sakala",
    "slug": "pohja-sakala"
  },
  "EE735": {
    "name": "Sillamäe",
    "slug": "sillamae"
  },
  "EE424": {
    "name": "Loksa",
    "slug": "loksa"
  },
  "EE514": {
    "name": "Narva-Joesuu",
    "slug": "narva-joesuu"
  },
  "EE511": {
    "name": "Narva",
    "slug": "narva"
  },
  "EE480": {
    "name": "Mulgi",
    "slug": "mulgi"
  },
  "EE503": {
    "name": "Marjamaa",
    "slug": "marjamaa"
  },
  "EE708": {
    "name": "Räpina",
    "slug": "rapina"
  },
  "EE191": {
    "name": "Haljala",
    "slug": "haljala"
  },
  "EE430": {
    "name": "Lääneranna",
    "slug": "laaneranna"
  },
  "EE272": {
    "name": "Kadrina",
    "slug": "kadrina"
  },
  "EE661": {
    "name": "Rakvere",
    "slug": "rakvere"
  },
  "EE903": {
    "name": "Viru-Nigula",
    "slug": "viru-nigula"
  },
  "EE557": {
    "name": "Otepää",
    "slug": "otepaa"
  },
  "EE792": {
    "name": "Tapa",
    "slug": "tapa"
  },
  "EE622": {
    "name": "Põlva",
    "slug": "polva"
  },
  "EE284": {
    "name": "Kanepi",
    "slug": "kanepi"
  },
  "EE732": {
    "name": "Setomaa",
    "slug": "setomaa"
  },
  "EE486": {
    "name": "Mustvee",
    "slug": "mustvee"
  },
  "EE431": {
    "name": "Lääne-Harju",
    "slug": "laane-harju"
  },
  "EE719": {
    "name": "Saku",
    "slug": "saku"
  },
  "EE303": {
    "name": "Kihnu",
    "slug": "kihnu"
  },
  "EE441": {
    "name": "Lääne-Nigula",
    "slug": "laane-nigula"
  },
  "EE824": {
    "name": "Tõrva",
    "slug": "torva"
  },
  "EE130": {
    "name": "Alutaguse",
    "slug": "alutaguse"
  },
  "EE528": {
    "name": "Nõo",
    "slug": "noo"
  },
  "EE624": {
    "name": "Pärnu",
    "slug": "parnu"
  },
  "EE305": {
    "name": "Kiili",
    "slug": "kiili"
  },
  "EE293": {
    "name": "Kehtna",
    "slug": "kehtna"
  },
  "EE432": {
    "name": "Luunja",
    "slug": "luunja"
  },
  "EE668": {
    "name": "Rapla",
    "slug": "rapla"
  },
  "EE919": {
    "name": "Võru",
    "slug": "voru"
  },
  "EE142": {
    "name": "Antsla",
    "slug": "antsla"
  },
  "EE855": {
    "name": "Valga",
    "slug": "valga"
  },
  "EE712": {
    "name": "Saarde",
    "slug": "saarde"
  },
  "EE793": {
    "name": "Tartu",
    "slug": "tartu"
  },
  "EE214": {
    "name": "Häädemeeste",
    "slug": "haademeeste"
  },
  "EE184": {
    "name": "Haapsalu",
    "slug": "haapsalu"
  },
  "EE638": {
    "name": "Põhja-Pärnumaa",
    "slug": "pohja-parnumaa"
  },
  "EE809": {
    "name": "Tori",
    "slug": "tori"
  },
  "EE567": {
    "name": "Paide",
    "slug": "paide"
  },
  "EE442": {
    "name": "Lüganuse",
    "slug": "luganuse"
  },
  "EE247": {
    "name": "Jõgeva",
    "slug": "jogeva"
  },
  "EE586": {
    "name": "Peipsiääre",
    "slug": "peipsiaare"
  },
  "EE796": {
    "name": "Tartu",
    "slug": "tartu"
  },
  "EE618": {
    "name": "Põltsamaa",
    "slug": "poltsamaa"
  },
  "EE283": {
    "name": "Kambja",
    "slug": "kambja"
  },
  "EE698": {
    "name": "Rõuge",
    "slug": "rouge"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return estSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return estSvgToSlugMapping[regionId];
}
