// SVG region mapping for Ethiopia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const ethSvgToSlugMapping: RegionMapping = {
  "ETSN": {
    "name": "SNNP",
    "slug": "snnp"
  },
  "ETAA": {
    "name": "Addis Ababa",
    "slug": "addis-ababa"
  },
  "ETAF": {
    "name": "Afar",
    "slug": "afar"
  },
  "ETAM": {
    "name": "Amara",
    "slug": "amara"
  },
  "ETBE": {
    "name": "Benishangul Gumz",
    "slug": "benishangul-gumz"
  },
  "ETDD": {
    "name": "Dire Dawa",
    "slug": "dire-dawa"
  },
  "ETGA": {
    "name": "Gambela",
    "slug": "gambela"
  },
  "ETHA": {
    "name": "Harari",
    "slug": "harari"
  },
  "ETOR": {
    "name": "Oromia",
    "slug": "oromia"
  },
  "ETSI": {
    "name": "Sidama",
    "slug": "sidama"
  },
  "ETSO": {
    "name": "Somali",
    "slug": "somali"
  },
  "ETTI": {
    "name": "Tigray",
    "slug": "tigray"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return ethSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return ethSvgToSlugMapping[regionId];
}
