// SVG region mapping for Finland
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const finSvgToSlugMapping: RegionMapping = {
  "FI01": {
    "name": "Åland",
    "slug": "land"
  },
  "FI10": {
    "name": "Lapland",
    "slug": "lapland"
  },
  "FI14": {
    "name": "Northern Ostrobothnia",
    "slug": "northern-ostrobothnia"
  },
  "FI05": {
    "name": "Kainuu",
    "slug": "kainuu"
  },
  "FI13": {
    "name": "North Karelia",
    "slug": "north-karelia"
  },
  "FI02": {
    "name": "South Karelia",
    "slug": "south-karelia"
  },
  "FI09": {
    "name": "Kymenlaakso",
    "slug": "kymenlaakso"
  },
  "FI18": {
    "name": "Uusimaa",
    "slug": "uusimaa"
  },
  "FI19": {
    "name": "Finland Proper",
    "slug": "finland-proper"
  },
  "FI17": {
    "name": "Satakunta",
    "slug": "satakunta"
  },
  "FI12": {
    "name": "Ostrobothnia",
    "slug": "ostrobothnia"
  },
  "FI07": {
    "name": "Central Ostrobothnia",
    "slug": "central-ostrobothnia"
  },
  "FI15": {
    "name": "Northern Savonia",
    "slug": "northern-savonia"
  },
  "FI04": {
    "name": "Southern Savonia",
    "slug": "southern-savonia"
  },
  "FI08": {
    "name": "Central Finland",
    "slug": "central-finland"
  },
  "FI03": {
    "name": "Southern Ostrobothnia",
    "slug": "southern-ostrobothnia"
  },
  "FI11": {
    "name": "Pirkanmaa",
    "slug": "pirkanmaa"
  },
  "FI06": {
    "name": "Tavastia Proper",
    "slug": "tavastia-proper"
  },
  "FI16": {
    "name": "Päijät-Häme",
    "slug": "pijt-hme"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return finSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return finSvgToSlugMapping[regionId];
}
