// SVG region mapping for Fiji
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const fjiSvgToSlugMapping: RegionMapping = {
  "FJE": {
    "name": "Central",
    "slug": "central"
  },
  "FJW": {
    "name": "Western",
    "slug": "western"
  },
  "FJC": {
    "name": "Central",
    "slug": "central"
  },
  "FJN": {
    "name": "Central",
    "slug": "central"
  },
  "FJR": {
    "name": "Central",
    "slug": "central"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return fjiSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return fjiSvgToSlugMapping[regionId];
}
