// SVG region mapping for France
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const fraSvgToSlugMapping: RegionMapping = {
  "FRHDF": {
    "name": "Hauts de France",
    "slug": "hauts-de-france"
  },
  "FRGES": {
    "name": "Grand Est",
    "slug": "grand-est"
  },
  "FRPAC": {
    "name": "Provence Alpes Côte d'Azu",
    "slug": "provence-alpes-cte-dazu"
  },
  "FRARA": {
    "name": "Auvergne Rhône Alpes",
    "slug": "auvergne-rhne-alpes"
  },
  "FRBFC": {
    "name": "Bourgogne Franche Comté",
    "slug": "bourgogne-franche-comt"
  },
  "FROCC": {
    "name": "Occitanie",
    "slug": "occitanie"
  },
  "FRPDL": {
    "name": "Pays de la Loire",
    "slug": "pays-de-la-loire"
  },
  "FRBRE": {
    "name": "Bretagne",
    "slug": "bretagne"
  },
  "FRNOR": {
    "name": "Normandie",
    "slug": "normandie"
  },
  "FR20R": {
    "name": "Corse",
    "slug": "corse"
  },
  "FRNAQ": {
    "name": "Nouvelle Aquitaine",
    "slug": "nouvelle-aquitaine"
  },
  "FRCVL": {
    "name": "Centre Val de Loire",
    "slug": "centre-val-de-loire"
  },
  "FRIDF": {
    "name": "Île de France",
    "slug": "le-de-france"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return fraSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return fraSvgToSlugMapping[regionId];
}
