// SVG region mapping for Gabon
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const gabSvgToSlugMapping: RegionMapping = {
  "GA9": {
    "name": "Wouleu-Ntem",
    "slug": "wouleu-ntem"
  },
  "GA6": {
    "name": "Ogooué-Ivindo",
    "slug": "ogooue-ivindo"
  },
  "GA2": {
    "name": "Haut-Ogooué",
    "slug": "haut-ogooue"
  },
  "GA7": {
    "name": "Ogooué-Lolo",
    "slug": "ogooue-lolo"
  },
  "GA4": {
    "name": "Ngounié",
    "slug": "ngounie"
  },
  "GA5": {
    "name": "Nyanga",
    "slug": "nyanga"
  },
  "GA1": {
    "name": "Estuaire",
    "slug": "estuaire"
  },
  "GA8": {
    "name": "Ogooué-Maritime",
    "slug": "ogooue-maritime"
  },
  "GA3": {
    "name": "Moyen-Ogooué",
    "slug": "moyen-ogooue"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return gabSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return gabSvgToSlugMapping[regionId];
}
