// SVG region mapping for Gabon
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const gabSvgToSlugMapping: RegionMapping = {
  "GA9": {
    "name": "9",
    "slug": "9"
  },
  "GA6": {
    "name": "6",
    "slug": "6"
  },
  "GA2": {
    "name": "2",
    "slug": "2"
  },
  "GA7": {
    "name": "7",
    "slug": "7"
  },
  "GA4": {
    "name": "4",
    "slug": "4"
  },
  "GA5": {
    "name": "5",
    "slug": "5"
  },
  "GA1": {
    "name": "1",
    "slug": "1"
  },
  "GA8": {
    "name": "8",
    "slug": "8"
  },
  "GA3": {
    "name": "3",
    "slug": "3"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return gabSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return gabSvgToSlugMapping[regionId];
}
