// SVG region mapping for United Kingdom
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const gbrSvgToSlugMapping: RegionMapping = {
  "GBDRY": {
    "name": "Derry",
    "slug": "derry"
  },
  "GBSTB": {
    "name": "Strabane",
    "slug": "strabane"
  },
  "GBFER": {
    "name": "Fermanagh",
    "slug": "fermanagh"
  },
  "GBDGN": {
    "name": "Dungannon",
    "slug": "dungannon"
  },
  "GBARM": {
    "name": "Armagh",
    "slug": "armagh"
  },
  "GBNYM": {
    "name": "Newry and Mourne",
    "slug": "newry-and-mourne"
  },
  "GBFLN": {
    "name": "Flintshire",
    "slug": "flintshire"
  },
  "GBCHW": {
    "name": "Cheshire West and Chester",
    "slug": "cheshire-west-and-chester"
  },
  "GBWRX": {
    "name": "Wrexham",
    "slug": "wrexham"
  },
  "GBSHR": {
    "name": "Shropshire",
    "slug": "shropshire"
  },
  "GBPOW": {
    "name": "Powys",
    "slug": "powys"
  },
  "GBHEF": {
    "name": "Herefordshire",
    "slug": "herefordshire"
  },
  "GBMON": {
    "name": "Monmouthshire",
    "slug": "monmouthshire"
  },
  "GBGLS": {
    "name": "Gloucestershire",
    "slug": "gloucestershire"
  },
  "GBSCB": {
    "name": "Scottish Borders",
    "slug": "scottish-borders"
  },
  "GBNBL": {
    "name": "Northumberland",
    "slug": "northumberland"
  },
  "GBCMA": {
    "name": "Cumbria",
    "slug": "cumbria"
  },
  "GBDGY": {
    "name": "Dumfries and Galloway",
    "slug": "dumfries-and-galloway"
  },
  "GBLMV": {
    "name": "Limavady",
    "slug": "limavady"
  },
  "GBCLR": {
    "name": "Coleraine",
    "slug": "coleraine"
  },
  "GBMYL": {
    "name": "Moyle",
    "slug": "moyle"
  },
  "GBLRN": {
    "name": "Larne",
    "slug": "larne"
  },
  "GBCKF": {
    "name": "Carrickfergus",
    "slug": "carrickfergus"
  },
  "GBNTA": {
    "name": "Newtownabbey",
    "slug": "newtownabbey"
  },
  "GBBFS": {
    "name": "Belfast",
    "slug": "belfast"
  },
  "GBNDN": {
    "name": "North Down",
    "slug": "north-down"
  },
  "GBARD": {
    "name": "Ards",
    "slug": "ards"
  },
  "GBDOW": {
    "name": "Down",
    "slug": "down"
  },
  "GBCLK": {
    "name": "Clackmannanshire",
    "slug": "clackmannanshire"
  },
  "GBSTG": {
    "name": "Stirling",
    "slug": "stirling"
  },
  "GBFAL": {
    "name": "Falkirk",
    "slug": "falkirk"
  },
  "GBWLN": {
    "name": "West Lothian",
    "slug": "west-lothian"
  },
  "GBEDH": {
    "name": "Edinburgh",
    "slug": "edinburgh"
  },
  "GBMLN": {
    "name": "Midlothian",
    "slug": "midlothian"
  },
  "GBELN": {
    "name": "East Lothian",
    "slug": "east-lothian"
  },
  "GBNTY": {
    "name": "North Tyneside",
    "slug": "north-tyneside"
  },
  "GBSTY": {
    "name": "South Tyneside",
    "slug": "south-tyneside"
  },
  "GBSND": {
    "name": "Sunderland",
    "slug": "sunderland"
  },
  "GBDUR": {
    "name": "Durham",
    "slug": "durham"
  },
  "GBHPL": {
    "name": "Hartlepool",
    "slug": "hartlepool"
  },
  "GBRCC": {
    "name": "Redcar and Cleveland",
    "slug": "redcar-and-cleveland"
  },
  "GBNYK": {
    "name": "North Yorkshire",
    "slug": "north-yorkshire"
  },
  "GBERY": {
    "name": "East Riding of Yorkshire",
    "slug": "east-riding-of-yorkshire"
  },
  "GBKHL": {
    "name": "Kingston upon Hull",
    "slug": "kingston-upon-hull"
  },
  "GBNLN": {
    "name": "North Lincolnshire",
    "slug": "north-lincolnshire"
  },
  "GBNEL": {
    "name": "North East Lincolnshire",
    "slug": "north-east-lincolnshire"
  },
  "GBLIN": {
    "name": "Lincolnshire",
    "slug": "lincolnshire"
  },
  "GBNFK": {
    "name": "Norfolk",
    "slug": "norfolk"
  },
  "GBSFK": {
    "name": "Suffolk",
    "slug": "suffolk"
  },
  "GBESS": {
    "name": "Essex",
    "slug": "essex"
  },
  "GBSOS": {
    "name": "Southend-on-Sea",
    "slug": "southend-on-sea"
  },
  "GBTHR": {
    "name": "Thurrock",
    "slug": "thurrock"
  },
  "GBKEN": {
    "name": "Kent",
    "slug": "kent"
  },
  "GBMDW": {
    "name": "Medway",
    "slug": "medway"
  },
  "GBESX": {
    "name": "East Sussex",
    "slug": "east-sussex"
  },
  "GBBNH": {
    "name": "Brighton and Hove",
    "slug": "brighton-and-hove"
  },
  "GBWSX": {
    "name": "West Sussex",
    "slug": "west-sussex"
  },
  "GBHAM": {
    "name": "Hampshire",
    "slug": "hampshire"
  },
  "GBPOR": {
    "name": "Portsmouth",
    "slug": "portsmouth"
  },
  "GBSTH": {
    "name": "Southampton",
    "slug": "southampton"
  },
  "GBDOR": {
    "name": "Dorset",
    "slug": "dorset"
  },
  "GBBMH": {
    "name": "Bournemouth",
    "slug": "bournemouth"
  },
  "GBPOL": {
    "name": "Poole",
    "slug": "poole"
  },
  "GBDEV": {
    "name": "Devon",
    "slug": "devon"
  },
  "GBTOB": {
    "name": "Torbay",
    "slug": "torbay"
  },
  "GBPLY": {
    "name": "Plymouth",
    "slug": "plymouth"
  },
  "GBCON": {
    "name": "Cornwall",
    "slug": "cornwall"
  },
  "GBSOM": {
    "name": "Somerset",
    "slug": "somerset"
  },
  "GBNSM": {
    "name": "North Somerset",
    "slug": "north-somerset"
  },
  "GBBST": {
    "name": "Bristol",
    "slug": "bristol"
  },
  "GBSGC": {
    "name": "South Gloucestershire",
    "slug": "south-gloucestershire"
  },
  "GBNWP": {
    "name": "Newport",
    "slug": "newport"
  },
  "GBCRF": {
    "name": "Cardiff",
    "slug": "cardiff"
  },
  "GBVGL": {
    "name": "Vale of Glamorgan",
    "slug": "vale-of-glamorgan"
  },
  "GBBGE": {
    "name": "Bridgend",
    "slug": "bridgend"
  },
  "GBNTL": {
    "name": "Neath Port Talbot",
    "slug": "neath-port-talbot"
  },
  "GBSWA": {
    "name": "Swansea",
    "slug": "swansea"
  },
  "GBCMN": {
    "name": "Carmarthenshire",
    "slug": "carmarthenshire"
  },
  "GBPEM": {
    "name": "Pembrokeshire",
    "slug": "pembrokeshire"
  },
  "GBCGN": {
    "name": "Ceredigion",
    "slug": "ceredigion"
  },
  "GBGWN": {
    "name": "Gwynedd",
    "slug": "gwynedd"
  },
  "GBCWY": {
    "name": "Conwy",
    "slug": "conwy"
  },
  "GBDEN": {
    "name": "Denbighshire",
    "slug": "denbighshire"
  },
  "GBWRL": {
    "name": "Halton",
    "slug": "halton"
  },
  "GBHAL": {
    "name": "Halton",
    "slug": "halton"
  },
  "GBKWL": {
    "name": "Knowsley",
    "slug": "knowsley"
  },
  "GBLIV": {
    "name": "Liverpool",
    "slug": "liverpool"
  },
  "GBSFT": {
    "name": "Sefton",
    "slug": "sefton"
  },
  "GBLAN": {
    "name": "Lancashire",
    "slug": "lancashire"
  },
  "GBBPL": {
    "name": "Blackpool",
    "slug": "blackpool"
  },
  "GBSAY": {
    "name": "South Ayrshire",
    "slug": "south-ayrshire"
  },
  "GBNAY": {
    "name": "North Ayshire",
    "slug": "north-ayshire"
  },
  "GBIVC": {
    "name": "Inverclyde",
    "slug": "inverclyde"
  },
  "GBRFW": {
    "name": "Renfrewshire",
    "slug": "renfrewshire"
  },
  "GBWDU": {
    "name": "West Dunbartonshire",
    "slug": "west-dunbartonshire"
  },
  "GBAGB": {
    "name": "Argyll and Bute",
    "slug": "argyll-and-bute"
  },
  "GBHLD": {
    "name": "Highland",
    "slug": "highland"
  },
  "GBMRY": {
    "name": "Moray",
    "slug": "moray"
  },
  "GBABD": {
    "name": "Aberdeenshire",
    "slug": "aberdeenshire"
  },
  "GBABE": {
    "name": "Aberdeen",
    "slug": "aberdeen"
  },
  "GBANS": {
    "name": "Angus",
    "slug": "angus"
  },
  "GBDND": {
    "name": "Dundee",
    "slug": "dundee"
  },
  "GBPKN": {
    "name": "Perthshire and Kinross",
    "slug": "perthshire-and-kinross"
  },
  "GBFIF": {
    "name": "Fife",
    "slug": "fife"
  },
  "GBIOW": {
    "name": "Isle of Wight",
    "slug": "isle-of-wight"
  },
  "GBAGY": {
    "name": "Anglesey",
    "slug": "anglesey"
  },
  "GBELS": {
    "name": "Eilean Siar",
    "slug": "eilean-siar"
  },
  "GBORK": {
    "name": "Orkney",
    "slug": "orkney"
  },
  "GBZET": {
    "name": "Shetland Islands",
    "slug": "shetland-islands"
  },
  "GBIOS": {
    "name": "Isles of Scilly",
    "slug": "isles-of-scilly"
  },
  "GBCAY": {
    "name": "Caerphilly",
    "slug": "caerphilly"
  },
  "GBRCT": {
    "name": "Rhondda, Cynon, Taff",
    "slug": "rhondda-cynon-taff"
  },
  "GBBGW": {
    "name": "Blaenau Gwent",
    "slug": "blaenau-gwent"
  },
  "GBTOF": {
    "name": "Torfaen",
    "slug": "torfaen"
  },
  "GBMTY": {
    "name": "Merthyr Tydfil",
    "slug": "merthyr-tydfil"
  },
  "GBNLK": {
    "name": "North Lanarkshire",
    "slug": "north-lanarkshire"
  },
  "GBEDU": {
    "name": "East Dunbartonshire",
    "slug": "east-dunbartonshire"
  },
  "GBGLG": {
    "name": "Glasgow",
    "slug": "glasgow"
  },
  "GBERW": {
    "name": "East Renfrewshire",
    "slug": "east-renfrewshire"
  },
  "GBEAY": {
    "name": "East Ayrshire",
    "slug": "east-ayrshire"
  },
  "GBSLK": {
    "name": "South Lanarkshire",
    "slug": "south-lanarkshire"
  },
  "GBMFT": {
    "name": "Magherafelt",
    "slug": "magherafelt"
  },
  "GBOMH": {
    "name": "Omagh",
    "slug": "omagh"
  },
  "GBCKT": {
    "name": "Mid Ulster",
    "slug": "mid-ulster"
  },
  "GBCGV": {
    "name": "Craigavon",
    "slug": "craigavon"
  },
  "GBBNB": {
    "name": "Banbridge",
    "slug": "banbridge"
  },
  "GBANT": {
    "name": "Antrim",
    "slug": "antrim"
  },
  "GBLSB": {
    "name": "Lisburn",
    "slug": "lisburn"
  },
  "GBBLY": {
    "name": "Ballymoney",
    "slug": "ballymoney"
  },
  "GBBLA": {
    "name": "Ballymena",
    "slug": "ballymena"
  },
  "GBCSR": {
    "name": "Castlereagh",
    "slug": "castlereagh"
  },
  "GBWND": {
    "name": "Wandsworth",
    "slug": "wandsworth"
  },
  "GBMRT": {
    "name": "Merton",
    "slug": "merton"
  },
  "GBWSM": {
    "name": "Westminster",
    "slug": "westminster"
  },
  "GBKEC": {
    "name": "Kensington and Chelsea",
    "slug": "kensington-and-chelsea"
  },
  "GBHNS": {
    "name": "Hounslow",
    "slug": "hounslow"
  },
  "GBEAL": {
    "name": "Ealing",
    "slug": "ealing"
  },
  "GBHMF": {
    "name": "Hammersmith and Fulham",
    "slug": "hammersmith-and-fulham"
  },
  "GBSTT": {
    "name": "Stockton-on-Tees",
    "slug": "stockton-on-tees"
  },
  "GBDAL": {
    "name": "Darlington",
    "slug": "darlington"
  },
  "GBMDB": {
    "name": "Middlesbrough",
    "slug": "middlesbrough"
  },
  "GBRIC": {
    "name": "Richmond upon Thames",
    "slug": "richmond-upon-thames"
  },
  "GBLND": {
    "name": "City",
    "slug": "city"
  },
  "GBTWH": {
    "name": "Tower Hamlets",
    "slug": "tower-hamlets"
  },
  "GBGAT": {
    "name": "Gateshead",
    "slug": "gateshead"
  },
  "GBNET": {
    "name": "Newcastle upon Tyne",
    "slug": "newcastle-upon-tyne"
  },
  "GBYOR": {
    "name": "York",
    "slug": "york"
  },
  "GBSHN": {
    "name": "Merseyside",
    "slug": "merseyside"
  },
  "GBENF": {
    "name": "Enfield",
    "slug": "enfield"
  },
  "GBHRT": {
    "name": "Hertfordshire",
    "slug": "hertfordshire"
  },
  "GBBNE": {
    "name": "Barnet",
    "slug": "barnet"
  },
  "GBWFT": {
    "name": "Waltham Forest",
    "slug": "waltham-forest"
  },
  "GBRDB": {
    "name": "Redbridge",
    "slug": "redbridge"
  },
  "GBHAV": {
    "name": "Havering",
    "slug": "havering"
  },
  "GBCAM": {
    "name": "Cambridgeshire",
    "slug": "cambridgeshire"
  },
  "GBBEX": {
    "name": "Bexley",
    "slug": "bexley"
  },
  "GBSTN": {
    "name": "Sutton",
    "slug": "sutton"
  },
  "GBMIK": {
    "name": "Milton Keynes",
    "slug": "milton-keynes"
  },
  "GBBKM": {
    "name": "Buckinghamshire",
    "slug": "buckinghamshire"
  },
  "GBHIL": {
    "name": "Hillingdon",
    "slug": "hillingdon"
  },
  "GBBEN": {
    "name": "Brent",
    "slug": "brent"
  },
  "GBLUT": {
    "name": "Luton",
    "slug": "luton"
  },
  "GBHRW": {
    "name": "Harrow",
    "slug": "harrow"
  },
  "GBCBF": {
    "name": "Central Bedfordshire",
    "slug": "central-bedfordshire"
  },
  "GBBDF": {
    "name": "Bedford",
    "slug": "bedford"
  },
  "GBRUT": {
    "name": "Rutland",
    "slug": "rutland"
  },
  "GBNTT": {
    "name": "Nottinghamshire",
    "slug": "nottinghamshire"
  },
  "GBNTH": {
    "name": "Northamptonshire",
    "slug": "northamptonshire"
  },
  "GBCMD": {
    "name": "Camden",
    "slug": "camden"
  },
  "GBISL": {
    "name": "Islington",
    "slug": "islington"
  },
  "GBPTE": {
    "name": "Peterborough",
    "slug": "peterborough"
  },
  "GBLBH": {
    "name": "Lambeth",
    "slug": "lambeth"
  },
  "GBSWK": {
    "name": "Southwark",
    "slug": "southwark"
  },
  "GBDNC": {
    "name": "Doncaster",
    "slug": "doncaster"
  },
  "GBCRY": {
    "name": "Croydon",
    "slug": "croydon"
  },
  "GBLEW": {
    "name": "Lewisham",
    "slug": "lewisham"
  },
  "GBHRY": {
    "name": "Haringey",
    "slug": "haringey"
  },
  "GBKTT": {
    "name": "Kingston upon Thames",
    "slug": "kingston-upon-thames"
  },
  "GBNWM": {
    "name": "Newham",
    "slug": "newham"
  },
  "GBGRE": {
    "name": "Greenwich",
    "slug": "greenwich"
  },
  "GBHCK": {
    "name": "Hackney",
    "slug": "hackney"
  },
  "GBBDG": {
    "name": "Barking and Dagenham",
    "slug": "barking-and-dagenham"
  },
  "GBLEC": {
    "name": "Leicestershire",
    "slug": "leicestershire"
  },
  "GBCHE": {
    "name": "Cheshire East",
    "slug": "cheshire-east"
  },
  "GBDBY": {
    "name": "Derbyshire",
    "slug": "derbyshire"
  },
  "GBROT": {
    "name": "Rotherham",
    "slug": "rotherham"
  },
  "GBSHF": {
    "name": "Sheffield",
    "slug": "sheffield"
  },
  "GBSTE": {
    "name": "Stoke-on-Trent",
    "slug": "stoke-on-trent"
  },
  "GBTFW": {
    "name": "Telford and Wrekin",
    "slug": "telford-and-wrekin"
  },
  "GBSTS": {
    "name": "Staffordshire",
    "slug": "staffordshire"
  },
  "GBBRY": {
    "name": "Bromley",
    "slug": "bromley"
  },
  "GBWOR": {
    "name": "Worcestershire",
    "slug": "worcestershire"
  },
  "GBWAR": {
    "name": "Warwickshire",
    "slug": "warwickshire"
  },
  "GBOXF": {
    "name": "Oxfordshire",
    "slug": "oxfordshire"
  },
  "GBWGN": {
    "name": "Wigan",
    "slug": "wigan"
  },
  "GBSKP": {
    "name": "Stockport",
    "slug": "stockport"
  },
  "GBWRT": {
    "name": "Warrington",
    "slug": "warrington"
  },
  "GBWBK": {
    "name": "West Berkshire",
    "slug": "west-berkshire"
  },
  "GBWOK": {
    "name": "Wokingham",
    "slug": "wokingham"
  },
  "GBBRC": {
    "name": "Bracknell Forest",
    "slug": "bracknell-forest"
  },
  "GBWNM": {
    "name": "Royal Borough of Windsor and Maidenhead",
    "slug": "royal-borough-of-windsor-and-maidenhead"
  },
  "GBSLG": {
    "name": "Slough",
    "slug": "slough"
  },
  "GBRDG": {
    "name": "Reading",
    "slug": "reading"
  },
  "GBSRY": {
    "name": "Surrey",
    "slug": "surrey"
  },
  "GBBBD": {
    "name": "Blackburn with Darwen",
    "slug": "blackburn-with-darwen"
  },
  "GBSWD": {
    "name": "Swindon",
    "slug": "swindon"
  },
  "GBBAS": {
    "name": "Bath and North East Somerset",
    "slug": "bath-and-north-east-somerset"
  },
  "GBWIL": {
    "name": "Wiltshire",
    "slug": "wiltshire"
  },
  "GBCLD": {
    "name": "Calderdale",
    "slug": "calderdale"
  },
  "GBKIR": {
    "name": "Kirklees",
    "slug": "kirklees"
  },
  "GBNGM": {
    "name": "Nottingham",
    "slug": "nottingham"
  },
  "GBLCE": {
    "name": "Leicester",
    "slug": "leicester"
  },
  "GBDER": {
    "name": "Derby",
    "slug": "derby"
  },
  "GBLDS": {
    "name": "Leeds",
    "slug": "leeds"
  },
  "GBBRD": {
    "name": "Bradford",
    "slug": "bradford"
  },
  "GBWKF": {
    "name": "Wakefield",
    "slug": "wakefield"
  },
  "GBBNS": {
    "name": "Barnsley",
    "slug": "barnsley"
  },
  "GBSLF": {
    "name": "Salford",
    "slug": "salford"
  },
  "GBBOL": {
    "name": "Bolton",
    "slug": "bolton"
  },
  "GBTRF": {
    "name": "Trafford",
    "slug": "trafford"
  },
  "GBMAN": {
    "name": "Manchester",
    "slug": "manchester"
  },
  "GBOLD": {
    "name": "Oldham",
    "slug": "oldham"
  },
  "GBRCH": {
    "name": "Rochdale",
    "slug": "rochdale"
  },
  "GBTAM": {
    "name": "Tameside",
    "slug": "tameside"
  },
  "GBBUR": {
    "name": "Bury",
    "slug": "bury"
  },
  "GBSOL": {
    "name": "Solihull",
    "slug": "solihull"
  },
  "GBCOV": {
    "name": "Coventry",
    "slug": "coventry"
  },
  "GBBIR": {
    "name": "Birmingham",
    "slug": "birmingham"
  },
  "GBSAW": {
    "name": "Sandwell",
    "slug": "sandwell"
  },
  "GBDUD": {
    "name": "Dudley",
    "slug": "dudley"
  },
  "GBWLL": {
    "name": "Walsall",
    "slug": "walsall"
  },
  "GBWLV": {
    "name": "Wolverhampton",
    "slug": "wolverhampton"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return gbrSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return gbrSvgToSlugMapping[regionId];
}
