// SVG region mapping for Georgia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const geoSvgToSlugMapping: RegionMapping = {
  "GEAB": {
    "name": "Abkhazia",
    "slug": "abkhazia"
  },
  "GESZ": {
    "name": "Samegrelo-Zemo Svaneti",
    "slug": "samegrelo-zemo-svaneti"
  },
  "GESK": {
    "name": "Shida Kartli",
    "slug": "shida-kartli"
  },
  "GERL": {
    "name": "Racha-Lechkhumi-Kvemo Svaneti",
    "slug": "racha-lechkhumi-kvemo-svaneti"
  },
  "GEMM": {
    "name": "Mtskheta-Mtianeti",
    "slug": "mtskheta-mtianeti"
  },
  "GEKA": {
    "name": "Kakheti",
    "slug": "kakheti"
  },
  "GESJ": {
    "name": "Samtskhe-Javakheti",
    "slug": "samtskhe-javakheti"
  },
  "GEAJ": {
    "name": "Ajaria",
    "slug": "ajaria"
  },
  "GEKK": {
    "name": "Kvemo Kartli",
    "slug": "kvemo-kartli"
  },
  "GEGU": {
    "name": "Guria",
    "slug": "guria"
  },
  "GETB": {
    "name": "Tbilisi",
    "slug": "tbilisi"
  },
  "GEIM": {
    "name": "Imereti",
    "slug": "imereti"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return geoSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return geoSvgToSlugMapping[regionId];
}
