// SVG region mapping for Ghana
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const ghaSvgToSlugMapping: RegionMapping = {
  "GHAF": {
    "name": "Ahafo",
    "slug": "ahafo"
  },
  "GHAH": {
    "name": "Ashanti",
    "slug": "ashanti"
  },
  "GHBO": {
    "name": "Bono",
    "slug": "bono"
  },
  "GHBE": {
    "name": "Bono East",
    "slug": "bono-east"
  },
  "GHCP": {
    "name": "Central",
    "slug": "central"
  },
  "GHEP": {
    "name": "Eastern",
    "slug": "eastern"
  },
  "GHAA": {
    "name": "Greater Accra",
    "slug": "greater-accra"
  },
  "GHNP": {
    "name": "Northern",
    "slug": "northern"
  },
  "GHNE": {
    "name": "Northern East",
    "slug": "northern-east"
  },
  "GHOT": {
    "name": "OT",
    "slug": "ot"
  },
  "GHSV": {
    "name": "Savannah",
    "slug": "savannah"
  },
  "GHUE": {
    "name": "Upper East",
    "slug": "upper-east"
  },
  "GHUW": {
    "name": "Upper West",
    "slug": "upper-west"
  },
  "GHTV": {
    "name": "Volta",
    "slug": "volta"
  },
  "GHWP": {
    "name": "Western",
    "slug": "western"
  },
  "GHWN": {
    "name": "Western North",
    "slug": "western-north"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return ghaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return ghaSvgToSlugMapping[regionId];
}
