// SVG region mapping for Guinea
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const ginSvgToSlugMapping: RegionMapping = {
  "GNFA": {
    "name": "Faranah",
    "slug": "faranah"
  },
  "GNKD": {
    "name": "Kindia",
    "slug": "kindia"
  },
  "GNMM": {
    "name": "Mamou",
    "slug": "mamou"
  },
  "GNDB": {
    "name": "Dabola",
    "slug": "dabola"
  },
  "GNFO": {
    "name": "Forécariah",
    "slug": "forcariah"
  },
  "GNGU": {
    "name": "Guéckédou",
    "slug": "guckdou"
  },
  "GNKA": {
    "name": "Kankan",
    "slug": "kankan"
  },
  "GNMD": {
    "name": "Mandiana",
    "slug": "mandiana"
  },
  "GNBE": {
    "name": "Beyla",
    "slug": "beyla"
  },
  "GNLO": {
    "name": "Lola",
    "slug": "lola"
  },
  "GNKN": {
    "name": "Koundara",
    "slug": "koundara"
  },
  "GNML": {
    "name": "Mali",
    "slug": "mali"
  },
  "GNMC": {
    "name": "Macenta",
    "slug": "macenta"
  },
  "GNYO": {
    "name": "Yomou",
    "slug": "yomou"
  },
  "GNNZ": {
    "name": "Nzérékoré",
    "slug": "nzrkor"
  },
  "GNGA": {
    "name": "Gaoual",
    "slug": "gaoual"
  },
  "GNBK": {
    "name": "Boke",
    "slug": "boke"
  },
  "GNSI": {
    "name": "Siguiri",
    "slug": "siguiri"
  },
  "GNKB": {
    "name": "Koubia",
    "slug": "koubia"
  },
  "GNTO": {
    "name": "Tougué",
    "slug": "tougu"
  },
  "GNDI": {
    "name": "Dinguiraye",
    "slug": "dinguiraye"
  },
  "GNBF": {
    "name": "Boffa",
    "slug": "boffa"
  },
  "GNDU": {
    "name": "Dubréka",
    "slug": "dubrka"
  },
  "GNC": {
    "name": "Conakry",
    "slug": "conakry"
  },
  "GNCO": {
    "name": "Coyah",
    "slug": "coyah"
  },
  "GNKS": {
    "name": "Kissidougou",
    "slug": "kissidougou"
  },
  "GNKE": {
    "name": "Kérouané",
    "slug": "krouan"
  },
  "GNTE": {
    "name": "Télimélé",
    "slug": "tliml"
  },
  "GNLE": {
    "name": "Lélouma",
    "slug": "llouma"
  },
  "GNDL": {
    "name": "Dalaba",
    "slug": "dalaba"
  },
  "GNLA": {
    "name": "Labé",
    "slug": "lab"
  },
  "GNPI": {
    "name": "Pita",
    "slug": "pita"
  },
  "GNKO": {
    "name": "Kouroussa",
    "slug": "kouroussa"
  },
  "GNFR": {
    "name": "Fria",
    "slug": "fria"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return ginSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return ginSvgToSlugMapping[regionId];
}
