// SVG region mapping for Gambia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const gmbSvgToSlugMapping: RegionMapping = {
  "GMM": {
    "name": "Brikama",
    "slug": "brikama"
  },
  "GMN": {
    "name": "Banjul",
    "slug": "banjul"
  },
  "GMU": {
    "name": "Banjul",
    "slug": "banjul"
  },
  "GML": {
    "name": "Banjul",
    "slug": "banjul"
  },
  "GMW": {
    "name": "Kerewan",
    "slug": "kerewan"
  },
  "GMB": {
    "name": "Banjul",
    "slug": "banjul"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return gmbSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return gmbSvgToSlugMapping[regionId];
}
