// SVG region mapping for Guinea-Bissau
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const gnbSvgToSlugMapping: RegionMapping = {
  "GWGA": {
    "name": "Gabú",
    "slug": "gab"
  },
  "GWTO": {
    "name": "Tombali",
    "slug": "tombali"
  },
  "GWBA": {
    "name": "Bafatá",
    "slug": "bafat"
  },
  "GWOI": {
    "name": "Oio",
    "slug": "oio"
  },
  "GWCA": {
    "name": "Cacheu",
    "slug": "cacheu"
  },
  "GWBM": {
    "name": "Biombo",
    "slug": "biombo"
  },
  "GWBS": {
    "name": "Bissau",
    "slug": "bissau"
  },
  "GWQU": {
    "name": "Quinara",
    "slug": "quinara"
  },
  "GWBL": {
    "name": "Bolama",
    "slug": "bolama"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return gnbSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return gnbSvgToSlugMapping[regionId];
}
