// SVG region mapping for Equatorial Guinea
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const gnqSvgToSlugMapping: RegionMapping = {
  "GQLI": {
    "name": "Litoral",
    "slug": "litoral"
  },
  "GQKN": {
    "name": "Kié-Ntem",
    "slug": "ki-ntem"
  },
  "GQCS": {
    "name": "Centro Sur",
    "slug": "centro-sur"
  },
  "GQWN": {
    "name": "Wele-Nzás",
    "slug": "wele-nzs"
  },
  "GQAN": {
    "name": "Annobón",
    "slug": "annobn"
  },
  "GQBN": {
    "name": "Bioko Norte",
    "slug": "bioko-norte"
  },
  "GQBS": {
    "name": "Bioko Sur",
    "slug": "bioko-sur"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return gnqSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return gnqSvgToSlugMapping[regionId];
}
