// SVG region mapping for Greece
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const grcSvgToSlugMapping: RegionMapping = {
  "GRC": {
    "name": "Dytiki Makedonia",
    "slug": "dytiki-makedonia"
  },
  "GRD": {
    "name": "Ipeiros",
    "slug": "ipeiros"
  },
  "GRB": {
    "name": "Kentriki Makedonia",
    "slug": "kentriki-makedonia"
  },
  "GRA": {
    "name": "Anatoliki Makedonia kai Thraki",
    "slug": "anatoliki-makedonia-kai-thraki"
  },
  "GR69": {
    "name": "Ayion Oros",
    "slug": "ayion-oros"
  },
  "GRE": {
    "name": "Thessalia",
    "slug": "thessalia"
  },
  "GRH": {
    "name": "Stereá Elláda",
    "slug": "sterea-ellada"
  },
  "GRA1": {
    "name": "Attiki",
    "slug": "attiki"
  },
  "GRJ": {
    "name": "Peloponnisos",
    "slug": "peloponnisos"
  },
  "GRG": {
    "name": "Dytiki Ellada",
    "slug": "dytiki-ellada"
  },
  "GRM": {
    "name": "Kriti",
    "slug": "kriti"
  },
  "GRL": {
    "name": "Notio Aigaio",
    "slug": "notio-aigaio"
  },
  "GRK": {
    "name": "Voreio Aigaio",
    "slug": "voreio-aigaio"
  },
  "GRF": {
    "name": "Ionioi Nisoi",
    "slug": "ionioi-nisoi"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return grcSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return grcSvgToSlugMapping[regionId];
}
