// SVG region mapping for Greece
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const grcSvgToSlugMapping: RegionMapping = {
  "GRC": {
    "name": "Acharnes",
    "slug": "acharnes"
  },
  "GRD": {
    "name": "Arkadia",
    "slug": "arkadia"
  },
  "GRB": {
    "name": "B",
    "slug": "b"
  },
  "GRA": {
    "name": "Acharnes",
    "slug": "acharnes"
  },
  "GR69": {
    "name": "Ayion Oros",
    "slug": "ayion-oros"
  },
  "GRE": {
    "name": "Acharnes",
    "slug": "acharnes"
  },
  "GRH": {
    "name": "Acharnes",
    "slug": "acharnes"
  },
  "GRA1": {
    "name": "Attiki",
    "slug": "attiki"
  },
  "GRJ": {
    "name": "J",
    "slug": "j"
  },
  "GRG": {
    "name": "Argolis",
    "slug": "argolis"
  },
  "GRM": {
    "name": "Drama",
    "slug": "drama"
  },
  "GRL": {
    "name": "Aitolia kai Akarnania",
    "slug": "aitolia-kai-akarnania"
  },
  "GRK": {
    "name": "Aitolia kai Akarnania",
    "slug": "aitolia-kai-akarnania"
  },
  "GRF": {
    "name": "Florina",
    "slug": "florina"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return grcSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return grcSvgToSlugMapping[regionId];
}
