// SVG region mapping for Grenada
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const grdSvgToSlugMapping: RegionMapping = {
  "GD03": {
    "name": "Saint George",
    "slug": "saint-george"
  },
  "GD02": {
    "name": "Saint David",
    "slug": "saint-david"
  },
  "GD01": {
    "name": "Saint Andrew",
    "slug": "saint-andrew"
  },
  "GD06": {
    "name": "Saint Patrick",
    "slug": "saint-patrick"
  },
  "GD05": {
    "name": "Saint Mark",
    "slug": "saint-mark"
  },
  "GD04": {
    "name": "Saint John",
    "slug": "saint-john"
  },
  "GD10": {
    "name": "Carriacou and Petite Martinique",
    "slug": "carriacou-and-petite-martinique"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return grdSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return grdSvgToSlugMapping[regionId];
}
