// SVG region mapping for Greenland
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const grlSvgToSlugMapping: RegionMapping = {
  "GLSM": {
    "name": "Kommuneqarfik Sermersooq",
    "slug": "kommuneqarfik-sermersooq"
  },
  "GLUO": {
    "name": "Nationalparken",
    "slug": "nationalparken"
  },
  "GLQA": {
    "name": "Qaasuitsup Kommunia",
    "slug": "qaasuitsup-kommunia"
  },
  "GLQE": {
    "name": "Qeqqata Kommunia",
    "slug": "qeqqata-kommunia"
  },
  "GLKU": {
    "name": "Kommune Kujalleq",
    "slug": "kommune-kujalleq"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return grlSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return grlSvgToSlugMapping[regionId];
}
