// SVG region mapping for Guatemala
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const gtmSvgToSlugMapping: RegionMapping = {
  "GT22": {
    "name": "Jutiapa",
    "slug": "jutiapa"
  },
  "GT20": {
    "name": "Chiquimula",
    "slug": "chiquimula"
  },
  "GT17": {
    "name": "Petén",
    "slug": "petn"
  },
  "GT12": {
    "name": "San Marcos",
    "slug": "san-marcos"
  },
  "GT13": {
    "name": "Huehuetenango",
    "slug": "huehuetenango"
  },
  "GT14": {
    "name": "Quiché",
    "slug": "quich"
  },
  "GT16": {
    "name": "Alta Verapaz",
    "slug": "alta-verapaz"
  },
  "GT18": {
    "name": "Izabal",
    "slug": "izabal"
  },
  "GT19": {
    "name": "Zacapa",
    "slug": "zacapa"
  },
  "GT11": {
    "name": "Retalhuleu",
    "slug": "retalhuleu"
  },
  "GT10": {
    "name": "Suchitepéquez",
    "slug": "suchitepquez"
  },
  "GT05": {
    "name": "Escuintla",
    "slug": "escuintla"
  },
  "GT06": {
    "name": "Santa Rosa",
    "slug": "santa-rosa"
  },
  "GT04": {
    "name": "Chimaltenango",
    "slug": "chimaltenango"
  },
  "GT03": {
    "name": "Sacatepéquez",
    "slug": "sacatepquez"
  },
  "GT01": {
    "name": "Guatemala",
    "slug": "guatemala"
  },
  "GT21": {
    "name": "Jalapa",
    "slug": "jalapa"
  },
  "GT02": {
    "name": "El Progreso",
    "slug": "el-progreso"
  },
  "GT07": {
    "name": "Sololá",
    "slug": "solol"
  },
  "GT09": {
    "name": "Quezaltenango",
    "slug": "quezaltenango"
  },
  "GT15": {
    "name": "Baja Verapaz",
    "slug": "baja-verapaz"
  },
  "GT08": {
    "name": "Totonicapán",
    "slug": "totonicapn"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return gtmSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return gtmSvgToSlugMapping[regionId];
}
