// SVG region mapping for Guyana
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const guySvgToSlugMapping: RegionMapping = {
  "GYMA": {
    "name": "Mahaica-Berbice",
    "slug": "mahaica-berbice"
  },
  "GYPM": {
    "name": "Pomeroon-Supenaam",
    "slug": "pomeroon-supenaam"
  },
  "GYPT": {
    "name": "Potaro-Siparuni",
    "slug": "potaro-siparuni"
  },
  "GYUD": {
    "name": "Upper Demerara-Berbice",
    "slug": "upper-demerara-berbice"
  },
  "GYBA": {
    "name": "Barima-Waini",
    "slug": "barima-waini"
  },
  "GYDE": {
    "name": "Demerara-Mahaica",
    "slug": "demerara-mahaica"
  },
  "GYCU": {
    "name": "Cuyuni-Mazaruni",
    "slug": "cuyuni-mazaruni"
  },
  "GYUT": {
    "name": "Upper Takutu-Upper Essequibo",
    "slug": "upper-takutu-upper-essequibo"
  },
  "GYEB": {
    "name": "East Berbice-Corentyne",
    "slug": "east-berbice-corentyne"
  },
  "GYES": {
    "name": "Essequibo Islands-West Demerara",
    "slug": "essequibo-islands-west-demerara"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return guySvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return guySvgToSlugMapping[regionId];
}
