// SVG region mapping for Hong Kong
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const hkgSvgToSlugMapping: RegionMapping = {
  "HK5168": {
    "name": "5168",
    "slug": "5168"
  },
  "HK5170": {
    "name": "5170",
    "slug": "5170"
  },
  "HK5156": {
    "name": "5156",
    "slug": "5156"
  },
  "HK5153": {
    "name": "5153",
    "slug": "5153"
  },
  "HK5154": {
    "name": "5154",
    "slug": "5154"
  },
  "HK5155": {
    "name": "5155",
    "slug": "5155"
  },
  "HK5165": {
    "name": "5165",
    "slug": "5165"
  },
  "HK5169": {
    "name": "5169",
    "slug": "5169"
  },
  "HK5163": {
    "name": "5163",
    "slug": "5163"
  },
  "HK5162": {
    "name": "5162",
    "slug": "5162"
  },
  "HK5161": {
    "name": "5161",
    "slug": "5161"
  },
  "HK5158": {
    "name": "5158",
    "slug": "5158"
  },
  "HK5157": {
    "name": "5157",
    "slug": "5157"
  },
  "HK5159": {
    "name": "5159",
    "slug": "5159"
  },
  "HK5164": {
    "name": "5164",
    "slug": "5164"
  },
  "HK5166": {
    "name": "5166",
    "slug": "5166"
  },
  "HK5167": {
    "name": "5167",
    "slug": "5167"
  },
  "HK5160": {
    "name": "5160",
    "slug": "5160"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return hkgSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return hkgSvgToSlugMapping[regionId];
}
