// SVG region mapping for Hong Kong
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const hkgSvgToSlugMapping: RegionMapping = {
  "HK5168": {
    "name": "North",
    "slug": "north"
  },
  "HK5170": {
    "name": "Islands",
    "slug": "islands"
  },
  "HK5156": {
    "name": "Southern",
    "slug": "southern"
  },
  "HK5153": {
    "name": "Central and Western",
    "slug": "central-and-western"
  },
  "HK5154": {
    "name": "Wan Chai",
    "slug": "wan-chai"
  },
  "HK5155": {
    "name": "Eastern",
    "slug": "eastern"
  },
  "HK5165": {
    "name": "Tsuen Wan",
    "slug": "tsuen-wan"
  },
  "HK5169": {
    "name": "Tai Po",
    "slug": "tai-po"
  },
  "HK5163": {
    "name": "Sha Tin",
    "slug": "sha-tin"
  },
  "HK5162": {
    "name": "Sai Kung",
    "slug": "sai-kung"
  },
  "HK5161": {
    "name": "Kwun Tong",
    "slug": "kwun-tong"
  },
  "HK5158": {
    "name": "Kowloon City",
    "slug": "kowloon-city"
  },
  "HK5157": {
    "name": "Yau Tsim Mong",
    "slug": "yau-tsim-mong"
  },
  "HK5159": {
    "name": "Sham Shui Po",
    "slug": "sham-shui-po"
  },
  "HK5164": {
    "name": "Kwai Tsing",
    "slug": "kwai-tsing"
  },
  "HK5166": {
    "name": "Tuen Mun",
    "slug": "tuen-mun"
  },
  "HK5167": {
    "name": "Yuen Long",
    "slug": "yuen-long"
  },
  "HK5160": {
    "name": "Wong Tai Sin",
    "slug": "wong-tai-sin"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return hkgSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return hkgSvgToSlugMapping[regionId];
}
