// SVG region mapping for Honduras
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const hndSvgToSlugMapping: RegionMapping = {
  "HNOC": {
    "name": "Ocotepeque",
    "slug": "ocotepeque"
  },
  "HNLE": {
    "name": "Lempira",
    "slug": "lempira"
  },
  "HNIN": {
    "name": "Intibucá",
    "slug": "intibuc"
  },
  "HNLP": {
    "name": "La Paz",
    "slug": "la-paz"
  },
  "HNVA": {
    "name": "Valle",
    "slug": "valle"
  },
  "HNOL": {
    "name": "Olancho",
    "slug": "olancho"
  },
  "HNGD": {
    "name": "Gracias a Dios",
    "slug": "gracias-a-dios"
  },
  "HNEP": {
    "name": "El Paraíso",
    "slug": "el-paraso"
  },
  "HNCH": {
    "name": "Choluteca",
    "slug": "choluteca"
  },
  "HNCR": {
    "name": "Cortés",
    "slug": "corts"
  },
  "HNSB": {
    "name": "Santa Bárbara",
    "slug": "santa-brbara"
  },
  "HNCP": {
    "name": "Copán",
    "slug": "copn"
  },
  "HNCL": {
    "name": "Colón",
    "slug": "coln"
  },
  "HNAT": {
    "name": "Atlántida",
    "slug": "atlntida"
  },
  "HNIB": {
    "name": "Islas de la Bahía",
    "slug": "islas-de-la-baha"
  },
  "HNCM": {
    "name": "Comayagua",
    "slug": "comayagua"
  },
  "HNYO": {
    "name": "Yoro",
    "slug": "yoro"
  },
  "HNFM": {
    "name": "Francisco Morazán",
    "slug": "francisco-morazn"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return hndSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return hndSvgToSlugMapping[regionId];
}
