// SVG region mapping for Croatia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const hrvSvgToSlugMapping: RegionMapping = {
  "HR20": {
    "name": "Medimurska",
    "slug": "medimurska"
  },
  "HR10": {
    "name": "Viroviticko-Podravska",
    "slug": "viroviticko-podravska"
  },
  "HR06": {
    "name": "Koprivničko-Križevačka",
    "slug": "koprivniko-krievaka"
  },
  "HR14": {
    "name": "Osjecko-Baranjska",
    "slug": "osjecko-baranjska"
  },
  "HR18": {
    "name": "Istarska",
    "slug": "istarska"
  },
  "HR19": {
    "name": "Dubrovacko-Neretvanska",
    "slug": "dubrovacko-neretvanska"
  },
  "HR03": {
    "name": "Sisacko-Moslavacka",
    "slug": "sisacko-moslavacka"
  },
  "HR12": {
    "name": "Brodsko-Posavska",
    "slug": "brodsko-posavska"
  },
  "HR04": {
    "name": "Karlovacka",
    "slug": "karlovacka"
  },
  "HR13": {
    "name": "Zadarska",
    "slug": "zadarska"
  },
  "HR16": {
    "name": "Vukovarsko-Srijemska",
    "slug": "vukovarsko-srijemska"
  },
  "HR17": {
    "name": "Splitsko-Dalmatinska",
    "slug": "splitsko-dalmatinska"
  },
  "HR05": {
    "name": "Varaždinska",
    "slug": "varadinska"
  },
  "HR02": {
    "name": "Krapinsko-Zagorska",
    "slug": "krapinsko-zagorska"
  },
  "HR01": {
    "name": "Zagrebacka",
    "slug": "zagrebacka"
  },
  "HR08": {
    "name": "Primorsko-Goranska",
    "slug": "primorsko-goranska"
  },
  "HR15": {
    "name": "Šibensko-Kninska",
    "slug": "ibensko-kninska"
  },
  "HR09": {
    "name": "Licko-Senjska",
    "slug": "licko-senjska"
  },
  "HR07": {
    "name": "Bjelovarsko-bilogorska",
    "slug": "bjelovarsko-bilogorska"
  },
  "HR21": {
    "name": "Grad Zagreb",
    "slug": "grad-zagreb"
  },
  "HR11": {
    "name": "Požeško-slavonska županija",
    "slug": "poeko-slavonska-upanija"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return hrvSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return hrvSvgToSlugMapping[regionId];
}
