// SVG region mapping for Haiti
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const htiSvgToSlugMapping: RegionMapping = {
  "HTNE": {
    "name": "Nord-Est",
    "slug": "nord-est"
  },
  "HTCE": {
    "name": "Centre",
    "slug": "centre"
  },
  "HTOU": {
    "name": "Ouest",
    "slug": "ouest"
  },
  "HTSE": {
    "name": "Sud-Est",
    "slug": "sud-est"
  },
  "HTSD": {
    "name": "SD",
    "slug": "sd"
  },
  "HTGA": {
    "name": "Grand'Anse",
    "slug": "grandanse"
  },
  "HTNO": {
    "name": "Nord-Ouest",
    "slug": "nord-ouest"
  },
  "HTND": {
    "name": "Nord",
    "slug": "nord"
  },
  "HTAR": {
    "name": "L'Artibonite",
    "slug": "lartibonite"
  },
  "HTNI": {
    "name": "Nippes",
    "slug": "nippes"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return htiSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return htiSvgToSlugMapping[regionId];
}
