// SVG region mapping for Hungary
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const hunSvgToSlugMapping: RegionMapping = {
  "HUSZ": {
    "name": "Szabolcs-Szatmár-Bereg",
    "slug": "szabolcs-szatmr-bereg"
  },
  "HUBE": {
    "name": "Békés",
    "slug": "bks"
  },
  "HUHB": {
    "name": "Hajdú-Bihar",
    "slug": "hajd-bihar"
  },
  "HUCS": {
    "name": "Csongrád",
    "slug": "csongrd"
  },
  "HUGS": {
    "name": "Gyor-Moson-Sopron",
    "slug": "gyor-moson-sopron"
  },
  "HUSN": {
    "name": "Sopron",
    "slug": "sopron"
  },
  "HUVA": {
    "name": "Vas",
    "slug": "vas"
  },
  "HUBK": {
    "name": "Bács-Kiskun",
    "slug": "bcs-kiskun"
  },
  "HUSD": {
    "name": "Szeged",
    "slug": "szeged"
  },
  "HUZA": {
    "name": "Zala",
    "slug": "zala"
  },
  "HUSO": {
    "name": "Somogy",
    "slug": "somogy"
  },
  "HUBA": {
    "name": "Baranya",
    "slug": "baranya"
  },
  "HUBZ": {
    "name": "Borsod-Abaúj-Zemplén",
    "slug": "borsod-abaj-zempln"
  },
  "HUNO": {
    "name": "Nógrád",
    "slug": "ngrd"
  },
  "HUST": {
    "name": "Salgótarján",
    "slug": "salgtarjn"
  },
  "HUKE": {
    "name": "Komárom-Esztergom",
    "slug": "komrom-esztergom"
  },
  "HUPE": {
    "name": "Pest",
    "slug": "pest"
  },
  "HUJN": {
    "name": "Jász-Nagykun-Szolnok",
    "slug": "jsz-nagykun-szolnok"
  },
  "HUFE": {
    "name": "Fejér",
    "slug": "fejr"
  },
  "HUVE": {
    "name": "Veszprém",
    "slug": "veszprm"
  },
  "HUTO": {
    "name": "Tolna",
    "slug": "tolna"
  },
  "HUSK": {
    "name": "Szolnok",
    "slug": "szolnok"
  },
  "HUBU": {
    "name": "Budapest",
    "slug": "budapest"
  },
  "HUER": {
    "name": "Fejer",
    "slug": "fejer"
  },
  "HUHE": {
    "name": "Heves",
    "slug": "heves"
  },
  "HUEG": {
    "name": "Eger",
    "slug": "eger"
  },
  "HUMI": {
    "name": "Miskolc",
    "slug": "miskolc"
  },
  "HUHV": {
    "name": "Hódmezôvásárhely",
    "slug": "hdmezvsrhely"
  },
  "HUDU": {
    "name": "Dunaújváros",
    "slug": "dunajvros"
  },
  "HUKM": {
    "name": "Kecskemét",
    "slug": "kecskemt"
  },
  "HUTB": {
    "name": "Tatabánya",
    "slug": "tatabnya"
  },
  "HUGY": {
    "name": "Gyôr",
    "slug": "gyr"
  },
  "HUSH": {
    "name": "Szombathely",
    "slug": "szombathely"
  },
  "HUZE": {
    "name": "Zalaegerszeg",
    "slug": "zalaegerszeg"
  },
  "HUNK": {
    "name": "Nagykanizsa",
    "slug": "nagykanizsa"
  },
  "HUVM": {
    "name": "Veszprém",
    "slug": "veszprm"
  },
  "HUKV": {
    "name": "Kaposvár",
    "slug": "kaposvr"
  },
  "HUPS": {
    "name": "Pécs",
    "slug": "pcs"
  },
  "HUSS": {
    "name": "Szekszárd",
    "slug": "szekszrd"
  },
  "HUSF": {
    "name": "Székesfehérvár",
    "slug": "szkesfehrvr"
  },
  "HUBC": {
    "name": "Békéscsaba",
    "slug": "bkscsaba"
  },
  "HUDE": {
    "name": "Debrecen",
    "slug": "debrecen"
  },
  "HUNY": {
    "name": "Nyíregyháza",
    "slug": "nyregyhza"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return hunSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return hunSvgToSlugMapping[regionId];
}
