// SVG region mapping for Indonesia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const idnSvgToSlugMapping: RegionMapping = {
  "IDKU": {
    "name": "North Kalimantan",
    "slug": "north-kalimantan"
  },
  "IDNT": {
    "name": "Nusa Tenggara Timur",
    "slug": "nusa-tenggara-timur"
  },
  "IDKB": {
    "name": "Kalimantan Barat",
    "slug": "kalimantan-barat"
  },
  "IDPA": {
    "name": "Papua",
    "slug": "papua"
  },
  "IDJI": {
    "name": "Jawa Timur",
    "slug": "jawa-timur"
  },
  "IDMA": {
    "name": "Maluku",
    "slug": "maluku"
  },
  "IDNB": {
    "name": "Nusa Tenggara Barat",
    "slug": "nusa-tenggara-barat"
  },
  "IDSN": {
    "name": "Sulawesi Selatan",
    "slug": "sulawesi-selatan"
  },
  "IDJT": {
    "name": "Jawa Tengah",
    "slug": "jawa-tengah"
  },
  "IDJB": {
    "name": "Jawa Barat",
    "slug": "jawa-barat"
  },
  "IDJK": {
    "name": "Jakarta Raya",
    "slug": "jakarta-raya"
  },
  "IDBT": {
    "name": "Banten",
    "slug": "banten"
  },
  "IDYO": {
    "name": "Yogyakarta",
    "slug": "yogyakarta"
  },
  "IDSG": {
    "name": "Sulawesi Tenggara",
    "slug": "sulawesi-tenggara"
  },
  "IDPB": {
    "name": "Papua Barat",
    "slug": "papua-barat"
  },
  "IDST": {
    "name": "Sulawesi Tengah",
    "slug": "sulawesi-tengah"
  },
  "IDMU": {
    "name": "Maluku Utara",
    "slug": "maluku-utara"
  },
  "IDKR": {
    "name": "Kepulauan Riau",
    "slug": "kepulauan-riau"
  },
  "IDRI": {
    "name": "Riau",
    "slug": "riau"
  },
  "IDGO": {
    "name": "Gorontalo",
    "slug": "gorontalo"
  },
  "IDSA": {
    "name": "Sulawesi Utara",
    "slug": "sulawesi-utara"
  },
  "IDSR": {
    "name": "Sulawesi Barat",
    "slug": "sulawesi-barat"
  },
  "IDJA": {
    "name": "Jambi",
    "slug": "jambi"
  },
  "IDSS": {
    "name": "Sumatera Selatan",
    "slug": "sumatera-selatan"
  },
  "IDLA": {
    "name": "Lampung",
    "slug": "lampung"
  },
  "IDBE": {
    "name": "Bengkulu",
    "slug": "bengkulu"
  },
  "IDSB": {
    "name": "Sumatera Barat",
    "slug": "sumatera-barat"
  },
  "IDSU": {
    "name": "Sumatera Utara",
    "slug": "sumatera-utara"
  },
  "IDAC": {
    "name": "Aceh",
    "slug": "aceh"
  },
  "IDKT": {
    "name": "Kalimantan Tengah",
    "slug": "kalimantan-tengah"
  },
  "IDKS": {
    "name": "Kalimantan Selatan",
    "slug": "kalimantan-selatan"
  },
  "IDBA": {
    "name": "Bali",
    "slug": "bali"
  },
  "IDBB": {
    "name": "Bangka-Belitung",
    "slug": "bangka-belitung"
  },
  "IDKI": {
    "name": "Kalimantan Timur",
    "slug": "kalimantan-timur"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return idnSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return idnSvgToSlugMapping[regionId];
}
