// SVG region mapping for India
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const indSvgToSlugMapping: RegionMapping = {
  "INAN": {
    "name": "Andaman and Nicobar",
    "slug": "andaman-and-nicobar"
  },
  "INTG": {
    "name": "Telangana",
    "slug": "telangana"
  },
  "INAP": {
    "name": "Andhra Pradesh",
    "slug": "andhra-pradesh"
  },
  "INAR": {
    "name": "Arunachal Pradesh",
    "slug": "arunachal-pradesh"
  },
  "INAS": {
    "name": "Assam",
    "slug": "assam"
  },
  "INBR": {
    "name": "Bihar",
    "slug": "bihar"
  },
  "INCH": {
    "name": "Chandigarh",
    "slug": "chandigarh"
  },
  "INCT": {
    "name": "Chhattisgarh",
    "slug": "chhattisgarh"
  },
  "INDH": {
    "name": "Dādra and Nagar Haveli and Damān and Diu",
    "slug": "ddra-and-nagar-haveli-and-damn-and-diu"
  },
  "INDL": {
    "name": "Delhi",
    "slug": "delhi"
  },
  "INGA": {
    "name": "Chandigarh",
    "slug": "chandigarh"
  },
  "INGJ": {
    "name": "Gujarat",
    "slug": "gujarat"
  },
  "INHR": {
    "name": "Haryana",
    "slug": "haryana"
  },
  "INHP": {
    "name": "Himachal Pradesh",
    "slug": "himachal-pradesh"
  },
  "INJH": {
    "name": "Jharkhand",
    "slug": "jharkhand"
  },
  "INKA": {
    "name": "Karnataka",
    "slug": "karnataka"
  },
  "INKL": {
    "name": "Kerala",
    "slug": "kerala"
  },
  "INMP": {
    "name": "Madhya Pradesh",
    "slug": "madhya-pradesh"
  },
  "INMH": {
    "name": "Maharashtra",
    "slug": "maharashtra"
  },
  "INMN": {
    "name": "Manipur",
    "slug": "manipur"
  },
  "INML": {
    "name": "Meghalaya",
    "slug": "meghalaya"
  },
  "INMZ": {
    "name": "Mizoram",
    "slug": "mizoram"
  },
  "INNL": {
    "name": "Nagaland",
    "slug": "nagaland"
  },
  "INOR": {
    "name": "Orissa",
    "slug": "orissa"
  },
  "INPY": {
    "name": "Puducherry",
    "slug": "puducherry"
  },
  "INPB": {
    "name": "Punjab",
    "slug": "punjab"
  },
  "INRJ": {
    "name": "Rajasthan",
    "slug": "rajasthan"
  },
  "INSK": {
    "name": "Sikkim",
    "slug": "sikkim"
  },
  "INTN": {
    "name": "Tamil Nadu",
    "slug": "tamil-nadu"
  },
  "INTR": {
    "name": "Tripura",
    "slug": "tripura"
  },
  "INUP": {
    "name": "Uttar Pradesh",
    "slug": "uttar-pradesh"
  },
  "INUT": {
    "name": "Uttaranchal",
    "slug": "uttaranchal"
  },
  "INWB": {
    "name": "West Bengal",
    "slug": "west-bengal"
  },
  "INLD": {
    "name": "Lakshadweep",
    "slug": "lakshadweep"
  },
  "INJK": {
    "name": "Jammu and Kashmir",
    "slug": "jammu-and-kashmir"
  },
  "INLA": {
    "name": "Ladakh",
    "slug": "ladakh"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return indSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return indSvgToSlugMapping[regionId];
}
