// Central registry for all country SVG mappings
// Auto-generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export interface CountrySVGConfig {
  svgFileName: string;
  regionIdPrefix: string;
  regionMapping: RegionMapping;
}

// Import individual country mappings
import { afgSvgToSlugMapping } from "./afg-svg-mapping";
import { albSvgToSlugMapping } from "./alb-svg-mapping";
import { dzaSvgToSlugMapping } from "./dza-svg-mapping";
import { andSvgToSlugMapping } from "./and-svg-mapping";
import { agoSvgToSlugMapping } from "./ago-svg-mapping";
import { aiaSvgToSlugMapping } from "./aia-svg-mapping";
import { atgSvgToSlugMapping } from "./atg-svg-mapping";
import { argSvgToSlugMapping } from "./arg-svg-mapping";
import { armSvgToSlugMapping } from "./arm-svg-mapping";
import { ausSvgToSlugMapping } from "./aus-svg-mapping";
import { autSvgToSlugMapping } from "./aut-svg-mapping";
import { azeSvgToSlugMapping } from "./aze-svg-mapping";
import { bhsSvgToSlugMapping } from "./bhs-svg-mapping";
import { bhrSvgToSlugMapping } from "./bhr-svg-mapping";
import { bgdSvgToSlugMapping } from "./bgd-svg-mapping";
import { brbSvgToSlugMapping } from "./brb-svg-mapping";
import { blrSvgToSlugMapping } from "./blr-svg-mapping";
import { belSvgToSlugMapping } from "./bel-svg-mapping";
import { blzSvgToSlugMapping } from "./blz-svg-mapping";
import { benSvgToSlugMapping } from "./ben-svg-mapping";
import { bmuSvgToSlugMapping } from "./bmu-svg-mapping";
import { btnSvgToSlugMapping } from "./btn-svg-mapping";
import { bolSvgToSlugMapping } from "./bol-svg-mapping";
import { bihSvgToSlugMapping } from "./bih-svg-mapping";
import { bwaSvgToSlugMapping } from "./bwa-svg-mapping";
import { braSvgToSlugMapping } from "./bra-svg-mapping";
import { brnSvgToSlugMapping } from "./brn-svg-mapping";
import { bgrSvgToSlugMapping } from "./bgr-svg-mapping";
import { bfaSvgToSlugMapping } from "./bfa-svg-mapping";
import { bdiSvgToSlugMapping } from "./bdi-svg-mapping";
import { khmSvgToSlugMapping } from "./khm-svg-mapping";
import { cmrSvgToSlugMapping } from "./cmr-svg-mapping";
import { canSvgToSlugMapping } from "./can-svg-mapping";
import { cpvSvgToSlugMapping } from "./cpv-svg-mapping";
import { cafSvgToSlugMapping } from "./caf-svg-mapping";
import { tcdSvgToSlugMapping } from "./tcd-svg-mapping";
import { chlSvgToSlugMapping } from "./chl-svg-mapping";
import { chnSvgToSlugMapping } from "./chn-svg-mapping";
import { colSvgToSlugMapping } from "./col-svg-mapping";
import { comSvgToSlugMapping } from "./com-svg-mapping";
import { criSvgToSlugMapping } from "./cri-svg-mapping";
import { hrvSvgToSlugMapping } from "./hrv-svg-mapping";
import { cubSvgToSlugMapping } from "./cub-svg-mapping";
import { cypSvgToSlugMapping } from "./cyp-svg-mapping";
import { czeSvgToSlugMapping } from "./cze-svg-mapping";
import { civSvgToSlugMapping } from "./civ-svg-mapping";
import { codSvgToSlugMapping } from "./cod-svg-mapping";
import { dnkSvgToSlugMapping } from "./dnk-svg-mapping";
import { djiSvgToSlugMapping } from "./dji-svg-mapping";
import { dmaSvgToSlugMapping } from "./dma-svg-mapping";
import { domSvgToSlugMapping } from "./dom-svg-mapping";
import { ecuSvgToSlugMapping } from "./ecu-svg-mapping";
import { egySvgToSlugMapping } from "./egy-svg-mapping";
import { slvSvgToSlugMapping } from "./slv-svg-mapping";
import { gnqSvgToSlugMapping } from "./gnq-svg-mapping";
import { eriSvgToSlugMapping } from "./eri-svg-mapping";
import { estSvgToSlugMapping } from "./est-svg-mapping";
import { ethSvgToSlugMapping } from "./eth-svg-mapping";
import { fjiSvgToSlugMapping } from "./fji-svg-mapping";
import { finSvgToSlugMapping } from "./fin-svg-mapping";
import { fraSvgToSlugMapping } from "./fra-svg-mapping";
import { pyfSvgToSlugMapping } from "./pyf-svg-mapping";
import { gabSvgToSlugMapping } from "./gab-svg-mapping";
import { geoSvgToSlugMapping } from "./geo-svg-mapping";
import { deuSvgToSlugMapping } from "./deu-svg-mapping";
import { ghaSvgToSlugMapping } from "./gha-svg-mapping";
import { grcSvgToSlugMapping } from "./grc-svg-mapping";
import { grlSvgToSlugMapping } from "./grl-svg-mapping";
import { grdSvgToSlugMapping } from "./grd-svg-mapping";
import { gtmSvgToSlugMapping } from "./gtm-svg-mapping";
import { ginSvgToSlugMapping } from "./gin-svg-mapping";
import { gnbSvgToSlugMapping } from "./gnb-svg-mapping";
import { guySvgToSlugMapping } from "./guy-svg-mapping";
import { htiSvgToSlugMapping } from "./hti-svg-mapping";
import { hndSvgToSlugMapping } from "./hnd-svg-mapping";
import { hkgSvgToSlugMapping } from "./hkg-svg-mapping";
import { hunSvgToSlugMapping } from "./hun-svg-mapping";
import { islSvgToSlugMapping } from "./isl-svg-mapping";
import { indSvgToSlugMapping } from "./ind-svg-mapping";
import { idnSvgToSlugMapping } from "./idn-svg-mapping";
import { irnSvgToSlugMapping } from "./irn-svg-mapping";
import { irqSvgToSlugMapping } from "./irq-svg-mapping";
import { irlSvgToSlugMapping } from "./irl-svg-mapping";
import { isrSvgToSlugMapping } from "./isr-svg-mapping";
import { itaSvgToSlugMapping } from "./ita-svg-mapping";
import { jamSvgToSlugMapping } from "./jam-svg-mapping";
import { jpnSvgToSlugMapping } from "./jpn-svg-mapping";
import { jorSvgToSlugMapping } from "./jor-svg-mapping";
import { kazSvgToSlugMapping } from "./kaz-svg-mapping";
import { kenSvgToSlugMapping } from "./ken-svg-mapping";
import { kwtSvgToSlugMapping } from "./kwt-svg-mapping";
import { kgzSvgToSlugMapping } from "./kgz-svg-mapping";
import { laoSvgToSlugMapping } from "./lao-svg-mapping";
import { lvaSvgToSlugMapping } from "./lva-svg-mapping";
import { lbnSvgToSlugMapping } from "./lbn-svg-mapping";
import { lsoSvgToSlugMapping } from "./lso-svg-mapping";
import { lbrSvgToSlugMapping } from "./lbr-svg-mapping";
import { lbySvgToSlugMapping } from "./lby-svg-mapping";
import { lieSvgToSlugMapping } from "./lie-svg-mapping";
import { ltuSvgToSlugMapping } from "./ltu-svg-mapping";
import { luxSvgToSlugMapping } from "./lux-svg-mapping";
import { mkdSvgToSlugMapping } from "./mkd-svg-mapping";
import { mdgSvgToSlugMapping } from "./mdg-svg-mapping";
import { mwiSvgToSlugMapping } from "./mwi-svg-mapping";
import { mysSvgToSlugMapping } from "./mys-svg-mapping";
import { mdvSvgToSlugMapping } from "./mdv-svg-mapping";
import { mliSvgToSlugMapping } from "./mli-svg-mapping";
import { mltSvgToSlugMapping } from "./mlt-svg-mapping";
import { mrtSvgToSlugMapping } from "./mrt-svg-mapping";
import { musSvgToSlugMapping } from "./mus-svg-mapping";
import { mexSvgToSlugMapping } from "./mex-svg-mapping";
import { mdaSvgToSlugMapping } from "./mda-svg-mapping";
import { mngSvgToSlugMapping } from "./mng-svg-mapping";
import { mneSvgToSlugMapping } from "./mne-svg-mapping";
import { msrSvgToSlugMapping } from "./msr-svg-mapping";
import { marSvgToSlugMapping } from "./mar-svg-mapping";
import { mozSvgToSlugMapping } from "./moz-svg-mapping";
import { mmrSvgToSlugMapping } from "./mmr-svg-mapping";
import { namSvgToSlugMapping } from "./nam-svg-mapping";
import { nruSvgToSlugMapping } from "./nru-svg-mapping";
import { nplSvgToSlugMapping } from "./npl-svg-mapping";
import { nldSvgToSlugMapping } from "./nld-svg-mapping";
import { nclSvgToSlugMapping } from "./ncl-svg-mapping";
import { nzlSvgToSlugMapping } from "./nzl-svg-mapping";
import { nicSvgToSlugMapping } from "./nic-svg-mapping";
import { nerSvgToSlugMapping } from "./ner-svg-mapping";
import { ngaSvgToSlugMapping } from "./nga-svg-mapping";
import { prkSvgToSlugMapping } from "./prk-svg-mapping";
import { norSvgToSlugMapping } from "./nor-svg-mapping";
import { omnSvgToSlugMapping } from "./omn-svg-mapping";
import { pakSvgToSlugMapping } from "./pak-svg-mapping";
import { pseSvgToSlugMapping } from "./pse-svg-mapping";
import { panSvgToSlugMapping } from "./pan-svg-mapping";
import { pngSvgToSlugMapping } from "./png-svg-mapping";
import { prySvgToSlugMapping } from "./pry-svg-mapping";
import { perSvgToSlugMapping } from "./per-svg-mapping";
import { phlSvgToSlugMapping } from "./phl-svg-mapping";
import { polSvgToSlugMapping } from "./pol-svg-mapping";
import { prtSvgToSlugMapping } from "./prt-svg-mapping";
import { qatSvgToSlugMapping } from "./qat-svg-mapping";
import { cogSvgToSlugMapping } from "./cog-svg-mapping";
import { rouSvgToSlugMapping } from "./rou-svg-mapping";
import { rusSvgToSlugMapping } from "./rus-svg-mapping";
import { rwaSvgToSlugMapping } from "./rwa-svg-mapping";
import { knaSvgToSlugMapping } from "./kna-svg-mapping";
import { lcaSvgToSlugMapping } from "./lca-svg-mapping";
import { vctSvgToSlugMapping } from "./vct-svg-mapping";
import { sauSvgToSlugMapping } from "./sau-svg-mapping";
import { senSvgToSlugMapping } from "./sen-svg-mapping";
import { srbSvgToSlugMapping } from "./srb-svg-mapping";
import { sycSvgToSlugMapping } from "./syc-svg-mapping";
import { sleSvgToSlugMapping } from "./sle-svg-mapping";
import { sgpSvgToSlugMapping } from "./sgp-svg-mapping";
import { svkSvgToSlugMapping } from "./svk-svg-mapping";
import { svnSvgToSlugMapping } from "./svn-svg-mapping";
import { slbSvgToSlugMapping } from "./slb-svg-mapping";
import { somSvgToSlugMapping } from "./som-svg-mapping";
import { zafSvgToSlugMapping } from "./zaf-svg-mapping";
import { korSvgToSlugMapping } from "./kor-svg-mapping";
import { ssdSvgToSlugMapping } from "./ssd-svg-mapping";
import { espSvgToSlugMapping } from "./esp-svg-mapping";
import { lkaSvgToSlugMapping } from "./lka-svg-mapping";
import { sdnSvgToSlugMapping } from "./sdn-svg-mapping";
import { surSvgToSlugMapping } from "./sur-svg-mapping";
import { swzSvgToSlugMapping } from "./swz-svg-mapping";
import { sweSvgToSlugMapping } from "./swe-svg-mapping";
import { cheSvgToSlugMapping } from "./che-svg-mapping";
import { syrSvgToSlugMapping } from "./syr-svg-mapping";
import { stpSvgToSlugMapping } from "./stp-svg-mapping";
import { twnSvgToSlugMapping } from "./twn-svg-mapping";
import { tjkSvgToSlugMapping } from "./tjk-svg-mapping";
import { tzaSvgToSlugMapping } from "./tza-svg-mapping";
import { thaSvgToSlugMapping } from "./tha-svg-mapping";
import { gmbSvgToSlugMapping } from "./gmb-svg-mapping";
import { tlsSvgToSlugMapping } from "./tls-svg-mapping";
import { tgoSvgToSlugMapping } from "./tgo-svg-mapping";
import { tonSvgToSlugMapping } from "./ton-svg-mapping";
import { ttoSvgToSlugMapping } from "./tto-svg-mapping";
import { tunSvgToSlugMapping } from "./tun-svg-mapping";
import { turSvgToSlugMapping } from "./tur-svg-mapping";
import { tkmSvgToSlugMapping } from "./tkm-svg-mapping";
import { tcaSvgToSlugMapping } from "./tca-svg-mapping";
import { ugaSvgToSlugMapping } from "./uga-svg-mapping";
import { ukrSvgToSlugMapping } from "./ukr-svg-mapping";
import { areSvgToSlugMapping } from "./are-svg-mapping";
import { gbrSvgToSlugMapping } from "./gbr-svg-mapping";
import { usaSvgToSlugMapping } from "./usa-svg-mapping";
import { virSvgToSlugMapping } from "./vir-svg-mapping";
import { urySvgToSlugMapping } from "./ury-svg-mapping";
import { uzbSvgToSlugMapping } from "./uzb-svg-mapping";
import { vutSvgToSlugMapping } from "./vut-svg-mapping";
import { venSvgToSlugMapping } from "./ven-svg-mapping";
import { vnmSvgToSlugMapping } from "./vnm-svg-mapping";
import { yemSvgToSlugMapping } from "./yem-svg-mapping";
import { zmbSvgToSlugMapping } from "./zmb-svg-mapping";
import { zweSvgToSlugMapping } from "./zwe-svg-mapping";

// Central registry
const svgMappings: { [countrySlug: string]: CountrySVGConfig } = {
  afg: {
    svgFileName: "afg-map.svg",
    regionIdPrefix: "AF",
    regionMapping: afgSvgToSlugMapping,
  },
  alb: {
    svgFileName: "alb-map.svg",
    regionIdPrefix: "AL",
    regionMapping: albSvgToSlugMapping,
  },
  dza: {
    svgFileName: "dza-map.svg",
    regionIdPrefix: "DZ",
    regionMapping: dzaSvgToSlugMapping,
  },
  and: {
    svgFileName: "and-map.svg",
    regionIdPrefix: "AD",
    regionMapping: andSvgToSlugMapping,
  },
  ago: {
    svgFileName: "ago-map.svg",
    regionIdPrefix: "AO",
    regionMapping: agoSvgToSlugMapping,
  },
  aia: {
    svgFileName: "aia-map.svg",
    regionIdPrefix: "AI",
    regionMapping: aiaSvgToSlugMapping,
  },
  atg: {
    svgFileName: "atg-map.svg",
    regionIdPrefix: "AG",
    regionMapping: atgSvgToSlugMapping,
  },
  arg: {
    svgFileName: "arg-map.svg",
    regionIdPrefix: "AR",
    regionMapping: argSvgToSlugMapping,
  },
  arm: {
    svgFileName: "arm-map.svg",
    regionIdPrefix: "AM",
    regionMapping: armSvgToSlugMapping,
  },
  aus: {
    svgFileName: "aus-map.svg",
    regionIdPrefix: "AU",
    regionMapping: ausSvgToSlugMapping,
  },
  aut: {
    svgFileName: "aut-map.svg",
    regionIdPrefix: "AT",
    regionMapping: autSvgToSlugMapping,
  },
  aze: {
    svgFileName: "aze-map.svg",
    regionIdPrefix: "AZ",
    regionMapping: azeSvgToSlugMapping,
  },
  bhs: {
    svgFileName: "bhs-map.svg",
    regionIdPrefix: "BS",
    regionMapping: bhsSvgToSlugMapping,
  },
  bhr: {
    svgFileName: "bhr-map.svg",
    regionIdPrefix: "BH",
    regionMapping: bhrSvgToSlugMapping,
  },
  bgd: {
    svgFileName: "bgd-map.svg",
    regionIdPrefix: "BD",
    regionMapping: bgdSvgToSlugMapping,
  },
  brb: {
    svgFileName: "brb-map.svg",
    regionIdPrefix: "BB",
    regionMapping: brbSvgToSlugMapping,
  },
  blr: {
    svgFileName: "blr-map.svg",
    regionIdPrefix: "BY",
    regionMapping: blrSvgToSlugMapping,
  },
  bel: {
    svgFileName: "bel-map.svg",
    regionIdPrefix: "BE",
    regionMapping: belSvgToSlugMapping,
  },
  blz: {
    svgFileName: "blz-map.svg",
    regionIdPrefix: "BZ",
    regionMapping: blzSvgToSlugMapping,
  },
  ben: {
    svgFileName: "ben-map.svg",
    regionIdPrefix: "BJ",
    regionMapping: benSvgToSlugMapping,
  },
  bmu: {
    svgFileName: "bmu-map.svg",
    regionIdPrefix: "BM",
    regionMapping: bmuSvgToSlugMapping,
  },
  btn: {
    svgFileName: "btn-map.svg",
    regionIdPrefix: "BT",
    regionMapping: btnSvgToSlugMapping,
  },
  bol: {
    svgFileName: "bol-map.svg",
    regionIdPrefix: "BO",
    regionMapping: bolSvgToSlugMapping,
  },
  bih: {
    svgFileName: "bih-map.svg",
    regionIdPrefix: "BA",
    regionMapping: bihSvgToSlugMapping,
  },
  bwa: {
    svgFileName: "bwa-map.svg",
    regionIdPrefix: "BW",
    regionMapping: bwaSvgToSlugMapping,
  },
  bra: {
    svgFileName: "bra-map.svg",
    regionIdPrefix: "BR",
    regionMapping: braSvgToSlugMapping,
  },
  brn: {
    svgFileName: "brn-map.svg",
    regionIdPrefix: "BN",
    regionMapping: brnSvgToSlugMapping,
  },
  bgr: {
    svgFileName: "bgr-map.svg",
    regionIdPrefix: "BG",
    regionMapping: bgrSvgToSlugMapping,
  },
  bfa: {
    svgFileName: "bfa-map.svg",
    regionIdPrefix: "BF",
    regionMapping: bfaSvgToSlugMapping,
  },
  bdi: {
    svgFileName: "bdi-map.svg",
    regionIdPrefix: "BI",
    regionMapping: bdiSvgToSlugMapping,
  },
  khm: {
    svgFileName: "khm-map.svg",
    regionIdPrefix: "KH",
    regionMapping: khmSvgToSlugMapping,
  },
  cmr: {
    svgFileName: "cmr-map.svg",
    regionIdPrefix: "CM",
    regionMapping: cmrSvgToSlugMapping,
  },
  can: {
    svgFileName: "can-map.svg",
    regionIdPrefix: "CA",
    regionMapping: canSvgToSlugMapping,
  },
  cpv: {
    svgFileName: "cpv-map.svg",
    regionIdPrefix: "CV",
    regionMapping: cpvSvgToSlugMapping,
  },
  caf: {
    svgFileName: "caf-map.svg",
    regionIdPrefix: "CF",
    regionMapping: cafSvgToSlugMapping,
  },
  tcd: {
    svgFileName: "tcd-map.svg",
    regionIdPrefix: "TD",
    regionMapping: tcdSvgToSlugMapping,
  },
  chl: {
    svgFileName: "chl-map.svg",
    regionIdPrefix: "CL",
    regionMapping: chlSvgToSlugMapping,
  },
  chn: {
    svgFileName: "chn-map.svg",
    regionIdPrefix: "CN",
    regionMapping: chnSvgToSlugMapping,
  },
  col: {
    svgFileName: "col-map.svg",
    regionIdPrefix: "CO",
    regionMapping: colSvgToSlugMapping,
  },
  com: {
    svgFileName: "com-map.svg",
    regionIdPrefix: "KM",
    regionMapping: comSvgToSlugMapping,
  },
  cri: {
    svgFileName: "cri-map.svg",
    regionIdPrefix: "CR",
    regionMapping: criSvgToSlugMapping,
  },
  hrv: {
    svgFileName: "hrv-map.svg",
    regionIdPrefix: "HR",
    regionMapping: hrvSvgToSlugMapping,
  },
  cub: {
    svgFileName: "cub-map.svg",
    regionIdPrefix: "CU",
    regionMapping: cubSvgToSlugMapping,
  },
  cyp: {
    svgFileName: "cyp-map.svg",
    regionIdPrefix: "CY",
    regionMapping: cypSvgToSlugMapping,
  },
  cze: {
    svgFileName: "cze-map.svg",
    regionIdPrefix: "CZ",
    regionMapping: czeSvgToSlugMapping,
  },
  civ: {
    svgFileName: "civ-map.svg",
    regionIdPrefix: "CI",
    regionMapping: civSvgToSlugMapping,
  },
  cod: {
    svgFileName: "cod-map.svg",
    regionIdPrefix: "CD",
    regionMapping: codSvgToSlugMapping,
  },
  dnk: {
    svgFileName: "dnk-map.svg",
    regionIdPrefix: "DK",
    regionMapping: dnkSvgToSlugMapping,
  },
  dji: {
    svgFileName: "dji-map.svg",
    regionIdPrefix: "DJ",
    regionMapping: djiSvgToSlugMapping,
  },
  dma: {
    svgFileName: "dma-map.svg",
    regionIdPrefix: "DM",
    regionMapping: dmaSvgToSlugMapping,
  },
  dom: {
    svgFileName: "dom-map.svg",
    regionIdPrefix: "DO",
    regionMapping: domSvgToSlugMapping,
  },
  ecu: {
    svgFileName: "ecu-map.svg",
    regionIdPrefix: "EC",
    regionMapping: ecuSvgToSlugMapping,
  },
  egy: {
    svgFileName: "egy-map.svg",
    regionIdPrefix: "EG",
    regionMapping: egySvgToSlugMapping,
  },
  slv: {
    svgFileName: "slv-map.svg",
    regionIdPrefix: "SV",
    regionMapping: slvSvgToSlugMapping,
  },
  gnq: {
    svgFileName: "gnq-map.svg",
    regionIdPrefix: "GQ",
    regionMapping: gnqSvgToSlugMapping,
  },
  eri: {
    svgFileName: "eri-map.svg",
    regionIdPrefix: "ER",
    regionMapping: eriSvgToSlugMapping,
  },
  est: {
    svgFileName: "est-map.svg",
    regionIdPrefix: "EE",
    regionMapping: estSvgToSlugMapping,
  },
  eth: {
    svgFileName: "eth-map.svg",
    regionIdPrefix: "ET",
    regionMapping: ethSvgToSlugMapping,
  },
  fji: {
    svgFileName: "fji-map.svg",
    regionIdPrefix: "FJ",
    regionMapping: fjiSvgToSlugMapping,
  },
  fin: {
    svgFileName: "fin-map.svg",
    regionIdPrefix: "FI",
    regionMapping: finSvgToSlugMapping,
  },
  fra: {
    svgFileName: "fra-map.svg",
    regionIdPrefix: "FR",
    regionMapping: fraSvgToSlugMapping,
  },
  pyf: {
    svgFileName: "pyf-map.svg",
    regionIdPrefix: "PF",
    regionMapping: pyfSvgToSlugMapping,
  },
  gab: {
    svgFileName: "gab-map.svg",
    regionIdPrefix: "GA",
    regionMapping: gabSvgToSlugMapping,
  },
  geo: {
    svgFileName: "geo-map.svg",
    regionIdPrefix: "GE",
    regionMapping: geoSvgToSlugMapping,
  },
  deu: {
    svgFileName: "deu-map.svg",
    regionIdPrefix: "DE",
    regionMapping: deuSvgToSlugMapping,
  },
  gha: {
    svgFileName: "gha-map.svg",
    regionIdPrefix: "GH",
    regionMapping: ghaSvgToSlugMapping,
  },
  grc: {
    svgFileName: "grc-map.svg",
    regionIdPrefix: "GR",
    regionMapping: grcSvgToSlugMapping,
  },
  grl: {
    svgFileName: "grl-map.svg",
    regionIdPrefix: "GL",
    regionMapping: grlSvgToSlugMapping,
  },
  grd: {
    svgFileName: "grd-map.svg",
    regionIdPrefix: "GD",
    regionMapping: grdSvgToSlugMapping,
  },
  gtm: {
    svgFileName: "gtm-map.svg",
    regionIdPrefix: "GT",
    regionMapping: gtmSvgToSlugMapping,
  },
  gin: {
    svgFileName: "gin-map.svg",
    regionIdPrefix: "GN",
    regionMapping: ginSvgToSlugMapping,
  },
  gnb: {
    svgFileName: "gnb-map.svg",
    regionIdPrefix: "GW",
    regionMapping: gnbSvgToSlugMapping,
  },
  guy: {
    svgFileName: "guy-map.svg",
    regionIdPrefix: "GY",
    regionMapping: guySvgToSlugMapping,
  },
  hti: {
    svgFileName: "hti-map.svg",
    regionIdPrefix: "HT",
    regionMapping: htiSvgToSlugMapping,
  },
  hnd: {
    svgFileName: "hnd-map.svg",
    regionIdPrefix: "HN",
    regionMapping: hndSvgToSlugMapping,
  },
  hkg: {
    svgFileName: "hkg-map.svg",
    regionIdPrefix: "HK",
    regionMapping: hkgSvgToSlugMapping,
  },
  hun: {
    svgFileName: "hun-map.svg",
    regionIdPrefix: "HU",
    regionMapping: hunSvgToSlugMapping,
  },
  isl: {
    svgFileName: "isl-map.svg",
    regionIdPrefix: "IS",
    regionMapping: islSvgToSlugMapping,
  },
  ind: {
    svgFileName: "ind-map.svg",
    regionIdPrefix: "IN",
    regionMapping: indSvgToSlugMapping,
  },
  idn: {
    svgFileName: "idn-map.svg",
    regionIdPrefix: "ID",
    regionMapping: idnSvgToSlugMapping,
  },
  irn: {
    svgFileName: "irn-map.svg",
    regionIdPrefix: "IR",
    regionMapping: irnSvgToSlugMapping,
  },
  irq: {
    svgFileName: "irq-map.svg",
    regionIdPrefix: "IQ",
    regionMapping: irqSvgToSlugMapping,
  },
  irl: {
    svgFileName: "irl-map.svg",
    regionIdPrefix: "IE",
    regionMapping: irlSvgToSlugMapping,
  },
  isr: {
    svgFileName: "isr-map.svg",
    regionIdPrefix: "IL",
    regionMapping: isrSvgToSlugMapping,
  },
  ita: {
    svgFileName: "ita-map.svg",
    regionIdPrefix: "IT",
    regionMapping: itaSvgToSlugMapping,
  },
  jam: {
    svgFileName: "jam-map.svg",
    regionIdPrefix: "JM",
    regionMapping: jamSvgToSlugMapping,
  },
  jpn: {
    svgFileName: "jpn-map.svg",
    regionIdPrefix: "JP",
    regionMapping: jpnSvgToSlugMapping,
  },
  jor: {
    svgFileName: "jor-map.svg",
    regionIdPrefix: "JO",
    regionMapping: jorSvgToSlugMapping,
  },
  kaz: {
    svgFileName: "kaz-map.svg",
    regionIdPrefix: "KZ",
    regionMapping: kazSvgToSlugMapping,
  },
  ken: {
    svgFileName: "ken-map.svg",
    regionIdPrefix: "KE",
    regionMapping: kenSvgToSlugMapping,
  },
  kwt: {
    svgFileName: "kwt-map.svg",
    regionIdPrefix: "KW",
    regionMapping: kwtSvgToSlugMapping,
  },
  kgz: {
    svgFileName: "kgz-map.svg",
    regionIdPrefix: "KG",
    regionMapping: kgzSvgToSlugMapping,
  },
  lao: {
    svgFileName: "lao-map.svg",
    regionIdPrefix: "LA",
    regionMapping: laoSvgToSlugMapping,
  },
  lva: {
    svgFileName: "lva-map.svg",
    regionIdPrefix: "LV",
    regionMapping: lvaSvgToSlugMapping,
  },
  lbn: {
    svgFileName: "lbn-map.svg",
    regionIdPrefix: "LB",
    regionMapping: lbnSvgToSlugMapping,
  },
  lso: {
    svgFileName: "lso-map.svg",
    regionIdPrefix: "LS",
    regionMapping: lsoSvgToSlugMapping,
  },
  lbr: {
    svgFileName: "lbr-map.svg",
    regionIdPrefix: "LR",
    regionMapping: lbrSvgToSlugMapping,
  },
  lby: {
    svgFileName: "lby-map.svg",
    regionIdPrefix: "LY",
    regionMapping: lbySvgToSlugMapping,
  },
  lie: {
    svgFileName: "lie-map.svg",
    regionIdPrefix: "LI",
    regionMapping: lieSvgToSlugMapping,
  },
  ltu: {
    svgFileName: "ltu-map.svg",
    regionIdPrefix: "LT",
    regionMapping: ltuSvgToSlugMapping,
  },
  lux: {
    svgFileName: "lux-map.svg",
    regionIdPrefix: "LU",
    regionMapping: luxSvgToSlugMapping,
  },
  mkd: {
    svgFileName: "mkd-map.svg",
    regionIdPrefix: "MK",
    regionMapping: mkdSvgToSlugMapping,
  },
  mdg: {
    svgFileName: "mdg-map.svg",
    regionIdPrefix: "MG",
    regionMapping: mdgSvgToSlugMapping,
  },
  mwi: {
    svgFileName: "mwi-map.svg",
    regionIdPrefix: "MW",
    regionMapping: mwiSvgToSlugMapping,
  },
  mys: {
    svgFileName: "mys-map.svg",
    regionIdPrefix: "MY",
    regionMapping: mysSvgToSlugMapping,
  },
  mdv: {
    svgFileName: "mdv-map.svg",
    regionIdPrefix: "MV",
    regionMapping: mdvSvgToSlugMapping,
  },
  mli: {
    svgFileName: "mli-map.svg",
    regionIdPrefix: "ML",
    regionMapping: mliSvgToSlugMapping,
  },
  mlt: {
    svgFileName: "mlt-map.svg",
    regionIdPrefix: "MT",
    regionMapping: mltSvgToSlugMapping,
  },
  mrt: {
    svgFileName: "mrt-map.svg",
    regionIdPrefix: "MR",
    regionMapping: mrtSvgToSlugMapping,
  },
  mus: {
    svgFileName: "mus-map.svg",
    regionIdPrefix: "MU",
    regionMapping: musSvgToSlugMapping,
  },
  mex: {
    svgFileName: "mex-map.svg",
    regionIdPrefix: "MX",
    regionMapping: mexSvgToSlugMapping,
  },
  mda: {
    svgFileName: "mda-map.svg",
    regionIdPrefix: "MD",
    regionMapping: mdaSvgToSlugMapping,
  },
  mng: {
    svgFileName: "mng-map.svg",
    regionIdPrefix: "MN",
    regionMapping: mngSvgToSlugMapping,
  },
  mne: {
    svgFileName: "mne-map.svg",
    regionIdPrefix: "ME",
    regionMapping: mneSvgToSlugMapping,
  },
  msr: {
    svgFileName: "msr-map.svg",
    regionIdPrefix: "MS",
    regionMapping: msrSvgToSlugMapping,
  },
  mar: {
    svgFileName: "mar-map.svg",
    regionIdPrefix: "MA",
    regionMapping: marSvgToSlugMapping,
  },
  moz: {
    svgFileName: "moz-map.svg",
    regionIdPrefix: "MZ",
    regionMapping: mozSvgToSlugMapping,
  },
  mmr: {
    svgFileName: "mmr-map.svg",
    regionIdPrefix: "MM",
    regionMapping: mmrSvgToSlugMapping,
  },
  nam: {
    svgFileName: "nam-map.svg",
    regionIdPrefix: "NA",
    regionMapping: namSvgToSlugMapping,
  },
  nru: {
    svgFileName: "nru-map.svg",
    regionIdPrefix: "NR",
    regionMapping: nruSvgToSlugMapping,
  },
  npl: {
    svgFileName: "npl-map.svg",
    regionIdPrefix: "NP",
    regionMapping: nplSvgToSlugMapping,
  },
  nld: {
    svgFileName: "nld-map.svg",
    regionIdPrefix: "NL",
    regionMapping: nldSvgToSlugMapping,
  },
  ncl: {
    svgFileName: "ncl-map.svg",
    regionIdPrefix: "NC",
    regionMapping: nclSvgToSlugMapping,
  },
  nzl: {
    svgFileName: "nzl-map.svg",
    regionIdPrefix: "NZ",
    regionMapping: nzlSvgToSlugMapping,
  },
  nic: {
    svgFileName: "nic-map.svg",
    regionIdPrefix: "NI",
    regionMapping: nicSvgToSlugMapping,
  },
  ner: {
    svgFileName: "ner-map.svg",
    regionIdPrefix: "NE",
    regionMapping: nerSvgToSlugMapping,
  },
  nga: {
    svgFileName: "nga-map.svg",
    regionIdPrefix: "NG",
    regionMapping: ngaSvgToSlugMapping,
  },
  prk: {
    svgFileName: "prk-map.svg",
    regionIdPrefix: "KP",
    regionMapping: prkSvgToSlugMapping,
  },
  nor: {
    svgFileName: "nor-map.svg",
    regionIdPrefix: "NO",
    regionMapping: norSvgToSlugMapping,
  },
  omn: {
    svgFileName: "omn-map.svg",
    regionIdPrefix: "OM",
    regionMapping: omnSvgToSlugMapping,
  },
  pak: {
    svgFileName: "pak-map.svg",
    regionIdPrefix: "PK",
    regionMapping: pakSvgToSlugMapping,
  },
  pse: {
    svgFileName: "pse-map.svg",
    regionIdPrefix: "PS",
    regionMapping: pseSvgToSlugMapping,
  },
  pan: {
    svgFileName: "pan-map.svg",
    regionIdPrefix: "PA",
    regionMapping: panSvgToSlugMapping,
  },
  png: {
    svgFileName: "png-map.svg",
    regionIdPrefix: "PG",
    regionMapping: pngSvgToSlugMapping,
  },
  pry: {
    svgFileName: "pry-map.svg",
    regionIdPrefix: "PY",
    regionMapping: prySvgToSlugMapping,
  },
  per: {
    svgFileName: "per-map.svg",
    regionIdPrefix: "PE",
    regionMapping: perSvgToSlugMapping,
  },
  phl: {
    svgFileName: "phl-map.svg",
    regionIdPrefix: "PH",
    regionMapping: phlSvgToSlugMapping,
  },
  pol: {
    svgFileName: "pol-map.svg",
    regionIdPrefix: "PL",
    regionMapping: polSvgToSlugMapping,
  },
  prt: {
    svgFileName: "prt-map.svg",
    regionIdPrefix: "PT",
    regionMapping: prtSvgToSlugMapping,
  },
  qat: {
    svgFileName: "qat-map.svg",
    regionIdPrefix: "QA",
    regionMapping: qatSvgToSlugMapping,
  },
  cog: {
    svgFileName: "cog-map.svg",
    regionIdPrefix: "CG",
    regionMapping: cogSvgToSlugMapping,
  },
  rou: {
    svgFileName: "rou-map.svg",
    regionIdPrefix: "RO",
    regionMapping: rouSvgToSlugMapping,
  },
  rus: {
    svgFileName: "rus-map.svg",
    regionIdPrefix: "RU",
    regionMapping: rusSvgToSlugMapping,
  },
  rwa: {
    svgFileName: "rwa-map.svg",
    regionIdPrefix: "RW",
    regionMapping: rwaSvgToSlugMapping,
  },
  kna: {
    svgFileName: "kna-map.svg",
    regionIdPrefix: "KN",
    regionMapping: knaSvgToSlugMapping,
  },
  lca: {
    svgFileName: "lca-map.svg",
    regionIdPrefix: "LC",
    regionMapping: lcaSvgToSlugMapping,
  },
  vct: {
    svgFileName: "vct-map.svg",
    regionIdPrefix: "VC",
    regionMapping: vctSvgToSlugMapping,
  },
  sau: {
    svgFileName: "sau-map.svg",
    regionIdPrefix: "SA",
    regionMapping: sauSvgToSlugMapping,
  },
  sen: {
    svgFileName: "sen-map.svg",
    regionIdPrefix: "SN",
    regionMapping: senSvgToSlugMapping,
  },
  srb: {
    svgFileName: "srb-map.svg",
    regionIdPrefix: "RS",
    regionMapping: srbSvgToSlugMapping,
  },
  syc: {
    svgFileName: "syc-map.svg",
    regionIdPrefix: "SC",
    regionMapping: sycSvgToSlugMapping,
  },
  sle: {
    svgFileName: "sle-map.svg",
    regionIdPrefix: "SL",
    regionMapping: sleSvgToSlugMapping,
  },
  sgp: {
    svgFileName: "sgp-map.svg",
    regionIdPrefix: "SG",
    regionMapping: sgpSvgToSlugMapping,
  },
  svk: {
    svgFileName: "svk-map.svg",
    regionIdPrefix: "SK",
    regionMapping: svkSvgToSlugMapping,
  },
  svn: {
    svgFileName: "svn-map.svg",
    regionIdPrefix: "SI",
    regionMapping: svnSvgToSlugMapping,
  },
  slb: {
    svgFileName: "slb-map.svg",
    regionIdPrefix: "SB",
    regionMapping: slbSvgToSlugMapping,
  },
  som: {
    svgFileName: "som-map.svg",
    regionIdPrefix: "SO",
    regionMapping: somSvgToSlugMapping,
  },
  zaf: {
    svgFileName: "zaf-map.svg",
    regionIdPrefix: "ZA",
    regionMapping: zafSvgToSlugMapping,
  },
  kor: {
    svgFileName: "kor-map.svg",
    regionIdPrefix: "KR",
    regionMapping: korSvgToSlugMapping,
  },
  ssd: {
    svgFileName: "ssd-map.svg",
    regionIdPrefix: "SS",
    regionMapping: ssdSvgToSlugMapping,
  },
  esp: {
    svgFileName: "esp-map.svg",
    regionIdPrefix: "ES",
    regionMapping: espSvgToSlugMapping,
  },
  lka: {
    svgFileName: "lka-map.svg",
    regionIdPrefix: "LK",
    regionMapping: lkaSvgToSlugMapping,
  },
  sdn: {
    svgFileName: "sdn-map.svg",
    regionIdPrefix: "SD",
    regionMapping: sdnSvgToSlugMapping,
  },
  sur: {
    svgFileName: "sur-map.svg",
    regionIdPrefix: "SR",
    regionMapping: surSvgToSlugMapping,
  },
  swz: {
    svgFileName: "swz-map.svg",
    regionIdPrefix: "SZ",
    regionMapping: swzSvgToSlugMapping,
  },
  swe: {
    svgFileName: "swe-map.svg",
    regionIdPrefix: "SE",
    regionMapping: sweSvgToSlugMapping,
  },
  che: {
    svgFileName: "che-map.svg",
    regionIdPrefix: "CH",
    regionMapping: cheSvgToSlugMapping,
  },
  syr: {
    svgFileName: "syr-map.svg",
    regionIdPrefix: "SY",
    regionMapping: syrSvgToSlugMapping,
  },
  stp: {
    svgFileName: "stp-map.svg",
    regionIdPrefix: "ST",
    regionMapping: stpSvgToSlugMapping,
  },
  twn: {
    svgFileName: "twn-map.svg",
    regionIdPrefix: "TW",
    regionMapping: twnSvgToSlugMapping,
  },
  tjk: {
    svgFileName: "tjk-map.svg",
    regionIdPrefix: "TJ",
    regionMapping: tjkSvgToSlugMapping,
  },
  tza: {
    svgFileName: "tza-map.svg",
    regionIdPrefix: "TZ",
    regionMapping: tzaSvgToSlugMapping,
  },
  tha: {
    svgFileName: "tha-map.svg",
    regionIdPrefix: "TH",
    regionMapping: thaSvgToSlugMapping,
  },
  gmb: {
    svgFileName: "gmb-map.svg",
    regionIdPrefix: "GM",
    regionMapping: gmbSvgToSlugMapping,
  },
  tls: {
    svgFileName: "tls-map.svg",
    regionIdPrefix: "TL",
    regionMapping: tlsSvgToSlugMapping,
  },
  tgo: {
    svgFileName: "tgo-map.svg",
    regionIdPrefix: "TG",
    regionMapping: tgoSvgToSlugMapping,
  },
  ton: {
    svgFileName: "ton-map.svg",
    regionIdPrefix: "TO",
    regionMapping: tonSvgToSlugMapping,
  },
  tto: {
    svgFileName: "tto-map.svg",
    regionIdPrefix: "TT",
    regionMapping: ttoSvgToSlugMapping,
  },
  tun: {
    svgFileName: "tun-map.svg",
    regionIdPrefix: "TN",
    regionMapping: tunSvgToSlugMapping,
  },
  tur: {
    svgFileName: "tur-map.svg",
    regionIdPrefix: "TR",
    regionMapping: turSvgToSlugMapping,
  },
  tkm: {
    svgFileName: "tkm-map.svg",
    regionIdPrefix: "TM",
    regionMapping: tkmSvgToSlugMapping,
  },
  tca: {
    svgFileName: "tca-map.svg",
    regionIdPrefix: "TC",
    regionMapping: tcaSvgToSlugMapping,
  },
  uga: {
    svgFileName: "uga-map.svg",
    regionIdPrefix: "UG",
    regionMapping: ugaSvgToSlugMapping,
  },
  ukr: {
    svgFileName: "ukr-map.svg",
    regionIdPrefix: "UA",
    regionMapping: ukrSvgToSlugMapping,
  },
  are: {
    svgFileName: "are-map.svg",
    regionIdPrefix: "AE",
    regionMapping: areSvgToSlugMapping,
  },
  gbr: {
    svgFileName: "gbr-map.svg",
    regionIdPrefix: "GB",
    regionMapping: gbrSvgToSlugMapping,
  },
  usa: {
    svgFileName: "usa-map.svg",
    regionIdPrefix: "US",
    regionMapping: usaSvgToSlugMapping,
  },
  vir: {
    svgFileName: "vir-map.svg",
    regionIdPrefix: "VI",
    regionMapping: virSvgToSlugMapping,
  },
  ury: {
    svgFileName: "ury-map.svg",
    regionIdPrefix: "UY",
    regionMapping: urySvgToSlugMapping,
  },
  uzb: {
    svgFileName: "uzb-map.svg",
    regionIdPrefix: "UZ",
    regionMapping: uzbSvgToSlugMapping,
  },
  vut: {
    svgFileName: "vut-map.svg",
    regionIdPrefix: "VU",
    regionMapping: vutSvgToSlugMapping,
  },
  ven: {
    svgFileName: "ven-map.svg",
    regionIdPrefix: "VE",
    regionMapping: venSvgToSlugMapping,
  },
  vnm: {
    svgFileName: "vnm-map.svg",
    regionIdPrefix: "VN",
    regionMapping: vnmSvgToSlugMapping,
  },
  yem: {
    svgFileName: "yem-map.svg",
    regionIdPrefix: "YE",
    regionMapping: yemSvgToSlugMapping,
  },
  zmb: {
    svgFileName: "zmb-map.svg",
    regionIdPrefix: "ZM",
    regionMapping: zmbSvgToSlugMapping,
  },
  zwe: {
    svgFileName: "zwe-map.svg",
    regionIdPrefix: "ZW",
    regionMapping: zweSvgToSlugMapping,
  },
};

export function getSVGConfigForCountry(countrySlug: string): CountrySVGConfig | undefined {
  return svgMappings[countrySlug.toLowerCase()];
}

export function getSvgRegionSlugForCountry(countrySlug: string, regionId: string): string | undefined {
  const config = getSVGConfigForCountry(countrySlug);
  return config?.regionMapping[regionId]?.slug;
}

export function getSvgRegionInfoForCountry(countrySlug: string, regionId: string): { name: string; slug: string } | undefined {
  const config = getSVGConfigForCountry(countrySlug);
  return config?.regionMapping[regionId];
}
