// SVG region mapping for Ireland
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const irlSvgToSlugMapping: RegionMapping = {
  "IEDL": {
    "name": "Donegal",
    "slug": "donegal"
  },
  "IELM": {
    "name": "Leitrim",
    "slug": "leitrim"
  },
  "IECN": {
    "name": "Cavan",
    "slug": "cavan"
  },
  "IEMN": {
    "name": "Monaghan",
    "slug": "monaghan"
  },
  "IELH": {
    "name": "Louth",
    "slug": "louth"
  },
  "IED": {
    "name": "Donegal",
    "slug": "donegal"
  },
  "IEWW": {
    "name": "Wicklow",
    "slug": "wicklow"
  },
  "IEWX": {
    "name": "Wexford",
    "slug": "wexford"
  },
  "IEKK": {
    "name": "Kilkenny",
    "slug": "kilkenny"
  },
  "IEWD": {
    "name": "Waterford",
    "slug": "waterford"
  },
  "IECO": {
    "name": "Cork",
    "slug": "cork"
  },
  "IEKY": {
    "name": "Kerry",
    "slug": "kerry"
  },
  "IELK": {
    "name": "Limerick",
    "slug": "limerick"
  },
  "IECE": {
    "name": "Clare",
    "slug": "clare"
  },
  "IEG": {
    "name": "Armagh",
    "slug": "armagh"
  },
  "IEMO": {
    "name": "Mayo",
    "slug": "mayo"
  },
  "IESO": {
    "name": "Sligo",
    "slug": "sligo"
  },
  "IEMH": {
    "name": "Meath",
    "slug": "meath"
  },
  "IEKE": {
    "name": "Kildare",
    "slug": "kildare"
  },
  "IECW": {
    "name": "Carlow",
    "slug": "carlow"
  },
  "IELS": {
    "name": "Laoighis",
    "slug": "laoighis"
  },
  "IEOY": {
    "name": "Offaly",
    "slug": "offaly"
  },
  "IEWH": {
    "name": "Westmeath",
    "slug": "westmeath"
  },
  "IELD": {
    "name": "Longford",
    "slug": "longford"
  },
  "IERN": {
    "name": "Roscommon",
    "slug": "roscommon"
  },
  "IETA": {
    "name": "Tipperary",
    "slug": "tipperary"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return irlSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return irlSvgToSlugMapping[regionId];
}
