// SVG region mapping for Iran
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const irnSvgToSlugMapping: RegionMapping = {
  "IR02": {
    "name": "West Azarbaijan",
    "slug": "west-azarbaijan"
  },
  "IR01": {
    "name": "East Azarbaijan",
    "slug": "east-azarbaijan"
  },
  "IR03": {
    "name": "Ardebil",
    "slug": "ardebil"
  },
  "IR19": {
    "name": "Gilan",
    "slug": "gilan"
  },
  "IR16": {
    "name": "Kordestan",
    "slug": "kordestan"
  },
  "IR17": {
    "name": "Kermanshah",
    "slug": "kermanshah"
  },
  "IR05": {
    "name": "Ilam",
    "slug": "ilam"
  },
  "IR10": {
    "name": "Khuzestan",
    "slug": "khuzestan"
  },
  "IR28": {
    "name": "Qazvin",
    "slug": "qazvin"
  },
  "IR27": {
    "name": "Golestan",
    "slug": "golestan"
  },
  "IR30": {
    "name": "Razavi Khorasan",
    "slug": "razavi-khorasan"
  },
  "IR29": {
    "name": "South Khorasan",
    "slug": "south-khorasan"
  },
  "IR13": {
    "name": "Sistan and Baluchestan",
    "slug": "sistan-and-baluchestan"
  },
  "IR06": {
    "name": "Bushehr",
    "slug": "bushehr"
  },
  "IR23": {
    "name": "Hormozgan",
    "slug": "hormozgan"
  },
  "IR21": {
    "name": "Mazandaran",
    "slug": "mazandaran"
  },
  "IR12": {
    "name": "Semnan",
    "slug": "semnan"
  },
  "IR11": {
    "name": "Zanjan",
    "slug": "zanjan"
  },
  "IR22": {
    "name": "Markazi",
    "slug": "markazi"
  },
  "IR04": {
    "name": "Esfahan",
    "slug": "esfahan"
  },
  "IR08": {
    "name": "Chahar Mahall and Bakhtiari",
    "slug": "chahar-mahall-and-bakhtiari"
  },
  "IR18": {
    "name": "Kohgiluyeh and Buyer Ahmad",
    "slug": "kohgiluyeh-and-buyer-ahmad"
  },
  "IR14": {
    "name": "Fars",
    "slug": "fars"
  },
  "IR15": {
    "name": "Kerman",
    "slug": "kerman"
  },
  "IR24": {
    "name": "Hamadan",
    "slug": "hamadan"
  },
  "IR20": {
    "name": "Lorestan",
    "slug": "lorestan"
  },
  "IR25": {
    "name": "Yazd",
    "slug": "yazd"
  },
  "IR26": {
    "name": "26",
    "slug": "26"
  },
  "IR07": {
    "name": "Tehran",
    "slug": "tehran"
  },
  "IR09": {
    "name": "Alborz",
    "slug": "alborz"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return irnSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return irnSvgToSlugMapping[regionId];
}
