// SVG region mapping for Iraq
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const irqSvgToSlugMapping: RegionMapping = {
  "IQDA": {
    "name": "Dihok",
    "slug": "dihok"
  },
  "IQAR": {
    "name": "Arbil",
    "slug": "arbil"
  },
  "IQBA": {
    "name": "Al-Basrah",
    "slug": "al-basrah"
  },
  "IQMU": {
    "name": "Al-Muthannia",
    "slug": "al-muthannia"
  },
  "IQSU": {
    "name": "As-Sulaymaniyah",
    "slug": "as-sulaymaniyah"
  },
  "IQDI": {
    "name": "Diyala",
    "slug": "diyala"
  },
  "IQWA": {
    "name": "Wasit",
    "slug": "wasit"
  },
  "IQMA": {
    "name": "Maysan",
    "slug": "maysan"
  },
  "IQAN": {
    "name": "Al-Anbar",
    "slug": "al-anbar"
  },
  "IQNA": {
    "name": "An-Najaf",
    "slug": "an-najaf"
  },
  "IQNI": {
    "name": "Ninawa",
    "slug": "ninawa"
  },
  "IQSD": {
    "name": "Sala ad-Din",
    "slug": "sala-ad-din"
  },
  "IQKI": {
    "name": "Kirkūk",
    "slug": "kirkk"
  },
  "IQBG": {
    "name": "Baghdad",
    "slug": "baghdad"
  },
  "IQBB": {
    "name": "Babil",
    "slug": "babil"
  },
  "IQQA": {
    "name": "Al-Qādisiyyah",
    "slug": "al-qdisiyyah"
  },
  "IQDQ": {
    "name": "Dhi-Qar",
    "slug": "dhi-qar"
  },
  "IQKA": {
    "name": "Karbala'",
    "slug": "karbala"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return irqSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return irqSvgToSlugMapping[regionId];
}
