// SVG region mapping for Iceland
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const islSvgToSlugMapping: RegionMapping = {
  "IS7": {
    "name": "Austurland",
    "slug": "austurland"
  },
  "IS8": {
    "name": "Suðurland",
    "slug": "sudurland"
  },
  "IS2": {
    "name": "Suðurnes",
    "slug": "sudurnes"
  },
  "IS1": {
    "name": "Höfuðborgarsvæði",
    "slug": "hofudborgarsvaedi"
  },
  "IS3": {
    "name": "Vesturland",
    "slug": "vesturland"
  },
  "IS4": {
    "name": "Vestfirðir",
    "slug": "vestfirdir"
  },
  "IS5": {
    "name": "Norðurland vestra",
    "slug": "nordurland-vestra"
  },
  "IS6": {
    "name": "Norðurland eystra",
    "slug": "nordurland-eystra"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return islSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return islSvgToSlugMapping[regionId];
}
