// SVG region mapping for Iceland
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const islSvgToSlugMapping: RegionMapping = {
  "IS7": {
    "name": "7",
    "slug": "7"
  },
  "IS8": {
    "name": "8",
    "slug": "8"
  },
  "IS2": {
    "name": "2",
    "slug": "2"
  },
  "IS1": {
    "name": "1",
    "slug": "1"
  },
  "IS3": {
    "name": "3",
    "slug": "3"
  },
  "IS4": {
    "name": "4",
    "slug": "4"
  },
  "IS5": {
    "name": "5",
    "slug": "5"
  },
  "IS6": {
    "name": "6",
    "slug": "6"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return islSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return islSvgToSlugMapping[regionId];
}
