// SVG region mapping for Israel
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const isrSvgToSlugMapping: RegionMapping = {
  "ILD": {
    "name": "Hadaron",
    "slug": "hadaron"
  },
  "ILZ": {
    "name": "Gaza",
    "slug": "gaza"
  },
  "ILHA": {
    "name": "Haifa",
    "slug": "haifa"
  },
  "ILM": {
    "name": "Bethlehem",
    "slug": "bethlehem"
  },
  "ILJM": {
    "name": "Jerusalem",
    "slug": "jerusalem"
  },
  "ILTA": {
    "name": "Tel Aviv",
    "slug": "tel-aviv"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return isrSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return isrSvgToSlugMapping[regionId];
}
