// SVG region mapping for Italy
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const itaSvgToSlugMapping: RegionMapping = {
  "IT23": {
    "name": "Valle d'Aosta",
    "slug": "valle-daosta"
  },
  "IT21": {
    "name": "Piedmont",
    "slug": "piedmont"
  },
  "IT42": {
    "name": "Liguria",
    "slug": "liguria"
  },
  "IT25": {
    "name": "Lombardy",
    "slug": "lombardy"
  },
  "IT32": {
    "name": "Trentino-Alto Adige",
    "slug": "trentino-alto-adige"
  },
  "IT34": {
    "name": "Veneto",
    "slug": "veneto"
  },
  "IT36": {
    "name": "Friuli Venezia Giulia",
    "slug": "friuli-venezia-giulia"
  },
  "IT52": {
    "name": "Tuscany",
    "slug": "tuscany"
  },
  "IT55": {
    "name": "Umbria",
    "slug": "umbria"
  },
  "IT62": {
    "name": "Lazio",
    "slug": "lazio"
  },
  "IT65": {
    "name": "Abruzzo",
    "slug": "abruzzo"
  },
  "IT75": {
    "name": "Puglia",
    "slug": "puglia"
  },
  "IT72": {
    "name": "Campania",
    "slug": "campania"
  },
  "IT67": {
    "name": "Molise",
    "slug": "molise"
  },
  "IT77": {
    "name": "Basilicata",
    "slug": "basilicata"
  },
  "IT78": {
    "name": "Calabria",
    "slug": "calabria"
  },
  "IT82": {
    "name": "Sicilia",
    "slug": "sicilia"
  },
  "IT88": {
    "name": "Sardegna",
    "slug": "sardegna"
  },
  "IT45": {
    "name": "Emilia-Romagna",
    "slug": "emilia-romagna"
  },
  "IT57": {
    "name": "Marche",
    "slug": "marche"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return itaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return itaSvgToSlugMapping[regionId];
}
