// SVG region mapping for Jamaica
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const jamSvgToSlugMapping: RegionMapping = {
  "JM06": {
    "name": "Saint Ann",
    "slug": "saint-ann"
  },
  "JM07": {
    "name": "Trelawny",
    "slug": "trelawny"
  },
  "JM08": {
    "name": "Saint James",
    "slug": "saint-james"
  },
  "JM09": {
    "name": "Hanover",
    "slug": "hanover"
  },
  "JM10": {
    "name": "Westmoreland",
    "slug": "westmoreland"
  },
  "JM11": {
    "name": "Saint Elizabeth",
    "slug": "saint-elizabeth"
  },
  "JM12": {
    "name": "Manchester",
    "slug": "manchester"
  },
  "JM13": {
    "name": "Clarendon",
    "slug": "clarendon"
  },
  "JM14": {
    "name": "Saint Catherine",
    "slug": "saint-catherine"
  },
  "JM02": {
    "name": "Saint Andrew",
    "slug": "saint-andrew"
  },
  "JM01": {
    "name": "Kingston",
    "slug": "kingston"
  },
  "JM03": {
    "name": "Saint Thomas",
    "slug": "saint-thomas"
  },
  "JM04": {
    "name": "Portland",
    "slug": "portland"
  },
  "JM05": {
    "name": "Saint Mary",
    "slug": "saint-mary"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return jamSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return jamSvgToSlugMapping[regionId];
}
