// SVG region mapping for Jordan
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const jorSvgToSlugMapping: RegionMapping = {
  "JOIR": {
    "name": "Irbid",
    "slug": "irbid"
  },
  "JOMD": {
    "name": "Madaba",
    "slug": "madaba"
  },
  "JOKA": {
    "name": "Karak",
    "slug": "karak"
  },
  "JOAT": {
    "name": "Tafilah",
    "slug": "tafilah"
  },
  "JOAQ": {
    "name": "Aqaba",
    "slug": "aqaba"
  },
  "JOBA": {
    "name": "Balqa",
    "slug": "balqa"
  },
  "JOMA": {
    "name": "Mafraq",
    "slug": "mafraq"
  },
  "JOMN": {
    "name": "Ma`an",
    "slug": "maan"
  },
  "JOAM": {
    "name": "Amman",
    "slug": "amman"
  },
  "JOAZ": {
    "name": "Zarqa",
    "slug": "zarqa"
  },
  "JOAJ": {
    "name": "Ajlun",
    "slug": "ajlun"
  },
  "JOJA": {
    "name": "Jarash",
    "slug": "jarash"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return jorSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return jorSvgToSlugMapping[regionId];
}
