// SVG region mapping for Japan
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const jpnSvgToSlugMapping: RegionMapping = {
  "JP46": {
    "name": "Kagoshima",
    "slug": "kagoshima"
  },
  "JP44": {
    "name": "Ōita",
    "slug": "ita"
  },
  "JP40": {
    "name": "Fukuoka",
    "slug": "fukuoka"
  },
  "JP41": {
    "name": "Saga",
    "slug": "saga"
  },
  "JP42": {
    "name": "Nagasaki",
    "slug": "nagasaki"
  },
  "JP43": {
    "name": "Kumamoto",
    "slug": "kumamoto"
  },
  "JP45": {
    "name": "Miyazaki",
    "slug": "miyazaki"
  },
  "JP36": {
    "name": "Tokushima",
    "slug": "tokushima"
  },
  "JP37": {
    "name": "Kagawa",
    "slug": "kagawa"
  },
  "JP38": {
    "name": "Ehime",
    "slug": "ehime"
  },
  "JP39": {
    "name": "Kōchi",
    "slug": "kchi"
  },
  "JP32": {
    "name": "Shimane",
    "slug": "shimane"
  },
  "JP35": {
    "name": "Yamaguchi",
    "slug": "yamaguchi"
  },
  "JP31": {
    "name": "Tottori",
    "slug": "tottori"
  },
  "JP28": {
    "name": "Hyōgo",
    "slug": "hygo"
  },
  "JP26": {
    "name": "Kyōto",
    "slug": "kyto"
  },
  "JP18": {
    "name": "Fukui",
    "slug": "fukui"
  },
  "JP17": {
    "name": "Ishikawa",
    "slug": "ishikawa"
  },
  "JP16": {
    "name": "Toyama",
    "slug": "toyama"
  },
  "JP15": {
    "name": "Niigata",
    "slug": "niigata"
  },
  "JP06": {
    "name": "Yamagata",
    "slug": "yamagata"
  },
  "JP05": {
    "name": "Akita",
    "slug": "akita"
  },
  "JP02": {
    "name": "Aomori",
    "slug": "aomori"
  },
  "JP03": {
    "name": "Iwate",
    "slug": "iwate"
  },
  "JP04": {
    "name": "Miyagi",
    "slug": "miyagi"
  },
  "JP07": {
    "name": "Fukushima",
    "slug": "fukushima"
  },
  "JP08": {
    "name": "Ibaraki",
    "slug": "ibaraki"
  },
  "JP12": {
    "name": "Chiba",
    "slug": "chiba"
  },
  "JP13": {
    "name": "Tokyo",
    "slug": "tokyo"
  },
  "JP14": {
    "name": "Kanagawa",
    "slug": "kanagawa"
  },
  "JP22": {
    "name": "Shizuoka",
    "slug": "shizuoka"
  },
  "JP23": {
    "name": "Aichi",
    "slug": "aichi"
  },
  "JP24": {
    "name": "Mie",
    "slug": "mie"
  },
  "JP30": {
    "name": "Wakayama",
    "slug": "wakayama"
  },
  "JP27": {
    "name": "Ōsaka",
    "slug": "saka"
  },
  "JP33": {
    "name": "Okayama",
    "slug": "okayama"
  },
  "JP34": {
    "name": "Hiroshima",
    "slug": "hiroshima"
  },
  "JP01": {
    "name": "Hokkaidō",
    "slug": "hokkaid"
  },
  "JP47": {
    "name": "Okinawa",
    "slug": "okinawa"
  },
  "JP10": {
    "name": "Gunma",
    "slug": "gunma"
  },
  "JP20": {
    "name": "Nagano",
    "slug": "nagano"
  },
  "JP09": {
    "name": "Tochigi",
    "slug": "tochigi"
  },
  "JP21": {
    "name": "Gifu",
    "slug": "gifu"
  },
  "JP25": {
    "name": "Shiga",
    "slug": "shiga"
  },
  "JP11": {
    "name": "Saitama",
    "slug": "saitama"
  },
  "JP19": {
    "name": "Yamanashi",
    "slug": "yamanashi"
  },
  "JP29": {
    "name": "Nara",
    "slug": "nara"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return jpnSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return jpnSvgToSlugMapping[regionId];
}
