// SVG region mapping for Kazakhstan
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const kazSvgToSlugMapping: RegionMapping = {
  "KZ11": {
    "name": "Akmola",
    "slug": "akmola"
  },
  "KZ15": {
    "name": "Aktobe",
    "slug": "aktobe"
  },
  "KZ19": {
    "name": "Almaty",
    "slug": "almaty"
  },
  "KZ75": {
    "name": "Almaty (city)",
    "slug": "almaty-city"
  },
  "KZ23": {
    "name": "Atyrau",
    "slug": "atyrau"
  },
  "KZ10": {
    "name": "Abai",
    "slug": "abai"
  },
  "KZ31": {
    "name": "Jambyl",
    "slug": "jambyl"
  },
  "KZ62": {
    "name": "Ulytau",
    "slug": "ulytau"
  },
  "KZ39": {
    "name": "Kostanay",
    "slug": "kostanay"
  },
  "KZ43": {
    "name": "Kyzylorda",
    "slug": "kyzylorda"
  },
  "KZ47": {
    "name": "Mangystau",
    "slug": "mangystau"
  },
  "KZ59": {
    "name": "North Kazakhstan",
    "slug": "north-kazakhstan"
  },
  "KZ71": {
    "name": "Astana",
    "slug": "astana"
  },
  "KZ55": {
    "name": "Pavlodar",
    "slug": "pavlodar"
  },
  "KZ79": {
    "name": "Shymkent (city)",
    "slug": "shymkent-city"
  },
  "KZ61": {
    "name": "Turkestan",
    "slug": "turkestan"
  },
  "KZ27": {
    "name": "West Kazakhstan",
    "slug": "west-kazakhstan"
  },
  "KZ35": {
    "name": "Karaganda",
    "slug": "karaganda"
  },
  "KZ33": {
    "name": "Jetisu",
    "slug": "jetisu"
  },
  "KZ63": {
    "name": "East Kazakhstan",
    "slug": "east-kazakhstan"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return kazSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return kazSvgToSlugMapping[regionId];
}
