// SVG region mapping for Kenya
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const kenSvgToSlugMapping: RegionMapping = {
  "KE30": {
    "name": "Baringo",
    "slug": "baringo"
  },
  "KE36": {
    "name": "Bomet",
    "slug": "bomet"
  },
  "KE39": {
    "name": "Bungoma",
    "slug": "bungoma"
  },
  "KE40": {
    "name": "Busia",
    "slug": "busia"
  },
  "KE28": {
    "name": "Elgeyo-Marakwet",
    "slug": "elgeyo-marakwet"
  },
  "KE14": {
    "name": "Embu",
    "slug": "embu"
  },
  "KE07": {
    "name": "Garissa",
    "slug": "garissa"
  },
  "KE43": {
    "name": "Homa Bay",
    "slug": "homa-bay"
  },
  "KE11": {
    "name": "Isiolo",
    "slug": "isiolo"
  },
  "KE34": {
    "name": "Kajiado",
    "slug": "kajiado"
  },
  "KE37": {
    "name": "Kakamega",
    "slug": "kakamega"
  },
  "KE35": {
    "name": "Kericho",
    "slug": "kericho"
  },
  "KE22": {
    "name": "Kiambu",
    "slug": "kiambu"
  },
  "KE03": {
    "name": "Kilifi",
    "slug": "kilifi"
  },
  "KE20": {
    "name": "Kirinyaga",
    "slug": "kirinyaga"
  },
  "KE45": {
    "name": "Kisii",
    "slug": "kisii"
  },
  "KE42": {
    "name": "Kisumu",
    "slug": "kisumu"
  },
  "KE15": {
    "name": "Kitui",
    "slug": "kitui"
  },
  "KE02": {
    "name": "Kwale",
    "slug": "kwale"
  },
  "KE31": {
    "name": "Laikipia",
    "slug": "laikipia"
  },
  "KE05": {
    "name": "Lamu",
    "slug": "lamu"
  },
  "KE16": {
    "name": "Machakos",
    "slug": "machakos"
  },
  "KE17": {
    "name": "Makueni",
    "slug": "makueni"
  },
  "KE09": {
    "name": "Mandera",
    "slug": "mandera"
  },
  "KE10": {
    "name": "Marsabit",
    "slug": "marsabit"
  },
  "KE12": {
    "name": "Meru",
    "slug": "meru"
  },
  "KE44": {
    "name": "Migori",
    "slug": "migori"
  },
  "KE01": {
    "name": "Mombasa",
    "slug": "mombasa"
  },
  "KE21": {
    "name": "Murang'a",
    "slug": "muranga"
  },
  "KE47": {
    "name": "Nairobi",
    "slug": "nairobi"
  },
  "KE29": {
    "name": "Nandi",
    "slug": "nandi"
  },
  "KE33": {
    "name": "Narok",
    "slug": "narok"
  },
  "KE46": {
    "name": "Nyamira",
    "slug": "nyamira"
  },
  "KE18": {
    "name": "Nyandarua",
    "slug": "nyandarua"
  },
  "KE19": {
    "name": "Nyeri",
    "slug": "nyeri"
  },
  "KE25": {
    "name": "Samburu",
    "slug": "samburu"
  },
  "KE41": {
    "name": "Siaya",
    "slug": "siaya"
  },
  "KE06": {
    "name": "Taita Taveta",
    "slug": "taita-taveta"
  },
  "KE04": {
    "name": "Tana River",
    "slug": "tana-river"
  },
  "KE13": {
    "name": "Tharaka-Nithi",
    "slug": "tharaka-nithi"
  },
  "KE26": {
    "name": "Trans Nzoia",
    "slug": "trans-nzoia"
  },
  "KE23": {
    "name": "Turkana",
    "slug": "turkana"
  },
  "KE27": {
    "name": "Uasin Gishu",
    "slug": "uasin-gishu"
  },
  "KE38": {
    "name": "Vihiga",
    "slug": "vihiga"
  },
  "KE08": {
    "name": "Wajir",
    "slug": "wajir"
  },
  "KE24": {
    "name": "West Pokot",
    "slug": "west-pokot"
  },
  "KE32": {
    "name": "Nakuru",
    "slug": "nakuru"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return kenSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return kenSvgToSlugMapping[regionId];
}
