// SVG region mapping for Kyrgyzstan
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const kgzSvgToSlugMapping: RegionMapping = {
  "KGB": {
    "name": "Batken",
    "slug": "batken"
  },
  "KGGB": {
    "name": "Bishkek (city)",
    "slug": "bishkek-city"
  },
  "KGC": {
    "name": "Chui",
    "slug": "chui"
  },
  "KGY": {
    "name": "Issyk-Kul",
    "slug": "issyk-kul"
  },
  "KGJ": {
    "name": "Jalal-Abad",
    "slug": "jalal-abad"
  },
  "KGN": {
    "name": "Batken",
    "slug": "batken"
  },
  "KGO": {
    "name": "Osh",
    "slug": "osh"
  },
  "KGGO": {
    "name": "Osh (city)",
    "slug": "osh-city"
  },
  "KGT": {
    "name": "Batken",
    "slug": "batken"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return kgzSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return kgzSvgToSlugMapping[regionId];
}
