// SVG region mapping for Cambodia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const khmSvgToSlugMapping: RegionMapping = {
  "KH1": {
    "name": "1",
    "slug": "1"
  },
  "KH2": {
    "name": "2",
    "slug": "2"
  },
  "KH3": {
    "name": "3",
    "slug": "3"
  },
  "KH4": {
    "name": "4",
    "slug": "4"
  },
  "KH5": {
    "name": "5",
    "slug": "5"
  },
  "KH6": {
    "name": "6",
    "slug": "6"
  },
  "KH7": {
    "name": "7",
    "slug": "7"
  },
  "KH8": {
    "name": "8",
    "slug": "8"
  },
  "KH23": {
    "name": "23",
    "slug": "23"
  },
  "KH9": {
    "name": "9",
    "slug": "9"
  },
  "KH10": {
    "name": "Kratie",
    "slug": "kratie"
  },
  "KH11": {
    "name": "Mondul Kiri",
    "slug": "mondul-kiri"
  },
  "KH22": {
    "name": "Oddar Meanchey",
    "slug": "oddar-meanchey"
  },
  "KH24": {
    "name": "Pailin",
    "slug": "pailin"
  },
  "KH12": {
    "name": "Phnom Penh",
    "slug": "phnom-penh"
  },
  "KH18": {
    "name": "Preah Sihanouk",
    "slug": "preah-sihanouk"
  },
  "KH13": {
    "name": "Preah Vihear",
    "slug": "preah-vihear"
  },
  "KH14": {
    "name": "Prey Veng",
    "slug": "prey-veng"
  },
  "KH15": {
    "name": "Pursat",
    "slug": "pursat"
  },
  "KH16": {
    "name": "Ratanak Kiri",
    "slug": "ratanak-kiri"
  },
  "KH17": {
    "name": "Siemreap",
    "slug": "siemreap"
  },
  "KH19": {
    "name": "Stung Treng",
    "slug": "stung-treng"
  },
  "KH20": {
    "name": "Svay Rieng",
    "slug": "svay-rieng"
  },
  "KH21": {
    "name": "Takeo",
    "slug": "takeo"
  },
  "KH25": {
    "name": "Tboung Khmum",
    "slug": "tboung-khmum"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return khmSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return khmSvgToSlugMapping[regionId];
}
