// SVG region mapping for Cambodia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const khmSvgToSlugMapping: RegionMapping = {
  "KH1": {
    "name": "Banteay Meanchey",
    "slug": "banteay-meanchey"
  },
  "KH2": {
    "name": "Battambang",
    "slug": "battambang"
  },
  "KH3": {
    "name": "Kampong Cham",
    "slug": "kampong-cham"
  },
  "KH4": {
    "name": "Kampong Chhnang",
    "slug": "kampong-chhnang"
  },
  "KH5": {
    "name": "Kampong Speu",
    "slug": "kampong-speu"
  },
  "KH6": {
    "name": "Kampong Thom",
    "slug": "kampong-thom"
  },
  "KH7": {
    "name": "Kampot",
    "slug": "kampot"
  },
  "KH8": {
    "name": "Kandal",
    "slug": "kandal"
  },
  "KH23": {
    "name": "Kep",
    "slug": "kep"
  },
  "KH9": {
    "name": "Koh Kong",
    "slug": "koh-kong"
  },
  "KH10": {
    "name": "Kratie",
    "slug": "kratie"
  },
  "KH11": {
    "name": "Mondul Kiri",
    "slug": "mondul-kiri"
  },
  "KH22": {
    "name": "Oddar Meanchey",
    "slug": "oddar-meanchey"
  },
  "KH24": {
    "name": "Pailin",
    "slug": "pailin"
  },
  "KH12": {
    "name": "Phnom Penh",
    "slug": "phnom-penh"
  },
  "KH18": {
    "name": "Preah Sihanouk",
    "slug": "preah-sihanouk"
  },
  "KH13": {
    "name": "Preah Vihear",
    "slug": "preah-vihear"
  },
  "KH14": {
    "name": "Prey Veng",
    "slug": "prey-veng"
  },
  "KH15": {
    "name": "Pursat",
    "slug": "pursat"
  },
  "KH16": {
    "name": "Ratanak Kiri",
    "slug": "ratanak-kiri"
  },
  "KH17": {
    "name": "Siemreap",
    "slug": "siemreap"
  },
  "KH19": {
    "name": "Stung Treng",
    "slug": "stung-treng"
  },
  "KH20": {
    "name": "Svay Rieng",
    "slug": "svay-rieng"
  },
  "KH21": {
    "name": "Takeo",
    "slug": "takeo"
  },
  "KH25": {
    "name": "Tboung Khmum",
    "slug": "tboung-khmum"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return khmSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return khmSvgToSlugMapping[regionId];
}
