// SVG region mapping for Saint Kitts and Nevis
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const knaSvgToSlugMapping: RegionMapping = {
  "KN10": {
    "name": "Saint Paul Charlestown",
    "slug": "saint-paul-charlestown"
  },
  "KN07": {
    "name": "Saint John Figtree",
    "slug": "saint-john-figtree"
  },
  "KN04": {
    "name": "Saint George Gingerland",
    "slug": "saint-george-gingerland"
  },
  "KN05": {
    "name": "Saint James Windward",
    "slug": "saint-james-windward"
  },
  "KN12": {
    "name": "Saint Thomas Lowland",
    "slug": "saint-thomas-lowland"
  },
  "KN09": {
    "name": "Saint Paul Capesterre",
    "slug": "saint-paul-capesterre"
  },
  "KN02": {
    "name": "Saint Anne Sandy Point",
    "slug": "saint-anne-sandy-point"
  },
  "KN13": {
    "name": "Saint Thomas Middle Island",
    "slug": "saint-thomas-middle-island"
  },
  "KN14": {
    "name": "Trinity Palmetto Point",
    "slug": "trinity-palmetto-point"
  },
  "KN03": {
    "name": "Saint George Basseterre",
    "slug": "saint-george-basseterre"
  },
  "KN11": {
    "name": "Saint Peter Basseterre",
    "slug": "saint-peter-basseterre"
  },
  "KN08": {
    "name": "Saint Mary Cayon",
    "slug": "saint-mary-cayon"
  },
  "KN01": {
    "name": "Christ Church Nichola Town",
    "slug": "christ-church-nichola-town"
  },
  "KN06": {
    "name": "Saint John Capesterre",
    "slug": "saint-john-capesterre"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return knaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return knaSvgToSlugMapping[regionId];
}
