// SVG region mapping for South Korea
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const korSvgToSlugMapping: RegionMapping = {
  "KR42": {
    "name": "Gangwon",
    "slug": "gangwon"
  },
  "KR41": {
    "name": "Gyeonggi",
    "slug": "gyeonggi"
  },
  "KR44": {
    "name": "South Chungcheong",
    "slug": "south-chungcheong"
  },
  "KR28": {
    "name": "Incheon",
    "slug": "incheon"
  },
  "KR45": {
    "name": "North Jeolla",
    "slug": "north-jeolla"
  },
  "KR46": {
    "name": "South Jeolla",
    "slug": "south-jeolla"
  },
  "KR48": {
    "name": "South Gyeongsang",
    "slug": "south-gyeongsang"
  },
  "KR26": {
    "name": "Busan",
    "slug": "busan"
  },
  "KR31": {
    "name": "Ulsan",
    "slug": "ulsan"
  },
  "KR47": {
    "name": "North Gyeongsang",
    "slug": "north-gyeongsang"
  },
  "KR49": {
    "name": "Jeju",
    "slug": "jeju"
  },
  "KR11": {
    "name": "Seoul",
    "slug": "seoul"
  },
  "KR30": {
    "name": "Daejeon",
    "slug": "daejeon"
  },
  "KR50": {
    "name": "Sejong",
    "slug": "sejong"
  },
  "KR43": {
    "name": "North Chungcheong",
    "slug": "north-chungcheong"
  },
  "KR29": {
    "name": "Gwangju",
    "slug": "gwangju"
  },
  "KR27": {
    "name": "Daegu",
    "slug": "daegu"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return korSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return korSvgToSlugMapping[regionId];
}
