// SVG region mapping for Kuwait
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const kwtSvgToSlugMapping: RegionMapping = {
  "KWJA": {
    "name": "Al Jahrah",
    "slug": "al-jahrah"
  },
  "KWAH": {
    "name": "Al Ahmadi",
    "slug": "al-ahmadi"
  },
  "KWMU": {
    "name": "Mubarak Al-Kabeer",
    "slug": "mubarak-al-kabeer"
  },
  "KWHA": {
    "name": "Hawalli",
    "slug": "hawalli"
  },
  "KWKU": {
    "name": "Al Asimah",
    "slug": "al-asimah"
  },
  "KWFA": {
    "name": "Al Farwaniyah",
    "slug": "al-farwaniyah"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return kwtSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return kwtSvgToSlugMapping[regionId];
}
