// SVG region mapping for Laos
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const laoSvgToSlugMapping: RegionMapping = {
  "LAAT": {
    "name": "Attapeu",
    "slug": "attapeu"
  },
  "LABK": {
    "name": "Bokeo",
    "slug": "bokeo"
  },
  "LABL": {
    "name": "Bolikhamxai",
    "slug": "bolikhamxai"
  },
  "LACH": {
    "name": "Champasack",
    "slug": "champasack"
  },
  "LAHO": {
    "name": "Houaphan",
    "slug": "houaphan"
  },
  "LAKH": {
    "name": "Khammouan",
    "slug": "khammouan"
  },
  "LALM": {
    "name": "Louangnamtha",
    "slug": "louangnamtha"
  },
  "LALP": {
    "name": "Louangphabang",
    "slug": "louangphabang"
  },
  "LAOU": {
    "name": "Oudomxai",
    "slug": "oudomxai"
  },
  "LAPH": {
    "name": "Phongsaly",
    "slug": "phongsaly"
  },
  "LASL": {
    "name": "Salavan",
    "slug": "salavan"
  },
  "LASV": {
    "name": "Savannakhet",
    "slug": "savannakhet"
  },
  "LAXE": {
    "name": "Sekong",
    "slug": "sekong"
  },
  "LAVI": {
    "name": "Vientiane",
    "slug": "vientiane"
  },
  "LAVT": {
    "name": "Vientiane Capital",
    "slug": "vientiane-capital"
  },
  "LAXA": {
    "name": "Xaignabouly",
    "slug": "xaignabouly"
  },
  "LAXS": {
    "name": "Xaisomboon",
    "slug": "xaisomboon"
  },
  "LAXI": {
    "name": "Xiengkhouang",
    "slug": "xiengkhouang"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return laoSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return laoSvgToSlugMapping[regionId];
}
