// SVG region mapping for Lebanon
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const lbnSvgToSlugMapping: RegionMapping = {
  "LBAS": {
    "name": "North",
    "slug": "north"
  },
  "LBBH": {
    "name": "Baalbek-El Hermel",
    "slug": "baalbek-el-hermel"
  },
  "LBJL": {
    "name": "Mount Lebanon",
    "slug": "mount-lebanon"
  },
  "LBJA": {
    "name": "South",
    "slug": "south"
  },
  "LBNA": {
    "name": "El Nabatieh",
    "slug": "el-nabatieh"
  },
  "LBAK": {
    "name": "Akkar",
    "slug": "akkar"
  },
  "LBBI": {
    "name": "Bekaa",
    "slug": "bekaa"
  },
  "LBBA": {
    "name": "Beirut",
    "slug": "beirut"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return lbnSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return lbnSvgToSlugMapping[regionId];
}
