// SVG region mapping for Liberia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const lbrSvgToSlugMapping: RegionMapping = {
  "LRCM": {
    "name": "Grand Cape Mount",
    "slug": "grand-cape-mount"
  },
  "LRGP": {
    "name": "Gbarpolu",
    "slug": "gbarpolu"
  },
  "LRLO": {
    "name": "Lofa",
    "slug": "lofa"
  },
  "LRNI": {
    "name": "Nimba",
    "slug": "nimba"
  },
  "LRGG": {
    "name": "Grand Gedeh",
    "slug": "grand-gedeh"
  },
  "LRRG": {
    "name": "River Gee",
    "slug": "river-gee"
  },
  "LRMY": {
    "name": "Maryland",
    "slug": "maryland"
  },
  "LRBG": {
    "name": "Bong",
    "slug": "bong"
  },
  "LRBM": {
    "name": "Bomi",
    "slug": "bomi"
  },
  "LRMO": {
    "name": "Montserrado",
    "slug": "montserrado"
  },
  "LRMG": {
    "name": "Margibi",
    "slug": "margibi"
  },
  "LRGB": {
    "name": "Grand Bassa",
    "slug": "grand-bassa"
  },
  "LRRI": {
    "name": "River Cess",
    "slug": "river-cess"
  },
  "LRSI": {
    "name": "Sinoe",
    "slug": "sinoe"
  },
  "LRGK": {
    "name": "Grand Kru",
    "slug": "grand-kru"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return lbrSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return lbrSvgToSlugMapping[regionId];
}
