// SVG region mapping for Libya
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const lbySvgToSlugMapping: RegionMapping = {
  "LYNL": {
    "name": "Nalut",
    "slug": "nalut"
  },
  "LYNQ": {
    "name": "An Nuqat al Khams",
    "slug": "an-nuqat-al-khams"
  },
  "LYKF": {
    "name": "Al Kufrah",
    "slug": "al-kufrah"
  },
  "LYMQ": {
    "name": "Murzuq",
    "slug": "murzuq"
  },
  "LYBU": {
    "name": "Al Butnan",
    "slug": "al-butnan"
  },
  "LYWA": {
    "name": "Oases",
    "slug": "oases"
  },
  "LYWS": {
    "name": "Ash Shati'",
    "slug": "ash-shati"
  },
  "LYGT": {
    "name": "Ghat",
    "slug": "ghat"
  },
  "LYSR": {
    "name": "Surt",
    "slug": "surt"
  },
  "LYMI": {
    "name": "Misratah",
    "slug": "misratah"
  },
  "LYMB": {
    "name": "Al Marqab",
    "slug": "al-marqab"
  },
  "LYTB": {
    "name": "Trípoli",
    "slug": "trpoli"
  },
  "LYZA": {
    "name": "Az Zawiyah",
    "slug": "az-zawiyah"
  },
  "LYDR": {
    "name": "Derna",
    "slug": "derna"
  },
  "LYJA": {
    "name": "Al Jabal al Akhdar",
    "slug": "al-jabal-al-akhdar"
  },
  "LYMJ": {
    "name": "Al Marj",
    "slug": "al-marj"
  },
  "LYBA": {
    "name": "Benghazi",
    "slug": "benghazi"
  },
  "LYJI": {
    "name": "Al Jifarah",
    "slug": "al-jifarah"
  },
  "LYJG": {
    "name": "Al Jabal al Gharbi",
    "slug": "al-jabal-al-gharbi"
  },
  "LYJU": {
    "name": "Al Jufrah",
    "slug": "al-jufrah"
  },
  "LYSB": {
    "name": "Sabha",
    "slug": "sabha"
  },
  "LYWD": {
    "name": "Wadi al Hayaa",
    "slug": "wadi-al-hayaa"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return lbySvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return lbySvgToSlugMapping[regionId];
}
