// SVG region mapping for Saint Lucia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const lcaSvgToSlugMapping: RegionMapping = {
  "LC06": {
    "name": "Gros Islet",
    "slug": "gros-islet"
  },
  "LC02": {
    "name": "Castries",
    "slug": "castries"
  },
  "LC01": {
    "name": "Anse-la-Raye",
    "slug": "anse-la-raye"
  },
  "LC10": {
    "name": "Soufrière",
    "slug": "soufrire"
  },
  "LC03": {
    "name": "Choiseul",
    "slug": "choiseul"
  },
  "LC07": {
    "name": "Laborie",
    "slug": "laborie"
  },
  "LC11": {
    "name": "Vieux Fort",
    "slug": "vieux-fort"
  },
  "LC08": {
    "name": "Micoud",
    "slug": "micoud"
  },
  "LC09": {
    "name": "Praslin",
    "slug": "praslin"
  },
  "LC05": {
    "name": "Dennery",
    "slug": "dennery"
  },
  "LC04": {
    "name": "Dauphin",
    "slug": "dauphin"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return lcaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return lcaSvgToSlugMapping[regionId];
}
