// SVG region mapping for Liechtenstein
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const lieSvgToSlugMapping: RegionMapping = {
  "LI09": {
    "name": "Triesen",
    "slug": "triesen"
  },
  "LI07": {
    "name": "Schaan",
    "slug": "schaan"
  },
  "LI10": {
    "name": "Triesenberg",
    "slug": "triesenberg"
  },
  "LI01": {
    "name": "Balzers",
    "slug": "balzers"
  },
  "LI05": {
    "name": "Planken",
    "slug": "planken"
  },
  "LI02": {
    "name": "Eschen",
    "slug": "eschen"
  },
  "LI04": {
    "name": "Mauren",
    "slug": "mauren"
  },
  "LI08": {
    "name": "Schellenberg",
    "slug": "schellenberg"
  },
  "LI06": {
    "name": "Ruggell",
    "slug": "ruggell"
  },
  "LI11": {
    "name": "Vaduz",
    "slug": "vaduz"
  },
  "LI03": {
    "name": "Gamprin",
    "slug": "gamprin"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return lieSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return lieSvgToSlugMapping[regionId];
}
