// SVG region mapping for Sri Lanka
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const lkaSvgToSlugMapping: RegionMapping = {
  "LK53": {
    "name": "Trikuṇāmalaya",
    "slug": "trikumalaya"
  },
  "LK45": {
    "name": "Mulativ",
    "slug": "mulativ"
  },
  "LK41": {
    "name": "Yāpanaya",
    "slug": "ypanaya"
  },
  "LK42": {
    "name": "Kilinŏchchi",
    "slug": "kilinchchi"
  },
  "LK43": {
    "name": "Mannārama",
    "slug": "mannrama"
  },
  "LK62": {
    "name": "Puttalama",
    "slug": "puttalama"
  },
  "LK12": {
    "name": "Gampaha",
    "slug": "gampaha"
  },
  "LK11": {
    "name": "Kŏḷamba",
    "slug": "kamba"
  },
  "LK13": {
    "name": "Kaḷutara",
    "slug": "kautara"
  },
  "LK31": {
    "name": "Gālla",
    "slug": "glla"
  },
  "LK32": {
    "name": "Mātara",
    "slug": "mtara"
  },
  "LK33": {
    "name": "Hambantŏṭa",
    "slug": "hambanta"
  },
  "LK52": {
    "name": "Ampāra",
    "slug": "ampra"
  },
  "LK51": {
    "name": "Maḍakalapuva",
    "slug": "maakalapuva"
  },
  "LK91": {
    "name": "Ratnapura",
    "slug": "ratnapura"
  },
  "LK82": {
    "name": "Mŏṇarāgala",
    "slug": "margala"
  },
  "LK92": {
    "name": "Kægalla",
    "slug": "kgalla"
  },
  "LK81": {
    "name": "Badulla",
    "slug": "badulla"
  },
  "LK22": {
    "name": "Mātale",
    "slug": "mtale"
  },
  "LK72": {
    "name": "Pŏḷŏnnaruva",
    "slug": "pnnaruva"
  },
  "LK61": {
    "name": "Kuruṇægala",
    "slug": "kurugala"
  },
  "LK71": {
    "name": "Anurādhapura",
    "slug": "anurdhapura"
  },
  "LK23": {
    "name": "Nuvara Ĕliya",
    "slug": "nuvara-liya"
  },
  "LK44": {
    "name": "Vavuniyāva",
    "slug": "vavuniyva"
  },
  "LK21": {
    "name": "Mahanuvara",
    "slug": "mahanuvara"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return lkaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return lkaSvgToSlugMapping[regionId];
}
