// SVG region mapping for Lesotho
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const lsoSvgToSlugMapping: RegionMapping = {
  "LSJ": {
    "name": "J",
    "slug": "j"
  },
  "LSB": {
    "name": "Berea",
    "slug": "berea"
  },
  "LSC": {
    "name": "Qacha''s Nek",
    "slug": "qachas-nek"
  },
  "LSH": {
    "name": "Butha-Buthe",
    "slug": "butha-buthe"
  },
  "LSK": {
    "name": "Mohale''s Hoek",
    "slug": "mohales-hoek"
  },
  "LSD": {
    "name": "D",
    "slug": "d"
  },
  "LSA": {
    "name": "Berea",
    "slug": "berea"
  },
  "LSE": {
    "name": "Berea",
    "slug": "berea"
  },
  "LSF": {
    "name": "Mafeteng",
    "slug": "mafeteng"
  },
  "LSG": {
    "name": "Mafeteng",
    "slug": "mafeteng"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return lsoSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return lsoSvgToSlugMapping[regionId];
}
