// SVG region mapping for Lesotho
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const lsoSvgToSlugMapping: RegionMapping = {
  "LSJ": {
    "name": "Mokhotlong",
    "slug": "mokhotlong"
  },
  "LSB": {
    "name": "Butha-Buthe",
    "slug": "butha-buthe"
  },
  "LSC": {
    "name": "Leribe",
    "slug": "leribe"
  },
  "LSH": {
    "name": "Qacha's Nek",
    "slug": "qacha-s-nek"
  },
  "LSK": {
    "name": "Thaba-Tseka",
    "slug": "thaba-tseka"
  },
  "LSD": {
    "name": "Berea",
    "slug": "berea"
  },
  "LSA": {
    "name": "Maseru",
    "slug": "maseru"
  },
  "LSE": {
    "name": "Mafeteng",
    "slug": "mafeteng"
  },
  "LSF": {
    "name": "Mohale's Hoek",
    "slug": "mohale-s-hoek"
  },
  "LSG": {
    "name": "Quthing",
    "slug": "quthing"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return lsoSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return lsoSvgToSlugMapping[regionId];
}
