// SVG region mapping for Lithuania
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const ltuSvgToSlugMapping: RegionMapping = {
  "LT43": {
    "name": "Siauliu Miestas",
    "slug": "siauliu-miestas"
  },
  "LT44": {
    "name": "Šiauliai",
    "slug": "iauliai"
  },
  "LT34": {
    "name": "Pasvalys",
    "slug": "pasvalys"
  },
  "LT35": {
    "name": "Plunge",
    "slug": "plunge"
  },
  "LT32": {
    "name": "Panevezio Miestas",
    "slug": "panevezio-miestas"
  },
  "LT33": {
    "name": "Panevezys",
    "slug": "panevezys"
  },
  "LT38": {
    "name": "Raseiniai",
    "slug": "raseiniai"
  },
  "LT39": {
    "name": "Rietavas",
    "slug": "rietavas"
  },
  "LT36": {
    "name": "Prienai",
    "slug": "prienai"
  },
  "LT37": {
    "name": "Radviliskis",
    "slug": "radviliskis"
  },
  "LT26": {
    "name": "Mazeikiai",
    "slug": "mazeikiai"
  },
  "LT27": {
    "name": "Moletai",
    "slug": "moletai"
  },
  "LT24": {
    "name": "Lazdijai",
    "slug": "lazdijai"
  },
  "LT25": {
    "name": "Marijampole",
    "slug": "marijampole"
  },
  "LT30": {
    "name": "Pakruojis",
    "slug": "pakruojis"
  },
  "LT31": {
    "name": "Palangos Miestas",
    "slug": "palangos-miestas"
  },
  "LT28": {
    "name": "Neringa",
    "slug": "neringa"
  },
  "LT29": {
    "name": "Pagegiai",
    "slug": "pagegiai"
  },
  "LT18": {
    "name": "Kedainiai",
    "slug": "kedainiai"
  },
  "LT19": {
    "name": "Kelme",
    "slug": "kelme"
  },
  "LT16": {
    "name": "Kaunas",
    "slug": "kaunas"
  },
  "LT17": {
    "name": "Kazlu Rudos",
    "slug": "kazlu-rudos"
  },
  "LT22": {
    "name": "Kretinga",
    "slug": "kretinga"
  },
  "LT23": {
    "name": "Kupiskis",
    "slug": "kupiskis"
  },
  "LT20": {
    "name": "Klaipedos Miestas",
    "slug": "klaipedos-miestas"
  },
  "LT21": {
    "name": "Klaipeda",
    "slug": "klaipeda"
  },
  "LT10": {
    "name": "Jonava",
    "slug": "jonava"
  },
  "LT11": {
    "name": "Joniskis",
    "slug": "joniskis"
  },
  "LT08": {
    "name": "Elektrenai",
    "slug": "elektrenai"
  },
  "LT09": {
    "name": "Ignalina",
    "slug": "ignalina"
  },
  "LT14": {
    "name": "Kalvarija",
    "slug": "kalvarija"
  },
  "LT15": {
    "name": "Kauno Miestas",
    "slug": "kauno-miestas"
  },
  "LT12": {
    "name": "Jurbarkas",
    "slug": "jurbarkas"
  },
  "LT13": {
    "name": "Kaisiadorys",
    "slug": "kaisiadorys"
  },
  "LT02": {
    "name": "Alytaus Miestas",
    "slug": "alytaus-miestas"
  },
  "LT03": {
    "name": "Alytus",
    "slug": "alytus"
  },
  "LT01": {
    "name": "Akmene",
    "slug": "akmene"
  },
  "LT06": {
    "name": "Birzai",
    "slug": "birzai"
  },
  "LT07": {
    "name": "Druskininkai",
    "slug": "druskininkai"
  },
  "LT04": {
    "name": "Anyksciai",
    "slug": "anyksciai"
  },
  "LT05": {
    "name": "Birstonas",
    "slug": "birstonas"
  },
  "LT58": {
    "name": "Vilnius",
    "slug": "vilnius"
  },
  "LT59": {
    "name": "Visaginas",
    "slug": "visaginas"
  },
  "LT56": {
    "name": "Vilkaviskis",
    "slug": "vilkaviskis"
  },
  "LT57": {
    "name": "Vilniaus Miestas",
    "slug": "vilniaus-miestas"
  },
  "LT60": {
    "name": "Zarasai",
    "slug": "zarasai"
  },
  "LT50": {
    "name": "Taurage",
    "slug": "taurage"
  },
  "LT51": {
    "name": "Telsiai",
    "slug": "telsiai"
  },
  "LT47": {
    "name": "Sirvintos",
    "slug": "sirvintos"
  },
  "LT49": {
    "name": "Svencionys",
    "slug": "svencionys"
  },
  "LT54": {
    "name": "Utena",
    "slug": "utena"
  },
  "LT55": {
    "name": "Varena",
    "slug": "varena"
  },
  "LT52": {
    "name": "Trakai",
    "slug": "trakai"
  },
  "LT53": {
    "name": "Ukmerge",
    "slug": "ukmerge"
  },
  "LT41": {
    "name": "Sakiai",
    "slug": "sakiai"
  },
  "LT42": {
    "name": "Salcininkai",
    "slug": "salcininkai"
  },
  "LT40": {
    "name": "Rokiskis",
    "slug": "rokiskis"
  },
  "LT48": {
    "name": "Skuodas",
    "slug": "skuodas"
  },
  "LT45": {
    "name": "Silale",
    "slug": "silale"
  },
  "LT46": {
    "name": "Silute",
    "slug": "silute"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return ltuSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return ltuSvgToSlugMapping[regionId];
}
