// SVG region mapping for Luxembourg
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const luxSvgToSlugMapping: RegionMapping = {
  "LUWI": {
    "name": "Wiltz",
    "slug": "wiltz"
  },
  "LUCL": {
    "name": "Clervaux",
    "slug": "clervaux"
  },
  "LURD": {
    "name": "Redange",
    "slug": "redange"
  },
  "LUDI": {
    "name": "Diekirch",
    "slug": "diekirch"
  },
  "LUES": {
    "name": "Esch-sur-Alzette",
    "slug": "esch-sur-alzette"
  },
  "LUEC": {
    "name": "Echternach",
    "slug": "echternach"
  },
  "LUGR": {
    "name": "Grevenmacher",
    "slug": "grevenmacher"
  },
  "LUCA": {
    "name": "Capellen",
    "slug": "capellen"
  },
  "LUME": {
    "name": "Mersch",
    "slug": "mersch"
  },
  "LURM": {
    "name": "Remich",
    "slug": "remich"
  },
  "LUVD": {
    "name": "Vianden",
    "slug": "vianden"
  },
  "LULU": {
    "name": "Luxembourg",
    "slug": "luxembourg"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return luxSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return luxSvgToSlugMapping[regionId];
}
