// SVG region mapping for Latvia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const lvaSvgToSlugMapping: RegionMapping = {
  "LV007": {
    "name": "Alūksnes novads",
    "slug": "alksnes-novads"
  },
  "LV056": {
    "name": "Līvānu novads",
    "slug": "lvnu-novads"
  },
  "LV033": {
    "name": "Gulbenes novads",
    "slug": "gulbenes-novads"
  },
  "LV106": {
    "name": "Ventspils novads",
    "slug": "ventspils-novads"
  },
  "LV101": {
    "name": "Valkas novads",
    "slug": "valkas-novads"
  },
  "LV087": {
    "name": "Salaspils novads",
    "slug": "salaspils-novads"
  },
  "LVJEL": {
    "name": "Jelgavas pilsēta",
    "slug": "jelgavas-pilsta"
  },
  "LVREZ": {
    "name": "Rēzeknes pilsēta",
    "slug": "rzeknes-pilsta"
  },
  "LVJUR": {
    "name": "Jūrmalas pilsēta",
    "slug": "jrmalas-pilsta"
  },
  "LVVEN": {
    "name": "Ventspils pilsēta",
    "slug": "ventspils-pilsta"
  },
  "LVRIX": {
    "name": "Rīgas pilsēta",
    "slug": "rgas-pilsta"
  },
  "LVLPX": {
    "name": "Liepājas pilsēta",
    "slug": "liepjas-pilsta"
  },
  "LV112": {
    "name": "Dienvidkurzemes novads",
    "slug": "dienvidkurzemes-novads"
  },
  "LV050": {
    "name": "Kuldīgas novads",
    "slug": "kuldgas-novads"
  },
  "LV088": {
    "name": "Saldus novads",
    "slug": "saldus-novads"
  },
  "LV097": {
    "name": "Talsu novads",
    "slug": "talsu-novads"
  },
  "LV099": {
    "name": "Tukuma novads",
    "slug": "tukuma-novads"
  },
  "LV026": {
    "name": "Dobeles novads",
    "slug": "dobeles-novads"
  },
  "LV041": {
    "name": "Jelgavas novads",
    "slug": "jelgavas-novads"
  },
  "LV062": {
    "name": "Mārupes novads",
    "slug": "mrupes-novads"
  },
  "LV016": {
    "name": "Bauskas novads",
    "slug": "bauskas-novads"
  },
  "LV067": {
    "name": "Ogres novads",
    "slug": "ogres-novads"
  },
  "LV002": {
    "name": "Aizkraukles novads",
    "slug": "aizkraukles-novads"
  },
  "LV042": {
    "name": "Jēkabpils novads",
    "slug": "jkabpils-novads"
  },
  "LV058": {
    "name": "Ludzas novads",
    "slug": "ludzas-novads"
  },
  "LV077": {
    "name": "Rēzeknes novads",
    "slug": "rzeknes-novads"
  },
  "LV015": {
    "name": "Balvu novads",
    "slug": "balvu-novads"
  },
  "LV059": {
    "name": "Madonas novads",
    "slug": "madonas-novads"
  },
  "LV094": {
    "name": "Smiltenes novads",
    "slug": "smiltenes-novads"
  },
  "LV022": {
    "name": "Cēsu novads",
    "slug": "csu-novads"
  },
  "LV113": {
    "name": "Valmieras novads",
    "slug": "valmieras-novads"
  },
  "LV011": {
    "name": "Ādažu novads",
    "slug": "dau-novads"
  },
  "LV080": {
    "name": "Ropažu novads",
    "slug": "ropau-novads"
  },
  "LV091": {
    "name": "Siguldas novads",
    "slug": "siguldas-novads"
  },
  "LV073": {
    "name": "Preiļu novads",
    "slug": "preiu-novads"
  },
  "LV047": {
    "name": "Krāslavas novads",
    "slug": "krslavas-novads"
  },
  "LV052": {
    "name": "Ķekavas novads",
    "slug": "ekavas-novads"
  },
  "LV068": {
    "name": "Olaines novads",
    "slug": "olaines-novads"
  },
  "LV089": {
    "name": "Saulkrastu novads",
    "slug": "saulkrastu-novads"
  },
  "LV054": {
    "name": "Limbažu novads",
    "slug": "limbau-novads"
  },
  "LV111": {
    "name": "Augšdaugavas novads",
    "slug": "augdaugavas-novads"
  },
  "LV102": {
    "name": "Varakļānu novads",
    "slug": "varaknu-novads"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return lvaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return lvaSvgToSlugMapping[regionId];
}
