// SVG region mapping for Morocco
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const marSvgToSlugMapping: RegionMapping = {
  "MA11": {
    "name": "Laâyoune-Sakia El Hamra",
    "slug": "layoune-sakia-el-hamra"
  },
  "MA01": {
    "name": "Tangier-Tetouan-Al Hoceima",
    "slug": "tangier-tetouan-al-hoceima"
  },
  "MA02": {
    "name": "Oriental",
    "slug": "oriental"
  },
  "MA08": {
    "name": "Drâa-Tafilalet",
    "slug": "dra-tafilalet"
  },
  "MA09": {
    "name": "Souss-Massa",
    "slug": "souss-massa"
  },
  "MA10": {
    "name": "Guelmim-Oued Noun",
    "slug": "guelmim-oued-noun"
  },
  "MA06": {
    "name": "Casablanca-Settat",
    "slug": "casablanca-settat"
  },
  "MA07": {
    "name": "Marrakech-Safi",
    "slug": "marrakech-safi"
  },
  "MA12": {
    "name": "Dakhla-Oued Ed-Dahab",
    "slug": "dakhla-oued-ed-dahab"
  },
  "MA04": {
    "name": "Rabat-Salé-Kenitra",
    "slug": "rabat-sal-kenitra"
  },
  "MA03": {
    "name": "Fez-Meknes",
    "slug": "fez-meknes"
  },
  "MA05": {
    "name": "Béni Mellal-Khénifra",
    "slug": "bni-mellal-khnifra"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return marSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return marSvgToSlugMapping[regionId];
}
