// SVG region mapping for Moldova
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mdaSvgToSlugMapping: RegionMapping = {
  "MDAN": {
    "name": "Anenii Noi",
    "slug": "anenii-noi"
  },
  "MDBA": {
    "name": "Balti",
    "slug": "balti"
  },
  "MDBS": {
    "name": "Basarabeasca",
    "slug": "basarabeasca"
  },
  "MDBD": {
    "name": "Bender",
    "slug": "bender"
  },
  "MDBR": {
    "name": "Briceni",
    "slug": "briceni"
  },
  "MDCA": {
    "name": "Cahul",
    "slug": "cahul"
  },
  "MDCL": {
    "name": "Calarasi",
    "slug": "calarasi"
  },
  "MDCT": {
    "name": "Cantemir",
    "slug": "cantemir"
  },
  "MDCS": {
    "name": "Causeni",
    "slug": "causeni"
  },
  "MDCU": {
    "name": "Chisinau",
    "slug": "chisinau"
  },
  "MDCM": {
    "name": "Cimislia",
    "slug": "cimislia"
  },
  "MDCR": {
    "name": "Criuleni",
    "slug": "criuleni"
  },
  "MDDO": {
    "name": "Donduseni",
    "slug": "donduseni"
  },
  "MDDR": {
    "name": "Drochia",
    "slug": "drochia"
  },
  "MDDU": {
    "name": "Dubasari",
    "slug": "dubasari"
  },
  "MDED": {
    "name": "Edinet",
    "slug": "edinet"
  },
  "MDFA": {
    "name": "Falesti",
    "slug": "falesti"
  },
  "MDFL": {
    "name": "Floresti",
    "slug": "floresti"
  },
  "MDGL": {
    "name": "Glodeni",
    "slug": "glodeni"
  },
  "MDHI": {
    "name": "Hincesti",
    "slug": "hincesti"
  },
  "MDIA": {
    "name": "Ialoveni",
    "slug": "ialoveni"
  },
  "MDLE": {
    "name": "Leova",
    "slug": "leova"
  },
  "MDNI": {
    "name": "Nisporeni",
    "slug": "nisporeni"
  },
  "MDOC": {
    "name": "Ocnita",
    "slug": "ocnita"
  },
  "MDOR": {
    "name": "Orhei",
    "slug": "orhei"
  },
  "MDRE": {
    "name": "Rezina",
    "slug": "rezina"
  },
  "MDRI": {
    "name": "Riscani",
    "slug": "riscani"
  },
  "MDSI": {
    "name": "Singerei",
    "slug": "singerei"
  },
  "MDSD": {
    "name": "Soldanesti",
    "slug": "soldanesti"
  },
  "MDSO": {
    "name": "Soroca",
    "slug": "soroca"
  },
  "MDSV": {
    "name": "Stefan Voda",
    "slug": "stefan-voda"
  },
  "MDST": {
    "name": "Straseni",
    "slug": "straseni"
  },
  "MDTA": {
    "name": "Taraclia",
    "slug": "taraclia"
  },
  "MDTE": {
    "name": "Telenesti",
    "slug": "telenesti"
  },
  "MDSN": {
    "name": "Transnistria",
    "slug": "transnistria"
  },
  "MDUN": {
    "name": "Ungheni",
    "slug": "ungheni"
  },
  "MDGA": {
    "name": "Unitate Teritoriala Autonoma Gagauzia",
    "slug": "unitate-teritoriala-autonoma-gagauzia"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mdaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mdaSvgToSlugMapping[regionId];
}
