// SVG region mapping for Madagascar
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mdgSvgToSlugMapping: RegionMapping = {
  "MGM": {
    "name": "Mahajanga",
    "slug": "mahajanga"
  },
  "MGD": {
    "name": "D",
    "slug": "d"
  },
  "MGA": {
    "name": "Antananarivo",
    "slug": "antananarivo"
  },
  "MGF": {
    "name": "Fianarantsoa",
    "slug": "fianarantsoa"
  },
  "MGU": {
    "name": "U",
    "slug": "u"
  },
  "MGT": {
    "name": "Antananarivo",
    "slug": "antananarivo"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mdgSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mdgSvgToSlugMapping[regionId];
}
