// SVG region mapping for Maldives
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mdvSvgToSlugMapping: RegionMapping = {
  "MV01": {
    "name": "Addu",
    "slug": "addu"
  },
  "MV29": {
    "name": "Gnaviyani",
    "slug": "gnaviyani"
  },
  "MV28": {
    "name": "Gaafu Dhaalu",
    "slug": "gaafu-dhaalu"
  },
  "MV27": {
    "name": "Gaafu Alifu",
    "slug": "gaafu-alifu"
  },
  "MV00": {
    "name": "Alifu Dhaalu",
    "slug": "alifu-dhaalu"
  },
  "MV26": {
    "name": "Kaafu",
    "slug": "kaafu"
  },
  "MV02": {
    "name": "Alifu Alifu",
    "slug": "alifu-alifu"
  },
  "MV20": {
    "name": "20",
    "slug": "20"
  },
  "MV03": {
    "name": "Lhaviyani",
    "slug": "lhaviyani"
  },
  "MV13": {
    "name": "13",
    "slug": "13"
  },
  "MV24": {
    "name": "Shaviyani",
    "slug": "shaviyani"
  },
  "MV05": {
    "name": "Laamu",
    "slug": "laamu"
  },
  "MV08": {
    "name": "Thaa",
    "slug": "thaa"
  },
  "MV17": {
    "name": "Dhaalu",
    "slug": "dhaalu"
  },
  "MV12": {
    "name": "Meemu",
    "slug": "meemu"
  },
  "MV14": {
    "name": "Faafu",
    "slug": "faafu"
  },
  "MV04": {
    "name": "Vaavu",
    "slug": "vaavu"
  },
  "MVMLE": {
    "name": "Malé",
    "slug": "mal"
  },
  "MV25": {
    "name": "Noonu",
    "slug": "noonu"
  },
  "MV23": {
    "name": "Haa Dhaalu",
    "slug": "haa-dhaalu"
  },
  "MV07": {
    "name": "Haa Alifu",
    "slug": "haa-alifu"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mdvSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mdvSvgToSlugMapping[regionId];
}
