// SVG region mapping for Mexico
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mexSvgToSlugMapping: RegionMapping = {
  "MXSON": {
    "name": "Sonora",
    "slug": "sonora"
  },
  "MXBCN": {
    "name": "Baja California",
    "slug": "baja-california"
  },
  "MXCHH": {
    "name": "Chihuahua",
    "slug": "chihuahua"
  },
  "MXCOA": {
    "name": "Coahuila",
    "slug": "coahuila"
  },
  "MXTAM": {
    "name": "Tamaulipas",
    "slug": "tamaulipas"
  },
  "MXNLE": {
    "name": "Nuevo León",
    "slug": "nuevo-len"
  },
  "MXROO": {
    "name": "Quintana Roo",
    "slug": "quintana-roo"
  },
  "MXCAM": {
    "name": "Campeche",
    "slug": "campeche"
  },
  "MXTAB": {
    "name": "Tabasco",
    "slug": "tabasco"
  },
  "MXCHP": {
    "name": "Chiapas",
    "slug": "chiapas"
  },
  "MXCOL": {
    "name": "Colima",
    "slug": "colima"
  },
  "MXNAY": {
    "name": "Nayarit",
    "slug": "nayarit"
  },
  "MXBCS": {
    "name": "Baja California Sur",
    "slug": "baja-california-sur"
  },
  "MXSIN": {
    "name": "Sinaloa",
    "slug": "sinaloa"
  },
  "MXYUC": {
    "name": "Yucatán",
    "slug": "yucatn"
  },
  "MXVER": {
    "name": "Veracruz",
    "slug": "veracruz"
  },
  "MXJAL": {
    "name": "Jalisco",
    "slug": "jalisco"
  },
  "MXMIC": {
    "name": "Michoacán",
    "slug": "michoacn"
  },
  "MXGRO": {
    "name": "Guerrero",
    "slug": "guerrero"
  },
  "MXOAX": {
    "name": "Oaxaca",
    "slug": "oaxaca"
  },
  "MXMEX": {
    "name": "México",
    "slug": "mxico"
  },
  "MXPUE": {
    "name": "Puebla",
    "slug": "puebla"
  },
  "MXMOR": {
    "name": "Morelos",
    "slug": "morelos"
  },
  "MXQUE": {
    "name": "Querétaro",
    "slug": "quertaro"
  },
  "MXHID": {
    "name": "Hidalgo",
    "slug": "hidalgo"
  },
  "MXGUA": {
    "name": "Guanajuato",
    "slug": "guanajuato"
  },
  "MXSLP": {
    "name": "San Luis Potosí",
    "slug": "san-luis-potos"
  },
  "MXZAC": {
    "name": "Zacatecas",
    "slug": "zacatecas"
  },
  "MXAGU": {
    "name": "Aguascalientes",
    "slug": "aguascalientes"
  },
  "MXDUR": {
    "name": "Durango",
    "slug": "durango"
  },
  "MXTLA": {
    "name": "Tlaxcala",
    "slug": "tlaxcala"
  },
  "MXCMX": {
    "name": "Ciudad de México",
    "slug": "ciudad-de-mxico"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mexSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mexSvgToSlugMapping[regionId];
}
