// SVG region mapping for North Macedonia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mkdSvgToSlugMapping: RegionMapping = {
  "MK312": {
    "name": "Struga",
    "slug": "struga"
  },
  "MK313": {
    "name": "Centar župa",
    "slug": "centar-upa"
  },
  "MK303": {
    "name": "Debar",
    "slug": "debar"
  },
  "MK607": {
    "name": "Mavrovo and Rostusa",
    "slug": "mavrovo-and-rostusa"
  },
  "MK604": {
    "name": "Gostivar",
    "slug": "gostivar"
  },
  "MK301": {
    "name": "Vevčani",
    "slug": "vevani"
  },
  "MK310": {
    "name": "Ohrid",
    "slug": "ohrid"
  },
  "MK304": {
    "name": "Debarca",
    "slug": "debarca"
  },
  "MK509": {
    "name": "Resen",
    "slug": "resen"
  },
  "MK408": {
    "name": "Novo Selo",
    "slug": "novo-selo"
  },
  "MK406": {
    "name": "Dojran",
    "slug": "dojran"
  },
  "MK403": {
    "name": "Valandovo",
    "slug": "valandovo"
  },
  "MK410": {
    "name": "Strumitsa",
    "slug": "strumitsa"
  },
  "MK401": {
    "name": "Bogdanci",
    "slug": "bogdanci"
  },
  "MK405": {
    "name": "Gevgelija",
    "slug": "gevgelija"
  },
  "MK104": {
    "name": "Kavadartsi",
    "slug": "kavadartsi"
  },
  "MK507": {
    "name": "Novaci",
    "slug": "novaci"
  },
  "MK508": {
    "name": "Prilep",
    "slug": "prilep"
  },
  "MK501": {
    "name": "Bitola",
    "slug": "bitola"
  },
  "MK704": {
    "name": "Lipkovo",
    "slug": "lipkovo"
  },
  "MK816": {
    "name": "Čučer Sandevo",
    "slug": "uer-sandevo"
  },
  "MK805": {
    "name": "Gjorče Petrov",
    "slug": "gjore-petrov"
  },
  "MK811": {
    "name": "Saraj",
    "slug": "saraj"
  },
  "MK606": {
    "name": "Jegunovce",
    "slug": "jegunovce"
  },
  "MK608": {
    "name": "Tearce",
    "slug": "tearce"
  },
  "MK601": {
    "name": "Bogovinje",
    "slug": "bogovinje"
  },
  "MK603": {
    "name": "Vrapcište",
    "slug": "vrapcite"
  },
  "MK702": {
    "name": "Kriva Palanka",
    "slug": "kriva-palanka"
  },
  "MK705": {
    "name": "Rankovce",
    "slug": "rankovce"
  },
  "MK706": {
    "name": "Staro Nagoričane",
    "slug": "staro-nagoriane"
  },
  "MK703": {
    "name": "Kumanovo",
    "slug": "kumanovo"
  },
  "MK203": {
    "name": "Delčevo",
    "slug": "delevo"
  },
  "MK207": {
    "name": "Makedonska Kamenica",
    "slug": "makedonska-kamenica"
  },
  "MK201": {
    "name": "Berovo",
    "slug": "berovo"
  },
  "MK208": {
    "name": "Pehčevo",
    "slug": "pehevo"
  },
  "MK605": {
    "name": "Želino",
    "slug": "elino"
  },
  "MK602": {
    "name": "Brvenica",
    "slug": "brvenica"
  },
  "MK308": {
    "name": "Brod",
    "slug": "brod"
  },
  "MK307": {
    "name": "Kičevo",
    "slug": "kievo"
  },
  "MK812": {
    "name": "Sopište",
    "slug": "sopite"
  },
  "MK808": {
    "name": "Karpoš",
    "slug": "karpo"
  },
  "MK817": {
    "name": "Šuto Orizari",
    "slug": "uto-orizari"
  },
  "MK803": {
    "name": "Butel",
    "slug": "butel"
  },
  "MK815": {
    "name": "Čair",
    "slug": "air"
  },
  "MK814": {
    "name": "Centar",
    "slug": "centar"
  },
  "MK503": {
    "name": "Dolneni",
    "slug": "dolneni"
  },
  "MK504": {
    "name": "Krivogaštani",
    "slug": "krivogatani"
  },
  "MK506": {
    "name": "Mogila",
    "slug": "mogila"
  },
  "MK109": {
    "name": "Čaška",
    "slug": "aka"
  },
  "MK107": {
    "name": "Rosoman",
    "slug": "rosoman"
  },
  "MK106": {
    "name": "Negotino",
    "slug": "negotino"
  },
  "MK804": {
    "name": "Gazi Baba",
    "slug": "gazi-baba"
  },
  "MK505": {
    "name": "Kruševo",
    "slug": "kruevo"
  },
  "MK502": {
    "name": "Demir Hisar",
    "slug": "demir-hisar"
  },
  "MK801": {
    "name": "Aerodrom",
    "slug": "aerodrom"
  },
  "MK813": {
    "name": "Studeničani",
    "slug": "studeniani"
  },
  "MK809": {
    "name": "Kisela Voda",
    "slug": "kisela-voda"
  },
  "MK209": {
    "name": "Probištip",
    "slug": "probitip"
  },
  "MK210": {
    "name": "Češinovo-Obleševo",
    "slug": "einovo-obleevo"
  },
  "MK802": {
    "name": "Aračinovo",
    "slug": "arainovo"
  },
  "MK806": {
    "name": "Zelenikovo",
    "slug": "zelenikovo"
  },
  "MK311": {
    "name": "Plasnica",
    "slug": "plasnica"
  },
  "MK810": {
    "name": "Skopje",
    "slug": "skopje"
  },
  "MK105": {
    "name": "Lozovo",
    "slug": "lozovo"
  },
  "MK108": {
    "name": "Sveti Nikole",
    "slug": "sveti-nikole"
  },
  "MK102": {
    "name": "Gradsko",
    "slug": "gradsko"
  },
  "MK701": {
    "name": "Kratovo",
    "slug": "kratovo"
  },
  "MK807": {
    "name": "Ilinden",
    "slug": "ilinden"
  },
  "MK205": {
    "name": "Karbinci",
    "slug": "karbinci"
  },
  "MK211": {
    "name": "Štip",
    "slug": "tip"
  },
  "MK206": {
    "name": "Kočani",
    "slug": "koani"
  },
  "MK204": {
    "name": "Zrnovci",
    "slug": "zrnovci"
  },
  "MK101": {
    "name": "Veles",
    "slug": "veles"
  },
  "MK103": {
    "name": "Demir Kapija",
    "slug": "demir-kapija"
  },
  "MK202": {
    "name": "Vinica",
    "slug": "vinica"
  },
  "MK402": {
    "name": "Bosilovo",
    "slug": "bosilovo"
  },
  "MK409": {
    "name": "Radoviš",
    "slug": "radovi"
  },
  "MK404": {
    "name": "Vasilevo",
    "slug": "vasilevo"
  },
  "MK407": {
    "name": "Konče",
    "slug": "kone"
  },
  "MK609": {
    "name": "Tetovo",
    "slug": "tetovo"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mkdSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mkdSvgToSlugMapping[regionId];
}
