// SVG region mapping for Mali
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mliSvgToSlugMapping: RegionMapping = {
  "ML1": {
    "name": "1",
    "slug": "1"
  },
  "ML2": {
    "name": "2",
    "slug": "2"
  },
  "ML3": {
    "name": "3",
    "slug": "3"
  },
  "ML4": {
    "name": "4",
    "slug": "4"
  },
  "ML5": {
    "name": "5",
    "slug": "5"
  },
  "ML6": {
    "name": "6",
    "slug": "6"
  },
  "ML7": {
    "name": "7",
    "slug": "7"
  },
  "ML8": {
    "name": "8",
    "slug": "8"
  },
  "MLBKO": {
    "name": "Bamako",
    "slug": "bamako"
  },
  "ML9": {
    "name": "9",
    "slug": "9"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mliSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mliSvgToSlugMapping[regionId];
}
