// SVG region mapping for Mali
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mliSvgToSlugMapping: RegionMapping = {
  "ML1": {
    "name": "Kayes",
    "slug": "kayes"
  },
  "ML2": {
    "name": "Koulikoro",
    "slug": "koulikoro"
  },
  "ML3": {
    "name": "Sikasso",
    "slug": "sikasso"
  },
  "ML4": {
    "name": "Ségou",
    "slug": "segou"
  },
  "ML5": {
    "name": "Mopti",
    "slug": "mopti"
  },
  "ML6": {
    "name": "Tombouctou",
    "slug": "tombouctou"
  },
  "ML7": {
    "name": "Gao",
    "slug": "gao"
  },
  "ML8": {
    "name": "Kidal",
    "slug": "kidal"
  },
  "BKO": {
    "name": "Bamako",
    "slug": "bamako"
  },
  "ML9": {
    "name": "Menaka",
    "slug": "menaka"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mliSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mliSvgToSlugMapping[regionId];
}
