// SVG region mapping for Malta
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mltSvgToSlugMapping: RegionMapping = {
  "MT21": {
    "name": "Kalkara",
    "slug": "kalkara"
  },
  "MT60": {
    "name": "Valletta",
    "slug": "valletta"
  },
  "MT56": {
    "name": "Sliema",
    "slug": "sliema"
  },
  "MT48": {
    "name": "San Giljan",
    "slug": "san-giljan"
  },
  "MT40": {
    "name": "Pembroke",
    "slug": "pembroke"
  },
  "MT38": {
    "name": "Naxxar",
    "slug": "naxxar"
  },
  "MT51": {
    "name": "San Pawl il-Bahar",
    "slug": "san-pawl-il-bahar"
  },
  "MT30": {
    "name": "Mellieħa",
    "slug": "melliea"
  },
  "MT31": {
    "name": "Mġarr",
    "slug": "marr"
  },
  "MT46": {
    "name": "Rabat",
    "slug": "rabat"
  },
  "MT07": {
    "name": "Dingli",
    "slug": "dingli"
  },
  "MT55": {
    "name": "Siġġiewi",
    "slug": "siiewi"
  },
  "MT44": {
    "name": "Qrendi",
    "slug": "qrendi"
  },
  "MT68": {
    "name": "Żurrieq",
    "slug": "urrieq"
  },
  "MT05": {
    "name": "Birżebbuġa",
    "slug": "birebbua"
  },
  "MT28": {
    "name": "Marsaxlokk",
    "slug": "marsaxlokk"
  },
  "MT27": {
    "name": "Marsaskala",
    "slug": "marsaskala"
  },
  "MT64": {
    "name": "Żabbar",
    "slug": "abbar"
  },
  "MT63": {
    "name": "Xgħajra",
    "slug": "xgajra"
  },
  "MT50": {
    "name": "San Lawrenz",
    "slug": "san-lawrenz"
  },
  "MT22": {
    "name": "Kerċem",
    "slug": "kerem"
  },
  "MT36": {
    "name": "Munxar",
    "slug": "munxar"
  },
  "MT52": {
    "name": "Sannat",
    "slug": "sannat"
  },
  "MT13": {
    "name": "Għajnsielem",
    "slug": "gajnsielem"
  },
  "MT42": {
    "name": "Qala",
    "slug": "qala"
  },
  "MT37": {
    "name": "Nadur",
    "slug": "nadur"
  },
  "MT61": {
    "name": "Xagħra",
    "slug": "xagra"
  },
  "MT65": {
    "name": "Żebbuġ",
    "slug": "ebbu"
  },
  "MT16": {
    "name": "Għasri",
    "slug": "gasri"
  },
  "MT14": {
    "name": "Għarb",
    "slug": "garb"
  },
  "MT45": {
    "name": "Victoria",
    "slug": "victoria"
  },
  "MT10": {
    "name": "Fontana, Gozo",
    "slug": "fontana-gozo"
  },
  "MT62": {
    "name": "Xewkija",
    "slug": "xewkija"
  },
  "MT32": {
    "name": "Mosta",
    "slug": "mosta"
  },
  "MT24": {
    "name": "Lija",
    "slug": "lija"
  },
  "MT01": {
    "name": "Attard",
    "slug": "attard"
  },
  "MT35": {
    "name": "Mtarfa",
    "slug": "mtarfa"
  },
  "MT29": {
    "name": "Mdina",
    "slug": "mdina"
  },
  "MT66": {
    "name": "Żebbuġ",
    "slug": "ebbu"
  },
  "MT43": {
    "name": "Qormi",
    "slug": "qormi"
  },
  "MT57": {
    "name": "Swieqi",
    "slug": "swieqi"
  },
  "MT15": {
    "name": "Għargħur",
    "slug": "gargur"
  },
  "MT49": {
    "name": "San Ġwann",
    "slug": "san-wann"
  },
  "MT19": {
    "name": "Iklin",
    "slug": "iklin"
  },
  "MT04": {
    "name": "Birkirkara",
    "slug": "birkirkara"
  },
  "MT02": {
    "name": "Balzan",
    "slug": "balzan"
  },
  "MT54": {
    "name": "Santa Venera",
    "slug": "santa-venera"
  },
  "MT18": {
    "name": "Ħamrun",
    "slug": "amrun"
  },
  "MT26": {
    "name": "Marsa",
    "slug": "marsa"
  },
  "MT25": {
    "name": "Luqa",
    "slug": "luqa"
  },
  "MT33": {
    "name": "Mqabba",
    "slug": "mqabba"
  },
  "MT23": {
    "name": "Kirkop",
    "slug": "kirkop"
  },
  "MT47": {
    "name": "Safi",
    "slug": "safi"
  },
  "MT17": {
    "name": "Għaxaq",
    "slug": "gaxaq"
  },
  "MT67": {
    "name": "Żejtun",
    "slug": "ejtun"
  },
  "MT08": {
    "name": "Fgura",
    "slug": "fgura"
  },
  "MT59": {
    "name": "Tarxien",
    "slug": "tarxien"
  },
  "MT53": {
    "name": "Santa Luċija",
    "slug": "santa-luija"
  },
  "MT11": {
    "name": "Gudja",
    "slug": "gudja"
  },
  "MT39": {
    "name": "Paola",
    "slug": "paola"
  },
  "MT12": {
    "name": "Gżira",
    "slug": "gira"
  },
  "MT09": {
    "name": "Floriana",
    "slug": "floriana"
  },
  "MT58": {
    "name": "Ta' Xbiex",
    "slug": "ta-xbiex"
  },
  "MT20": {
    "name": "Isla",
    "slug": "isla"
  },
  "MT06": {
    "name": "Cospicua",
    "slug": "cospicua"
  },
  "MT41": {
    "name": "Pietà",
    "slug": "piet"
  },
  "MT34": {
    "name": "Msida",
    "slug": "msida"
  },
  "MT03": {
    "name": "Birgu",
    "slug": "birgu"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mltSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mltSvgToSlugMapping[regionId];
}
