// SVG region mapping for Myanmar
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mmrSvgToSlugMapping: RegionMapping = {
  "MM16": {
    "name": "Rakhine",
    "slug": "rakhine"
  },
  "MM14": {
    "name": "Chin",
    "slug": "chin"
  },
  "MM11": {
    "name": "Kachin",
    "slug": "kachin"
  },
  "MM01": {
    "name": "Sagaing",
    "slug": "sagaing"
  },
  "MM17": {
    "name": "Shan",
    "slug": "shan"
  },
  "MM12": {
    "name": "Kayah",
    "slug": "kayah"
  },
  "MM13": {
    "name": "Kayin",
    "slug": "kayin"
  },
  "MM15": {
    "name": "15",
    "slug": "15"
  },
  "MM05": {
    "name": "Tanintharyi",
    "slug": "tanintharyi"
  },
  "MM07": {
    "name": "Ayeyarwady",
    "slug": "ayeyarwady"
  },
  "MM06": {
    "name": "Yangon",
    "slug": "yangon"
  },
  "MM02": {
    "name": "Bago",
    "slug": "bago"
  },
  "MM03": {
    "name": "Magway",
    "slug": "magway"
  },
  "MM04": {
    "name": "Mandalay",
    "slug": "mandalay"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mmrSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mmrSvgToSlugMapping[regionId];
}
