// SVG region mapping for Montenegro
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mneSvgToSlugMapping: RegionMapping = {
  "ME08": {
    "name": "Herceg Novi",
    "slug": "herceg-novi"
  },
  "ME17": {
    "name": "Rožaje",
    "slug": "roaje"
  },
  "ME03": {
    "name": "Berane",
    "slug": "berane"
  },
  "ME13": {
    "name": "Plav",
    "slug": "plav"
  },
  "ME14": {
    "name": "Pljevlja",
    "slug": "pljevlja"
  },
  "ME04": {
    "name": "Bijelo Polje",
    "slug": "bijelo-polje"
  },
  "ME21": {
    "name": "Žabljak",
    "slug": "abljak"
  },
  "ME15": {
    "name": "Plužine",
    "slug": "pluine"
  },
  "ME12": {
    "name": "Nikšic",
    "slug": "nikic"
  },
  "ME10": {
    "name": "Kotor",
    "slug": "kotor"
  },
  "ME01": {
    "name": "Andrijevica",
    "slug": "andrijevica"
  },
  "ME16": {
    "name": "Podgorica",
    "slug": "podgorica"
  },
  "ME02": {
    "name": "02",
    "slug": "02"
  },
  "ME20": {
    "name": "Ulcinj",
    "slug": "ulcinj"
  },
  "ME05": {
    "name": "Budva",
    "slug": "budva"
  },
  "ME19": {
    "name": "Tivat",
    "slug": "tivat"
  },
  "ME11": {
    "name": "Mojkovac",
    "slug": "mojkovac"
  },
  "ME06": {
    "name": "Cetinje",
    "slug": "cetinje"
  },
  "ME18": {
    "name": "Šavnik",
    "slug": "avnik"
  },
  "ME09": {
    "name": "Kolašin",
    "slug": "kolain"
  },
  "ME07": {
    "name": "Danilovgrad",
    "slug": "danilovgrad"
  },
  "ME22": {
    "name": "Gusinje",
    "slug": "gusinje"
  },
  "ME24": {
    "name": "Tuzi",
    "slug": "tuzi"
  },
  "ME23": {
    "name": "Petnjica",
    "slug": "petnjica"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mneSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mneSvgToSlugMapping[regionId];
}
