// SVG region mapping for Mongolia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mngSvgToSlugMapping: RegionMapping = {
  "MN061": {
    "name": "Dornod",
    "slug": "dornod"
  },
  "MN071": {
    "name": "Bayan-Ölgiy",
    "slug": "bayan-lgiy"
  },
  "MN043": {
    "name": "Hovd",
    "slug": "hovd"
  },
  "MN051": {
    "name": "Sühbaatar",
    "slug": "shbaatar"
  },
  "MN063": {
    "name": "Dornogovi",
    "slug": "dornogovi"
  },
  "MN065": {
    "name": "Govi-Altay",
    "slug": "govi-altay"
  },
  "MN069": {
    "name": "Bayanhongor",
    "slug": "bayanhongor"
  },
  "MN053": {
    "name": "Ömnögovi",
    "slug": "mngovi"
  },
  "MN041": {
    "name": "Hövsgöl",
    "slug": "hvsgl"
  },
  "MN067": {
    "name": "Bulgan",
    "slug": "bulgan"
  },
  "MN046": {
    "name": "Uvs",
    "slug": "uvs"
  },
  "MN049": {
    "name": "Selenge",
    "slug": "selenge"
  },
  "MN057": {
    "name": "Dzavhan",
    "slug": "dzavhan"
  },
  "MN039": {
    "name": "Hentiy",
    "slug": "hentiy"
  },
  "MN037": {
    "name": "Darhan-Uul",
    "slug": "darhan-uul"
  },
  "MN047": {
    "name": "Töv",
    "slug": "tov"
  },
  "MN073": {
    "name": "Arhangay",
    "slug": "arhangay"
  },
  "MN035": {
    "name": "Orhon",
    "slug": "orhon"
  },
  "MN059": {
    "name": "Dundgovi",
    "slug": "dundgovi"
  },
  "MN055": {
    "name": "Övörhangay",
    "slug": "vrhangay"
  },
  "MN064": {
    "name": "Govĭ-Sümber",
    "slug": "gov-smber"
  },
  "MN1": {
    "name": "Ulaanbaatar",
    "slug": "ulaanbaatar"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mngSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mngSvgToSlugMapping[regionId];
}
