// SVG region mapping for Mozambique
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mozSvgToSlugMapping: RegionMapping = {
  "MZL": {
    "name": "Maputo",
    "slug": "maputo"
  },
  "MZP": {
    "name": "Cabo Delgado",
    "slug": "cabo-delgado"
  },
  "MZA": {
    "name": "Niassa",
    "slug": "niassa"
  },
  "MZT": {
    "name": "Tete",
    "slug": "tete"
  },
  "MZB": {
    "name": "Manica",
    "slug": "manica"
  },
  "MZG": {
    "name": "Gaza",
    "slug": "gaza"
  },
  "MZQ": {
    "name": "Zambezia",
    "slug": "zambezia"
  },
  "MPM": {
    "name": "Maputo City",
    "slug": "maputo-city"
  },
  "MZI": {
    "name": "Inhambane",
    "slug": "inhambane"
  },
  "MZS": {
    "name": "Sofala",
    "slug": "sofala"
  },
  "MZN": {
    "name": "Nampula",
    "slug": "nampula"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mozSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mozSvgToSlugMapping[regionId];
}
