// SVG region mapping for Mauritania
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mrtSvgToSlugMapping: RegionMapping = {
  "MR11": {
    "name": "Tiris Zemmour",
    "slug": "tiris-zemmour"
  },
  "MR08": {
    "name": "Dakhlet Nouadhibou",
    "slug": "dakhlet-nouadhibou"
  },
  "MR07": {
    "name": "Adrar",
    "slug": "adrar"
  },
  "MR05": {
    "name": "Brakna",
    "slug": "brakna"
  },
  "MR06": {
    "name": "Trarza",
    "slug": "trarza"
  },
  "MR04": {
    "name": "Gorgol",
    "slug": "gorgol"
  },
  "MR10": {
    "name": "Guidimaka",
    "slug": "guidimaka"
  },
  "MR01": {
    "name": "Hodh ech Chargui",
    "slug": "hodh-ech-chargui"
  },
  "MR02": {
    "name": "Hodh el Gharbi",
    "slug": "hodh-el-gharbi"
  },
  "MR03": {
    "name": "Assaba",
    "slug": "assaba"
  },
  "MR12": {
    "name": "Inchiri",
    "slug": "inchiri"
  },
  "MR13": {
    "name": "Nouakchott-Oues",
    "slug": "nouakchott-oues"
  },
  "MR09": {
    "name": "Tagant",
    "slug": "tagant"
  },
  "MR14": {
    "name": "Nouakchott-Nord",
    "slug": "nouakchott-nord"
  },
  "MR15": {
    "name": "Nouakchott-Sud",
    "slug": "nouakchott-sud"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mrtSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mrtSvgToSlugMapping[regionId];
}
