// SVG region mapping for Montserrat
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const msrSvgToSlugMapping: RegionMapping = {
  "MSP": {
    "name": "P",
    "slug": "p"
  },
  "MSA": {
    "name": "Montserrat",
    "slug": "montserrat"
  },
  "MSG": {
    "name": "G",
    "slug": "g"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return msrSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return msrSvgToSlugMapping[regionId];
}
