// SVG region mapping for Montserrat
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const msrSvgToSlugMapping: RegionMapping = {
  "MSP": {
    "name": "Saint Peter",
    "slug": "saint-peter"
  },
  "MSA": {
    "name": "Saint Anthony",
    "slug": "saint-anthony"
  },
  "MSG": {
    "name": "Saint Georges",
    "slug": "saint-georges"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return msrSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return msrSvgToSlugMapping[regionId];
}
