// SVG region mapping for Mauritius
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const musSvgToSlugMapping: RegionMapping = {
  "MUBL": {
    "name": "Black River",
    "slug": "black-river"
  },
  "MUFL": {
    "name": "Flacq",
    "slug": "flacq"
  },
  "MUGP": {
    "name": "Grand Port",
    "slug": "grand-port"
  },
  "MUMO": {
    "name": "Moka",
    "slug": "moka"
  },
  "MUPA": {
    "name": "Pamplemousses",
    "slug": "pamplemousses"
  },
  "MUPW": {
    "name": "Plaine Wilhems",
    "slug": "plaine-wilhems"
  },
  "MUPL": {
    "name": "Port Louis",
    "slug": "port-louis"
  },
  "MURR": {
    "name": "Riviere du Rempart",
    "slug": "riviere-du-rempart"
  },
  "MUSA": {
    "name": "Savanne",
    "slug": "savanne"
  },
  "MUCC": {
    "name": "Saint Brandon Islands",
    "slug": "saint-brandon-islands"
  },
  "MURO": {
    "name": "Rodriguez Island",
    "slug": "rodriguez-island"
  },
  "MUAG": {
    "name": "North Islands",
    "slug": "north-islands"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return musSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return musSvgToSlugMapping[regionId];
}
