// SVG region mapping for Malawi
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mwiSvgToSlugMapping: RegionMapping = {
  "MWKR": {
    "name": "Karonga",
    "slug": "karonga"
  },
  "MWRU": {
    "name": "Rumphi",
    "slug": "rumphi"
  },
  "MWNB": {
    "name": "Nkhata Bay",
    "slug": "nkhata-bay"
  },
  "MWLK": {
    "name": "Likoma",
    "slug": "likoma"
  },
  "MWCT": {
    "name": "Chitipa",
    "slug": "chitipa"
  },
  "MWMZ": {
    "name": "Mzimba",
    "slug": "mzimba"
  },
  "MWKS": {
    "name": "Kasungu",
    "slug": "kasungu"
  },
  "MWMC": {
    "name": "Mchinji",
    "slug": "mchinji"
  },
  "MWNK": {
    "name": "Nkhotakota",
    "slug": "nkhotakota"
  },
  "MWSA": {
    "name": "Salima",
    "slug": "salima"
  },
  "MWMG": {
    "name": "Mangochi",
    "slug": "mangochi"
  },
  "MWMH": {
    "name": "Machinga",
    "slug": "machinga"
  },
  "MWDE": {
    "name": "Dedza",
    "slug": "dedza"
  },
  "MWLI": {
    "name": "Lilongwe",
    "slug": "lilongwe"
  },
  "MWNS": {
    "name": "Nsanje",
    "slug": "nsanje"
  },
  "MWCK": {
    "name": "Chikwawa",
    "slug": "chikwawa"
  },
  "MWMW": {
    "name": "Mwanza",
    "slug": "mwanza"
  },
  "MWNE": {
    "name": "Neno",
    "slug": "neno"
  },
  "MWNU": {
    "name": "Ntcheu",
    "slug": "ntcheu"
  },
  "MWZO": {
    "name": "Zomba",
    "slug": "zomba"
  },
  "MWPH": {
    "name": "Phalombe",
    "slug": "phalombe"
  },
  "MWMU": {
    "name": "Mulanje",
    "slug": "mulanje"
  },
  "MWTH": {
    "name": "Thyolo",
    "slug": "thyolo"
  },
  "MWDO": {
    "name": "Dowa",
    "slug": "dowa"
  },
  "MWBA": {
    "name": "Balaka",
    "slug": "balaka"
  },
  "MWCR": {
    "name": "Chiradzulu",
    "slug": "chiradzulu"
  },
  "MWBL": {
    "name": "Blantyre",
    "slug": "blantyre"
  },
  "MWNI": {
    "name": "Ntchisi",
    "slug": "ntchisi"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mwiSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mwiSvgToSlugMapping[regionId];
}
