// SVG region mapping for Malaysia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const mysSvgToSlugMapping: RegionMapping = {
  "MY12": {
    "name": "Sabah",
    "slug": "sabah"
  },
  "MY09": {
    "name": "Perlis",
    "slug": "perlis"
  },
  "MY02": {
    "name": "Kedah",
    "slug": "kedah"
  },
  "MY03": {
    "name": "Kelantan",
    "slug": "kelantan"
  },
  "MY08": {
    "name": "Perak",
    "slug": "perak"
  },
  "MY13": {
    "name": "Sarawak",
    "slug": "sarawak"
  },
  "MY07": {
    "name": "Pulau Pinang",
    "slug": "pulau-pinang"
  },
  "MY10": {
    "name": "Selangor",
    "slug": "selangor"
  },
  "MY05": {
    "name": "Negeri Sembilan",
    "slug": "negeri-sembilan"
  },
  "MY04": {
    "name": "Melaka",
    "slug": "melaka"
  },
  "MY01": {
    "name": "Johor",
    "slug": "johor"
  },
  "MY06": {
    "name": "Pahang",
    "slug": "pahang"
  },
  "MY11": {
    "name": "Terengganu",
    "slug": "terengganu"
  },
  "MY15": {
    "name": "Labuan",
    "slug": "labuan"
  },
  "MY14": {
    "name": "Kuala Lumpur",
    "slug": "kuala-lumpur"
  },
  "MY16": {
    "name": "Putrajaya",
    "slug": "putrajaya"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return mysSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return mysSvgToSlugMapping[regionId];
}
