// SVG region mapping for Namibia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const namSvgToSlugMapping: RegionMapping = {
  "NAER": {
    "name": "Erongo",
    "slug": "erongo"
  },
  "NAHA": {
    "name": "Hardap",
    "slug": "hardap"
  },
  "NAKA": {
    "name": "Karas",
    "slug": "karas"
  },
  "NAKE": {
    "name": "Kavango East",
    "slug": "kavango-east"
  },
  "NAKW": {
    "name": "Kavango West",
    "slug": "kavango-west"
  },
  "NAKH": {
    "name": "Khomas",
    "slug": "khomas"
  },
  "NAKU": {
    "name": "Kunene",
    "slug": "kunene"
  },
  "NAOW": {
    "name": "Ohangwena",
    "slug": "ohangwena"
  },
  "NAOH": {
    "name": "Omaheke",
    "slug": "omaheke"
  },
  "NAOS": {
    "name": "Omusati",
    "slug": "omusati"
  },
  "NAON": {
    "name": "Oshana",
    "slug": "oshana"
  },
  "NAOT": {
    "name": "Oshikoto",
    "slug": "oshikoto"
  },
  "NAOD": {
    "name": "Otjozondjupa",
    "slug": "otjozondjupa"
  },
  "NACA": {
    "name": "Zambezi",
    "slug": "zambezi"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return namSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return namSvgToSlugMapping[regionId];
}
