// SVG region mapping for New Caledonia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const nclSvgToSlugMapping: RegionMapping = {
  "NCX03": {
    "name": "Nord",
    "slug": "nord"
  },
  "NCX02": {
    "name": "X02",
    "slug": "x02"
  },
  "NCX01": {
    "name": "Îles Loyauté",
    "slug": "les-loyaut"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return nclSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return nclSvgToSlugMapping[regionId];
}
