// SVG region mapping for Niger
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const nerSvgToSlugMapping: RegionMapping = {
  "NE5": {
    "name": "5",
    "slug": "5"
  },
  "NE3": {
    "name": "3",
    "slug": "3"
  },
  "NE2": {
    "name": "2",
    "slug": "2"
  },
  "NE4": {
    "name": "4",
    "slug": "4"
  },
  "NE7": {
    "name": "7",
    "slug": "7"
  },
  "NE6": {
    "name": "6",
    "slug": "6"
  },
  "NE1": {
    "name": "1",
    "slug": "1"
  },
  "NE8": {
    "name": "8",
    "slug": "8"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return nerSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return nerSvgToSlugMapping[regionId];
}
