// SVG region mapping for Niger
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const nerSvgToSlugMapping: RegionMapping = {
  "NE5": {
    "name": "Tahoua",
    "slug": "tahoua"
  },
  "NE3": {
    "name": "Dosso",
    "slug": "dosso"
  },
  "NE2": {
    "name": "Diffa",
    "slug": "diffa"
  },
  "NE4": {
    "name": "Maradi",
    "slug": "maradi"
  },
  "NE7": {
    "name": "Zinder",
    "slug": "zinder"
  },
  "NE6": {
    "name": "Tillabéri",
    "slug": "tillaberi"
  },
  "NE1": {
    "name": "Agadez",
    "slug": "agadez"
  },
  "NE8": {
    "name": "Niamey",
    "slug": "niamey"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return nerSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return nerSvgToSlugMapping[regionId];
}
