// SVG region mapping for Nigeria
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const ngaSvgToSlugMapping: RegionMapping = {
  "NGKE": {
    "name": "Kebbi",
    "slug": "kebbi"
  },
  "NGNI": {
    "name": "Niger",
    "slug": "niger"
  },
  "NGKW": {
    "name": "Kwara",
    "slug": "kwara"
  },
  "NGOG": {
    "name": "Ogun",
    "slug": "ogun"
  },
  "NGOY": {
    "name": "Oyo",
    "slug": "oyo"
  },
  "NGLA": {
    "name": "Lagos",
    "slug": "lagos"
  },
  "NGBO": {
    "name": "Borno",
    "slug": "borno"
  },
  "NGAD": {
    "name": "Adamawa",
    "slug": "adamawa"
  },
  "NGTA": {
    "name": "Taraba",
    "slug": "taraba"
  },
  "NGBE": {
    "name": "Benue",
    "slug": "benue"
  },
  "NGCR": {
    "name": "Cross River",
    "slug": "cross-river"
  },
  "NGSO": {
    "name": "Sokoto",
    "slug": "sokoto"
  },
  "NGZA": {
    "name": "Zamfara",
    "slug": "zamfara"
  },
  "NGYO": {
    "name": "Yobe",
    "slug": "yobe"
  },
  "NGKT": {
    "name": "Katsina",
    "slug": "katsina"
  },
  "NGJI": {
    "name": "Jigawa",
    "slug": "jigawa"
  },
  "NGON": {
    "name": "Ondo",
    "slug": "ondo"
  },
  "NGDE": {
    "name": "Delta",
    "slug": "delta"
  },
  "NGBY": {
    "name": "Bayelsa",
    "slug": "bayelsa"
  },
  "NGRI": {
    "name": "Rivers",
    "slug": "rivers"
  },
  "NGAK": {
    "name": "Akwa Ibom",
    "slug": "akwa-ibom"
  },
  "NGAB": {
    "name": "Abia",
    "slug": "abia"
  },
  "NGEB": {
    "name": "Ebonyi",
    "slug": "ebonyi"
  },
  "NGAN": {
    "name": "Anambra",
    "slug": "anambra"
  },
  "NGED": {
    "name": "Abuja (Federal Capital Territory)",
    "slug": "abuja-federal-capital-territory"
  },
  "NGBA": {
    "name": "Bauchi",
    "slug": "bauchi"
  },
  "NGPL": {
    "name": "Plateau",
    "slug": "plateau"
  },
  "NGNA": {
    "name": "Nassarawa",
    "slug": "nassarawa"
  },
  "NGGO": {
    "name": "Gombe",
    "slug": "gombe"
  },
  "NGEN": {
    "name": "Enugu",
    "slug": "enugu"
  },
  "NGKO": {
    "name": "Kogi",
    "slug": "kogi"
  },
  "NGOS": {
    "name": "Osun",
    "slug": "osun"
  },
  "NGIM": {
    "name": "Imo",
    "slug": "imo"
  },
  "NGEK": {
    "name": "Ekiti",
    "slug": "ekiti"
  },
  "NGKD": {
    "name": "Kaduna",
    "slug": "kaduna"
  },
  "NGKN": {
    "name": "Kano",
    "slug": "kano"
  },
  "NGFC": {
    "name": "Federal Capital Territory",
    "slug": "federal-capital-territory"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return ngaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return ngaSvgToSlugMapping[regionId];
}
