// SVG region mapping for Nicaragua
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const nicSvgToSlugMapping: RegionMapping = {
  "NISJ": {
    "name": "Rio San Juan",
    "slug": "rio-san-juan"
  },
  "NIAN": {
    "name": "Atlántico Norte",
    "slug": "atlntico-norte"
  },
  "NIJI": {
    "name": "Jinotega",
    "slug": "jinotega"
  },
  "NINS": {
    "name": "Nueva Segovia",
    "slug": "nueva-segovia"
  },
  "NICI": {
    "name": "Chinandega",
    "slug": "chinandega"
  },
  "NIMD": {
    "name": "Madriz",
    "slug": "madriz"
  },
  "NIRI": {
    "name": "Rivas",
    "slug": "rivas"
  },
  "NIAS": {
    "name": "Atlántico Sur",
    "slug": "atlntico-sur"
  },
  "NILE": {
    "name": "León",
    "slug": "len"
  },
  "NIMN": {
    "name": "Managua",
    "slug": "managua"
  },
  "NICA": {
    "name": "Carazo",
    "slug": "carazo"
  },
  "NIMT": {
    "name": "Matagalpa",
    "slug": "matagalpa"
  },
  "NIBO": {
    "name": "Boaco",
    "slug": "boaco"
  },
  "NICO": {
    "name": "Chontales",
    "slug": "chontales"
  },
  "NIES": {
    "name": "Estelí",
    "slug": "estel"
  },
  "NIGR": {
    "name": "Granada",
    "slug": "granada"
  },
  "NIMS": {
    "name": "Masaya",
    "slug": "masaya"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return nicSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return nicSvgToSlugMapping[regionId];
}
