// SVG region mapping for Netherlands
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const nldSvgToSlugMapping: RegionMapping = {
  "NLGR": {
    "name": "Groningen",
    "slug": "groningen"
  },
  "NLDR": {
    "name": "Drenthe",
    "slug": "drenthe"
  },
  "NLOV": {
    "name": "Overijssel",
    "slug": "overijssel"
  },
  "NLGE": {
    "name": "Gelderland",
    "slug": "gelderland"
  },
  "NLLI": {
    "name": "Limburg",
    "slug": "limburg"
  },
  "NLZE": {
    "name": "Zeeland",
    "slug": "zeeland"
  },
  "NLNB": {
    "name": "Noord-Brabant",
    "slug": "noord-brabant"
  },
  "NLZH": {
    "name": "Zuid-Holland",
    "slug": "zuid-holland"
  },
  "NLNH": {
    "name": "Noord-Holland",
    "slug": "noord-holland"
  },
  "NLFR": {
    "name": "Friesland",
    "slug": "friesland"
  },
  "NLFL": {
    "name": "Flevoland",
    "slug": "flevoland"
  },
  "NLUT": {
    "name": "Utrecht",
    "slug": "utrecht"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return nldSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return nldSvgToSlugMapping[regionId];
}
