// SVG region mapping for Norway
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const norSvgToSlugMapping: RegionMapping = {
  "NO54": {
    "name": "Troms og Finnmark",
    "slug": "troms-og-finnmark"
  },
  "NO50": {
    "name": "Trøndelag",
    "slug": "trndelag"
  },
  "NO30": {
    "name": "Viken",
    "slug": "viken"
  },
  "NO03": {
    "name": "Oslo",
    "slug": "oslo"
  },
  "NO38": {
    "name": "Vestfold og Telemark",
    "slug": "vestfold-og-telemark"
  },
  "NO42": {
    "name": "Agder",
    "slug": "agder"
  },
  "NO11": {
    "name": "Rogaland",
    "slug": "rogaland"
  },
  "NO46": {
    "name": "Vestland",
    "slug": "vestland"
  },
  "NO15": {
    "name": "Møre og Romsdal",
    "slug": "mre-og-romsdal"
  },
  "NO34": {
    "name": "Innlandet",
    "slug": "innlandet"
  },
  "NO18": {
    "name": "Nordland",
    "slug": "nordland"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return norSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return norSvgToSlugMapping[regionId];
}
