// SVG region mapping for Nepal
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const nplSvgToSlugMapping: RegionMapping = {
  "NPKA": {
    "name": "Karnali",
    "slug": "karnali"
  },
  "NPMA": {
    "name": "Mahakali",
    "slug": "mahakali"
  },
  "NPSE": {
    "name": "Seti",
    "slug": "seti"
  },
  "NPDH": {
    "name": "Dhawalagiri",
    "slug": "dhawalagiri"
  },
  "NPGA": {
    "name": "Gandaki",
    "slug": "gandaki"
  },
  "NPBA": {
    "name": "Bagmati",
    "slug": "bagmati"
  },
  "NPJA": {
    "name": "Janakpur",
    "slug": "janakpur"
  },
  "NPSA": {
    "name": "Sagarmatha",
    "slug": "sagarmatha"
  },
  "NPKO": {
    "name": "Bhojpur",
    "slug": "bhojpur"
  },
  "NPME": {
    "name": "Mechi",
    "slug": "mechi"
  },
  "NPNA": {
    "name": "Narayani",
    "slug": "narayani"
  },
  "NPLU": {
    "name": "Lumbini",
    "slug": "lumbini"
  },
  "NPRA": {
    "name": "Rapti",
    "slug": "rapti"
  },
  "NPBH": {
    "name": "Bheri",
    "slug": "bheri"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return nplSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return nplSvgToSlugMapping[regionId];
}
