// SVG region mapping for Nauru
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const nruSvgToSlugMapping: RegionMapping = {
  "NR03": {
    "name": "Anetan",
    "slug": "anetan"
  },
  "NR09": {
    "name": "Ewa",
    "slug": "ewa"
  },
  "NR05": {
    "name": "Baiti",
    "slug": "baiti"
  },
  "NR13": {
    "name": "Uaboe",
    "slug": "uaboe"
  },
  "NR12": {
    "name": "Nibok",
    "slug": "nibok"
  },
  "NR08": {
    "name": "Denigomodu",
    "slug": "denigomodu"
  },
  "NR01": {
    "name": "Aiwo",
    "slug": "aiwo"
  },
  "NR06": {
    "name": "Boe",
    "slug": "boe"
  },
  "NR14": {
    "name": "Yaren",
    "slug": "yaren"
  },
  "NR11": {
    "name": "Meneng",
    "slug": "meneng"
  },
  "NR04": {
    "name": "Anibare",
    "slug": "anibare"
  },
  "NR10": {
    "name": "Ijuw",
    "slug": "ijuw"
  },
  "NR02": {
    "name": "Anabar",
    "slug": "anabar"
  },
  "NR07": {
    "name": "Buada",
    "slug": "buada"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return nruSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return nruSvgToSlugMapping[regionId];
}
