// SVG region mapping for New Zealand
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const nzlSvgToSlugMapping: RegionMapping = {
  "NZSTL": {
    "name": "Southland",
    "slug": "southland"
  },
  "NZMBH": {
    "name": "Marlborough District",
    "slug": "marlborough-district"
  },
  "NZNSN": {
    "name": "Nelson City",
    "slug": "nelson-city"
  },
  "NZTAS": {
    "name": "Tasman District",
    "slug": "tasman-district"
  },
  "NZWTC": {
    "name": "West Coast",
    "slug": "west-coast"
  },
  "NZOTA": {
    "name": "Otago",
    "slug": "otago"
  },
  "NZCAN": {
    "name": "Canterbury",
    "slug": "canterbury"
  },
  "NZAUK": {
    "name": "Auckland",
    "slug": "auckland"
  },
  "NZWKO": {
    "name": "Waikato",
    "slug": "waikato"
  },
  "NZWGN": {
    "name": "Wellington",
    "slug": "wellington"
  },
  "NZMWT": {
    "name": "Manawatu-Wanganui",
    "slug": "manawatu-wanganui"
  },
  "NZTKI": {
    "name": "Taranaki",
    "slug": "taranaki"
  },
  "NZNTL": {
    "name": "Northland",
    "slug": "northland"
  },
  "NZBOP": {
    "name": "Bay of Plenty",
    "slug": "bay-of-plenty"
  },
  "NZGIS": {
    "name": "Gisborne District",
    "slug": "gisborne-district"
  },
  "NZHKB": {
    "name": "Hawke's Bay",
    "slug": "hawkes-bay"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return nzlSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return nzlSvgToSlugMapping[regionId];
}
