// SVG region mapping for Oman
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const omnSvgToSlugMapping: RegionMapping = {
  "OMMU": {
    "name": "Musandam",
    "slug": "musandam"
  },
  "OMBA": {
    "name": "Al Batnah North",
    "slug": "al-batnah-north"
  },
  "OMBU": {
    "name": "Al Buraymi",
    "slug": "al-buraymi"
  },
  "OMZA": {
    "name": "Al Dhahira",
    "slug": "al-dhahira"
  },
  "OMZU": {
    "name": "Dhofar",
    "slug": "dhofar"
  },
  "OMWU": {
    "name": "Al Wusta",
    "slug": "al-wusta"
  },
  "OMSH": {
    "name": "Ash Sharqiyah South",
    "slug": "ash-sharqiyah-south"
  },
  "OMSS": {
    "name": "Ash Sharqiyah North",
    "slug": "ash-sharqiyah-north"
  },
  "OMMA": {
    "name": "Muscat",
    "slug": "muscat"
  },
  "OMBJ": {
    "name": "Al Batnah South",
    "slug": "al-batnah-south"
  },
  "OMDA": {
    "name": "Ad Dakhliyah",
    "slug": "ad-dakhliyah"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return omnSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return omnSvgToSlugMapping[regionId];
}
