// SVG region mapping for Pakistan
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const pakSvgToSlugMapping: RegionMapping = {
  "PKGB": {
    "name": "Northern Areas",
    "slug": "northern-areas"
  },
  "PKKP": {
    "name": "K.P.",
    "slug": "kp"
  },
  "PKBA": {
    "name": "Baluchistan",
    "slug": "baluchistan"
  },
  "PKPB": {
    "name": "Punjab",
    "slug": "punjab"
  },
  "PKSD": {
    "name": "Sind",
    "slug": "sind"
  },
  "PKJK": {
    "name": "Azad Kashmir",
    "slug": "azad-kashmir"
  },
  "PKIS": {
    "name": "F.C.T.",
    "slug": "fct"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return pakSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return pakSvgToSlugMapping[regionId];
}
