// SVG region mapping for Panama
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const panSvgToSlugMapping: RegionMapping = {
  "PA1": {
    "name": "Bocas del Toro",
    "slug": "bocas-del-toro"
  },
  "PA2": {
    "name": "Coclé",
    "slug": "cocle"
  },
  "PA3": {
    "name": "Colón",
    "slug": "colon"
  },
  "PA4": {
    "name": "Chiriquí",
    "slug": "chiriqui"
  },
  "PA5": {
    "name": "Darién",
    "slug": "darien"
  },
  "PA6": {
    "name": "Herrera",
    "slug": "herrera"
  },
  "PA7": {
    "name": "Los Santos",
    "slug": "los-santos"
  },
  "PA8": {
    "name": "Panamá",
    "slug": "panama"
  },
  "PA9": {
    "name": "Veraguas",
    "slug": "veraguas"
  },
  "PA10": {
    "name": "Panamá Oeste",
    "slug": "panama-oeste"
  },
  "PAEM": {
    "name": "Emberá",
    "slug": "embera"
  },
  "PAKY": {
    "name": "Kuna Yala",
    "slug": "kuna-yala"
  },
  "PANB": {
    "name": "Ngöbe Buglé",
    "slug": "ngobe-bugle"
  },
  "PANT": {
    "name": "Naso Tjër Di",
    "slug": "naso-tjer-di"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return panSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return panSvgToSlugMapping[regionId];
}
