// SVG region mapping for Panama
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const panSvgToSlugMapping: RegionMapping = {
  "PA1": {
    "name": "1",
    "slug": "1"
  },
  "PANT": {
    "name": "Naso Tjër Di",
    "slug": "naso-tjr-di"
  },
  "PA4": {
    "name": "4",
    "slug": "4"
  },
  "PA2": {
    "name": "2",
    "slug": "2"
  },
  "PA3": {
    "name": "3",
    "slug": "3"
  },
  "PA5": {
    "name": "5",
    "slug": "5"
  },
  "PAEM": {
    "name": "Emberá",
    "slug": "ember"
  },
  "PA6": {
    "name": "6",
    "slug": "6"
  },
  "PAKY": {
    "name": "Kuna Yala",
    "slug": "kuna-yala"
  },
  "PA7": {
    "name": "7",
    "slug": "7"
  },
  "PANB": {
    "name": "Ngöbe Buglé",
    "slug": "ngbe-bugl"
  },
  "PA10": {
    "name": "Panamá Oeste",
    "slug": "panam-oeste"
  },
  "PA8": {
    "name": "8",
    "slug": "8"
  },
  "PA9": {
    "name": "9",
    "slug": "9"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return panSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return panSvgToSlugMapping[regionId];
}
