// SVG region mapping for Peru
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const perSvgToSlugMapping: RegionMapping = {
  "PETAC": {
    "name": "Tacna",
    "slug": "tacna"
  },
  "PEMDD": {
    "name": "Madre de Dios",
    "slug": "madre-de-dios"
  },
  "PELOR": {
    "name": "Loreto",
    "slug": "loreto"
  },
  "PEAMA": {
    "name": "Amazonas",
    "slug": "amazonas"
  },
  "PECAJ": {
    "name": "Cajamarca",
    "slug": "cajamarca"
  },
  "PETUM": {
    "name": "Tumbes",
    "slug": "tumbes"
  },
  "PEPIU": {
    "name": "Piura",
    "slug": "piura"
  },
  "PEUCA": {
    "name": "Ucayali",
    "slug": "ucayali"
  },
  "PEPUN": {
    "name": "Puno",
    "slug": "puno"
  },
  "PEMOQ": {
    "name": "Moquegua",
    "slug": "moquegua"
  },
  "PEARE": {
    "name": "Arequipa",
    "slug": "arequipa"
  },
  "PEICA": {
    "name": "Huancavelica",
    "slug": "huancavelica"
  },
  "PELIM": {
    "name": "Lima Province",
    "slug": "lima-province"
  },
  "PELMA": {
    "name": "Lima",
    "slug": "lima"
  },
  "PECAL": {
    "name": "Callao",
    "slug": "callao"
  },
  "PEANC": {
    "name": "Áncash",
    "slug": "ncash"
  },
  "PELAL": {
    "name": "La Libertad",
    "slug": "la-libertad"
  },
  "PELAM": {
    "name": "Lambayeque",
    "slug": "lambayeque"
  },
  "PECUS": {
    "name": "Cusco",
    "slug": "cusco"
  },
  "PEAYA": {
    "name": "Ayacucho",
    "slug": "ayacucho"
  },
  "PEAPU": {
    "name": "Apurímac",
    "slug": "apurmac"
  },
  "PEHUV": {
    "name": "Huancavelica",
    "slug": "huancavelica"
  },
  "PESAM": {
    "name": "San Martín",
    "slug": "san-martn"
  },
  "PEHUC": {
    "name": "Huánuco",
    "slug": "hunuco"
  },
  "PEPAS": {
    "name": "Pasco",
    "slug": "pasco"
  },
  "PEJUN": {
    "name": "Junín",
    "slug": "junn"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return perSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return perSvgToSlugMapping[regionId];
}
