// SVG region mapping for Philippines
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const phlSvgToSlugMapping: RegionMapping = {
  "PH11": {
    "name": "Davao",
    "slug": "davao"
  },
  "PH13": {
    "name": "Caraga",
    "slug": "caraga"
  },
  "PH10": {
    "name": "Northern Mindanao",
    "slug": "northern-mindanao"
  },
  "PH14": {
    "name": "Autonomous Region in Muslim Mindanao",
    "slug": "autonomous-region-in-muslim-mindanao"
  },
  "PH09": {
    "name": "Zamboanga Peninsula",
    "slug": "zamboanga-peninsula"
  },
  "PH41": {
    "name": "Mimaropa",
    "slug": "mimaropa"
  },
  "PH40": {
    "name": "Calabarzon",
    "slug": "calabarzon"
  },
  "PH08": {
    "name": "Eastern Visayas",
    "slug": "eastern-visayas"
  },
  "PH05": {
    "name": "Bicol",
    "slug": "bicol"
  },
  "PH03": {
    "name": "Central Luzon",
    "slug": "central-luzon"
  },
  "PH02": {
    "name": "Cagayan Valley",
    "slug": "cagayan-valley"
  },
  "PH00": {
    "name": "National Capital Region",
    "slug": "national-capital-region"
  },
  "PH15": {
    "name": "Cordillera Administrative Region",
    "slug": "cordillera-administrative-region"
  },
  "PH01": {
    "name": "Ilocos",
    "slug": "ilocos"
  },
  "PH07": {
    "name": "Central Visayas",
    "slug": "central-visayas"
  },
  "PH06": {
    "name": "Western Visayas",
    "slug": "western-visayas"
  },
  "PH12": {
    "name": "Soccsksargen",
    "slug": "soccsksargen"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return phlSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return phlSvgToSlugMapping[regionId];
}
