// SVG region mapping for Papua New Guinea
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const pngSvgToSlugMapping: RegionMapping = {
  "PGNSB": {
    "name": "Autonomous Region of Bougainville",
    "slug": "autonomous-region-of-bougainville"
  },
  "PGCPM": {
    "name": "Central Province",
    "slug": "central-province"
  },
  "PGCPK": {
    "name": "Chimbu (Simbu) Province",
    "slug": "chimbu-simbu-province"
  },
  "PGEBR": {
    "name": "East New Britain Province",
    "slug": "east-new-britain-province"
  },
  "PGESW": {
    "name": "East Sepik Province",
    "slug": "east-sepik-province"
  },
  "PGEHG": {
    "name": "Eastern Highlands Province",
    "slug": "eastern-highlands-province"
  },
  "PGEPW": {
    "name": "Enga Province",
    "slug": "enga-province"
  },
  "PGGPK": {
    "name": "Gulf Province",
    "slug": "gulf-province"
  },
  "PGHLA": {
    "name": "Hela Province",
    "slug": "hela-province"
  },
  "PGJWK": {
    "name": "Jiwaka Province",
    "slug": "jiwaka-province"
  },
  "PGMPM": {
    "name": "Madang Province",
    "slug": "madang-province"
  },
  "PGMRL": {
    "name": "Manus Province",
    "slug": "manus-province"
  },
  "PGMBA": {
    "name": "Milne Bay Province",
    "slug": "milne-bay-province"
  },
  "PGMPL": {
    "name": "Morobe Province",
    "slug": "morobe-province"
  },
  "PGNCD": {
    "name": "National Capital District",
    "slug": "national-capital-district"
  },
  "PGNIK": {
    "name": "New Ireland Province",
    "slug": "new-ireland-province"
  },
  "PGNPP": {
    "name": "Northern (Oro) Province",
    "slug": "northern-oro-province"
  },
  "PGSHM": {
    "name": "Southern Highlands Province",
    "slug": "southern-highlands-province"
  },
  "PGWBK": {
    "name": "West New Britain Province",
    "slug": "west-new-britain-province"
  },
  "PGSAN": {
    "name": "West Sepik (Sandaun) Province",
    "slug": "west-sepik-sandaun-province"
  },
  "PGWHM": {
    "name": "Western Highlands Province",
    "slug": "western-highlands-province"
  },
  "PGWPD": {
    "name": "Western Province",
    "slug": "western-province"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return pngSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return pngSvgToSlugMapping[regionId];
}
