// SVG region mapping for Poland
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const polSvgToSlugMapping: RegionMapping = {
  "PL24": {
    "name": "Silesian",
    "slug": "silesian"
  },
  "PL12": {
    "name": "Lesser Poland",
    "slug": "lesser-poland"
  },
  "PL18": {
    "name": "Subcarpathian",
    "slug": "subcarpathian"
  },
  "PL02": {
    "name": "Lower Silesian",
    "slug": "lower-silesian"
  },
  "PL16": {
    "name": "Opole",
    "slug": "opole"
  },
  "PL20": {
    "name": "Podlachian",
    "slug": "podlachian"
  },
  "PL28": {
    "name": "Warmian-Masurian",
    "slug": "warmian-masurian"
  },
  "PL08": {
    "name": "Lubusz",
    "slug": "lubusz"
  },
  "PL32": {
    "name": "West Pomeranian",
    "slug": "west-pomeranian"
  },
  "PL06": {
    "name": "Lublin",
    "slug": "lublin"
  },
  "PL22": {
    "name": "Pomeranian",
    "slug": "pomeranian"
  },
  "PL14": {
    "name": "Masovian",
    "slug": "masovian"
  },
  "PL10": {
    "name": "Łódź",
    "slug": "d"
  },
  "PL04": {
    "name": "Kuyavian-Pomeranian",
    "slug": "kuyavian-pomeranian"
  },
  "PL30": {
    "name": "Greater Poland",
    "slug": "greater-poland"
  },
  "PL26": {
    "name": "Świętokrzyskie",
    "slug": "witokrzyskie"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return polSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return polSvgToSlugMapping[regionId];
}
