// SVG region mapping for North Korea
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const prkSvgToSlugMapping: RegionMapping = {
  "KP04": {
    "name": "Jagang",
    "slug": "jagang"
  },
  "KP07": {
    "name": "Kangwon",
    "slug": "kangwon"
  },
  "KP14": {
    "name": "Nampo",
    "slug": "nampo"
  },
  "KP09": {
    "name": "North Hamgyong",
    "slug": "north-hamgyong"
  },
  "KP06": {
    "name": "North Hwanghae",
    "slug": "north-hwanghae"
  },
  "KP03": {
    "name": "North Pyongan",
    "slug": "north-pyongan"
  },
  "KP01": {
    "name": "Pyongyang",
    "slug": "pyongyang"
  },
  "KP10": {
    "name": "Ryanggang",
    "slug": "ryanggang"
  },
  "KP08": {
    "name": "South Hamgyong",
    "slug": "south-hamgyong"
  },
  "KP05": {
    "name": "South Hwanghae",
    "slug": "south-hwanghae"
  },
  "KP02": {
    "name": "South Pyongan",
    "slug": "south-pyongan"
  },
  "KP13": {
    "name": "Rason",
    "slug": "rason"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return prkSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return prkSvgToSlugMapping[regionId];
}
