// SVG region mapping for Portugal
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const prtSvgToSlugMapping: RegionMapping = {
  "PT07": {
    "name": "Évora",
    "slug": "vora"
  },
  "PT12": {
    "name": "Portalegre",
    "slug": "portalegre"
  },
  "PT16": {
    "name": "Viana do Castelo",
    "slug": "viana-do-castelo"
  },
  "PT05": {
    "name": "Castelo Branco",
    "slug": "castelo-branco"
  },
  "PT09": {
    "name": "Guarda",
    "slug": "guarda"
  },
  "PT04": {
    "name": "Bragança",
    "slug": "bragana"
  },
  "PT17": {
    "name": "Vila Real",
    "slug": "vila-real"
  },
  "PT03": {
    "name": "Braga",
    "slug": "braga"
  },
  "PT08": {
    "name": "Faro",
    "slug": "faro"
  },
  "PT02": {
    "name": "Beja",
    "slug": "beja"
  },
  "PT15": {
    "name": "Setúbal",
    "slug": "setbal"
  },
  "PT11": {
    "name": "Lisboa",
    "slug": "lisboa"
  },
  "PT14": {
    "name": "Santarém",
    "slug": "santarm"
  },
  "PT10": {
    "name": "Leiria",
    "slug": "leiria"
  },
  "PT06": {
    "name": "Coimbra",
    "slug": "coimbra"
  },
  "PT01": {
    "name": "Aveiro",
    "slug": "aveiro"
  },
  "PT13": {
    "name": "Porto",
    "slug": "porto"
  },
  "PT30": {
    "name": "Madeira",
    "slug": "madeira"
  },
  "PT20": {
    "name": "Azores",
    "slug": "azores"
  },
  "PT18": {
    "name": "Viseu",
    "slug": "viseu"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return prtSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return prtSvgToSlugMapping[regionId];
}
