// SVG region mapping for Paraguay
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const prySvgToSlugMapping: RegionMapping = {
  "PY19": {
    "name": "Boquerón",
    "slug": "boquern"
  },
  "PY15": {
    "name": "Presidente Hayes",
    "slug": "presidente-hayes"
  },
  "PY11": {
    "name": "Central",
    "slug": "central"
  },
  "ASU": {
    "name": "Asunción",
    "slug": "asuncion"
  },
  "PY10": {
    "name": "Alto Paraná",
    "slug": "alto-paran"
  },
  "PY7": {
    "name": "Itapúa",
    "slug": "itapua"
  },
  "PY12": {
    "name": "Ñeembucú",
    "slug": "eembuc"
  },
  "PY8": {
    "name": "Misiones",
    "slug": "misiones"
  },
  "PY16": {
    "name": "Alto Paraguay",
    "slug": "alto-paraguay"
  },
  "PY1": {
    "name": "Concepción",
    "slug": "concepcion"
  },
  "PY13": {
    "name": "Amambay",
    "slug": "amambay"
  },
  "PY14": {
    "name": "Canindeyú",
    "slug": "canindey"
  },
  "PY2": {
    "name": "San Pedro",
    "slug": "san-pedro"
  },
  "PY5": {
    "name": "Caaguazú",
    "slug": "caaguazu"
  },
  "PY3": {
    "name": "Cordillera",
    "slug": "cordillera"
  },
  "PY6": {
    "name": "Caazapá",
    "slug": "caazapa"
  },
  "PY9": {
    "name": "Paraguarí",
    "slug": "paraguari"
  },
  "PY4": {
    "name": "Guairá",
    "slug": "guaira"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return prySvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return prySvgToSlugMapping[regionId];
}
