// SVG region mapping for Paraguay
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const prySvgToSlugMapping: RegionMapping = {
  "PY19": {
    "name": "Boquerón",
    "slug": "boquern"
  },
  "PY15": {
    "name": "Presidente Hayes",
    "slug": "presidente-hayes"
  },
  "PY11": {
    "name": "Central",
    "slug": "central"
  },
  "PYASU": {
    "name": "Asunción",
    "slug": "asuncin"
  },
  "PY10": {
    "name": "Alto Paraná",
    "slug": "alto-paran"
  },
  "PY7": {
    "name": "7",
    "slug": "7"
  },
  "PY12": {
    "name": "Ñeembucú",
    "slug": "eembuc"
  },
  "PY8": {
    "name": "8",
    "slug": "8"
  },
  "PY16": {
    "name": "Alto Paraguay",
    "slug": "alto-paraguay"
  },
  "PY1": {
    "name": "1",
    "slug": "1"
  },
  "PY13": {
    "name": "Amambay",
    "slug": "amambay"
  },
  "PY14": {
    "name": "Canindeyú",
    "slug": "canindey"
  },
  "PY2": {
    "name": "2",
    "slug": "2"
  },
  "PY5": {
    "name": "5",
    "slug": "5"
  },
  "PY3": {
    "name": "3",
    "slug": "3"
  },
  "PY6": {
    "name": "6",
    "slug": "6"
  },
  "PY9": {
    "name": "9",
    "slug": "9"
  },
  "PY4": {
    "name": "4",
    "slug": "4"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return prySvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return prySvgToSlugMapping[regionId];
}
