// SVG region mapping for Palestine
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const pseSvgToSlugMapping: RegionMapping = {
  "PSGZZ": {
    "name": "Gaza Strip",
    "slug": "gaza-strip"
  },
  "PSWBK": {
    "name": "West Bank",
    "slug": "west-bank"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return pseSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return pseSvgToSlugMapping[regionId];
}
