// SVG region mapping for French Polynesia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const pyfSvgToSlugMapping: RegionMapping = {
  "PFX03": {
    "name": "Tuamotu-Gambier",
    "slug": "tuamotu-gambier"
  },
  "PFX01": {
    "name": "Windward Islands",
    "slug": "windward-islands"
  },
  "PFX02": {
    "name": "Leeward Islands",
    "slug": "leeward-islands"
  },
  "PFX04": {
    "name": "Austral Islands",
    "slug": "austral-islands"
  },
  "PFX05": {
    "name": "Marquesas Islands",
    "slug": "marquesas-islands"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return pyfSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return pyfSvgToSlugMapping[regionId];
}
