// SVG region mapping for Qatar
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const qatSvgToSlugMapping: RegionMapping = {
  "QADA": {
    "name": "Ad Dawhah",
    "slug": "ad-dawhah"
  },
  "QAZA": {
    "name": "Al Daayen",
    "slug": "al-daayen"
  },
  "QAKH": {
    "name": "Al Khor",
    "slug": "al-khor"
  },
  "QAWA": {
    "name": "Al Wakrah",
    "slug": "al-wakrah"
  },
  "QARA": {
    "name": "Ar Rayyan",
    "slug": "ar-rayyan"
  },
  "QAUS": {
    "name": "Umm Salal",
    "slug": "umm-salal"
  },
  "QAMS": {
    "name": "Al Shamal",
    "slug": "al-shamal"
  },
  "QASH": {
    "name": "Al Shahaniya",
    "slug": "al-shahaniya"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return qatSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return qatSvgToSlugMapping[regionId];
}
