// SVG region mapping for Romania
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const rouSvgToSlugMapping: RegionMapping = {
  "ROSM": {
    "name": "Satu Mare",
    "slug": "satu-mare"
  },
  "ROAR": {
    "name": "Arad",
    "slug": "arad"
  },
  "ROBH": {
    "name": "Bihor",
    "slug": "bihor"
  },
  "ROTM": {
    "name": "Timis",
    "slug": "timis"
  },
  "ROMH": {
    "name": "Mehedinti",
    "slug": "mehedinti"
  },
  "RODJ": {
    "name": "Dolj",
    "slug": "dolj"
  },
  "ROCL": {
    "name": "Calarasi",
    "slug": "calarasi"
  },
  "ROTR": {
    "name": "Teleorman",
    "slug": "teleorman"
  },
  "ROGR": {
    "name": "Giurgiu",
    "slug": "giurgiu"
  },
  "ROCT": {
    "name": "Constanta",
    "slug": "constanta"
  },
  "ROOT": {
    "name": "Botosani",
    "slug": "botosani"
  },
  "ROCS": {
    "name": "Caras-Severin",
    "slug": "caras-severin"
  },
  "ROBT": {
    "name": "Botosani",
    "slug": "botosani"
  },
  "ROIS": {
    "name": "Iasi",
    "slug": "iasi"
  },
  "ROVS": {
    "name": "Vaslui",
    "slug": "vaslui"
  },
  "ROGL": {
    "name": "Galati",
    "slug": "galati"
  },
  "ROSV": {
    "name": "Suceava",
    "slug": "suceava"
  },
  "ROMM": {
    "name": "Maramures",
    "slug": "maramures"
  },
  "ROTL": {
    "name": "Tulcea",
    "slug": "tulcea"
  },
  "ROCJ": {
    "name": "Cluj",
    "slug": "cluj"
  },
  "ROBN": {
    "name": "Bistrita-Nasaud",
    "slug": "bistrita-nasaud"
  },
  "ROSJ": {
    "name": "Salaj",
    "slug": "salaj"
  },
  "RODB": {
    "name": "Dâmbovita",
    "slug": "dmbovita"
  },
  "ROIF": {
    "name": "Ilfov",
    "slug": "ilfov"
  },
  "ROAG": {
    "name": "Arges",
    "slug": "arges"
  },
  "ROGJ": {
    "name": "Gorj",
    "slug": "gorj"
  },
  "ROHD": {
    "name": "Hunedoara",
    "slug": "hunedoara"
  },
  "ROVL": {
    "name": "Vâlcea",
    "slug": "vlcea"
  },
  "ROPH": {
    "name": "Prahova",
    "slug": "prahova"
  },
  "ROCV": {
    "name": "Covasna",
    "slug": "covasna"
  },
  "ROVN": {
    "name": "Vrancea",
    "slug": "vrancea"
  },
  "ROBZ": {
    "name": "Buzau",
    "slug": "buzau"
  },
  "ROBV": {
    "name": "Brasov",
    "slug": "brasov"
  },
  "ROSB": {
    "name": "Sibiu",
    "slug": "sibiu"
  },
  "ROMS": {
    "name": "Mures",
    "slug": "mures"
  },
  "ROHR": {
    "name": "Harghita",
    "slug": "harghita"
  },
  "RONT": {
    "name": "Neamt",
    "slug": "neamt"
  },
  "ROBC": {
    "name": "Bacau",
    "slug": "bacau"
  },
  "ROAB": {
    "name": "Alba",
    "slug": "alba"
  },
  "ROBR": {
    "name": "Braila",
    "slug": "braila"
  },
  "ROIL": {
    "name": "Ialomita",
    "slug": "ialomita"
  },
  "ROB": {
    "name": "Alba",
    "slug": "alba"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return rouSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return rouSvgToSlugMapping[regionId];
}
