// SVG region mapping for Russia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const rusSvgToSlugMapping: RegionMapping = {
  "RUAL": {
    "name": "Gorno-Altay",
    "slug": "gorno-altay"
  },
  "RUPSK": {
    "name": "Pskov",
    "slug": "pskov"
  },
  "RUKDA": {
    "name": "Krasnodar",
    "slug": "krasnodar"
  },
  "RUKC": {
    "name": "Karachay-Cherkess",
    "slug": "karachay-cherkess"
  },
  "RUKB": {
    "name": "Kabardin-Balkar",
    "slug": "kabardin-balkar"
  },
  "RUSE": {
    "name": "North Ossetia",
    "slug": "north-ossetia"
  },
  "RUIN": {
    "name": "Ingush",
    "slug": "ingush"
  },
  "RUCE": {
    "name": "Chechnya",
    "slug": "chechnya"
  },
  "RUDA": {
    "name": "Dagestan",
    "slug": "dagestan"
  },
  "RUMUR": {
    "name": "Murmansk",
    "slug": "murmansk"
  },
  "RUKR": {
    "name": "Karelia",
    "slug": "karelia"
  },
  "RULEN": {
    "name": "Leningrad",
    "slug": "leningrad"
  },
  "RUKGD": {
    "name": "Kaliningrad",
    "slug": "kaliningrad"
  },
  "RUSMO": {
    "name": "Smolensk",
    "slug": "smolensk"
  },
  "RUBRY": {
    "name": "Bryansk",
    "slug": "bryansk"
  },
  "RUKRS": {
    "name": "Kursk",
    "slug": "kursk"
  },
  "RUBEL": {
    "name": "Belgorod",
    "slug": "belgorod"
  },
  "RUVOR": {
    "name": "Voronezh",
    "slug": "voronezh"
  },
  "RUROS": {
    "name": "Rostov",
    "slug": "rostov"
  },
  "RUBU": {
    "name": "Buryat",
    "slug": "buryat"
  },
  "RUTY": {
    "name": "Tuva",
    "slug": "tuva"
  },
  "RUZAB": {
    "name": "Chita",
    "slug": "chita"
  },
  "RUAMU": {
    "name": "Amur",
    "slug": "amur"
  },
  "RUYEV": {
    "name": "Yevrey",
    "slug": "yevrey"
  },
  "RUKHA": {
    "name": "Khabarovsk",
    "slug": "khabarovsk"
  },
  "RUPRI": {
    "name": "Primor'ye",
    "slug": "primorye"
  },
  "RUTYU": {
    "name": "Tyumen'",
    "slug": "tyumen"
  },
  "RUKGN": {
    "name": "Kurgan",
    "slug": "kurgan"
  },
  "RUOMS": {
    "name": "Omsk",
    "slug": "omsk"
  },
  "RUNVS": {
    "name": "Novosibirsk",
    "slug": "novosibirsk"
  },
  "RUCHE": {
    "name": "Chelyabinsk",
    "slug": "chelyabinsk"
  },
  "RUALT": {
    "name": "Altay",
    "slug": "altay"
  },
  "RUORE": {
    "name": "Orenburg",
    "slug": "orenburg"
  },
  "RUSAR": {
    "name": "Saratov",
    "slug": "saratov"
  },
  "RUAST": {
    "name": "Astrakhan'",
    "slug": "astrakhan"
  },
  "RUVGG": {
    "name": "Volgograd",
    "slug": "volgograd"
  },
  "RUMAG": {
    "name": "Maga Buryatdan",
    "slug": "maga-buryatdan"
  },
  "RUSAK": {
    "name": "Sakhalin",
    "slug": "sakhalin"
  },
  "RUCHU": {
    "name": "Chukchi Autonomous Okrug",
    "slug": "chukchi-autonomous-okrug"
  },
  "RUYAN": {
    "name": "Yamal-Nenets",
    "slug": "yamal-nenets"
  },
  "RUNEN": {
    "name": "Nenets",
    "slug": "nenets"
  },
  "RUSA": {
    "name": "Sakha (Yakutia)",
    "slug": "sakha-yakutia"
  },
  "RUSPE": {
    "name": "City of St. Petersburg",
    "slug": "city-of-st-petersburg"
  },
  "RUARK": {
    "name": "Arkhangel'sk",
    "slug": "arkhangelsk"
  },
  "RUKYA": {
    "name": "Krasnoyarsk",
    "slug": "krasnoyarsk"
  },
  "RUKL": {
    "name": "Kalmyk",
    "slug": "kalmyk"
  },
  "RUKAM": {
    "name": "Kamchatka",
    "slug": "kamchatka"
  },
  "RUBA": {
    "name": "Bashkortostan",
    "slug": "bashkortostan"
  },
  "RUSVE": {
    "name": "Sverdlovsk",
    "slug": "sverdlovsk"
  },
  "RUKHM": {
    "name": "Khanty-Mansiy",
    "slug": "khanty-mansiy"
  },
  "RULIP": {
    "name": "Lipetsk",
    "slug": "lipetsk"
  },
  "RUTAM": {
    "name": "Tambov",
    "slug": "tambov"
  },
  "RUTOM": {
    "name": "Tomsk",
    "slug": "tomsk"
  },
  "RUTA": {
    "name": "Tatarstan",
    "slug": "tatarstan"
  },
  "RUULY": {
    "name": "Ul'yanovsk",
    "slug": "ulyanovsk"
  },
  "RUPNZ": {
    "name": "Penza",
    "slug": "penza"
  },
  "RUKEM": {
    "name": "Kemerovo",
    "slug": "kemerovo"
  },
  "RUORL": {
    "name": "Orel",
    "slug": "orel"
  },
  "RUIRK": {
    "name": "Irkutsk",
    "slug": "irkutsk"
  },
  "RUKK": {
    "name": "Khakass",
    "slug": "khakass"
  },
  "RUMO": {
    "name": "Mordovia",
    "slug": "mordovia"
  },
  "RUKLU": {
    "name": "Kaluga",
    "slug": "kaluga"
  },
  "RUKOS": {
    "name": "Kostroma",
    "slug": "kostroma"
  },
  "RUYAR": {
    "name": "Yaroslavl'",
    "slug": "yaroslavl"
  },
  "RUVLA": {
    "name": "Vladimir",
    "slug": "vladimir"
  },
  "RURYA": {
    "name": "Ryazan'",
    "slug": "ryazan"
  },
  "RUIVA": {
    "name": "Ivanovo",
    "slug": "ivanovo"
  },
  "RUNIZ": {
    "name": "Nizhegorod",
    "slug": "nizhegorod"
  },
  "RUTUL": {
    "name": "Tula",
    "slug": "tula"
  },
  "RUCU": {
    "name": "Chuvash",
    "slug": "chuvash"
  },
  "RUVLG": {
    "name": "Vologda",
    "slug": "vologda"
  },
  "RUNGR": {
    "name": "Novgorod",
    "slug": "novgorod"
  },
  "RUTVE": {
    "name": "Tver'",
    "slug": "tver"
  },
  "RUMOW": {
    "name": "Moskovskaya",
    "slug": "moskovskaya"
  },
  "RUMOS": {
    "name": "Moskva",
    "slug": "moskva"
  },
  "RUME": {
    "name": "Mariy-El",
    "slug": "mariy-el"
  },
  "RUKIR": {
    "name": "Kirov",
    "slug": "kirov"
  },
  "RUUD": {
    "name": "Udmurt",
    "slug": "udmurt"
  },
  "RUKO": {
    "name": "Komi",
    "slug": "komi"
  },
  "RUPER": {
    "name": "Perm'",
    "slug": "perm"
  },
  "RUSAM": {
    "name": "Samara",
    "slug": "samara"
  },
  "RUSTA": {
    "name": "Stavropol'",
    "slug": "stavropol"
  },
  "RUAD": {
    "name": "Adygey",
    "slug": "adygey"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return rusSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return rusSvgToSlugMapping[regionId];
}
