// SVG region mapping for Rwanda
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const rwaSvgToSlugMapping: RegionMapping = {
  "RW02": {
    "name": "Eastern",
    "slug": "eastern"
  },
  "RW05": {
    "name": "Southern",
    "slug": "southern"
  },
  "RW04": {
    "name": "Western",
    "slug": "western"
  },
  "RW03": {
    "name": "Northern",
    "slug": "northern"
  },
  "RW01": {
    "name": "Kigali City",
    "slug": "kigali-city"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return rwaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return rwaSvgToSlugMapping[regionId];
}
