// SVG region mapping for Saudi Arabia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const sauSvgToSlugMapping: RegionMapping = {
  "SA04": {
    "name": "Ash Sharqiyah",
    "slug": "ash-sharqiyah"
  },
  "SA08": {
    "name": "Al Hudud ash Shamaliyah",
    "slug": "al-hudud-ash-shamaliyah"
  },
  "SA12": {
    "name": "Al Jawf",
    "slug": "al-jawf"
  },
  "SA10": {
    "name": "Najran",
    "slug": "najran"
  },
  "SA14": {
    "name": "`Asir",
    "slug": "asir"
  },
  "SA09": {
    "name": "Jizan",
    "slug": "jizan"
  },
  "SA07": {
    "name": "Tabuk",
    "slug": "tabuk"
  },
  "SA03": {
    "name": "Al Madinah",
    "slug": "al-madinah"
  },
  "SA02": {
    "name": "Makkah",
    "slug": "makkah"
  },
  "SA01": {
    "name": "Ar Riyad",
    "slug": "ar-riyad"
  },
  "SA05": {
    "name": "Al Quassim",
    "slug": "al-quassim"
  },
  "SA06": {
    "name": "Ha'il",
    "slug": "hail"
  },
  "SA11": {
    "name": "Al Bahah",
    "slug": "al-bahah"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return sauSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return sauSvgToSlugMapping[regionId];
}
