// SVG region mapping for Sudan
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const sdnSvgToSlugMapping: RegionMapping = {
  "SDGZ": {
    "name": "Gezira",
    "slug": "gezira"
  },
  "SDNB": {
    "name": "Blue Nile",
    "slug": "blue-nile"
  },
  "SDDC": {
    "name": "Central Darfur",
    "slug": "central-darfur"
  },
  "SDDE": {
    "name": "East Darfur",
    "slug": "east-darfur"
  },
  "SDGD": {
    "name": "Gedaref",
    "slug": "gedaref"
  },
  "SDKA": {
    "name": "Kassala",
    "slug": "kassala"
  },
  "SDKH": {
    "name": "Khartoum",
    "slug": "khartoum"
  },
  "SDDN": {
    "name": "North Darfur",
    "slug": "north-darfur"
  },
  "SDKN": {
    "name": "North Kordofan",
    "slug": "north-kordofan"
  },
  "SDNO": {
    "name": "Northern",
    "slug": "northern"
  },
  "SDRS": {
    "name": "Red Sea",
    "slug": "red-sea"
  },
  "SDNR": {
    "name": "River Nile",
    "slug": "river-nile"
  },
  "SDSI": {
    "name": "Sennar",
    "slug": "sennar"
  },
  "SDDS": {
    "name": "South Darfur",
    "slug": "south-darfur"
  },
  "SDKS": {
    "name": "South Kordofan",
    "slug": "south-kordofan"
  },
  "SDDW": {
    "name": "West Darfur",
    "slug": "west-darfur"
  },
  "SDGK": {
    "name": "West Kordofan",
    "slug": "west-kordofan"
  },
  "SDNW": {
    "name": "White Nile",
    "slug": "white-nile"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return sdnSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return sdnSvgToSlugMapping[regionId];
}
