// SVG region mapping for Senegal
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const senSvgToSlugMapping: RegionMapping = {
  "SNKE": {
    "name": "Kédougou",
    "slug": "kdougou"
  },
  "SNTC": {
    "name": "Tambacounda",
    "slug": "tambacounda"
  },
  "SNKD": {
    "name": "Kolda",
    "slug": "kolda"
  },
  "SNSE": {
    "name": "Sédhiou",
    "slug": "sdhiou"
  },
  "SNZG": {
    "name": "Ziguinchor",
    "slug": "ziguinchor"
  },
  "SNSL": {
    "name": "Saint-Louis",
    "slug": "saint-louis"
  },
  "SNMT": {
    "name": "Matam",
    "slug": "matam"
  },
  "SNKA": {
    "name": "Kaffrine",
    "slug": "kaffrine"
  },
  "SNKL": {
    "name": "Kaolack",
    "slug": "kaolack"
  },
  "SNFK": {
    "name": "Fatick",
    "slug": "fatick"
  },
  "SNLG": {
    "name": "Louga",
    "slug": "louga"
  },
  "SNTH": {
    "name": "Thiès",
    "slug": "this"
  },
  "SNDK": {
    "name": "Dakar",
    "slug": "dakar"
  },
  "SNDB": {
    "name": "Diourbel",
    "slug": "diourbel"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return senSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return senSvgToSlugMapping[regionId];
}
