// SVG region mapping for Singapore
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const sgpSvgToSlugMapping: RegionMapping = {
  "SG05": {
    "name": "South West",
    "slug": "south-west"
  },
  "SG01": {
    "name": "Central Singapore",
    "slug": "central-singapore"
  },
  "SG04": {
    "name": "South East",
    "slug": "south-east"
  },
  "SG02": {
    "name": "North East",
    "slug": "north-east"
  },
  "SG03": {
    "name": "North West",
    "slug": "north-west"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return sgpSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return sgpSvgToSlugMapping[regionId];
}
