// SVG region mapping for Solomon Islands
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const slbSvgToSlugMapping: RegionMapping = {
  "SBRB": {
    "name": "Rennell and Bellona",
    "slug": "rennell-and-bellona"
  },
  "SBMK": {
    "name": "Makira",
    "slug": "makira"
  },
  "SBTE": {
    "name": "Temotu",
    "slug": "temotu"
  },
  "SBML": {
    "name": "Malaita",
    "slug": "malaita"
  },
  "SBCT": {
    "name": "Capital Territory (Honiara)",
    "slug": "capital-territory-honiara"
  },
  "SBGU": {
    "name": "Guadalcanal",
    "slug": "guadalcanal"
  },
  "SBCE": {
    "name": "Central",
    "slug": "central"
  },
  "SBWE": {
    "name": "Western",
    "slug": "western"
  },
  "SBIS": {
    "name": "Isabel",
    "slug": "isabel"
  },
  "SBCH": {
    "name": "Choiseul",
    "slug": "choiseul"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return slbSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return slbSvgToSlugMapping[regionId];
}
