// SVG region mapping for Sierra Leone
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const sleSvgToSlugMapping: RegionMapping = {
  "SLNW": {
    "name": "Northern Western",
    "slug": "northern-western"
  },
  "SLE": {
    "name": "Eastern",
    "slug": "eastern"
  },
  "SLS": {
    "name": "Eastern",
    "slug": "eastern"
  },
  "SLW": {
    "name": "Western",
    "slug": "western"
  },
  "SLN": {
    "name": "Eastern",
    "slug": "eastern"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return sleSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return sleSvgToSlugMapping[regionId];
}
