// SVG region mapping for El Salvador
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const slvSvgToSlugMapping: RegionMapping = {
  "SVAH": {
    "name": "Ahuachapán",
    "slug": "ahuachapn"
  },
  "SVSA": {
    "name": "Santa Ana",
    "slug": "santa-ana"
  },
  "SVCH": {
    "name": "Chalatenango",
    "slug": "chalatenango"
  },
  "SVCA": {
    "name": "Cabañas",
    "slug": "cabaas"
  },
  "SVMO": {
    "name": "Morazán",
    "slug": "morazn"
  },
  "SVSM": {
    "name": "San Miguel",
    "slug": "san-miguel"
  },
  "SVUN": {
    "name": "La Unión",
    "slug": "la-unin"
  },
  "SVSO": {
    "name": "Sonsonate",
    "slug": "sonsonate"
  },
  "SVLI": {
    "name": "La Libertad",
    "slug": "la-libertad"
  },
  "SVPA": {
    "name": "La Paz",
    "slug": "la-paz"
  },
  "SVSV": {
    "name": "San Vicente",
    "slug": "san-vicente"
  },
  "SVUS": {
    "name": "Usulután",
    "slug": "usulutn"
  },
  "SVCU": {
    "name": "Cuscatlán",
    "slug": "cuscatln"
  },
  "SVSS": {
    "name": "San Salvador",
    "slug": "san-salvador"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return slvSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return slvSvgToSlugMapping[regionId];
}
