// SVG region mapping for Somalia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const somSvgToSlugMapping: RegionMapping = {
  "SOAW": {
    "name": "Awdal",
    "slug": "awdal"
  },
  "SOBK": {
    "name": "Bakool",
    "slug": "bakool"
  },
  "SOBN": {
    "name": "Banadir",
    "slug": "banadir"
  },
  "SOBR": {
    "name": "Bari",
    "slug": "bari"
  },
  "SOBY": {
    "name": "BY",
    "slug": "by"
  },
  "SOGA": {
    "name": "Galgaduud",
    "slug": "galgaduud"
  },
  "SOGE": {
    "name": "Gedo",
    "slug": "gedo"
  },
  "SOHI": {
    "name": "Hiraan",
    "slug": "hiraan"
  },
  "SOJD": {
    "name": "Middle Juba",
    "slug": "middle-juba"
  },
  "SOJH": {
    "name": "Lower Juba",
    "slug": "lower-juba"
  },
  "SOMU": {
    "name": "Mudug",
    "slug": "mudug"
  },
  "SONU": {
    "name": "Nugaal",
    "slug": "nugaal"
  },
  "SOSD": {
    "name": "Middle Shabelle",
    "slug": "middle-shabelle"
  },
  "SOSH": {
    "name": "Lower Shabelle",
    "slug": "lower-shabelle"
  },
  "SOWO": {
    "name": "Woqooyi Galbeed",
    "slug": "woqooyi-galbeed"
  },
  "SOTO": {
    "name": "Togdheer",
    "slug": "togdheer"
  },
  "SOSO": {
    "name": "Sool",
    "slug": "sool"
  },
  "SOSA": {
    "name": "Sanaag",
    "slug": "sanaag"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return somSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return somSvgToSlugMapping[regionId];
}
