// SVG region mapping for Serbia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const srbSvgToSlugMapping: RegionMapping = {
  "RS01": {
    "name": "Severno-Backi",
    "slug": "severno-backi"
  },
  "RS05": {
    "name": "Zapadno-Backi",
    "slug": "zapadno-backi"
  },
  "RS03": {
    "name": "Severno-Banatski",
    "slug": "severno-banatski"
  },
  "RS24": {
    "name": "Pcinjski",
    "slug": "pcinjski"
  },
  "RS14": {
    "name": "Borski",
    "slug": "borski"
  },
  "RS15": {
    "name": "Zajecarski",
    "slug": "zajecarski"
  },
  "RS22": {
    "name": "Pirotski",
    "slug": "pirotski"
  },
  "RS23": {
    "name": "Jablanicki",
    "slug": "jablanicki"
  },
  "RS18": {
    "name": "Raški",
    "slug": "raki"
  },
  "RS19": {
    "name": "Pomoravski",
    "slug": "pomoravski"
  },
  "RS21": {
    "name": "Toplicki",
    "slug": "toplicki"
  },
  "RS16": {
    "name": "Zlatiborski",
    "slug": "zlatiborski"
  },
  "RS07": {
    "name": "Sremski",
    "slug": "sremski"
  },
  "RS08": {
    "name": "Macvanski",
    "slug": "macvanski"
  },
  "RS06": {
    "name": "Južno-Backi",
    "slug": "juno-backi"
  },
  "RS02": {
    "name": "Srednje-Banatski",
    "slug": "srednje-banatski"
  },
  "RS04": {
    "name": "Južno-Banatski",
    "slug": "juno-banatski"
  },
  "RS11": {
    "name": "Branicevski",
    "slug": "branicevski"
  },
  "RS00": {
    "name": "Grad Beograd",
    "slug": "grad-beograd"
  },
  "RS10": {
    "name": "Podunavski",
    "slug": "podunavski"
  },
  "RS20": {
    "name": "Nišavski",
    "slug": "niavski"
  },
  "RS13": {
    "name": "Pomoravski",
    "slug": "pomoravski"
  },
  "RS12": {
    "name": "Šumadijski",
    "slug": "umadijski"
  },
  "RS17": {
    "name": "Moravicki",
    "slug": "moravicki"
  },
  "RS09": {
    "name": "Kolubarski",
    "slug": "kolubarski"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return srbSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return srbSvgToSlugMapping[regionId];
}
