// SVG region mapping for South Sudan
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const ssdSvgToSlugMapping: RegionMapping = {
  "SSEE": {
    "name": "Eastern Equatoria",
    "slug": "eastern-equatoria"
  },
  "SSBW": {
    "name": "Western Bahr el Ghazal",
    "slug": "western-bahr-el-ghazal"
  },
  "SSEW": {
    "name": "Western Equatoria",
    "slug": "western-equatoria"
  },
  "SSEC": {
    "name": "Central Equatoria",
    "slug": "central-equatoria"
  },
  "SSNU": {
    "name": "Upper Nile",
    "slug": "upper-nile"
  },
  "SSJG": {
    "name": "Jonglei",
    "slug": "jonglei"
  },
  "SSUY": {
    "name": "Unity",
    "slug": "unity"
  },
  "SSBN": {
    "name": "Northern Bahr el Ghazal",
    "slug": "northern-bahr-el-ghazal"
  },
  "SSLK": {
    "name": "Lakes",
    "slug": "lakes"
  },
  "SSWR": {
    "name": "Warrap",
    "slug": "warrap"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return ssdSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return ssdSvgToSlugMapping[regionId];
}
