// SVG region mapping for Sao Tome and Principe
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const stpSvgToSlugMapping: RegionMapping = {
  "STP": {
    "name": "Pague",
    "slug": "pague"
  },
  "ST01": {
    "name": "Água Grande",
    "slug": "gua-grande"
  },
  "ST02": {
    "name": "Cantagalo",
    "slug": "cantagalo"
  },
  "ST03": {
    "name": "Caué",
    "slug": "cau"
  },
  "ST04": {
    "name": "Lembá",
    "slug": "lemb"
  },
  "ST05": {
    "name": "Lobata",
    "slug": "lobata"
  },
  "ST06": {
    "name": "Mé-Zóchi",
    "slug": "m-zchi"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return stpSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return stpSvgToSlugMapping[regionId];
}
