// SVG region mapping for Suriname
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const surSvgToSlugMapping: RegionMapping = {
  "SRSI": {
    "name": "Sipaliwini",
    "slug": "sipaliwini"
  },
  "SRNI": {
    "name": "Nickerie",
    "slug": "nickerie"
  },
  "SRMA": {
    "name": "Marowijne",
    "slug": "marowijne"
  },
  "SRCR": {
    "name": "Coronie",
    "slug": "coronie"
  },
  "SRSA": {
    "name": "Saramacca",
    "slug": "saramacca"
  },
  "SRWA": {
    "name": "Wanica",
    "slug": "wanica"
  },
  "SRPM": {
    "name": "Paramaribo",
    "slug": "paramaribo"
  },
  "SRCM": {
    "name": "Commewijne",
    "slug": "commewijne"
  },
  "SRPR": {
    "name": "Para",
    "slug": "para"
  },
  "SRBR": {
    "name": "Brokopondo",
    "slug": "brokopondo"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return surSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return surSvgToSlugMapping[regionId];
}
