// SVG region mapping for Slovakia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const svkSvgToSlugMapping: RegionMapping = {
  "SKZI": {
    "name": "Žilinský",
    "slug": "ilinsk"
  },
  "SKPV": {
    "name": "Prešov",
    "slug": "preov"
  },
  "SKKI": {
    "name": "Košický",
    "slug": "koick"
  },
  "SKBL": {
    "name": "Bratislavský",
    "slug": "bratislavsk"
  },
  "SKTA": {
    "name": "Trnavský",
    "slug": "trnavsk"
  },
  "SKTC": {
    "name": "Trenciansky",
    "slug": "trenciansky"
  },
  "SKBC": {
    "name": "Banskobystrický",
    "slug": "banskobystrick"
  },
  "SKNI": {
    "name": "Nitriansky",
    "slug": "nitriansky"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return svkSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return svkSvgToSlugMapping[regionId];
}
