// SVG region mapping for Slovenia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const svnSvgToSlugMapping: RegionMapping = {
  "SI090": {
    "name": "Piran",
    "slug": "piran"
  },
  "SI078": {
    "name": "Moravske Toplice",
    "slug": "moravske-toplice"
  },
  "SI033": {
    "name": "Šalovci",
    "slug": "alovci"
  },
  "SI161": {
    "name": "Hodoš",
    "slug": "hodo"
  },
  "SI031": {
    "name": "Gornji Petrovci",
    "slug": "gornji-petrovci"
  },
  "SI056": {
    "name": "Kuzma",
    "slug": "kuzma"
  },
  "SI059": {
    "name": "Lendava",
    "slug": "lendava"
  },
  "SI156": {
    "name": "Dobrovnik",
    "slug": "dobrovnik"
  },
  "SI047": {
    "name": "Kobilje",
    "slug": "kobilje"
  },
  "SI053": {
    "name": "Kranjska Gora",
    "slug": "kranjska-gora"
  },
  "SI006": {
    "name": "Bovec",
    "slug": "bovec"
  },
  "SI046": {
    "name": "Kobarid",
    "slug": "kobarid"
  },
  "SI128": {
    "name": "Tolmin",
    "slug": "tolmin"
  },
  "SI044": {
    "name": "Kanal",
    "slug": "kanal"
  },
  "SI007": {
    "name": "Brda",
    "slug": "brda"
  },
  "SI084": {
    "name": "Nova Goriška",
    "slug": "nova-gorika"
  },
  "SI183": {
    "name": "Šempeter-Vrtojba",
    "slug": "empeter-vrtojba"
  },
  "SI075": {
    "name": "Miren-Kostanjevica",
    "slug": "miren-kostanjevica"
  },
  "SI049": {
    "name": "Komen",
    "slug": "komen"
  },
  "SI111": {
    "name": "Sežana",
    "slug": "seana"
  },
  "SI035": {
    "name": "Hrpelje-Kozina",
    "slug": "hrpelje-kozina"
  },
  "SI213": {
    "name": "Ankaran",
    "slug": "ankaran"
  },
  "SI105": {
    "name": "Rogašovci",
    "slug": "rogaovci"
  },
  "SI029": {
    "name": "Gornja Radgona",
    "slug": "gornja-radgona"
  },
  "SI195": {
    "name": "Apace",
    "slug": "apace"
  },
  "SI118": {
    "name": "Šentilj",
    "slug": "entilj"
  },
  "SI055": {
    "name": "Kungota",
    "slug": "kungota"
  },
  "SI070": {
    "name": "Maribor",
    "slug": "maribor"
  },
  "SI178": {
    "name": "Selnica ob Dravi",
    "slug": "selnica-ob-dravi"
  },
  "SI101": {
    "name": "Radlje ob Dravi",
    "slug": "radlje-ob-dravi"
  },
  "SI081": {
    "name": "Muta",
    "slug": "muta"
  },
  "SI025": {
    "name": "Dravograd",
    "slug": "dravograd"
  },
  "SI093": {
    "name": "Podvelka",
    "slug": "podvelka"
  },
  "SI103": {
    "name": "Ravne na Koroškem",
    "slug": "ravne-na-korokem"
  },
  "SI175": {
    "name": "Prevalje",
    "slug": "prevalje"
  },
  "SI074": {
    "name": "Mežica",
    "slug": "meica"
  },
  "SI016": {
    "name": "Črna na Koroškem",
    "slug": "rna-na-korokem"
  },
  "SI131": {
    "name": "Tržič",
    "slug": "tri"
  },
  "SI192": {
    "name": "Žirovnica",
    "slug": "irovnica"
  },
  "SI041": {
    "name": "Jesenice",
    "slug": "jesenice"
  },
  "SI180": {
    "name": "Solcava",
    "slug": "solcava"
  },
  "SI163": {
    "name": "Jezersko",
    "slug": "jezersko"
  },
  "SI015": {
    "name": "Črenšovci",
    "slug": "renovci"
  },
  "SI063": {
    "name": "Ljutomer",
    "slug": "ljutomer"
  },
  "SI176": {
    "name": "Razkrižje",
    "slug": "razkrije"
  },
  "SI202": {
    "name": "Središče ob Dravi",
    "slug": "sredie-ob-dravi"
  },
  "SI143": {
    "name": "Zavrc",
    "slug": "zavrc"
  },
  "SI196": {
    "name": "Cirkulane",
    "slug": "cirkulane"
  },
  "SI135": {
    "name": "Videm",
    "slug": "videm"
  },
  "SI172": {
    "name": "Podlehnik",
    "slug": "podlehnik"
  },
  "SI191": {
    "name": "Žetale",
    "slug": "etale"
  },
  "SI107": {
    "name": "Rogatec",
    "slug": "rogatec"
  },
  "SI106": {
    "name": "Rogaška Slatina",
    "slug": "rogaka-slatina"
  },
  "SI149": {
    "name": "Bistrica ob Sotli",
    "slug": "bistrica-ob-sotli"
  },
  "SI092": {
    "name": "Podcetrtek",
    "slug": "podcetrtek"
  },
  "SI009": {
    "name": "Brežice",
    "slug": "breice"
  },
  "SI054": {
    "name": "Krško",
    "slug": "krko"
  },
  "SI119": {
    "name": "Šentjernej",
    "slug": "entjernej"
  },
  "SI203": {
    "name": "Straža",
    "slug": "straa"
  },
  "SI073": {
    "name": "Metlika",
    "slug": "metlika"
  },
  "SI017": {
    "name": "Crnomelj",
    "slug": "crnomelj"
  },
  "SI048": {
    "name": "Kocevje",
    "slug": "kocevje"
  },
  "SI088": {
    "name": "Osilnica",
    "slug": "osilnica"
  },
  "SI066": {
    "name": "Loški Potok",
    "slug": "loki-potok"
  },
  "SI065": {
    "name": "Loška dolina",
    "slug": "loka-dolina"
  },
  "SI038": {
    "name": "Ilirska Bistrica",
    "slug": "ilirska-bistrica"
  },
  "SI040": {
    "name": "Izola",
    "slug": "izola"
  },
  "SI089": {
    "name": "Pesnica",
    "slug": "pesnica"
  },
  "SI026": {
    "name": "Duplek",
    "slug": "duplek"
  },
  "SI169": {
    "name": "Miklavž na Dravskem polju",
    "slug": "miklav-na-dravskem-polju"
  },
  "SI160": {
    "name": "Hoce-Slivnica",
    "slug": "hoce-slivnica"
  },
  "SI058": {
    "name": "Lenart",
    "slug": "lenart"
  },
  "SI181": {
    "name": "Sveta Ana",
    "slug": "sveta-ana"
  },
  "SI167": {
    "name": "Lovrenc na Pohorju",
    "slug": "lovrenc-na-pohorju"
  },
  "SI177": {
    "name": "Ribnica na Pohorju",
    "slug": "ribnica-na-pohorju"
  },
  "SI112": {
    "name": "Slovenj Gradec",
    "slug": "slovenj-gradec"
  },
  "SI141": {
    "name": "Vuzenica",
    "slug": "vuzenica"
  },
  "SI095": {
    "name": "Preddvor",
    "slug": "preddvor"
  },
  "SI117": {
    "name": "Šenčur",
    "slug": "enur"
  },
  "SI012": {
    "name": "Cerklje na Gorenjskem",
    "slug": "cerklje-na-gorenjskem"
  },
  "SI043": {
    "name": "Kamnik",
    "slug": "kamnik"
  },
  "SI071": {
    "name": "Medvode",
    "slug": "medvode"
  },
  "SI052": {
    "name": "Kranj",
    "slug": "kranj"
  },
  "SI122": {
    "name": "Škofja Loka",
    "slug": "kofja-loka"
  },
  "SI146": {
    "name": "Železniki",
    "slug": "elezniki"
  },
  "SI004": {
    "name": "Bohinj",
    "slug": "bohinj"
  },
  "SI082": {
    "name": "Naklo",
    "slug": "naklo"
  },
  "SI102": {
    "name": "Radovljica",
    "slug": "radovljica"
  },
  "SI126": {
    "name": "Šoštanj",
    "slug": "otanj"
  },
  "SI062": {
    "name": "Ljubno",
    "slug": "ljubno"
  },
  "SI067": {
    "name": "Luce",
    "slug": "luce"
  },
  "SI068": {
    "name": "Lukovica",
    "slug": "lukovica"
  },
  "SI148": {
    "name": "Benedikt",
    "slug": "benedikt"
  },
  "SI057": {
    "name": "Laško",
    "slug": "lako"
  },
  "SI154": {
    "name": "Dobje",
    "slug": "dobje"
  },
  "SI108": {
    "name": "Ruše",
    "slug": "rue"
  },
  "SI138": {
    "name": "Vodice",
    "slug": "vodice"
  },
  "SI164": {
    "name": "Komenda",
    "slug": "komenda"
  },
  "SI072": {
    "name": "Mengeš",
    "slug": "menge"
  },
  "SI140": {
    "name": "Vrhnika",
    "slug": "vrhnika"
  },
  "SI162": {
    "name": "Horjul",
    "slug": "horjul"
  },
  "SI153": {
    "name": "Cerkvenjak",
    "slug": "cerkvenjak"
  },
  "SI186": {
    "name": "Trzin",
    "slug": "trzin"
  },
  "SI097": {
    "name": "Puconci",
    "slug": "puconci"
  },
  "SI158": {
    "name": "Grad",
    "slug": "grad"
  },
  "SI080": {
    "name": "Murska Sobota",
    "slug": "murska-sobota"
  },
  "SI182": {
    "name": "Sveti Andraž v Slovenskih Goricah",
    "slug": "sveti-andra-v-slovenskih-goricah"
  },
  "SI008": {
    "name": "Brezovica",
    "slug": "brezovica"
  },
  "SI021": {
    "name": "Dobrova-Polhov Gradec",
    "slug": "dobrova-polhov-gradec"
  },
  "SI027": {
    "name": "Gorenja vas-Poljane",
    "slug": "gorenja-vas-poljane"
  },
  "SI064": {
    "name": "Logatec",
    "slug": "logatec"
  },
  "SI185": {
    "name": "Trnovska vas",
    "slug": "trnovska-vas"
  },
  "SI018": {
    "name": "Destrnik",
    "slug": "destrnik"
  },
  "SI098": {
    "name": "Race-Fram",
    "slug": "race-fram"
  },
  "SI115": {
    "name": "Starše",
    "slug": "stare"
  },
  "SI189": {
    "name": "Vransko",
    "slug": "vransko"
  },
  "SI133": {
    "name": "Velenje",
    "slug": "velenje"
  },
  "SI173": {
    "name": "Polzela",
    "slug": "polzela"
  },
  "SI125": {
    "name": "Šmartno ob Paki",
    "slug": "martno-ob-paki"
  },
  "SI209": {
    "name": "Rečica ob Savinji",
    "slug": "reica-ob-savinji"
  },
  "SI137": {
    "name": "Vitanje",
    "slug": "vitanje"
  },
  "SI139": {
    "name": "Vojnik",
    "slug": "vojnik"
  },
  "SI144": {
    "name": "Zrece",
    "slug": "zrece"
  },
  "SI076": {
    "name": "Mislinja",
    "slug": "mislinja"
  },
  "SI142": {
    "name": "Zagorje ob Savi",
    "slug": "zagorje-ob-savi"
  },
  "SI060": {
    "name": "Litija",
    "slug": "litija"
  },
  "SI030": {
    "name": "Gornji Grad",
    "slug": "gornji-grad"
  },
  "SI013": {
    "name": "Cerknica",
    "slug": "cerknica"
  },
  "SI134": {
    "name": "Velike Lašče",
    "slug": "velike-lae"
  },
  "SI005": {
    "name": "Borovnica",
    "slug": "borovnica"
  },
  "SI094": {
    "name": "Postojna",
    "slug": "postojna"
  },
  "SI091": {
    "name": "Pivka",
    "slug": "pivka"
  },
  "SI155": {
    "name": "Dobrna",
    "slug": "dobrna"
  },
  "SI011": {
    "name": "Celje",
    "slug": "celje"
  },
  "SI083": {
    "name": "Nazarje",
    "slug": "nazarje"
  },
  "SI023": {
    "name": "Domžale",
    "slug": "domale"
  },
  "SI039": {
    "name": "Ivancna Gorica",
    "slug": "ivancna-gorica"
  },
  "SI061": {
    "name": "Ljubljana",
    "slug": "ljubljana"
  },
  "SI194": {
    "name": "Šmartno in Litiji",
    "slug": "martno-in-litiji"
  },
  "SI037": {
    "name": "037",
    "slug": "037"
  },
  "SI022": {
    "name": "Dol pri Ljubljani",
    "slug": "dol-pri-ljubljani"
  },
  "SI174": {
    "name": "Prebold",
    "slug": "prebold"
  },
  "SI077": {
    "name": "Moravce",
    "slug": "moravce"
  },
  "SI020": {
    "name": "Dobrepolje",
    "slug": "dobrepolje"
  },
  "SI099": {
    "name": "Radece",
    "slug": "radece"
  },
  "SI127": {
    "name": "Štore",
    "slug": "tore"
  },
  "SI114": {
    "name": "Slovenske Konjice",
    "slug": "slovenske-konjice"
  },
  "SI147": {
    "name": "Žiri",
    "slug": "iri"
  },
  "SI171": {
    "name": "Oplotnica",
    "slug": "oplotnica"
  },
  "SI014": {
    "name": "Cerkno",
    "slug": "cerkno"
  },
  "SI207": {
    "name": "Gorje",
    "slug": "gorje"
  },
  "SI001": {
    "name": "Ajdovščina",
    "slug": "ajdovina"
  },
  "SI019": {
    "name": "Divaca",
    "slug": "divaca"
  },
  "SI036": {
    "name": "Idrija",
    "slug": "idrija"
  },
  "SI136": {
    "name": "Vipava",
    "slug": "vipava"
  },
  "SI150": {
    "name": "Bloke",
    "slug": "bloke"
  },
  "SI120": {
    "name": "Šentjur pri Celju",
    "slug": "entjur-pri-celju"
  },
  "SI051": {
    "name": "Kozje",
    "slug": "kozje"
  },
  "SI124": {
    "name": "Šmarje pri Jelšah",
    "slug": "marje-pri-jelah"
  },
  "SI110": {
    "name": "Sevnica",
    "slug": "sevnica"
  },
  "SI170": {
    "name": "Mirna Pec",
    "slug": "mirna-pec"
  },
  "SI199": {
    "name": "Mokronog-Trebelno",
    "slug": "mokronog-trebelno"
  },
  "SI193": {
    "name": "Žužemberk",
    "slug": "uemberk"
  },
  "SI132": {
    "name": "Turnišče",
    "slug": "turnie"
  },
  "SI100": {
    "name": "Radenci",
    "slug": "radenci"
  },
  "SI116": {
    "name": "Sveti Jurij",
    "slug": "sveti-jurij"
  },
  "SI187": {
    "name": "Velika Polana",
    "slug": "velika-polana"
  },
  "SI002": {
    "name": "Beltinci",
    "slug": "beltinci"
  },
  "SI188": {
    "name": "Veržej",
    "slug": "verej"
  },
  "SI086": {
    "name": "Odranci",
    "slug": "odranci"
  },
  "SI032": {
    "name": "Grosuplje",
    "slug": "grosuplje"
  },
  "SI123": {
    "name": "Škofljica",
    "slug": "kofljica"
  },
  "SI034": {
    "name": "Hrastnik",
    "slug": "hrastnik"
  },
  "SI190": {
    "name": "Žalec",
    "slug": "alec"
  },
  "SI129": {
    "name": "Trbovlje",
    "slug": "trbovlje"
  },
  "SI151": {
    "name": "Braslovce",
    "slug": "braslovce"
  },
  "SI184": {
    "name": "Tabor",
    "slug": "tabor"
  },
  "SI159": {
    "name": "Hajdina",
    "slug": "hajdina"
  },
  "SI096": {
    "name": "Ptuj",
    "slug": "ptuj"
  },
  "SI069": {
    "name": "Majšperk",
    "slug": "majperk"
  },
  "SI198": {
    "name": "Makole",
    "slug": "makole"
  },
  "SI168": {
    "name": "Markovci",
    "slug": "markovci"
  },
  "SI045": {
    "name": "Kidricevo",
    "slug": "kidricevo"
  },
  "SI024": {
    "name": "Dornava",
    "slug": "dornava"
  },
  "SI166": {
    "name": "Križevci",
    "slug": "krievci"
  },
  "SI042": {
    "name": "Juršinci",
    "slug": "jurinci"
  },
  "SI109": {
    "name": "Semic",
    "slug": "semic"
  },
  "SI157": {
    "name": "Dolenjske Toplice",
    "slug": "dolenjske-toplice"
  },
  "SI179": {
    "name": "Sodražica",
    "slug": "sodraica"
  },
  "SI104": {
    "name": "Ribnica",
    "slug": "ribnica"
  },
  "SI121": {
    "name": "Škocjan",
    "slug": "kocjan"
  },
  "SI050": {
    "name": "Koper",
    "slug": "koper"
  },
  "SI028": {
    "name": "Gorišnica",
    "slug": "gorinica"
  },
  "SI197": {
    "name": "Kostanjevica",
    "slug": "kostanjevica"
  },
  "SI113": {
    "name": "Slovenska Bistrica",
    "slug": "slovenska-bistrica"
  },
  "SI130": {
    "name": "Trebnje",
    "slug": "trebnje"
  },
  "SI200": {
    "name": "Poljčane",
    "slug": "poljane"
  },
  "SI201": {
    "name": "Renče-Vogrsko",
    "slug": "rene-vogrsko"
  },
  "SI087": {
    "name": "Ormož",
    "slug": "ormo"
  },
  "SI085": {
    "name": "Novo Mesto",
    "slug": "novo-mesto"
  },
  "SI204": {
    "name": "Sveta Trojica v Slovenskih goricah",
    "slug": "sveta-trojica-v-slovenskih-goricah"
  },
  "SI205": {
    "name": "Sveti Tomaž",
    "slug": "sveti-toma"
  },
  "SI206": {
    "name": "Šmarješke Toplice",
    "slug": "marjeke-toplice"
  },
  "SI003": {
    "name": "Bled",
    "slug": "bled"
  },
  "SI208": {
    "name": "Log-Dragomer",
    "slug": "log-dragomer"
  },
  "SI079": {
    "name": "Mozirje",
    "slug": "mozirje"
  },
  "SI210": {
    "name": "Sveti Jurij v Slovenskih goricah",
    "slug": "sveti-jurij-v-slovenskih-goricah"
  },
  "SI211": {
    "name": "Šentrupert",
    "slug": "entrupert"
  },
  "SI212": {
    "name": "Mirna",
    "slug": "mirna"
  },
  "SI010": {
    "name": "Tišina",
    "slug": "tiina"
  },
  "SI165": {
    "name": "Kostel",
    "slug": "kostel"
  },
  "SI152": {
    "name": "Cankova",
    "slug": "cankova"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return svnSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return svnSvgToSlugMapping[regionId];
}
