// SVG region mapping for Sweden
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const sweSvgToSlugMapping: RegionMapping = {
  "SEBD": {
    "name": "Norrbotten",
    "slug": "norrbotten"
  },
  "SEAC": {
    "name": "Västerbotten",
    "slug": "vsterbotten"
  },
  "SEZ": {
    "name": "Gaza",
    "slug": "gaza"
  },
  "SEW": {
    "name": "W",
    "slug": "w"
  },
  "SES": {
    "name": "Alvsborgs Lan",
    "slug": "alvsborgs-lan"
  },
  "SEO": {
    "name": "Alvsborgs Lan",
    "slug": "alvsborgs-lan"
  },
  "SEY": {
    "name": "Y",
    "slug": "y"
  },
  "SEX": {
    "name": "X",
    "slug": "x"
  },
  "SEC": {
    "name": "Stockholm",
    "slug": "stockholm"
  },
  "SEAB": {
    "name": "Stockholm",
    "slug": "stockholm"
  },
  "SED": {
    "name": "Angermanland",
    "slug": "angermanland"
  },
  "SEE": {
    "name": "Angermanland",
    "slug": "angermanland"
  },
  "SEH": {
    "name": "Bohuslan",
    "slug": "bohuslan"
  },
  "SEK": {
    "name": "Blekinge",
    "slug": "blekinge"
  },
  "SEM": {
    "name": "Angermanland",
    "slug": "angermanland"
  },
  "SEN": {
    "name": "Alvsborgs Lan",
    "slug": "alvsborgs-lan"
  },
  "SEI": {
    "name": "Blekinge",
    "slug": "blekinge"
  },
  "SEU": {
    "name": "Bohuslan",
    "slug": "bohuslan"
  },
  "SEF": {
    "name": "F",
    "slug": "f"
  },
  "SET": {
    "name": "Gotland",
    "slug": "gotland"
  },
  "SEG": {
    "name": "Alvsborgs Lan",
    "slug": "alvsborgs-lan"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return sweSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return sweSvgToSlugMapping[regionId];
}
