// SVG region mapping for Sweden
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const sweSvgToSlugMapping: RegionMapping = {
  "SEAB": {
    "name": "Stockholm",
    "slug": "stockholm"
  },
  "SEAC": {
    "name": "Västerbotten",
    "slug": "vasterbotten"
  },
  "SEBD": {
    "name": "Norrbotten",
    "slug": "norrbotten"
  },
  "SEC": {
    "name": "Uppsala",
    "slug": "uppsala"
  },
  "SED": {
    "name": "Södermanland",
    "slug": "sodermanland"
  },
  "SEE": {
    "name": "Östergötland",
    "slug": "ostergotland"
  },
  "SEF": {
    "name": "Jönköping",
    "slug": "jonkoping"
  },
  "SEG": {
    "name": "Kronoberg",
    "slug": "kronoberg"
  },
  "SEH": {
    "name": "Kalmar",
    "slug": "kalmar"
  },
  "SEI": {
    "name": "Gotland",
    "slug": "gotland"
  },
  "SEK": {
    "name": "Blekinge",
    "slug": "blekinge"
  },
  "SEM": {
    "name": "Skåne",
    "slug": "skane"
  },
  "SEN": {
    "name": "Halland",
    "slug": "halland"
  },
  "SEO": {
    "name": "Västra Götaland",
    "slug": "vastra-gotaland"
  },
  "SES": {
    "name": "Värmland",
    "slug": "varmland"
  },
  "SET": {
    "name": "Orebro",
    "slug": "orebro"
  },
  "SEU": {
    "name": "Västmanland",
    "slug": "vastmanland"
  },
  "SEW": {
    "name": "Dalarna",
    "slug": "dalarna"
  },
  "SEX": {
    "name": "Gävleborg",
    "slug": "gavleborg"
  },
  "SEY": {
    "name": "Västernorrland",
    "slug": "vasternorrland"
  },
  "SEZ": {
    "name": "Jämtland",
    "slug": "jamtland"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return sweSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return sweSvgToSlugMapping[regionId];
}
