// SVG region mapping for Eswatini
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const swzSvgToSlugMapping: RegionMapping = {
  "SZLU": {
    "name": "Lubombo",
    "slug": "lubombo"
  },
  "SZHH": {
    "name": "Hhohho",
    "slug": "hhohho"
  },
  "SZMA": {
    "name": "Manzini",
    "slug": "manzini"
  },
  "SZSH": {
    "name": "Shiselweni",
    "slug": "shiselweni"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return swzSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return swzSvgToSlugMapping[regionId];
}
