// SVG region mapping for Seychelles
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const sycSvgToSlugMapping: RegionMapping = {
  "SC15": {
    "name": "La Digue",
    "slug": "la-digue"
  },
  "SC01": {
    "name": "Anse Aux Pins",
    "slug": "anse-aux-pins"
  },
  "SC02": {
    "name": "Anse Boileau",
    "slug": "anse-boileau"
  },
  "SC04": {
    "name": "Au Cap",
    "slug": "au-cap"
  },
  "SC03": {
    "name": "Anse Etoile",
    "slug": "anse-etoile"
  },
  "SC05": {
    "name": "Anse Royale",
    "slug": "anse-royale"
  },
  "SC09": {
    "name": "Bel Air",
    "slug": "bel-air"
  },
  "SC06": {
    "name": "Baie Lazare",
    "slug": "baie-lazare"
  },
  "SC10": {
    "name": "Belombre",
    "slug": "belombre"
  },
  "SC08": {
    "name": "Beau Vallon",
    "slug": "beau-vallon"
  },
  "SC11": {
    "name": "Cascade",
    "slug": "cascade"
  },
  "SC12": {
    "name": "Glacis",
    "slug": "glacis"
  },
  "SC13": {
    "name": "Grand Anse Mahe",
    "slug": "grand-anse-mahe"
  },
  "SC24": {
    "name": "Les Mamelles",
    "slug": "les-mamelles"
  },
  "SC17": {
    "name": "Mont Buxton",
    "slug": "mont-buxton"
  },
  "SC18": {
    "name": "Mont Fleuri",
    "slug": "mont-fleuri"
  },
  "SC19": {
    "name": "Plaisance",
    "slug": "plaisance"
  },
  "SC21": {
    "name": "Port Glaud",
    "slug": "port-glaud"
  },
  "SC20": {
    "name": "Pointe Larue",
    "slug": "pointe-larue"
  },
  "SC25": {
    "name": "Roche Caiman",
    "slug": "roche-caiman"
  },
  "SC22": {
    "name": "Saint Louis",
    "slug": "saint-louis"
  },
  "SC23": {
    "name": "Takamaka",
    "slug": "takamaka"
  },
  "SC07": {
    "name": "Baie Sainte Anne",
    "slug": "baie-sainte-anne"
  },
  "SC14": {
    "name": "Grand Anse Praslin",
    "slug": "grand-anse-praslin"
  },
  "SC26": {
    "name": "Other Islands",
    "slug": "other-islands"
  },
  "SC16": {
    "name": "English River",
    "slug": "english-river"
  },
  "SC27": {
    "name": "Perseverance Island",
    "slug": "perseverance-island"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return sycSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return sycSvgToSlugMapping[regionId];
}
