// SVG region mapping for Syria
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const syrSvgToSlugMapping: RegionMapping = {
  "SYHI": {
    "name": "Homs (Hims)",
    "slug": "homs-hims"
  },
  "SYTA": {
    "name": "Tartus",
    "slug": "tartus"
  },
  "SYRD": {
    "name": "Rif Dimashq",
    "slug": "rif-dimashq"
  },
  "SYHA": {
    "name": "Hasaka (Al Haksa)",
    "slug": "hasaka-al-haksa"
  },
  "SYRA": {
    "name": "Ar Raqqah",
    "slug": "ar-raqqah"
  },
  "SYHL": {
    "name": "Aleppo",
    "slug": "aleppo"
  },
  "SYID": {
    "name": "Idlib",
    "slug": "idlib"
  },
  "SYLA": {
    "name": "Lattakia",
    "slug": "lattakia"
  },
  "SYSU": {
    "name": "As Suwayda'",
    "slug": "as-suwayda"
  },
  "SYDR": {
    "name": "Dar`a",
    "slug": "dara"
  },
  "SYDY": {
    "name": "Dayr Az Zawr",
    "slug": "dayr-az-zawr"
  },
  "SYQU": {
    "name": "Quneitra",
    "slug": "quneitra"
  },
  "SYHM": {
    "name": "Hamah",
    "slug": "hamah"
  },
  "SYDI": {
    "name": "Damascus",
    "slug": "damascus"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return syrSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return syrSvgToSlugMapping[regionId];
}
