// SVG region mapping for Turks and Caicos Islands
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const tcaSvgToSlugMapping: RegionMapping = {
  "TCX03": {
    "name": "Providenciales and West Caicos",
    "slug": "providenciales-and-west-caicos"
  },
  "TCX04": {
    "name": "South Caicos and East Caicos",
    "slug": "south-caicos-and-east-caicos"
  },
  "TCX01": {
    "name": "Middle Caicos",
    "slug": "middle-caicos"
  },
  "TCX02": {
    "name": "North Caicos",
    "slug": "north-caicos"
  },
  "TCX05": {
    "name": "Grand Turk",
    "slug": "grand-turk"
  },
  "TCX06": {
    "name": "Salt Cay",
    "slug": "salt-cay"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return tcaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return tcaSvgToSlugMapping[regionId];
}
