// SVG region mapping for Chad
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const tcdSvgToSlugMapping: RegionMapping = {
  "TDBA": {
    "name": "Batha",
    "slug": "batha"
  },
  "TDBO": {
    "name": "Borkou",
    "slug": "borkou"
  },
  "TDCB": {
    "name": "Chari-Baguirmi",
    "slug": "chari-baguirmi"
  },
  "TDGR": {
    "name": "Guéra",
    "slug": "gura"
  },
  "TDHL": {
    "name": "Hadjer-Lamis",
    "slug": "hadjer-lamis"
  },
  "TDKA": {
    "name": "Kanem",
    "slug": "kanem"
  },
  "TDLC": {
    "name": "LC",
    "slug": "lc"
  },
  "TDLO": {
    "name": "Logone Occidental",
    "slug": "logone-occidental"
  },
  "TDLR": {
    "name": "Logone Oriental",
    "slug": "logone-oriental"
  },
  "TDMA": {
    "name": "Mandoul",
    "slug": "mandoul"
  },
  "TDME": {
    "name": "Mayo-Kebbi Est",
    "slug": "mayo-kebbi-est"
  },
  "TDMO": {
    "name": "Mayo-Kebbi Ouest",
    "slug": "mayo-kebbi-ouest"
  },
  "TDMC": {
    "name": "Moyen-Chari",
    "slug": "moyen-chari"
  },
  "TDOD": {
    "name": "Ouaddaï",
    "slug": "ouadda"
  },
  "TDSA": {
    "name": "Salamat",
    "slug": "salamat"
  },
  "TDTA": {
    "name": "Tandjilé",
    "slug": "tandjil"
  },
  "TDWF": {
    "name": "Wadi Fira",
    "slug": "wadi-fira"
  },
  "TDND": {
    "name": "N'Djamena",
    "slug": "ndjamena"
  },
  "TDBG": {
    "name": "Barh-El-Gazel",
    "slug": "barh-el-gazel"
  },
  "TDEE": {
    "name": "Ennedi Est",
    "slug": "ennedi-est"
  },
  "TDSI": {
    "name": "Sila",
    "slug": "sila"
  },
  "TDTI": {
    "name": "Tibesti",
    "slug": "tibesti"
  },
  "TDEO": {
    "name": "Ennedi Ouest",
    "slug": "ennedi-ouest"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return tcdSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return tcdSvgToSlugMapping[regionId];
}
