// SVG region mapping for Togo
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const tgoSvgToSlugMapping: RegionMapping = {
  "TGS": {
    "name": "Savanes",
    "slug": "savanes"
  },
  "TGK": {
    "name": "Kara",
    "slug": "kara"
  },
  "TGC": {
    "name": "Centre",
    "slug": "centre"
  },
  "TGP": {
    "name": "Plateaux",
    "slug": "plateaux"
  },
  "TGM": {
    "name": "Maritime",
    "slug": "maritime"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return tgoSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return tgoSvgToSlugMapping[regionId];
}
