// SVG region mapping for Thailand
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const thaSvgToSlugMapping: RegionMapping = {
  "TH32": {
    "name": "Surin",
    "slug": "surin"
  },
  "TH33": {
    "name": "Si Sa Ket",
    "slug": "si-sa-ket"
  },
  "TH34": {
    "name": "Ubon Ratchathani",
    "slug": "ubon-ratchathani"
  },
  "TH27": {
    "name": "Sa Kaeo",
    "slug": "sa-kaeo"
  },
  "TH31": {
    "name": "Buri Ram",
    "slug": "buri-ram"
  },
  "TH23": {
    "name": "Trat",
    "slug": "trat"
  },
  "TH22": {
    "name": "Chanthaburi",
    "slug": "chanthaburi"
  },
  "TH91": {
    "name": "Satun",
    "slug": "satun"
  },
  "TH90": {
    "name": "Songkhla",
    "slug": "songkhla"
  },
  "TH95": {
    "name": "Yala",
    "slug": "yala"
  },
  "TH96": {
    "name": "Narathiwat",
    "slug": "narathiwat"
  },
  "TH57": {
    "name": "Chiang Rai",
    "slug": "chiang-rai"
  },
  "TH50": {
    "name": "Chiang Mai",
    "slug": "chiang-mai"
  },
  "TH58": {
    "name": "Mae Hong Son",
    "slug": "mae-hong-son"
  },
  "TH63": {
    "name": "63",
    "slug": "63"
  },
  "TH71": {
    "name": "Kanchanaburi",
    "slug": "kanchanaburi"
  },
  "TH77": {
    "name": "Prachuap Khiri Khan",
    "slug": "prachuap-khiri-khan"
  },
  "TH76": {
    "name": "Phetchaburi",
    "slug": "phetchaburi"
  },
  "TH70": {
    "name": "Ratchaburi",
    "slug": "ratchaburi"
  },
  "TH86": {
    "name": "Chumphon",
    "slug": "chumphon"
  },
  "TH85": {
    "name": "Ranong",
    "slug": "ranong"
  },
  "TH56": {
    "name": "Phayao",
    "slug": "phayao"
  },
  "TH55": {
    "name": "55",
    "slug": "55"
  },
  "TH53": {
    "name": "Uttaradit",
    "slug": "uttaradit"
  },
  "TH65": {
    "name": "Phitsanulok",
    "slug": "phitsanulok"
  },
  "TH42": {
    "name": "Loei",
    "slug": "loei"
  },
  "TH38": {
    "name": "Bueng Kan",
    "slug": "bueng-kan"
  },
  "TH43": {
    "name": "Nong Khai",
    "slug": "nong-khai"
  },
  "TH48": {
    "name": "Nakhon Phanom",
    "slug": "nakhon-phanom"
  },
  "TH49": {
    "name": "Mukdahan",
    "slug": "mukdahan"
  },
  "TH37": {
    "name": "Amnat Charoen",
    "slug": "amnat-charoen"
  },
  "TH82": {
    "name": "Phangnga",
    "slug": "phangnga"
  },
  "TH81": {
    "name": "Krabi",
    "slug": "krabi"
  },
  "TH92": {
    "name": "Trang",
    "slug": "trang"
  },
  "TH94": {
    "name": "Pattani",
    "slug": "pattani"
  },
  "TH93": {
    "name": "Phatthalung",
    "slug": "phatthalung"
  },
  "TH80": {
    "name": "Nakhon Si Thammarat",
    "slug": "nakhon-si-thammarat"
  },
  "TH84": {
    "name": "Surat Thani",
    "slug": "surat-thani"
  },
  "TH75": {
    "name": "Samut Songkhram",
    "slug": "samut-songkhram"
  },
  "TH74": {
    "name": "Samut Sakhon",
    "slug": "samut-sakhon"
  },
  "TH10": {
    "name": "Bangkok Metropolis",
    "slug": "bangkok-metropolis"
  },
  "TH11": {
    "name": "Samut Prakan",
    "slug": "samut-prakan"
  },
  "TH24": {
    "name": "Chachoengsao",
    "slug": "chachoengsao"
  },
  "THS": {
    "name": "Chachoengsao",
    "slug": "chachoengsao"
  },
  "TH21": {
    "name": "Rayong",
    "slug": "rayong"
  },
  "TH83": {
    "name": "Phuket",
    "slug": "phuket"
  },
  "TH40": {
    "name": "Khon Kaen",
    "slug": "khon-kaen"
  },
  "TH47": {
    "name": "Sakon Nakhon",
    "slug": "sakon-nakhon"
  },
  "TH72": {
    "name": "Suphan Buri",
    "slug": "suphan-buri"
  },
  "TH17": {
    "name": "Sing Buri",
    "slug": "sing-buri"
  },
  "TH18": {
    "name": "Chai Nat",
    "slug": "chai-nat"
  },
  "TH15": {
    "name": "Ang Thong",
    "slug": "ang-thong"
  },
  "TH19": {
    "name": "Saraburi",
    "slug": "saraburi"
  },
  "TH30": {
    "name": "Nakhon Ratchasima",
    "slug": "nakhon-ratchasima"
  },
  "TH26": {
    "name": "Nakhon Nayok",
    "slug": "nakhon-nayok"
  },
  "TH13": {
    "name": "Pathum Thani",
    "slug": "pathum-thani"
  },
  "TH61": {
    "name": "Uthai Thani",
    "slug": "uthai-thani"
  },
  "TH46": {
    "name": "Kalasin",
    "slug": "kalasin"
  },
  "TH45": {
    "name": "Roi Et",
    "slug": "roi-et"
  },
  "TH44": {
    "name": "Maha Sarakham",
    "slug": "maha-sarakham"
  },
  "TH39": {
    "name": "Nong Bua Lam Phu",
    "slug": "nong-bua-lam-phu"
  },
  "TH16": {
    "name": "Lop Buri",
    "slug": "lop-buri"
  },
  "TH41": {
    "name": "Udon Thani",
    "slug": "udon-thani"
  },
  "TH14": {
    "name": "Phra Nakhon Si Ayutthaya",
    "slug": "phra-nakhon-si-ayutthaya"
  },
  "TH12": {
    "name": "Nonthaburi",
    "slug": "nonthaburi"
  },
  "TH73": {
    "name": "Nakhon Pathom",
    "slug": "nakhon-pathom"
  },
  "TH62": {
    "name": "Kamphaeng Phet",
    "slug": "kamphaeng-phet"
  },
  "TH52": {
    "name": "Lampang",
    "slug": "lampang"
  },
  "TH64": {
    "name": "Sukhothai",
    "slug": "sukhothai"
  },
  "TH60": {
    "name": "Nakhon Sawan",
    "slug": "nakhon-sawan"
  },
  "TH67": {
    "name": "Phetchabun",
    "slug": "phetchabun"
  },
  "TH66": {
    "name": "Phichit",
    "slug": "phichit"
  },
  "TH36": {
    "name": "Chaiyaphum",
    "slug": "chaiyaphum"
  },
  "TH54": {
    "name": "Phrae",
    "slug": "phrae"
  },
  "TH51": {
    "name": "Lamphun",
    "slug": "lamphun"
  },
  "TH25": {
    "name": "Prachin Buri",
    "slug": "prachin-buri"
  },
  "TH35": {
    "name": "Yasothon",
    "slug": "yasothon"
  },
  "TH20": {
    "name": "Chon Buri",
    "slug": "chon-buri"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return thaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return thaSvgToSlugMapping[regionId];
}
