// SVG region mapping for Tajikistan
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const tjkSvgToSlugMapping: RegionMapping = {
  "TJSU": {
    "name": "Leninabad",
    "slug": "leninabad"
  },
  "TJRA": {
    "name": "Tadzhikistan Territories",
    "slug": "tadzhikistan-territories"
  },
  "TJGB": {
    "name": "Gorno-Badakhshan",
    "slug": "gorno-badakhshan"
  },
  "TJKT": {
    "name": "Khatlon",
    "slug": "khatlon"
  },
  "TJDU": {
    "name": "Dushanbe",
    "slug": "dushanbe"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return tjkSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return tjkSvgToSlugMapping[regionId];
}
