// SVG region mapping for Turkmenistan
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const tkmSvgToSlugMapping: RegionMapping = {
  "TMD": {
    "name": "Dasoguz",
    "slug": "dasoguz"
  },
  "TML": {
    "name": "Ahal",
    "slug": "ahal"
  },
  "TMM": {
    "name": "Mari",
    "slug": "mari"
  },
  "TMA": {
    "name": "Ahal",
    "slug": "ahal"
  },
  "TMB": {
    "name": "Asgabat",
    "slug": "asgabat"
  },
  "TMS": {
    "name": "Asgabat",
    "slug": "asgabat"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return tkmSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return tkmSvgToSlugMapping[regionId];
}
