// SVG region mapping for Timor-Leste
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const tlsSvgToSlugMapping: RegionMapping = {
  "TLOE": {
    "name": "Ambeno",
    "slug": "ambeno"
  },
  "TLBO": {
    "name": "Bobonaro",
    "slug": "bobonaro"
  },
  "TLCO": {
    "name": "Cova Lima",
    "slug": "cova-lima"
  },
  "TLAN": {
    "name": "Ainaro",
    "slug": "ainaro"
  },
  "TLMF": {
    "name": "Manufahi",
    "slug": "manufahi"
  },
  "TLMT": {
    "name": "Manatuto",
    "slug": "manatuto"
  },
  "TLVI": {
    "name": "Viqueque",
    "slug": "viqueque"
  },
  "TLLA": {
    "name": "Lautém",
    "slug": "lautm"
  },
  "TLBA": {
    "name": "Baucau",
    "slug": "baucau"
  },
  "TLDI": {
    "name": "Dili",
    "slug": "dili"
  },
  "TLLI": {
    "name": "Liquica",
    "slug": "liquica"
  },
  "TLER": {
    "name": "Ermera",
    "slug": "ermera"
  },
  "TLAL": {
    "name": "Aileu",
    "slug": "aileu"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return tlsSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return tlsSvgToSlugMapping[regionId];
}
