// SVG region mapping for Tonga
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const tonSvgToSlugMapping: RegionMapping = {
  "TO05": {
    "name": "Vava'u",
    "slug": "vavau"
  },
  "TO01": {
    "name": "01",
    "slug": "01"
  },
  "TO04": {
    "name": "Tongatapu",
    "slug": "tongatapu"
  },
  "TO02": {
    "name": "Ha'apai",
    "slug": "haapai"
  },
  "TO03": {
    "name": "Niuas",
    "slug": "niuas"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return tonSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return tonSvgToSlugMapping[regionId];
}
