// SVG region mapping for Trinidad and Tobago
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const ttoSvgToSlugMapping: RegionMapping = {
  "TTARI": {
    "name": "Arima",
    "slug": "arima"
  },
  "TTCHA": {
    "name": "Chaguanas",
    "slug": "chaguanas"
  },
  "TTCTT": {
    "name": "Couva-Tabaquite-Talparo",
    "slug": "couva-tabaquite-talparo"
  },
  "TTDMN": {
    "name": "Diego Martin",
    "slug": "diego-martin"
  },
  "TTMRC": {
    "name": "Mayaro/Rio Claro",
    "slug": "mayarorio-claro"
  },
  "TTPED": {
    "name": "Penal-Debe",
    "slug": "penal-debe"
  },
  "TTPTF": {
    "name": "Point Fortin",
    "slug": "point-fortin"
  },
  "TTPOS": {
    "name": "Port of Spain",
    "slug": "port-of-spain"
  },
  "TTPRT": {
    "name": "Princes Town",
    "slug": "princes-town"
  },
  "TTSFO": {
    "name": "San Fernando",
    "slug": "san-fernando"
  },
  "TTSJL": {
    "name": "San Juan-Laventille",
    "slug": "san-juan-laventille"
  },
  "TTSGE": {
    "name": "Sangre Grande",
    "slug": "sangre-grande"
  },
  "TTSIP": {
    "name": "Siparia",
    "slug": "siparia"
  },
  "TTTOB": {
    "name": "Tobago",
    "slug": "tobago"
  },
  "TTTUP": {
    "name": "Tunapuna/Piarco",
    "slug": "tunapunapiarco"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return ttoSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return ttoSvgToSlugMapping[regionId];
}
