// SVG region mapping for Tunisia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const tunSvgToSlugMapping: RegionMapping = {
  "TN83": {
    "name": "Tataouine",
    "slug": "tataouine"
  },
  "TN81": {
    "name": "Gabès",
    "slug": "gabs"
  },
  "TN82": {
    "name": "Médenine",
    "slug": "mdenine"
  },
  "TN72": {
    "name": "Tozeur",
    "slug": "tozeur"
  },
  "TN73": {
    "name": "Kebili",
    "slug": "kebili"
  },
  "TN71": {
    "name": "Gafsa",
    "slug": "gafsa"
  },
  "TN12": {
    "name": "Ariana",
    "slug": "ariana"
  },
  "TN13": {
    "name": "Ben Arous",
    "slug": "ben-arous"
  },
  "TN23": {
    "name": "Bizerte",
    "slug": "bizerte"
  },
  "TN11": {
    "name": "Tunis",
    "slug": "tunis"
  },
  "TN22": {
    "name": "Zaghouan",
    "slug": "zaghouan"
  },
  "TN14": {
    "name": "Manubah",
    "slug": "manubah"
  },
  "TN21": {
    "name": "Nabeul",
    "slug": "nabeul"
  },
  "TN33": {
    "name": "Le Kef",
    "slug": "le-kef"
  },
  "TN31": {
    "name": "Béja",
    "slug": "bja"
  },
  "TN32": {
    "name": "Jendouba",
    "slug": "jendouba"
  },
  "TN34": {
    "name": "Siliana",
    "slug": "siliana"
  },
  "TN52": {
    "name": "Monastir",
    "slug": "monastir"
  },
  "TN53": {
    "name": "Mahdia",
    "slug": "mahdia"
  },
  "TN51": {
    "name": "Sousse",
    "slug": "sousse"
  },
  "TN61": {
    "name": "Sfax",
    "slug": "sfax"
  },
  "TN42": {
    "name": "Kassérine",
    "slug": "kassrine"
  },
  "TN41": {
    "name": "Kairouan",
    "slug": "kairouan"
  },
  "TN43": {
    "name": "Sidi Bou Zid",
    "slug": "sidi-bou-zid"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return tunSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return tunSvgToSlugMapping[regionId];
}
