// SVG region mapping for Türkiye
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const turSvgToSlugMapping: RegionMapping = {
  "TR75": {
    "name": "Ardahan",
    "slug": "ardahan"
  },
  "TR08": {
    "name": "Artvin",
    "slug": "artvin"
  },
  "TR73": {
    "name": "Sirnak",
    "slug": "sirnak"
  },
  "TR30": {
    "name": "Hakkari",
    "slug": "hakkari"
  },
  "TR76": {
    "name": "Iğdir",
    "slug": "idir"
  },
  "TR04": {
    "name": "Agri",
    "slug": "agri"
  },
  "TR65": {
    "name": "Van",
    "slug": "van"
  },
  "TR39": {
    "name": "Kirklareli",
    "slug": "kirklareli"
  },
  "TR22": {
    "name": "Edirne",
    "slug": "edirne"
  },
  "TR36": {
    "name": "Kars",
    "slug": "kars"
  },
  "TR47": {
    "name": "Mardin",
    "slug": "mardin"
  },
  "TR63": {
    "name": "Sanliurfa",
    "slug": "sanliurfa"
  },
  "TR79": {
    "name": "Kilis",
    "slug": "kilis"
  },
  "TR27": {
    "name": "Gaziantep",
    "slug": "gaziantep"
  },
  "TR31": {
    "name": "Hatay",
    "slug": "hatay"
  },
  "TR34": {
    "name": "Istanbul",
    "slug": "istanbul"
  },
  "TR59": {
    "name": "Tekirdag",
    "slug": "tekirdag"
  },
  "TR17": {
    "name": "Çanakkale",
    "slug": "anakkale"
  },
  "TR53": {
    "name": "Rize",
    "slug": "rize"
  },
  "TR61": {
    "name": "Trabzon",
    "slug": "trabzon"
  },
  "TR28": {
    "name": "Giresun",
    "slug": "giresun"
  },
  "TR52": {
    "name": "Ordu",
    "slug": "ordu"
  },
  "TR55": {
    "name": "Samsun",
    "slug": "samsun"
  },
  "TR57": {
    "name": "Sinop",
    "slug": "sinop"
  },
  "TR37": {
    "name": "Kastamonu",
    "slug": "kastamonu"
  },
  "TR74": {
    "name": "Bartın",
    "slug": "bartn"
  },
  "TR67": {
    "name": "Zinguldak",
    "slug": "zinguldak"
  },
  "TR81": {
    "name": "Düzce",
    "slug": "dzce"
  },
  "TR54": {
    "name": "Sakarya",
    "slug": "sakarya"
  },
  "TR41": {
    "name": "Kocaeli",
    "slug": "kocaeli"
  },
  "TR77": {
    "name": "Yalova",
    "slug": "yalova"
  },
  "TR16": {
    "name": "Bursa",
    "slug": "bursa"
  },
  "TR10": {
    "name": "Balikesir",
    "slug": "balikesir"
  },
  "TR35": {
    "name": "Izmir",
    "slug": "izmir"
  },
  "TR09": {
    "name": "Aydin",
    "slug": "aydin"
  },
  "TR48": {
    "name": "Mugla",
    "slug": "mugla"
  },
  "TR07": {
    "name": "Antalya",
    "slug": "antalya"
  },
  "TR33": {
    "name": "Mersin",
    "slug": "mersin"
  },
  "TR01": {
    "name": "Adana",
    "slug": "adana"
  },
  "TR14": {
    "name": "Bolu",
    "slug": "bolu"
  },
  "TR06": {
    "name": "Ankara",
    "slug": "ankara"
  },
  "TR11": {
    "name": "Bilecik",
    "slug": "bilecik"
  },
  "TR26": {
    "name": "Eskisehir",
    "slug": "eskisehir"
  },
  "TR18": {
    "name": "Çankiri",
    "slug": "ankiri"
  },
  "TR78": {
    "name": "Karabük",
    "slug": "karabk"
  },
  "TR60": {
    "name": "Tokat",
    "slug": "tokat"
  },
  "TR58": {
    "name": "Sivas",
    "slug": "sivas"
  },
  "TR19": {
    "name": "Çorum",
    "slug": "orum"
  },
  "TR05": {
    "name": "Amasya",
    "slug": "amasya"
  },
  "TR43": {
    "name": "Kütahya",
    "slug": "ktahya"
  },
  "TR42": {
    "name": "Konya",
    "slug": "konya"
  },
  "TR70": {
    "name": "Karaman",
    "slug": "karaman"
  },
  "TR51": {
    "name": "Nigde",
    "slug": "nigde"
  },
  "TR38": {
    "name": "Kayseri",
    "slug": "kayseri"
  },
  "TR32": {
    "name": "Isparta",
    "slug": "isparta"
  },
  "TR45": {
    "name": "Manisa",
    "slug": "manisa"
  },
  "TR20": {
    "name": "Denizli",
    "slug": "denizli"
  },
  "TR15": {
    "name": "Burdur",
    "slug": "burdur"
  },
  "TR68": {
    "name": "Aksaray",
    "slug": "aksaray"
  },
  "TR50": {
    "name": "Nevsehir",
    "slug": "nevsehir"
  },
  "TR66": {
    "name": "Yozgat",
    "slug": "yozgat"
  },
  "TR40": {
    "name": "Kirsehir",
    "slug": "kirsehir"
  },
  "TR64": {
    "name": "Usak",
    "slug": "usak"
  },
  "TR24": {
    "name": "Erzincan",
    "slug": "erzincan"
  },
  "TR62": {
    "name": "Tunceli",
    "slug": "tunceli"
  },
  "TR03": {
    "name": "Afyonkarahisar",
    "slug": "afyonkarahisar"
  },
  "TR71": {
    "name": "Kinkkale",
    "slug": "kinkkale"
  },
  "TR46": {
    "name": "K. Maras",
    "slug": "k-maras"
  },
  "TR49": {
    "name": "Mus",
    "slug": "mus"
  },
  "TR25": {
    "name": "Erzurum",
    "slug": "erzurum"
  },
  "TR44": {
    "name": "Malatya",
    "slug": "malatya"
  },
  "TR23": {
    "name": "Elazig",
    "slug": "elazig"
  },
  "TR13": {
    "name": "Bitlis",
    "slug": "bitlis"
  },
  "TR12": {
    "name": "Bingöl",
    "slug": "bingl"
  },
  "TR80": {
    "name": "Osmaniye",
    "slug": "osmaniye"
  },
  "TR02": {
    "name": "Adiyaman",
    "slug": "adiyaman"
  },
  "TR21": {
    "name": "Diyarbakir",
    "slug": "diyarbakir"
  },
  "TR72": {
    "name": "Batman",
    "slug": "batman"
  },
  "TR56": {
    "name": "Siirt",
    "slug": "siirt"
  },
  "TR69": {
    "name": "Bayburt",
    "slug": "bayburt"
  },
  "TR29": {
    "name": "Gümüshane",
    "slug": "gmshane"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return turSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return turSvgToSlugMapping[regionId];
}
