// SVG region mapping for Taiwan
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const twnSvgToSlugMapping: RegionMapping = {
  "TWKIN": {
    "name": "Kinmen",
    "slug": "kinmen"
  },
  "TWLIE": {
    "name": "Matsu Islands",
    "slug": "matsu-islands"
  },
  "TWPEN": {
    "name": "Penghu",
    "slug": "penghu"
  },
  "TWTAO": {
    "name": "Taoyuan",
    "slug": "taoyuan"
  },
  "TWHSQ": {
    "name": "Hsinchu",
    "slug": "hsinchu"
  },
  "TWHSZ": {
    "name": "Hsinchu City",
    "slug": "hsinchu-city"
  },
  "TWMIA": {
    "name": "Miaoli",
    "slug": "miaoli"
  },
  "TWTXG": {
    "name": "Taichung City",
    "slug": "taichung-city"
  },
  "TWCHA": {
    "name": "Changhua",
    "slug": "changhua"
  },
  "TWYUN": {
    "name": "Yunlin",
    "slug": "yunlin"
  },
  "TWCYQ": {
    "name": "Chiayi",
    "slug": "chiayi"
  },
  "TWTNN": {
    "name": "Tainan City",
    "slug": "tainan-city"
  },
  "TWKHH": {
    "name": "Kaohsiung City",
    "slug": "kaohsiung-city"
  },
  "TWPIF": {
    "name": "Pingtung",
    "slug": "pingtung"
  },
  "TWTTT": {
    "name": "Taitung",
    "slug": "taitung"
  },
  "TWHUA": {
    "name": "Hualien",
    "slug": "hualien"
  },
  "TWILA": {
    "name": "Yilan",
    "slug": "yilan"
  },
  "TWNWT": {
    "name": "New Taipei City",
    "slug": "new-taipei-city"
  },
  "TWKEE": {
    "name": "Keelung City",
    "slug": "keelung-city"
  },
  "TWNAN": {
    "name": "Nantou",
    "slug": "nantou"
  },
  "TWTPE": {
    "name": "Taipei City",
    "slug": "taipei-city"
  },
  "TWCYI": {
    "name": "Chiayi City",
    "slug": "chiayi-city"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return twnSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return twnSvgToSlugMapping[regionId];
}
