// SVG region mapping for Tanzania
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const tzaSvgToSlugMapping: RegionMapping = {
  "TZ01": {
    "name": "Arusha",
    "slug": "arusha"
  },
  "TZ02": {
    "name": "Dar-es-salaam",
    "slug": "dar-es-salaam"
  },
  "TZ03": {
    "name": "Dodoma",
    "slug": "dodoma"
  },
  "TZ27": {
    "name": "Geita",
    "slug": "geita"
  },
  "TZ04": {
    "name": "Iringa",
    "slug": "iringa"
  },
  "TZ05": {
    "name": "Kagera",
    "slug": "kagera"
  },
  "TZ06": {
    "name": "Kaskazini Pemba",
    "slug": "kaskazini-pemba"
  },
  "TZ07": {
    "name": "Kaskazini Unguja",
    "slug": "kaskazini-unguja"
  },
  "TZ28": {
    "name": "Katavi",
    "slug": "katavi"
  },
  "TZ08": {
    "name": "Kigoma",
    "slug": "kigoma"
  },
  "TZ09": {
    "name": "Kilimanjaro",
    "slug": "kilimanjaro"
  },
  "TZ10": {
    "name": "Kusini Pemba",
    "slug": "kusini-pemba"
  },
  "TZ11": {
    "name": "Kusini Unguja",
    "slug": "kusini-unguja"
  },
  "TZ12": {
    "name": "Lindi",
    "slug": "lindi"
  },
  "TZ26": {
    "name": "Manyara",
    "slug": "manyara"
  },
  "TZ13": {
    "name": "Mara",
    "slug": "mara"
  },
  "TZ14": {
    "name": "Mbeya",
    "slug": "mbeya"
  },
  "TZ15": {
    "name": "Mjini Magharibi",
    "slug": "mjini-magharibi"
  },
  "TZ16": {
    "name": "Morogoro",
    "slug": "morogoro"
  },
  "TZ17": {
    "name": "Mtwara",
    "slug": "mtwara"
  },
  "TZ18": {
    "name": "Mwanza",
    "slug": "mwanza"
  },
  "TZ29": {
    "name": "Njombe",
    "slug": "njombe"
  },
  "TZ19": {
    "name": "Pwani",
    "slug": "pwani"
  },
  "TZ20": {
    "name": "Rukwa",
    "slug": "rukwa"
  },
  "TZ21": {
    "name": "Ruvuma",
    "slug": "ruvuma"
  },
  "TZ22": {
    "name": "Shinyanga",
    "slug": "shinyanga"
  },
  "TZ30": {
    "name": "Simiyu",
    "slug": "simiyu"
  },
  "TZ23": {
    "name": "Singida",
    "slug": "singida"
  },
  "TZ31": {
    "name": "Songwe",
    "slug": "songwe"
  },
  "TZ24": {
    "name": "Tabora",
    "slug": "tabora"
  },
  "TZ25": {
    "name": "Tanga",
    "slug": "tanga"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return tzaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return tzaSvgToSlugMapping[regionId];
}
