// SVG region mapping for Uganda
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const ugaSvgToSlugMapping: RegionMapping = {
  "UG314": {
    "name": "Abim",
    "slug": "abim"
  },
  "UG301": {
    "name": "Adjumani",
    "slug": "adjumani"
  },
  "UG322": {
    "name": "Agago",
    "slug": "agago"
  },
  "UG323": {
    "name": "Alebtong",
    "slug": "alebtong"
  },
  "UG315": {
    "name": "Amolatar",
    "slug": "amolatar"
  },
  "UG324": {
    "name": "Amudat",
    "slug": "amudat"
  },
  "UG216": {
    "name": "Amuria",
    "slug": "amuria"
  },
  "UG316": {
    "name": "Amuru",
    "slug": "amuru"
  },
  "UG302": {
    "name": "Apac",
    "slug": "apac"
  },
  "UG303": {
    "name": "Arua",
    "slug": "arua"
  },
  "UG217": {
    "name": "Budaka",
    "slug": "budaka"
  },
  "UG218": {
    "name": "Bududa",
    "slug": "bududa"
  },
  "UG201": {
    "name": "Bugiri",
    "slug": "bugiri"
  },
  "UG235": {
    "name": "Bugweri",
    "slug": "bugweri"
  },
  "UG420": {
    "name": "Buhweju",
    "slug": "buhweju"
  },
  "UG117": {
    "name": "Buikwe",
    "slug": "buikwe"
  },
  "UG219": {
    "name": "Bukedea",
    "slug": "bukedea"
  },
  "UG118": {
    "name": "Bukomansimbi",
    "slug": "bukomansimbi"
  },
  "UG220": {
    "name": "Bukwo",
    "slug": "bukwo"
  },
  "UG225": {
    "name": "Bulambuli",
    "slug": "bulambuli"
  },
  "UG416": {
    "name": "Buliisa",
    "slug": "buliisa"
  },
  "UG401": {
    "name": "Bundibugyo",
    "slug": "bundibugyo"
  },
  "UG430": {
    "name": "Bunyangabu",
    "slug": "bunyangabu"
  },
  "UG402": {
    "name": "Bushenyi",
    "slug": "bushenyi"
  },
  "UG202": {
    "name": "Busia",
    "slug": "busia"
  },
  "UG221": {
    "name": "Butaleja",
    "slug": "butaleja"
  },
  "UG119": {
    "name": "Butambala",
    "slug": "butambala"
  },
  "UG233": {
    "name": "Butebo",
    "slug": "butebo"
  },
  "UG120": {
    "name": "Buvuma",
    "slug": "buvuma"
  },
  "UG226": {
    "name": "Buyende",
    "slug": "buyende"
  },
  "UG317": {
    "name": "Dokolo",
    "slug": "dokolo"
  },
  "UG121": {
    "name": "Gomba",
    "slug": "gomba"
  },
  "UG304": {
    "name": "Gulu",
    "slug": "gulu"
  },
  "UG403": {
    "name": "Hoima",
    "slug": "hoima"
  },
  "UG417": {
    "name": "Ibanda",
    "slug": "ibanda"
  },
  "UG203": {
    "name": "Iganga",
    "slug": "iganga"
  },
  "UG418": {
    "name": "Isingiro",
    "slug": "isingiro"
  },
  "UG204": {
    "name": "Jinja",
    "slug": "jinja"
  },
  "UG318": {
    "name": "Kaabong",
    "slug": "kaabong"
  },
  "UG404": {
    "name": "Kabale",
    "slug": "kabale"
  },
  "UG405": {
    "name": "Kabarole",
    "slug": "kabarole"
  },
  "UG213": {
    "name": "Kaberamaido",
    "slug": "kaberamaido"
  },
  "UG427": {
    "name": "Kagadi",
    "slug": "kagadi"
  },
  "UG428": {
    "name": "Kakumiro",
    "slug": "kakumiro"
  },
  "UG237": {
    "name": "Kalaki",
    "slug": "kalaki"
  },
  "UG101": {
    "name": "Kalangala",
    "slug": "kalangala"
  },
  "UG222": {
    "name": "Kaliro",
    "slug": "kaliro"
  },
  "UG122": {
    "name": "Kalungu",
    "slug": "kalungu"
  },
  "UG102": {
    "name": "Kampala",
    "slug": "kampala"
  },
  "UG205": {
    "name": "Kamuli",
    "slug": "kamuli"
  },
  "UG413": {
    "name": "Kamwenge",
    "slug": "kamwenge"
  },
  "UG414": {
    "name": "Kanungu",
    "slug": "kanungu"
  },
  "UG206": {
    "name": "Kapchorwa",
    "slug": "kapchorwa"
  },
  "UG236": {
    "name": "Kapelebyong",
    "slug": "kapelebyong"
  },
  "UG335": {
    "name": "Karenga",
    "slug": "karenga"
  },
  "UG406": {
    "name": "Kasese",
    "slug": "kasese"
  },
  "UG126": {
    "name": "Kassanda",
    "slug": "kassanda"
  },
  "UG207": {
    "name": "Katakwi",
    "slug": "katakwi"
  },
  "UG112": {
    "name": "Kayunga",
    "slug": "kayunga"
  },
  "UG433": {
    "name": "Kazo",
    "slug": "kazo"
  },
  "UG407": {
    "name": "Kibaale",
    "slug": "kibaale"
  },
  "UG103": {
    "name": "Kiboga",
    "slug": "kiboga"
  },
  "UG227": {
    "name": "Kibuku",
    "slug": "kibuku"
  },
  "UG432": {
    "name": "Kikuube",
    "slug": "kikuube"
  },
  "UG419": {
    "name": "Kiruhura",
    "slug": "kiruhura"
  },
  "UG421": {
    "name": "Kiryandongo",
    "slug": "kiryandongo"
  },
  "UG408": {
    "name": "Kisoro",
    "slug": "kisoro"
  },
  "UG434": {
    "name": "Kitagwenda",
    "slug": "kitagwenda"
  },
  "UG305": {
    "name": "Kitgum",
    "slug": "kitgum"
  },
  "UG319": {
    "name": "Koboko",
    "slug": "koboko"
  },
  "UG325": {
    "name": "Kole",
    "slug": "kole"
  },
  "UG306": {
    "name": "Kotido",
    "slug": "kotido"
  },
  "UG208": {
    "name": "Kumi",
    "slug": "kumi"
  },
  "UG333": {
    "name": "Kwania",
    "slug": "kwania"
  },
  "UG228": {
    "name": "Kween",
    "slug": "kween"
  },
  "UG123": {
    "name": "Kyankwanzi",
    "slug": "kyankwanzi"
  },
  "UG422": {
    "name": "Kyegegwa",
    "slug": "kyegegwa"
  },
  "UG415": {
    "name": "Kyenjojo",
    "slug": "kyenjojo"
  },
  "UG125": {
    "name": "Kyotera",
    "slug": "kyotera"
  },
  "UG326": {
    "name": "Lamwo",
    "slug": "lamwo"
  },
  "UG307": {
    "name": "Lira",
    "slug": "lira"
  },
  "UG229": {
    "name": "Luuka",
    "slug": "luuka"
  },
  "UG104": {
    "name": "Luwero",
    "slug": "luwero"
  },
  "UG124": {
    "name": "Lwengo",
    "slug": "lwengo"
  },
  "UG114": {
    "name": "Lyantonde",
    "slug": "lyantonde"
  },
  "UG336": {
    "name": "Madi Okollo",
    "slug": "madi-okollo"
  },
  "UG223": {
    "name": "Manafwa",
    "slug": "manafwa"
  },
  "UG320": {
    "name": "Maracha",
    "slug": "maracha"
  },
  "UG105": {
    "name": "Masaka",
    "slug": "masaka"
  },
  "UG409": {
    "name": "Masindi",
    "slug": "masindi"
  },
  "UG214": {
    "name": "Mayuge",
    "slug": "mayuge"
  },
  "UG209": {
    "name": "Mbale",
    "slug": "mbale"
  },
  "UG410": {
    "name": "Mbarara",
    "slug": "mbarara"
  },
  "UG423": {
    "name": "Mitooma",
    "slug": "mitooma"
  },
  "UG115": {
    "name": "Mityana",
    "slug": "mityana"
  },
  "UG308": {
    "name": "Moroto",
    "slug": "moroto"
  },
  "UG309": {
    "name": "Moyo",
    "slug": "moyo"
  },
  "UG106": {
    "name": "Mpigi",
    "slug": "mpigi"
  },
  "UG107": {
    "name": "Mubende",
    "slug": "mubende"
  },
  "UG108": {
    "name": "Mukono",
    "slug": "mukono"
  },
  "UG334": {
    "name": "Nabilatuk",
    "slug": "nabilatuk"
  },
  "UG311": {
    "name": "Nakapiripirit",
    "slug": "nakapiripirit"
  },
  "UG116": {
    "name": "Nakaseke",
    "slug": "nakaseke"
  },
  "UG109": {
    "name": "Nakasongola",
    "slug": "nakasongola"
  },
  "UG230": {
    "name": "Namayingo",
    "slug": "namayingo"
  },
  "UG234": {
    "name": "Namisindwa",
    "slug": "namisindwa"
  },
  "UG224": {
    "name": "Namutumba",
    "slug": "namutumba"
  },
  "UG327": {
    "name": "Napak",
    "slug": "napak"
  },
  "UG310": {
    "name": "Nebbi",
    "slug": "nebbi"
  },
  "UG231": {
    "name": "Ngora",
    "slug": "ngora"
  },
  "UG424": {
    "name": "Ntoroko",
    "slug": "ntoroko"
  },
  "UG411": {
    "name": "Ntungamo",
    "slug": "ntungamo"
  },
  "UG328": {
    "name": "Nwoya",
    "slug": "nwoya"
  },
  "UG337": {
    "name": "Obongi",
    "slug": "obongi"
  },
  "UG331": {
    "name": "Omoro",
    "slug": "omoro"
  },
  "UG329": {
    "name": "Otuke",
    "slug": "otuke"
  },
  "UG321": {
    "name": "Oyam",
    "slug": "oyam"
  },
  "UG312": {
    "name": "Pader",
    "slug": "pader"
  },
  "UG332": {
    "name": "Pakwach",
    "slug": "pakwach"
  },
  "UG210": {
    "name": "Pallisa",
    "slug": "pallisa"
  },
  "UG110": {
    "name": "Rakai",
    "slug": "rakai"
  },
  "UG429": {
    "name": "Rubanda",
    "slug": "rubanda"
  },
  "UG425": {
    "name": "Rubirizi",
    "slug": "rubirizi"
  },
  "UG431": {
    "name": "Rukiga",
    "slug": "rukiga"
  },
  "UG412": {
    "name": "Rukungiri",
    "slug": "rukungiri"
  },
  "UG435": {
    "name": "Rwampara",
    "slug": "rwampara"
  },
  "UG232": {
    "name": "Serere",
    "slug": "serere"
  },
  "UG426": {
    "name": "Sheema",
    "slug": "sheema"
  },
  "UG215": {
    "name": "Sironko",
    "slug": "sironko"
  },
  "UG211": {
    "name": "Soroti",
    "slug": "soroti"
  },
  "UG111": {
    "name": "Ssembabule",
    "slug": "ssembabule"
  },
  "UG212": {
    "name": "Tororo",
    "slug": "tororo"
  },
  "UG113": {
    "name": "Wakiso",
    "slug": "wakiso"
  },
  "UG313": {
    "name": "Yumbe",
    "slug": "yumbe"
  },
  "UG330": {
    "name": "Zombo",
    "slug": "zombo"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return ugaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return ugaSvgToSlugMapping[regionId];
}
