// SVG region mapping for Ukraine
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const ukrSvgToSlugMapping: RegionMapping = {
  "UA43": {
    "name": "Avtonomna Respublika Krym",
    "slug": "avtonomna-respublika-krym"
  },
  "UA05": {
    "name": "Vinnytska",
    "slug": "vinnytska"
  },
  "UA07": {
    "name": "Volynska",
    "slug": "volynska"
  },
  "UA12": {
    "name": "Dnipropetrovska",
    "slug": "dnipropetrovska"
  },
  "UA14": {
    "name": "Donetska",
    "slug": "donetska"
  },
  "UA18": {
    "name": "Zhytomyrska",
    "slug": "zhytomyrska"
  },
  "UA21": {
    "name": "Zakarpatska",
    "slug": "zakarpatska"
  },
  "UA23": {
    "name": "Zaporizka",
    "slug": "zaporizka"
  },
  "UA26": {
    "name": "Ivano-Frankivska",
    "slug": "ivano-frankivska"
  },
  "UA30": {
    "name": "Kyivska",
    "slug": "kyivska"
  },
  "UA35": {
    "name": "Kirovohradska",
    "slug": "kirovohradska"
  },
  "UA09": {
    "name": "Luhanska",
    "slug": "luhanska"
  },
  "UA46": {
    "name": "Lvivska",
    "slug": "lvivska"
  },
  "UA48": {
    "name": "Mykolaivska",
    "slug": "mykolaivska"
  },
  "UA51": {
    "name": "Odeska",
    "slug": "odeska"
  },
  "UA53": {
    "name": "Poltavska",
    "slug": "poltavska"
  },
  "UA56": {
    "name": "Rivnenska",
    "slug": "rivnenska"
  },
  "UA59": {
    "name": "Sumska",
    "slug": "sumska"
  },
  "UA61": {
    "name": "Ternopilska",
    "slug": "ternopilska"
  },
  "UA63": {
    "name": "Kharkivska",
    "slug": "kharkivska"
  },
  "UA65": {
    "name": "Khersonska",
    "slug": "khersonska"
  },
  "UA68": {
    "name": "Khmelnytska",
    "slug": "khmelnytska"
  },
  "UA71": {
    "name": "Cherkaska",
    "slug": "cherkaska"
  },
  "UA77": {
    "name": "Chernivetska",
    "slug": "chernivetska"
  },
  "UA74": {
    "name": "Chernihivska",
    "slug": "chernihivska"
  },
  "UA32": {
    "name": "Kyivska",
    "slug": "kyivska"
  },
  "UA40": {
    "name": "Sevastopilska",
    "slug": "sevastopilska"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return ukrSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return ukrSvgToSlugMapping[regionId];
}
