// SVG region mapping for Uruguay
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const urySvgToSlugMapping: RegionMapping = {
  "UYPA": {
    "name": "Paysandú",
    "slug": "paysand"
  },
  "UYAR": {
    "name": "Artigas",
    "slug": "artigas"
  },
  "UYSA": {
    "name": "Salto",
    "slug": "salto"
  },
  "UYRV": {
    "name": "Rivera",
    "slug": "rivera"
  },
  "UYRO": {
    "name": "Rocha",
    "slug": "rocha"
  },
  "UYTT": {
    "name": "Treinta y Tres",
    "slug": "treinta-y-tres"
  },
  "UYCL": {
    "name": "Cerro Largo",
    "slug": "cerro-largo"
  },
  "UYMA": {
    "name": "Maldonado",
    "slug": "maldonado"
  },
  "UYCA": {
    "name": "Canelones",
    "slug": "canelones"
  },
  "UYMO": {
    "name": "Montevideo",
    "slug": "montevideo"
  },
  "UYSJ": {
    "name": "San José",
    "slug": "san-jos"
  },
  "UYCO": {
    "name": "Colonia",
    "slug": "colonia"
  },
  "UYSO": {
    "name": "Soriano",
    "slug": "soriano"
  },
  "UYRN": {
    "name": "Río Negro",
    "slug": "ro-negro"
  },
  "UYTA": {
    "name": "Tacuarembó",
    "slug": "tacuaremb"
  },
  "UYDU": {
    "name": "Durazno",
    "slug": "durazno"
  },
  "UYFS": {
    "name": "Flores",
    "slug": "flores"
  },
  "UYFD": {
    "name": "Florida",
    "slug": "florida"
  },
  "UYLA": {
    "name": "Lavalleja",
    "slug": "lavalleja"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return urySvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return urySvgToSlugMapping[regionId];
}
