// SVG region mapping for United States
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const usaSvgToSlugMapping: RegionMapping = {
  "USWA": {
    "name": "Washington",
    "slug": "washington"
  },
  "USID": {
    "name": "Idaho",
    "slug": "idaho"
  },
  "USMT": {
    "name": "Montana",
    "slug": "montana"
  },
  "USND": {
    "name": "North Dakota",
    "slug": "north-dakota"
  },
  "USMN": {
    "name": "Minnesota",
    "slug": "minnesota"
  },
  "USMI": {
    "name": "Michigan",
    "slug": "michigan"
  },
  "USOH": {
    "name": "Ohio",
    "slug": "ohio"
  },
  "USPA": {
    "name": "Pennsylvania",
    "slug": "pennsylvania"
  },
  "USNY": {
    "name": "New York",
    "slug": "new-york"
  },
  "USVT": {
    "name": "Vermont",
    "slug": "vermont"
  },
  "USNH": {
    "name": "New Hampshire",
    "slug": "new-hampshire"
  },
  "USME": {
    "name": "Maine",
    "slug": "maine"
  },
  "USAZ": {
    "name": "Arizona",
    "slug": "arizona"
  },
  "USCA": {
    "name": "California",
    "slug": "california"
  },
  "USNM": {
    "name": "New Mexico",
    "slug": "new-mexico"
  },
  "USTX": {
    "name": "Texas",
    "slug": "texas"
  },
  "USAK": {
    "name": "Alaska",
    "slug": "alaska"
  },
  "USLA": {
    "name": "Louisiana",
    "slug": "louisiana"
  },
  "USMS": {
    "name": "Mississippi",
    "slug": "mississippi"
  },
  "USAL": {
    "name": "Alabama",
    "slug": "alabama"
  },
  "USFL": {
    "name": "Florida",
    "slug": "florida"
  },
  "USGA": {
    "name": "Georgia",
    "slug": "georgia"
  },
  "USSC": {
    "name": "South Carolina",
    "slug": "south-carolina"
  },
  "USNC": {
    "name": "North Carolina",
    "slug": "north-carolina"
  },
  "USVA": {
    "name": "Virginia",
    "slug": "virginia"
  },
  "USDC": {
    "name": "District of Columbia",
    "slug": "district-of-columbia"
  },
  "USMD": {
    "name": "Maryland",
    "slug": "maryland"
  },
  "USDE": {
    "name": "Delaware",
    "slug": "delaware"
  },
  "USNJ": {
    "name": "New Jersey",
    "slug": "new-jersey"
  },
  "USCT": {
    "name": "Connecticut",
    "slug": "connecticut"
  },
  "USRI": {
    "name": "Rhode Island",
    "slug": "rhode-island"
  },
  "USMA": {
    "name": "Massachusetts",
    "slug": "massachusetts"
  },
  "USOR": {
    "name": "Oregon",
    "slug": "oregon"
  },
  "USHI": {
    "name": "Hawaii",
    "slug": "hawaii"
  },
  "USUT": {
    "name": "Utah",
    "slug": "utah"
  },
  "USWY": {
    "name": "Wyoming",
    "slug": "wyoming"
  },
  "USNV": {
    "name": "Nevada",
    "slug": "nevada"
  },
  "USCO": {
    "name": "Colorado",
    "slug": "colorado"
  },
  "USSD": {
    "name": "South Dakota",
    "slug": "south-dakota"
  },
  "USNE": {
    "name": "Nebraska",
    "slug": "nebraska"
  },
  "USKS": {
    "name": "Kansas",
    "slug": "kansas"
  },
  "USOK": {
    "name": "Oklahoma",
    "slug": "oklahoma"
  },
  "USIA": {
    "name": "Iowa",
    "slug": "iowa"
  },
  "USMO": {
    "name": "Missouri",
    "slug": "missouri"
  },
  "USWI": {
    "name": "Wisconsin",
    "slug": "wisconsin"
  },
  "USIL": {
    "name": "Illinois",
    "slug": "illinois"
  },
  "USKY": {
    "name": "Kentucky",
    "slug": "kentucky"
  },
  "USAR": {
    "name": "Arkansas",
    "slug": "arkansas"
  },
  "USTN": {
    "name": "Tennessee",
    "slug": "tennessee"
  },
  "USWV": {
    "name": "West Virginia",
    "slug": "west-virginia"
  },
  "USIN": {
    "name": "Indiana",
    "slug": "indiana"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return usaSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return usaSvgToSlugMapping[regionId];
}
