// SVG region mapping for Uzbekistan
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const uzbSvgToSlugMapping: RegionMapping = {
  "UZFA": {
    "name": "Ferghana",
    "slug": "ferghana"
  },
  "UZTO": {
    "name": "Tashkent",
    "slug": "tashkent"
  },
  "UZNG": {
    "name": "Namangan",
    "slug": "namangan"
  },
  "UZAN": {
    "name": "Andijon",
    "slug": "andijon"
  },
  "UZSI": {
    "name": "Sirdaryo",
    "slug": "sirdaryo"
  },
  "UZJI": {
    "name": "Jizzakh",
    "slug": "jizzakh"
  },
  "UZSA": {
    "name": "Samarkand",
    "slug": "samarkand"
  },
  "UZQA": {
    "name": "Kashkadarya",
    "slug": "kashkadarya"
  },
  "UZSU": {
    "name": "Surkhandarya",
    "slug": "surkhandarya"
  },
  "UZQR": {
    "name": "Karakalpakstan",
    "slug": "karakalpakstan"
  },
  "UZNW": {
    "name": "Navoi",
    "slug": "navoi"
  },
  "UZXO": {
    "name": "Khorezm",
    "slug": "khorezm"
  },
  "UZBU": {
    "name": "Bukhoro",
    "slug": "bukhoro"
  },
  "UZTK": {
    "name": "Tashkent",
    "slug": "tashkent"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return uzbSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return uzbSvgToSlugMapping[regionId];
}
