// SVG region mapping for Saint Vincent and the Grenadines
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const vctSvgToSlugMapping: RegionMapping = {
  "VC06": {
    "name": "Grenadines",
    "slug": "grenadines"
  },
  "VC02": {
    "name": "Saint Andrew",
    "slug": "saint-andrew"
  },
  "VC04": {
    "name": "Saint George",
    "slug": "saint-george"
  },
  "VC01": {
    "name": "Charlotte",
    "slug": "charlotte"
  },
  "VC03": {
    "name": "Saint David",
    "slug": "saint-david"
  },
  "VC05": {
    "name": "Saint Patrick",
    "slug": "saint-patrick"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return vctSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return vctSvgToSlugMapping[regionId];
}
