// SVG region mapping for Venezuela
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const venSvgToSlugMapping: RegionMapping = {
  "VEZ": {
    "name": "Amazonas",
    "slug": "amazonas"
  },
  "VEB": {
    "name": "Anzoátegui",
    "slug": "anzoategui"
  },
  "VEC": {
    "name": "Apure",
    "slug": "apure"
  },
  "VED": {
    "name": "Aragua",
    "slug": "aragua"
  },
  "VEE": {
    "name": "Barinas",
    "slug": "barinas"
  },
  "VEF": {
    "name": "Bolívar",
    "slug": "bolivar"
  },
  "VEG": {
    "name": "Carabobo",
    "slug": "carabobo"
  },
  "VEH": {
    "name": "Cojedes",
    "slug": "cojedes"
  },
  "VEY": {
    "name": "Delta Amacuro",
    "slug": "delta-amacuro"
  },
  "VEA": {
    "name": "Distrito Capital",
    "slug": "distrito-capital"
  },
  "VEI": {
    "name": "Falcón",
    "slug": "falcon"
  },
  "VEJ": {
    "name": "Guárico",
    "slug": "guarico"
  },
  "VEX": {
    "name": "La Guaira",
    "slug": "la-guaira"
  },
  "VEK": {
    "name": "Lara",
    "slug": "lara"
  },
  "VEL": {
    "name": "Mérida",
    "slug": "merida"
  },
  "VEM": {
    "name": "Miranda",
    "slug": "miranda"
  },
  "VEN": {
    "name": "Monagas",
    "slug": "monagas"
  },
  "VEO": {
    "name": "Nueva Esparta",
    "slug": "nueva-esparta"
  },
  "VEP": {
    "name": "Portuguesa",
    "slug": "portuguesa"
  },
  "VER": {
    "name": "Sucre",
    "slug": "sucre"
  },
  "VES": {
    "name": "Táchira",
    "slug": "tachira"
  },
  "VET": {
    "name": "Trujillo",
    "slug": "trujillo"
  },
  "VEU": {
    "name": "Yaracuy",
    "slug": "yaracuy"
  },
  "VEV": {
    "name": "Zulia",
    "slug": "zulia"
  },
  "VEW": {
    "name": "Dependencias Federales",
    "slug": "dependencias-federales"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return venSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return venSvgToSlugMapping[regionId];
}
