// SVG region mapping for Venezuela
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const venSvgToSlugMapping: RegionMapping = {
  "VEZ": {
    "name": "Amazonas",
    "slug": "amazonas"
  },
  "VEB": {
    "name": "Barinas",
    "slug": "barinas"
  },
  "VEC": {
    "name": "Carabobo",
    "slug": "carabobo"
  },
  "VED": {
    "name": "Cojedes",
    "slug": "cojedes"
  },
  "VEE": {
    "name": "Anzoategui",
    "slug": "anzoategui"
  },
  "VEF": {
    "name": "Distrito Federal",
    "slug": "distrito-federal"
  },
  "VEG": {
    "name": "Anzoategui",
    "slug": "anzoategui"
  },
  "VEH": {
    "name": "Tachira",
    "slug": "tachira"
  },
  "VEY": {
    "name": "Yaracuy",
    "slug": "yaracuy"
  },
  "VEA": {
    "name": "Amazonas",
    "slug": "amazonas"
  },
  "VEI": {
    "name": "Anzoategui",
    "slug": "anzoategui"
  },
  "VEJ": {
    "name": "Cojedes",
    "slug": "cojedes"
  },
  "VEX": {
    "name": "X",
    "slug": "x"
  },
  "VEK": {
    "name": "K",
    "slug": "k"
  },
  "VEL": {
    "name": "Bolivar",
    "slug": "bolivar"
  },
  "VEM": {
    "name": "Amazonas",
    "slug": "amazonas"
  },
  "VEN": {
    "name": "Amazonas",
    "slug": "amazonas"
  },
  "VEO": {
    "name": "Amazonas",
    "slug": "amazonas"
  },
  "VEP": {
    "name": "Apure",
    "slug": "apure"
  },
  "VER": {
    "name": "Apure",
    "slug": "apure"
  },
  "VES": {
    "name": "Amazonas",
    "slug": "amazonas"
  },
  "VET": {
    "name": "Anzoategui",
    "slug": "anzoategui"
  },
  "VEU": {
    "name": "Anzoategui",
    "slug": "anzoategui"
  },
  "VEV": {
    "name": "Bolivar",
    "slug": "bolivar"
  },
  "VEW": {
    "name": "W",
    "slug": "w"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return venSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return venSvgToSlugMapping[regionId];
}
