// SVG region mapping for Virgin Islands (U.S.)
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const virSvgToSlugMapping: RegionMapping = {
  "VIX01": {
    "name": "Saint Croix",
    "slug": "saint-croix"
  },
  "VIX03": {
    "name": "Saint John",
    "slug": "saint-john"
  },
  "VIX02": {
    "name": "Saint Thomas",
    "slug": "saint-thomas"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return virSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return virSvgToSlugMapping[regionId];
}
