// SVG region mapping for Vietnam
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const vnmSvgToSlugMapping: RegionMapping = {
  "VN28": {
    "name": "Kon Tum",
    "slug": "kon-tum"
  },
  "VN72": {
    "name": "Đắk Nông",
    "slug": "k-nng"
  },
  "VN33": {
    "name": "Đắk Lắk",
    "slug": "k-lk"
  },
  "VN30": {
    "name": "Gia Lai",
    "slug": "gia-lai"
  },
  "VN58": {
    "name": "Bình Phước",
    "slug": "bnh-phc"
  },
  "VN37": {
    "name": "Tây Ninh",
    "slug": "ty-ninh"
  },
  "VN41": {
    "name": "Long An",
    "slug": "long-an"
  },
  "VN45": {
    "name": "Ðong Tháp",
    "slug": "ong-thp"
  },
  "VN44": {
    "name": "An Giang",
    "slug": "an-giang"
  },
  "VN47": {
    "name": "Kiên Giang",
    "slug": "kin-giang"
  },
  "VN71": {
    "name": "Điện Biên",
    "slug": "in-bin"
  },
  "VN05": {
    "name": "Son La",
    "slug": "son-la"
  },
  "VN21": {
    "name": "Thanh Hóa",
    "slug": "thanh-ha"
  },
  "VN22": {
    "name": "Nghệ An",
    "slug": "ngh-an"
  },
  "VN23": {
    "name": "Ha Tinh",
    "slug": "ha-tinh"
  },
  "VN24": {
    "name": "Quảng Bình",
    "slug": "qung-bnh"
  },
  "VN25": {
    "name": "Quảng Trị",
    "slug": "qung-tr"
  },
  "VN26": {
    "name": "Thừa Thiên - Huế",
    "slug": "tha-thin-hu"
  },
  "VN27": {
    "name": "Quàng Nam",
    "slug": "qung-nam"
  },
  "VN03": {
    "name": "Hà Giang",
    "slug": "h-giang"
  },
  "VN04": {
    "name": "Cao Bằng",
    "slug": "cao-bng"
  },
  "VN02": {
    "name": "Lào Cai",
    "slug": "lo-cai"
  },
  "VN01": {
    "name": "Lai Chau",
    "slug": "lai-chau"
  },
  "VN09": {
    "name": "Lạng Sơn",
    "slug": "lng-sn"
  },
  "VN13": {
    "name": "Quảng Ninh",
    "slug": "qung-ninh"
  },
  "VN52": {
    "name": "Sóc Trăng",
    "slug": "sc-trng"
  },
  "VN46": {
    "name": "Tiền Giang",
    "slug": "tin-giang"
  },
  "VN43": {
    "name": "Bà Rịa - Vũng Tàu",
    "slug": "b-ra-vng-tu"
  },
  "VNSG": {
    "name": "Hồ Chí Minh city",
    "slug": "h-ch-minh-city"
  },
  "VN34": {
    "name": "Khánh Hòa",
    "slug": "khnh-ha"
  },
  "VN59": {
    "name": "Cà Mau",
    "slug": "c-mau"
  },
  "VN55": {
    "name": "Bạc Liêu",
    "slug": "bc-liu"
  },
  "VN73": {
    "name": "Hau Giang",
    "slug": "hau-giang"
  },
  "VN49": {
    "name": "Vĩnh Long",
    "slug": "vnh-long"
  },
  "VN51": {
    "name": "Trà Vinh",
    "slug": "tr-vinh"
  },
  "VN50": {
    "name": "Bến Tre",
    "slug": "bn-tre"
  },
  "VN39": {
    "name": "Đông Nam Bộ",
    "slug": "ng-nam-b"
  },
  "VN40": {
    "name": "Bình Thuận",
    "slug": "bnh-thun"
  },
  "VN36": {
    "name": "Ninh Thuận",
    "slug": "ninh-thun"
  },
  "VN32": {
    "name": "Phú Yên",
    "slug": "ph-yn"
  },
  "VN31": {
    "name": "Bình Định",
    "slug": "bnh-nh"
  },
  "VN29": {
    "name": "Quảng Ngãi",
    "slug": "qung-ngi"
  },
  "VNDN": {
    "name": "Đà Nẵng",
    "slug": "-nng"
  },
  "VN18": {
    "name": "Ninh Bình",
    "slug": "ninh-bnh"
  },
  "VN67": {
    "name": "Nam Định",
    "slug": "nam-nh"
  },
  "VN20": {
    "name": "Thái Bình",
    "slug": "thi-bnh"
  },
  "VNHP": {
    "name": "Hải Phòng",
    "slug": "hi-phng"
  },
  "VN14": {
    "name": "Hòa Bình",
    "slug": "ha-bnh"
  },
  "VN07": {
    "name": "Tuyên Quang",
    "slug": "tuyn-quang"
  },
  "VN06": {
    "name": "Yên Bái",
    "slug": "yn-bi"
  },
  "VN70": {
    "name": "Vĩnh Phúc",
    "slug": "vnh-phc"
  },
  "VN68": {
    "name": "Phú Thọ",
    "slug": "ph-th"
  },
  "VNHN": {
    "name": "Ha Noi",
    "slug": "ha-noi"
  },
  "VN53": {
    "name": "Đông Bắc",
    "slug": "ng-bc"
  },
  "VN66": {
    "name": "Đồng Bằng Sông Hồng",
    "slug": "ng-bng-sng-hng"
  },
  "VN56": {
    "name": "Bắc Ninh",
    "slug": "bc-ninh"
  },
  "VN54": {
    "name": "Bắc Giang",
    "slug": "bc-giang"
  },
  "VN69": {
    "name": "Thái Nguyên",
    "slug": "thi-nguyn"
  },
  "VN61": {
    "name": "Hải Dương",
    "slug": "hi-dng"
  },
  "VN63": {
    "name": "Hà Nam",
    "slug": "h-nam"
  },
  "VN57": {
    "name": "Bình Dương",
    "slug": "bnh-dng"
  },
  "VN35": {
    "name": "Lâm Đồng",
    "slug": "lm-ng"
  },
  "VNCT": {
    "name": "Can Tho",
    "slug": "can-tho"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return vnmSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return vnmSvgToSlugMapping[regionId];
}
