// SVG region mapping for Vanuatu
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const vutSvgToSlugMapping: RegionMapping = {
  "VUTAE": {
    "name": "Tafea",
    "slug": "tafea"
  },
  "VUSEE": {
    "name": "Shefa",
    "slug": "shefa"
  },
  "VUMAP": {
    "name": "Malampa",
    "slug": "malampa"
  },
  "VUSAM": {
    "name": "Sanma",
    "slug": "sanma"
  },
  "VUPAM": {
    "name": "Penama",
    "slug": "penama"
  },
  "VUTOB": {
    "name": "Torba",
    "slug": "torba"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return vutSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return vutSvgToSlugMapping[regionId];
}
