// SVG region mapping for Yemen
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const yemSvgToSlugMapping: RegionMapping = {
  "YEIB": {
    "name": "Ibb",
    "slug": "ibb"
  },
  "YEAB": {
    "name": "Abyan",
    "slug": "abyan"
  },
  "YESA": {
    "name": "Sana'a City",
    "slug": "sanaa-city"
  },
  "YEBA": {
    "name": "Al Bayda",
    "slug": "al-bayda"
  },
  "YETA": {
    "name": "Ta'iz",
    "slug": "taiz"
  },
  "YEJA": {
    "name": "Al Jawf",
    "slug": "al-jawf"
  },
  "YEHJ": {
    "name": "Hajjah",
    "slug": "hajjah"
  },
  "YEHU": {
    "name": "Al Hodeidah",
    "slug": "al-hodeidah"
  },
  "YEHD": {
    "name": "Hadramawt",
    "slug": "hadramawt"
  },
  "YEDH": {
    "name": "Dhamar",
    "slug": "dhamar"
  },
  "YESH": {
    "name": "Shabwah",
    "slug": "shabwah"
  },
  "YESD": {
    "name": "Sa'dah",
    "slug": "sadah"
  },
  "YESN": {
    "name": "Sana'a",
    "slug": "sanaa"
  },
  "YEAD": {
    "name": "Aden",
    "slug": "aden"
  },
  "YELA": {
    "name": "Lahj",
    "slug": "lahj"
  },
  "YEMA": {
    "name": "Ma'rib",
    "slug": "marib"
  },
  "YEMW": {
    "name": "Al Mahwit",
    "slug": "al-mahwit"
  },
  "YEMR": {
    "name": "Al Maharah",
    "slug": "al-maharah"
  },
  "YEAM": {
    "name": "Amran",
    "slug": "amran"
  },
  "YEDA": {
    "name": "Ad Dali'",
    "slug": "ad-dali"
  },
  "YERA": {
    "name": "Raymah",
    "slug": "raymah"
  },
  "YESU": {
    "name": "Socotra",
    "slug": "socotra"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return yemSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return yemSvgToSlugMapping[regionId];
}
