// SVG region mapping for South Africa
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const zafSvgToSlugMapping: RegionMapping = {
  "ZANC": {
    "name": "Northern Cape",
    "slug": "northern-cape"
  },
  "ZAKZN": {
    "name": "KwaZulu-Natal",
    "slug": "kwazulu-natal"
  },
  "ZAFS": {
    "name": "Free State",
    "slug": "free-state"
  },
  "ZAEC": {
    "name": "Eastern Cape",
    "slug": "eastern-cape"
  },
  "ZALP": {
    "name": "Limpopo",
    "slug": "limpopo"
  },
  "ZANW": {
    "name": "North West",
    "slug": "north-west"
  },
  "ZAMP": {
    "name": "Mpumalanga",
    "slug": "mpumalanga"
  },
  "ZAWC": {
    "name": "Western Cape",
    "slug": "western-cape"
  },
  "ZAGP": {
    "name": "Gauteng",
    "slug": "gauteng"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return zafSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return zafSvgToSlugMapping[regionId];
}
