// SVG region mapping for Zambia
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const zmbSvgToSlugMapping: RegionMapping = {
  "ZM10": {
    "name": "Muchinga",
    "slug": "muchinga"
  },
  "ZM03": {
    "name": "Eastern",
    "slug": "eastern"
  },
  "ZM05": {
    "name": "Northern",
    "slug": "northern"
  },
  "ZM09": {
    "name": "Lusaka",
    "slug": "lusaka"
  },
  "ZM07": {
    "name": "Southern",
    "slug": "southern"
  },
  "ZM01": {
    "name": "Western",
    "slug": "western"
  },
  "ZM06": {
    "name": "North-Western",
    "slug": "north-western"
  },
  "ZM04": {
    "name": "Luapula",
    "slug": "luapula"
  },
  "ZM08": {
    "name": "Copperbelt",
    "slug": "copperbelt"
  },
  "ZM02": {
    "name": "Central",
    "slug": "central"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return zmbSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return zmbSvgToSlugMapping[regionId];
}
