// SVG region mapping for Zimbabwe
// Generated by scripts/download-country-svgs.ts

export interface RegionMapping {
  [regionId: string]: {
    name: string;
    slug: string;
  };
}

export const zweSvgToSlugMapping: RegionMapping = {
  "ZWMN": {
    "name": "Matabeleland North",
    "slug": "matabeleland-north"
  },
  "ZWMS": {
    "name": "Matabeleland South",
    "slug": "matabeleland-south"
  },
  "ZWMV": {
    "name": "Masvingo",
    "slug": "masvingo"
  },
  "ZWMW": {
    "name": "Mashonaland West",
    "slug": "mashonaland-west"
  },
  "ZWMC": {
    "name": "Mashonaland Central",
    "slug": "mashonaland-central"
  },
  "ZWME": {
    "name": "Mashonaland East",
    "slug": "mashonaland-east"
  },
  "ZWMA": {
    "name": "Manicaland",
    "slug": "manicaland"
  },
  "ZWMI": {
    "name": "Midlands",
    "slug": "midlands"
  },
  "ZWHA": {
    "name": "Harare",
    "slug": "harare"
  },
  "ZWBU": {
    "name": "Bulawayo",
    "slug": "bulawayo"
  }
};

export function getSvgRegionSlug(regionId: string): string | undefined {
  return zweSvgToSlugMapping[regionId]?.slug;
}

export function getSvgRegionInfo(regionId: string): { name: string; slug: string } | undefined {
  return zweSvgToSlugMapping[regionId];
}
