CREATE TABLE "species" (
	"id" serial PRIMARY KEY NOT NULL,
	"taxon_id" integer NOT NULL,
	"name" varchar(255) NOT NULL,
	"preferred_common_name" varchar(255),
	"rank" varchar(50) NOT NULL,
	"kingdom" varchar(100),
	"phylum" varchar(100),
	"class" varchar(100),
	"order" varchar(100),
	"family" varchar(100),
	"genus" varchar(100),
	"wikipedia_url" text,
	"wikipedia_summary" text,
	"observations_count" integer DEFAULT 0,
	"default_photo_url" text,
	"default_photo_attribution" text,
	"default_photo_license" varchar(50),
	"conservation_status" varchar(50),
	"conservation_status_name" varchar(100),
	"taxon_photos" jsonb,
	"establishment_means" jsonb,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "species_taxon_id_unique" UNIQUE("taxon_id")
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" serial PRIMARY KEY NOT NULL,
	"email" varchar(255) NOT NULL,
	"name" varchar(255),
	"password_hash" text,
	"provider" varchar(50),
	"provider_id" varchar(255),
	"avatar_url" text,
	"bio" text,
	"preferences" jsonb,
	"is_active" boolean DEFAULT true NOT NULL,
	"email_verified" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	"last_login_at" timestamp,
	CONSTRAINT "users_email_unique" UNIQUE("email")
);
