export interface Country {
  isoCode: string; // ISO 3166-1 alpha-3 (3 letters)
  isoCode2: string; // ISO 3166-1 alpha-2 (2 letters)
  name: string;
  slug: string;
}

export const countries: Record<string, Country> = {
  ABW: { isoCode: "ABW", isoCode2: "AW", name: "Aruba", slug: "abw" },
  AFG: { isoCode: "AFG", isoCode2: "AF", name: "Afghanistan", slug: "afg" },
  AGO: { isoCode: "AGO", isoCode2: "AO", name: "Angola", slug: "ago" },
  AIA: { isoCode: "AIA", isoCode2: "AI", name: "Anguilla", slug: "aia" },
  ALA: { isoCode: "ALA", isoCode2: "AX", name: "Åland Islands", slug: "ala" },
  ALB: { isoCode: "ALB", isoCode2: "AL", name: "Albania", slug: "alb" },
  AND: { isoCode: "AND", isoCode2: "AD", name: "Andorra", slug: "and" },
  ARE: { isoCode: "ARE", isoCode2: "AE", name: "United Arab Emirates", slug: "are" },
  ARG: { isoCode: "ARG", isoCode2: "AR", name: "Argentina", slug: "arg" },
  ARM: { isoCode: "ARM", isoCode2: "AM", name: "Armenia", slug: "arm" },
  ASM: { isoCode: "ASM", isoCode2: "AS", name: "American Samoa", slug: "asm" },
  ATA: { isoCode: "ATA", isoCode2: "AQ", name: "Antarctica", slug: "ata" },
  ATF: { isoCode: "ATF", isoCode2: "TF", name: "French Southern Territories", slug: "atf" },
  ATG: { isoCode: "ATG", isoCode2: "AG", name: "Antigua and Barbuda", slug: "atg" },
  AUS: { isoCode: "AUS", isoCode2: "AU", name: "Australia", slug: "aus" },
  AUT: { isoCode: "AUT", isoCode2: "AT", name: "Austria", slug: "aut" },
  AZE: { isoCode: "AZE", isoCode2: "AZ", name: "Azerbaijan", slug: "aze" },
  BDI: { isoCode: "BDI", isoCode2: "BI", name: "Burundi", slug: "bdi" },
  BEL: { isoCode: "BEL", isoCode2: "BE", name: "Belgium", slug: "bel" },
  BEN: { isoCode: "BEN", isoCode2: "BJ", name: "Benin", slug: "ben" },
  BES: { isoCode: "BES", isoCode2: "BQ", name: "Bonaire, Sint Eustatius and Saba", slug: "bes" },
  BFA: { isoCode: "BFA", isoCode2: "BF", name: "Burkina Faso", slug: "bfa" },
  BGD: { isoCode: "BGD", isoCode2: "BD", name: "Bangladesh", slug: "bgd" },
  BGR: { isoCode: "BGR", isoCode2: "BG", name: "Bulgaria", slug: "bgr" },
  BHR: { isoCode: "BHR", isoCode2: "BH", name: "Bahrain", slug: "bhr" },
  BHS: { isoCode: "BHS", isoCode2: "BS", name: "Bahamas", slug: "bhs" },
  BIH: { isoCode: "BIH", isoCode2: "BA", name: "Bosnia and Herzegovina", slug: "bih" },
  BLM: { isoCode: "BLM", isoCode2: "BL", name: "Saint Barthélemy", slug: "blm" },
  BLR: { isoCode: "BLR", isoCode2: "BY", name: "Belarus", slug: "blr" },
  BLZ: { isoCode: "BLZ", isoCode2: "BZ", name: "Belize", slug: "blz" },
  BMU: { isoCode: "BMU", isoCode2: "BM", name: "Bermuda", slug: "bmu" },
  BOL: { isoCode: "BOL", isoCode2: "BO", name: "Bolivia", slug: "bol" },
  BRA: { isoCode: "BRA", isoCode2: "BR", name: "Brazil", slug: "bra" },
  BRB: { isoCode: "BRB", isoCode2: "BB", name: "Barbados", slug: "brb" },
  BRN: { isoCode: "BRN", isoCode2: "BN", name: "Brunei", slug: "brn" },
  BTN: { isoCode: "BTN", isoCode2: "BT", name: "Bhutan", slug: "btn" },
  BVT: { isoCode: "BVT", isoCode2: "BV", name: "Bouvet Island", slug: "bvt" },
  BWA: { isoCode: "BWA", isoCode2: "BW", name: "Botswana", slug: "bwa" },
  CAF: { isoCode: "CAF", isoCode2: "CF", name: "Central African Republic", slug: "caf" },
  CAN: { isoCode: "CAN", isoCode2: "CA", name: "Canada", slug: "can" },
  CCK: { isoCode: "CCK", isoCode2: "CC", name: "Cocos (Keeling) Islands", slug: "cck" },
  CHE: { isoCode: "CHE", isoCode2: "CH", name: "Switzerland", slug: "che" },
  CHL: { isoCode: "CHL", isoCode2: "CL", name: "Chile", slug: "chl" },
  CHN: { isoCode: "CHN", isoCode2: "CN", name: "China", slug: "chn" },
  CIV: { isoCode: "CIV", isoCode2: "CI", name: "Côte d'Ivoire", slug: "civ" },
  CMR: { isoCode: "CMR", isoCode2: "CM", name: "Cameroon", slug: "cmr" },
  COD: { isoCode: "COD", isoCode2: "CD", name: "Congo, Democratic Republic of the", slug: "cod" },
  COG: { isoCode: "COG", isoCode2: "CG", name: "Congo", slug: "cog" },
  COK: { isoCode: "COK", isoCode2: "CK", name: "Cook Islands", slug: "cok" },
  COL: { isoCode: "COL", isoCode2: "CO", name: "Colombia", slug: "col" },
  COM: { isoCode: "COM", isoCode2: "KM", name: "Comoros", slug: "com" },
  CPV: { isoCode: "CPV", isoCode2: "CV", name: "Cabo Verde", slug: "cpv" },
  CRI: { isoCode: "CRI", isoCode2: "CR", name: "Costa Rica", slug: "cri" },
  CUB: { isoCode: "CUB", isoCode2: "CU", name: "Cuba", slug: "cub" },
  CUW: { isoCode: "CUW", isoCode2: "CW", name: "Curaçao", slug: "cuw" },
  CXR: { isoCode: "CXR", isoCode2: "CX", name: "Christmas Island", slug: "cxr" },
  CYM: { isoCode: "CYM", isoCode2: "KY", name: "Cayman Islands", slug: "cym" },
  CYP: { isoCode: "CYP", isoCode2: "CY", name: "Cyprus", slug: "cyp" },
  CZE: { isoCode: "CZE", isoCode2: "CZ", name: "Czechia", slug: "cze" },
  DEU: { isoCode: "DEU", isoCode2: "DE", name: "Germany", slug: "deu" },
  DJI: { isoCode: "DJI", isoCode2: "DJ", name: "Djibouti", slug: "dji" },
  DMA: { isoCode: "DMA", isoCode2: "DM", name: "Dominica", slug: "dma" },
  DNK: { isoCode: "DNK", isoCode2: "DK", name: "Denmark", slug: "dnk" },
  DOM: { isoCode: "DOM", isoCode2: "DO", name: "Dominican Republic", slug: "dom" },
  DZA: { isoCode: "DZA", isoCode2: "DZ", name: "Algeria", slug: "dza" },
  ECU: { isoCode: "ECU", isoCode2: "EC", name: "Ecuador", slug: "ecu" },
  EGY: { isoCode: "EGY", isoCode2: "EG", name: "Egypt", slug: "egy" },
  ERI: { isoCode: "ERI", isoCode2: "ER", name: "Eritrea", slug: "eri" },
  ESH: { isoCode: "ESH", isoCode2: "EH", name: "Western Sahara", slug: "esh" },
  ESP: { isoCode: "ESP", isoCode2: "ES", name: "Spain", slug: "esp" },
  EST: { isoCode: "EST", isoCode2: "EE", name: "Estonia", slug: "est" },
  ETH: { isoCode: "ETH", isoCode2: "ET", name: "Ethiopia", slug: "eth" },
  FIN: { isoCode: "FIN", isoCode2: "FI", name: "Finland", slug: "fin" },
  FJI: { isoCode: "FJI", isoCode2: "FJ", name: "Fiji", slug: "fji" },
  FLK: { isoCode: "FLK", isoCode2: "FK", name: "Falkland Islands", slug: "flk" },
  FRA: { isoCode: "FRA", isoCode2: "FR", name: "France", slug: "fra" },
  FRO: { isoCode: "FRO", isoCode2: "FO", name: "Faroe Islands", slug: "fro" },
  FSM: { isoCode: "FSM", isoCode2: "FM", name: "Micronesia", slug: "fsm" },
  GAB: { isoCode: "GAB", isoCode2: "GA", name: "Gabon", slug: "gab" },
  GBR: { isoCode: "GBR", isoCode2: "GB", name: "United Kingdom", slug: "gbr" },
  GEO: { isoCode: "GEO", isoCode2: "GE", name: "Georgia", slug: "geo" },
  GGY: { isoCode: "GGY", isoCode2: "GG", name: "Guernsey", slug: "ggy" },
  GHA: { isoCode: "GHA", isoCode2: "GH", name: "Ghana", slug: "gha" },
  GIB: { isoCode: "GIB", isoCode2: "GI", name: "Gibraltar", slug: "gib" },
  GIN: { isoCode: "GIN", isoCode2: "GN", name: "Guinea", slug: "gin" },
  GLP: { isoCode: "GLP", isoCode2: "GP", name: "Guadeloupe", slug: "glp" },
  GMB: { isoCode: "GMB", isoCode2: "GM", name: "Gambia", slug: "gmb" },
  GNB: { isoCode: "GNB", isoCode2: "GW", name: "Guinea-Bissau", slug: "gnb" },
  GNQ: { isoCode: "GNQ", isoCode2: "GQ", name: "Equatorial Guinea", slug: "gnq" },
  GRC: { isoCode: "GRC", isoCode2: "GR", name: "Greece", slug: "grc" },
  GRD: { isoCode: "GRD", isoCode2: "GD", name: "Grenada", slug: "grd" },
  GRL: { isoCode: "GRL", isoCode2: "GL", name: "Greenland", slug: "grl" },
  GTM: { isoCode: "GTM", isoCode2: "GT", name: "Guatemala", slug: "gtm" },
  GUF: { isoCode: "GUF", isoCode2: "GF", name: "French Guiana", slug: "guf" },
  GUM: { isoCode: "GUM", isoCode2: "GU", name: "Guam", slug: "gum" },
  GUY: { isoCode: "GUY", isoCode2: "GY", name: "Guyana", slug: "guy" },
  HKG: { isoCode: "HKG", isoCode2: "HK", name: "Hong Kong", slug: "hkg" },
  HMD: { isoCode: "HMD", isoCode2: "HM", name: "Heard Island and McDonald Islands", slug: "hmd" },
  HND: { isoCode: "HND", isoCode2: "HN", name: "Honduras", slug: "hnd" },
  HRV: { isoCode: "HRV", isoCode2: "HR", name: "Croatia", slug: "hrv" },
  HTI: { isoCode: "HTI", isoCode2: "HT", name: "Haiti", slug: "hti" },
  HUN: { isoCode: "HUN", isoCode2: "HU", name: "Hungary", slug: "hun" },
  IDN: { isoCode: "IDN", isoCode2: "ID", name: "Indonesia", slug: "idn" },
  IMN: { isoCode: "IMN", isoCode2: "IM", name: "Isle of Man", slug: "imn" },
  IND: { isoCode: "IND", isoCode2: "IN", name: "India", slug: "ind" },
  IOT: { isoCode: "IOT", isoCode2: "IO", name: "British Indian Ocean Territory", slug: "iot" },
  IRL: { isoCode: "IRL", isoCode2: "IE", name: "Ireland", slug: "irl" },
  IRN: { isoCode: "IRN", isoCode2: "IR", name: "Iran", slug: "irn" },
  IRQ: { isoCode: "IRQ", isoCode2: "IQ", name: "Iraq", slug: "irq" },
  ISL: { isoCode: "ISL", isoCode2: "IS", name: "Iceland", slug: "isl" },
  ISR: { isoCode: "ISR", isoCode2: "IL", name: "Israel", slug: "isr" },
  ITA: { isoCode: "ITA", isoCode2: "IT", name: "Italy", slug: "ita" },
  JAM: { isoCode: "JAM", isoCode2: "JM", name: "Jamaica", slug: "jam" },
  JEY: { isoCode: "JEY", isoCode2: "JE", name: "Jersey", slug: "jey" },
  JOR: { isoCode: "JOR", isoCode2: "JO", name: "Jordan", slug: "jor" },
  JPN: { isoCode: "JPN", isoCode2: "JP", name: "Japan", slug: "jpn" },
  KAZ: { isoCode: "KAZ", isoCode2: "KZ", name: "Kazakhstan", slug: "kaz" },
  KEN: { isoCode: "KEN", isoCode2: "KE", name: "Kenya", slug: "ken" },
  KGZ: { isoCode: "KGZ", isoCode2: "KG", name: "Kyrgyzstan", slug: "kgz" },
  KHM: { isoCode: "KHM", isoCode2: "KH", name: "Cambodia", slug: "khm" },
  KIR: { isoCode: "KIR", isoCode2: "KI", name: "Kiribati", slug: "kir" },
  KNA: { isoCode: "KNA", isoCode2: "KN", name: "Saint Kitts and Nevis", slug: "kna" },
  KOR: { isoCode: "KOR", isoCode2: "KR", name: "South Korea", slug: "kor" },
  KWT: { isoCode: "KWT", isoCode2: "KW", name: "Kuwait", slug: "kwt" },
  LAO: { isoCode: "LAO", isoCode2: "LA", name: "Laos", slug: "lao" },
  LBN: { isoCode: "LBN", isoCode2: "LB", name: "Lebanon", slug: "lbn" },
  LBR: { isoCode: "LBR", isoCode2: "LR", name: "Liberia", slug: "lbr" },
  LBY: { isoCode: "LBY", isoCode2: "LY", name: "Libya", slug: "lby" },
  LCA: { isoCode: "LCA", isoCode2: "LC", name: "Saint Lucia", slug: "lca" },
  LIE: { isoCode: "LIE", isoCode2: "LI", name: "Liechtenstein", slug: "lie" },
  LKA: { isoCode: "LKA", isoCode2: "LK", name: "Sri Lanka", slug: "lka" },
  LSO: { isoCode: "LSO", isoCode2: "LS", name: "Lesotho", slug: "lso" },
  LTU: { isoCode: "LTU", isoCode2: "LT", name: "Lithuania", slug: "ltu" },
  LUX: { isoCode: "LUX", isoCode2: "LU", name: "Luxembourg", slug: "lux" },
  LVA: { isoCode: "LVA", isoCode2: "LV", name: "Latvia", slug: "lva" },
  MAC: { isoCode: "MAC", isoCode2: "MO", name: "Macao", slug: "mac" },
  MAF: { isoCode: "MAF", isoCode2: "MF", name: "Saint Martin", slug: "maf" },
  MAR: { isoCode: "MAR", isoCode2: "MA", name: "Morocco", slug: "mar" },
  MCO: { isoCode: "MCO", isoCode2: "MC", name: "Monaco", slug: "mco" },
  MDA: { isoCode: "MDA", isoCode2: "MD", name: "Moldova", slug: "mda" },
  MDG: { isoCode: "MDG", isoCode2: "MG", name: "Madagascar", slug: "mdg" },
  MDV: { isoCode: "MDV", isoCode2: "MV", name: "Maldives", slug: "mdv" },
  MEX: { isoCode: "MEX", isoCode2: "MX", name: "Mexico", slug: "mex" },
  MHL: { isoCode: "MHL", isoCode2: "MH", name: "Marshall Islands", slug: "mhl" },
  MKD: { isoCode: "MKD", isoCode2: "MK", name: "North Macedonia", slug: "mkd" },
  MLI: { isoCode: "MLI", isoCode2: "ML", name: "Mali", slug: "mli" },
  MLT: { isoCode: "MLT", isoCode2: "MT", name: "Malta", slug: "mlt" },
  MMR: { isoCode: "MMR", isoCode2: "MM", name: "Myanmar", slug: "mmr" },
  MNE: { isoCode: "MNE", isoCode2: "ME", name: "Montenegro", slug: "mne" },
  MNG: { isoCode: "MNG", isoCode2: "MN", name: "Mongolia", slug: "mng" },
  MNP: { isoCode: "MNP", isoCode2: "MP", name: "Northern Mariana Islands", slug: "mnp" },
  MOZ: { isoCode: "MOZ", isoCode2: "MZ", name: "Mozambique", slug: "moz" },
  MRT: { isoCode: "MRT", isoCode2: "MR", name: "Mauritania", slug: "mrt" },
  MSR: { isoCode: "MSR", isoCode2: "MS", name: "Montserrat", slug: "msr" },
  MTQ: { isoCode: "MTQ", isoCode2: "MQ", name: "Martinique", slug: "mtq" },
  MUS: { isoCode: "MUS", isoCode2: "MU", name: "Mauritius", slug: "mus" },
  MWI: { isoCode: "MWI", isoCode2: "MW", name: "Malawi", slug: "mwi" },
  MYS: { isoCode: "MYS", isoCode2: "MY", name: "Malaysia", slug: "mys" },
  MYT: { isoCode: "MYT", isoCode2: "YT", name: "Mayotte", slug: "myt" },
  NAM: { isoCode: "NAM", isoCode2: "NA", name: "Namibia", slug: "nam" },
  NCL: { isoCode: "NCL", isoCode2: "NC", name: "New Caledonia", slug: "ncl" },
  NER: { isoCode: "NER", isoCode2: "NE", name: "Niger", slug: "ner" },
  NFK: { isoCode: "NFK", isoCode2: "NF", name: "Norfolk Island", slug: "nfk" },
  NGA: { isoCode: "NGA", isoCode2: "NG", name: "Nigeria", slug: "nga" },
  NIC: { isoCode: "NIC", isoCode2: "NI", name: "Nicaragua", slug: "nic" },
  NIU: { isoCode: "NIU", isoCode2: "NU", name: "Niue", slug: "niu" },
  NLD: { isoCode: "NLD", isoCode2: "NL", name: "Netherlands", slug: "nld" },
  NOR: { isoCode: "NOR", isoCode2: "NO", name: "Norway", slug: "nor" },
  NPL: { isoCode: "NPL", isoCode2: "NP", name: "Nepal", slug: "npl" },
  NRU: { isoCode: "NRU", isoCode2: "NR", name: "Nauru", slug: "nru" },
  NZL: { isoCode: "NZL", isoCode2: "NZ", name: "New Zealand", slug: "nzl" },
  OMN: { isoCode: "OMN", isoCode2: "OM", name: "Oman", slug: "omn" },
  PAK: { isoCode: "PAK", isoCode2: "PK", name: "Pakistan", slug: "pak" },
  PAN: { isoCode: "PAN", isoCode2: "PA", name: "Panama", slug: "pan" },
  PCN: { isoCode: "PCN", isoCode2: "PN", name: "Pitcairn", slug: "pcn" },
  PER: { isoCode: "PER", isoCode2: "PE", name: "Peru", slug: "per" },
  PHL: { isoCode: "PHL", isoCode2: "PH", name: "Philippines", slug: "phl" },
  PLW: { isoCode: "PLW", isoCode2: "PW", name: "Palau", slug: "plw" },
  PNG: { isoCode: "PNG", isoCode2: "PG", name: "Papua New Guinea", slug: "png" },
  POL: { isoCode: "POL", isoCode2: "PL", name: "Poland", slug: "pol" },
  PRI: { isoCode: "PRI", isoCode2: "PR", name: "Puerto Rico", slug: "pri" },
  PRK: { isoCode: "PRK", isoCode2: "KP", name: "North Korea", slug: "prk" },
  PRT: { isoCode: "PRT", isoCode2: "PT", name: "Portugal", slug: "prt" },
  PRY: { isoCode: "PRY", isoCode2: "PY", name: "Paraguay", slug: "pry" },
  PSE: { isoCode: "PSE", isoCode2: "PS", name: "Palestine", slug: "pse" },
  PYF: { isoCode: "PYF", isoCode2: "PF", name: "French Polynesia", slug: "pyf" },
  QAT: { isoCode: "QAT", isoCode2: "QA", name: "Qatar", slug: "qat" },
  REU: { isoCode: "REU", isoCode2: "RE", name: "Réunion", slug: "reu" },
  ROU: { isoCode: "ROU", isoCode2: "RO", name: "Romania", slug: "rou" },
  RUS: { isoCode: "RUS", isoCode2: "RU", name: "Russia", slug: "rus" },
  RWA: { isoCode: "RWA", isoCode2: "RW", name: "Rwanda", slug: "rwa" },
  SAU: { isoCode: "SAU", isoCode2: "SA", name: "Saudi Arabia", slug: "sau" },
  SDN: { isoCode: "SDN", isoCode2: "SD", name: "Sudan", slug: "sdn" },
  SEN: { isoCode: "SEN", isoCode2: "SN", name: "Senegal", slug: "sen" },
  SGP: { isoCode: "SGP", isoCode2: "SG", name: "Singapore", slug: "sgp" },
  SGS: { isoCode: "SGS", isoCode2: "GS", name: "South Georgia and the South Sandwich Islands", slug: "sgs" },
  SHN: { isoCode: "SHN", isoCode2: "SH", name: "Saint Helena", slug: "shn" },
  SJM: { isoCode: "SJM", isoCode2: "SJ", name: "Svalbard and Jan Mayen", slug: "sjm" },
  SLB: { isoCode: "SLB", isoCode2: "SB", name: "Solomon Islands", slug: "slb" },
  SLE: { isoCode: "SLE", isoCode2: "SL", name: "Sierra Leone", slug: "sle" },
  SLV: { isoCode: "SLV", isoCode2: "SV", name: "El Salvador", slug: "slv" },
  SMR: { isoCode: "SMR", isoCode2: "SM", name: "San Marino", slug: "smr" },
  SOM: { isoCode: "SOM", isoCode2: "SO", name: "Somalia", slug: "som" },
  SPM: { isoCode: "SPM", isoCode2: "PM", name: "Saint Pierre and Miquelon", slug: "spm" },
  SRB: { isoCode: "SRB", isoCode2: "RS", name: "Serbia", slug: "srb" },
  SSD: { isoCode: "SSD", isoCode2: "SS", name: "South Sudan", slug: "ssd" },
  STP: { isoCode: "STP", isoCode2: "ST", name: "Sao Tome and Principe", slug: "stp" },
  SUR: { isoCode: "SUR", isoCode2: "SR", name: "Suriname", slug: "sur" },
  SVK: { isoCode: "SVK", isoCode2: "SK", name: "Slovakia", slug: "svk" },
  SVN: { isoCode: "SVN", isoCode2: "SI", name: "Slovenia", slug: "svn" },
  SWE: { isoCode: "SWE", isoCode2: "SE", name: "Sweden", slug: "swe" },
  SWZ: { isoCode: "SWZ", isoCode2: "SZ", name: "Eswatini", slug: "swz" },
  SXM: { isoCode: "SXM", isoCode2: "SX", name: "Sint Maarten", slug: "sxm" },
  SYC: { isoCode: "SYC", isoCode2: "SC", name: "Seychelles", slug: "syc" },
  SYR: { isoCode: "SYR", isoCode2: "SY", name: "Syria", slug: "syr" },
  TCA: { isoCode: "TCA", isoCode2: "TC", name: "Turks and Caicos Islands", slug: "tca" },
  TCD: { isoCode: "TCD", isoCode2: "TD", name: "Chad", slug: "tcd" },
  TGO: { isoCode: "TGO", isoCode2: "TG", name: "Togo", slug: "tgo" },
  THA: { isoCode: "THA", isoCode2: "TH", name: "Thailand", slug: "tha" },
  TJK: { isoCode: "TJK", isoCode2: "TJ", name: "Tajikistan", slug: "tjk" },
  TKL: { isoCode: "TKL", isoCode2: "TK", name: "Tokelau", slug: "tkl" },
  TKM: { isoCode: "TKM", isoCode2: "TM", name: "Turkmenistan", slug: "tkm" },
  TLS: { isoCode: "TLS", isoCode2: "TL", name: "Timor-Leste", slug: "tls" },
  TON: { isoCode: "TON", isoCode2: "TO", name: "Tonga", slug: "ton" },
  TTO: { isoCode: "TTO", isoCode2: "TT", name: "Trinidad and Tobago", slug: "tto" },
  TUN: { isoCode: "TUN", isoCode2: "TN", name: "Tunisia", slug: "tun" },
  TUR: { isoCode: "TUR", isoCode2: "TR", name: "Türkiye", slug: "tur" },
  TUV: { isoCode: "TUV", isoCode2: "TV", name: "Tuvalu", slug: "tuv" },
  TWN: { isoCode: "TWN", isoCode2: "TW", name: "Taiwan", slug: "twn" },
  TZA: { isoCode: "TZA", isoCode2: "TZ", name: "Tanzania", slug: "tza" },
  UGA: { isoCode: "UGA", isoCode2: "UG", name: "Uganda", slug: "uga" },
  UKR: { isoCode: "UKR", isoCode2: "UA", name: "Ukraine", slug: "ukr" },
  UMI: { isoCode: "UMI", isoCode2: "UM", name: "United States Minor Outlying Islands", slug: "umi" },
  URY: { isoCode: "URY", isoCode2: "UY", name: "Uruguay", slug: "ury" },
  USA: { isoCode: "USA", isoCode2: "US", name: "United States", slug: "usa" },
  UZB: { isoCode: "UZB", isoCode2: "UZ", name: "Uzbekistan", slug: "uzb" },
  VAT: { isoCode: "VAT", isoCode2: "VA", name: "Holy See", slug: "vat" },
  VCT: { isoCode: "VCT", isoCode2: "VC", name: "Saint Vincent and the Grenadines", slug: "vct" },
  VEN: { isoCode: "VEN", isoCode2: "VE", name: "Venezuela", slug: "ven" },
  VGB: { isoCode: "VGB", isoCode2: "VG", name: "Virgin Islands (British)", slug: "vgb" },
  VIR: { isoCode: "VIR", isoCode2: "VI", name: "Virgin Islands (U.S.)", slug: "vir" },
  VNM: { isoCode: "VNM", isoCode2: "VN", name: "Vietnam", slug: "vnm" },
  VUT: { isoCode: "VUT", isoCode2: "VU", name: "Vanuatu", slug: "vut" },
  WLF: { isoCode: "WLF", isoCode2: "WF", name: "Wallis and Futuna", slug: "wlf" },
  WSM: { isoCode: "WSM", isoCode2: "WS", name: "Samoa", slug: "wsm" },
  YEM: { isoCode: "YEM", isoCode2: "YE", name: "Yemen", slug: "yem" },
  ZAF: { isoCode: "ZAF", isoCode2: "ZA", name: "South Africa", slug: "zaf" },
  ZMB: { isoCode: "ZMB", isoCode2: "ZM", name: "Zambia", slug: "zmb" },
  ZWE: { isoCode: "ZWE", isoCode2: "ZW", name: "Zimbabwe", slug: "zwe" },
};

// Helper function to get country by slug
export function getCountryBySlug(slug: string): Country | undefined {
  return Object.values(countries).find(country => country.slug === slug.toLowerCase());
}

// Helper function to get country by ISO code
export function getCountryByIsoCode(isoCode: string): Country | undefined {
  return countries[isoCode.toUpperCase()];
}

// Get all countries as array
export function getAllCountries(): Country[] {
  return Object.values(countries);
}
